### ISSUE TITLE
switch random number generation to C++ random?

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#100]
We're currently using GNU-specific reentrant random number generators. ("This function is a GNU extension and should not be used in portable programs.", http://www.gnu.org/software/libc/manual/html_node/SVID-Random.html)

It seems like we should consider switching to C++11's random-number-generating facilities instead of the 48_r functions we're using now. Note https://isocpp.org/files/papers/n3551.pdf

We don't use random number generation very often, but it seems like this would be technically superior as well as more portable.

Assigning to @sgpyc but if it's a burden, assign it back to me. I will do the OS X testing if you'd like after you check in.

```
$ ack rand48_r
gunrock/app/rp/rp_partitioner.cuh
165:            srand48_r(seed_, &rand_data);
169:                lrand48_r(&rand_data, &x);

gunrock/graphio/rgg.cuh
162:        srand48_r(seed_, &rand_data);
173:            drand48_r(&rand_data, &t_value);
179:            drand48_r(&rand_data, &t_value);
267:                        drand48_r(&rand_data, &t_value);
313:                    //drand48_r(&rand_data, &rand_v);

gunrock/graphio/rmat.cuh
37:    drand48_r(rand_data, &result);
217:        srand48_r(seed_, &rand_data);
253:                drand48_r(&rand_data, &t_value);
270:                    drand48_r(&rand_data, &t_value);
```

**Comment by sgpyc** [comment]
I use rand48_r for its thread safety feature (std::rand() is known for not thread safe). Checking on the <random> library in C++11 to see whether it's thread safe. So far it seems C++11 libraries are mostly thread safe, but not clear for the specific ones (i.e. <random>).

**Comment by jowens** [comment]
Good stackoverflow thread here. Basically it appears that if you use a per-thread engine and per-thread distribution, C++11/<random> is thread safe ... http://stackoverflow.com/questions/21237905/how-do-i-generate-thread-safe-uniform-random-numbers

**Comment by neoblizz** [comment]
I believe the switch happened: https://github.com/gunrock/gunrock/search?l=Cuda&q=mt19937&type=&utf8=%E2%9C%93 (If I am incorrect, reopen the thread).
