### ISSUE TITLE
Segmentation fault occurs for mst under dev branch when setting device other than 0

### ISSUE THREAD

**Issue by Laurawly** [gunrock/gunrock#103]
$ bin/minimum_spanning_tree market ~/gunrock/dataset/small/test_mst.mtx --device=1
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (9 vertices, 34 edges):
    Degree   0: 0 (0.00%)
    Degree 2^0: 1 (11.11%)
    Degree 2^1: 3 (33.33%)
    Degree 2^2: 5 (55.56%)

Using 1 GPU(s): [ 1 ].

MINIMUM SPANNING TREE TEST
Segmentation fault (core dumped)

**Comment by sgpyc** [comment]
Pervious mst has issue propagating and using gpu_idx. Solved in commit 89db9cd
