### ISSUE TITLE
Bug with --disable-size-check

### ISSUE THREAD

**Issue by ctcyang** [gunrock/gunrock#105]
I was playing around with bfs-test.sh on the dev branch, and I noticed a bug when running Kron21 on normal BFS (not direction optimized). When I run "../../../gunrock/bin/breadth_first_search market /data/gunrock_dataset/large/kron_g500-logn21/kron_g500-logn21.mtx --src=0 --undirected --idempotence --traversal-mode=1 --iteration-num=10 --disable-size-check"

I receive the following error, but when I get rid of "--disable-size-check", the program seems to work fine.

The error message is below:
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] node_locks cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] node_locks_out cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] edges_queued cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] nodes_queued cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 242 @ gpu 0] output_length cudaHostUnregister failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/cta_work_progress.cuh, 255 @ gpu 0] CtaWorkProgress cudaFree d_counters failed:  (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 242 @ gpu 0] frontier_attribute cudaHostUnregister failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 242 @ gpu 0] enactor_stats cudaHostUnregister failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 242 @ gpu 0] work_progress cudaHostUnregister failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 242 @ gpu 0] cuda_props cudaHostUnregister failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] visited_mask cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] visited_mask cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] keys cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] keys cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] keys cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] keys cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] scanned_edges[] cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] scanned_edges[] cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] out_length cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] labels cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] out_length cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] data_slices[] cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] data_slices[] cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] row_offsets cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] column_indices cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] out_degrees cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] out_degrees cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] column_indices cudaFree failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 267 @ gpu 0] row_offsets cudaFree failed (CUDA error 77: an illegal memory access was encountered)

**Comment by sgpyc** [comment]
--disable-size-check only works when correct queue-sizing (and / or queue-sizing1, + in-sizing for multiple GPU) is specified. For "/data/gunrock_dataset/large/kron_g500-logn21/kron_g500-logn21.mtx --src=0 --undirected --idempotence --traversal-mode=1", the correct setting is "--queue-sizing=1 --queue-sizing1=60". If --disable-size-check and the allocated array size is not sufficient, https://github.com/gunrock/gunrock/blob/dev/gunrock/app/enactor_base.cuh#L634 should report an error. But currently the error message doesn't show up.

Anyway, don't use --disable-size-check if the required sizing parameters are unknown. The full running parameter for this particular  test should be "market /data/gunrock_dataset/large/kron_g500-logn21/kron_g500-logn21.mtx --src=0 --undirected --idempotence --traversal-mode=1 --queue-sizing=1 --queue-sizing1=60 --disable-size-check" and will generate the following output:

Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (2097152 vertices, 182081864 edges):
    Degree   0: 553065 (26.37%)
    Degree 2^0: 238482 (11.37%)
    Degree 2^1: 241389 (11.51%)
    Degree 2^2: 253643 (12.09%)
    Degree 2^3: 156277 (7.45%)
    Degree 2^4: 249285 (11.89%)
    Degree 2^5: 104845 (5.00%)
    Degree 2^6: 101726 (4.85%)
    Degree 2^7: 116250 (5.54%)
    Degree 2^8: 39 (0.00%)
    Degree 2^9: 54255 (2.59%)
    Degree 2^10: 20273 (0.97%)
    Degree 2^11: 76 (0.00%)
    Degree 2^12: 5985 (0.29%)
    Degree 2^13: 1330 (0.06%)
    Degree 2^14: 0 (0.00%)
    Degree 2^15: 210 (0.01%)
    Degree 2^16: 21 (0.00%)
    Degree 2^17: 1 (0.00%)

Source vertex: 0
Using 1 GPU: [ 0 ].
Computing reference value ...
CPU BFS finished in 1052.026978 msec. cpu_search_depth: 6

__________________________
--------------------------
Label Validity: 
CORRECT

First 40 labels of the GPU result:
[0:0 1:3 2:4 3:3 4:3 5:3 6:-1 7:3 8:4 9:3 10:3 11:3 12:3 13:-1 14:3 15:3 16:3 17:3 18:3 19:3 20:-1 21:-1 22:3 23:-1 24:4 25:3 26:3 27:3 28:4 29:-1 30:3 31:-1 32:3 33:3 34:3 35:-1 36:-1 37:3 38:4 39:2 ]

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 1277378560	 2097154	 125829122
	 queue_sizing =	 1.000001 	 60.000001

 [BFS] finished.
 elapsed: 131.0041 ms
 iterations: 6
 rate: 1389.8931 MiEdges/s
 src: 0
 nodes_visited: 1543901
 edges_visited: 182081678
 nodes queued: 1547304
 edges queued: 192986642
 nodes redundance: 0.22%
 edges redundance: 5.99%
 load time: 526.7029 ms
 preprocess time: 226.6550 ms
 postprocess time: 14.0650 ms
 total time: 1954.6881 ms

**Comment by jowens** [comment]
If we specify incompatible command-line parameters, we should print to cerr what we're doing. Somewhere in the code, there's likely something that sees that queue-sizing isn't specified and ignores disable-size-check. We should print to cerr that we're ignoring disable-size-check and why.

**Comment by sgpyc** [comment]
For this particular situation, the best the program can do is to report something like "Error, Array X on Device y is not sufficient: allocated = abcd, required = efgh". There is no (easy) way to enable the size checking during run-time, and no way to know what the correct sizing parameters are before a full successful run.

**Comment by jowens** [comment]
Throwing an error is fine. The worst case is for a user to specify a set of parameters, have something go wrong (either silently or with error messages), and not know what to do to fix it. Your error message is perfectly good, but should also say "Don't use --disable-size-check if sizing parameters are unknown."

**Comment by wetliu** [comment]
Since I am taking care of the problem of the command line, I think I can do it when I am checking the command line. Could you please send me a list of the old command line parameters that are already in use and the parameters that you want to write more error messages? @jowens @sgpyc @yzhwang

**Comment by jowens** [comment]
gunrock/util/info.cuh and gunrock/app/problem_base.cuh are good places to start (look for `CheckCmdLineFlag` and `GetCmdLineArgument`).

**Comment by wetliu** [comment]
Thank you!
