### ISSUE TITLE
Request for CPU and GPU code review and optimization for DAWN algorithm implementation

### ISSUE THREAD

**Issue by lxrzlyr** [gunrock/gunrock#1052]
**Is your feature request related to a problem? Please describe.**
Yes. I have submitted a pull request for the DAWN algorithm implementation, but I need help with reviewing and improving the CPU and GPU versions of the code.

**Describe the solution you'd like**
I am looking for suggestions on how to improve the performance of the CPU implementation and how to optimize the code for parallel execution on GPUs.

**Describe alternatives you've considered**
I have considered trying to optimize the code on my own, but I am not an expert in CPU or GPU programming and do not have the necessary knowledge to fully optimize the code. Therefore, I am requesting help from experts in these areas.

**Additional context**
I have already submitted a pull request for the DAWN algorithm implementation and would greatly appreciate any feedback or assistance in improving the code for both CPU and GPU platforms.

PS. DAWN for CPU already works, the GPU version doesn't work yet.

@neoblizz

**Comment by lxrzlyr** [comment]
Pull Request: https://github.com/gunrock/gunrock/pull/1051#issue-1784401941

**Comment by neoblizz** [comment]
@lxrzlyr hey, I just want to update that I have been very busy but have not forgotten about this. I will take a look at it when I get a chance.

**Comment by lxrzlyr** [comment]
@neoblizz We have completed the implementation of advanced DAWN. After consolidating functions and further reducing operations, we found it to be highly analogous to the BFS implementation. In essence, with minimal modifications, DAWN can be realized.
```cpp
### DAWN
auto iteration = this->iteration + 1;
auto sovm = [distances, single_source, iteration] __host__ __device__(
                    vertex_t const& source,    // ... source
                    vertex_t const& neighbor,  // neighbor
                    edge_t const& edge,        // edge
                    weight_t const& weight     // weight (tuple).
                    ) -> bool {
      auto old_distance = math::atomic::min(&distances[neighbor], iteration);
      return (iteration < old_distance);
    };
```
```cpp
### BFS
auto bfs = [distances, single_source, iteration] __host__ __device__(
                    vertex_t const& source,    // ... source
                    vertex_t const& neighbor,  // neighbor
                    edge_t const& edge,        // edge
                    weight_t const& weight     // weight (tuple).
                    ) -> bool {
      auto old_distance = math::atomic::min(&distances[neighbor], iteration + 1);
      return (iteration + 1 < old_distance);
    };
```
The correctness of this slight modification actually stems from the consolidation of the following two functions, where DAWN reduces two additions in each update compared to the original BFS.
```cpp
    auto iteration = this->iteration + 1;
    auto sovm = [visited, single_source, iteration] __host__ __device__(
                    vertex_t const& source,    // ... source
                    vertex_t const& neighbor,  // neighbor
                    edge_t const& edge,        // edge
                    weight_t const& weight     // weight (tuple).
                    ) -> bool {
      visited[neighbor] = iteration;
      return true;
    };
    auto merge = [visited, distances, iteration] __host__ __device__(
                     vertex_t const& vertex) -> bool {
      auto update_distance = thread::load(&(visited[vertex]));
      auto recover_distance =
          math::atomic::min(&(distances[vertex]), update_distance);
      return (update_distance < recover_distance);
    };
```
Since DAWN can be implemented with very small modifications based on the current BFS API, we suggest enhancing performance by directly modifying the existing BFS API, rather than setting up a separate algorithm. This approach can also reduce the complexity of the testing process. Once you have determined the specific approach for integrating DAWN or modifying BFS, please inform me.

Looking forward to your reply. Thanks!

**Comment by neoblizz** [comment]
Hi @lxrzlyr, thanks for the update. I'll check this out in ~1.5 weeks timeline. I am on a break right now. Thanks for your contribution!

**Comment by neoblizz** [comment]
> @neoblizz We have completed the implementation of advanced DAWN. After consolidating functions and further reducing operations, we found it to be highly analogous to the BFS implementation. In essence, with minimal modifications, DAWN can be realized.
> 
> ```c++
> ### DAWN
> auto iteration = this->iteration + 1;
> auto sovm = [distances, single_source, iteration] __host__ __device__(
>                     vertex_t const& source,    // ... source
>                     vertex_t const& neighbor,  // neighbor
>                     edge_t const& edge,        // edge
>                     weight_t const& weight     // weight (tuple).
>                     ) -> bool {
>       auto old_distance = math::atomic::min(&distances[neighbor], iteration);
>       return (iteration < old_distance);
>     };
> ```
> 
> ```c++
> ### BFS
> auto bfs = [distances, single_source, iteration] __host__ __device__(
>                     vertex_t const& source,    // ... source
>                     vertex_t const& neighbor,  // neighbor
>                     edge_t const& edge,        // edge
>                     weight_t const& weight     // weight (tuple).
>                     ) -> bool {
>       auto old_distance = math::atomic::min(&distances[neighbor], iteration + 1);
>       return (iteration + 1 < old_distance);
>     };
> ```
> 
> The correctness of this slight modification actually stems from the consolidation of the following two functions, where DAWN reduces two additions in each update compared to the original BFS.
> 
> ```c++
>     auto iteration = this->iteration + 1;
>     auto sovm = [visited, single_source, iteration] __host__ __device__(
>                     vertex_t const& source,    // ... source
>                     vertex_t const& neighbor,  // neighbor
>                     edge_t const& edge,        // edge
>                     weight_t const& weight     // weight (tuple).
>                     ) -> bool {
>       visited[neighbor] = iteration;
>       return true;
>     };
>     auto merge = [visited, distances, iteration] __host__ __device__(
>                      vertex_t const& vertex) -> bool {
>       auto update_distance = thread::load(&(visited[vertex]));
>       auto recover_distance =
>           math::atomic::min(&(distances[vertex]), update_distance);
>       return (update_distance < recover_distance);
>     };
> ```
> 
> Since DAWN can be implemented with very small modifications based on the current BFS API, we suggest enhancing performance by directly modifying the existing BFS API, rather than setting up a separate algorithm. This approach can also reduce the complexity of the testing process. Once you have determined the specific approach for integrating DAWN or modifying BFS, please inform me.
> 
> Looking forward to your reply. Thanks!

Can you create a PullRequest with these changes, and allow maybe a parameter to switch from one implementation to another? --dawn-bfs if enabled for example will give you your lambda functions?

**Comment by neoblizz** [comment]
@lxrzlyr I can merge that PR once it is ready, sorry for the delay.

**Comment by neoblizz** [comment]
Actually, I just looked at #1051, does this support the idea in this issue? If so, lets keep it a separate file. And let me know if that PR implements this idea and I can review and merge it. Thank you!

**Comment by lxrzlyr** [comment]
We wish to retain DAWN as a separate file because DAWN is not merely an optimized BFS algorithm; in the future, we will gradually add new functionalities, such as a version that runs on weighted graphs and a betweenness centrality algorithm based on DAWN.

Additionally, following your suggestion, we have added a global variable in the existing BFS file to control whether the method used is DAWN or the original BFS. Please review the new changes in PR https://github.com/gunrock/gunrock/pull/1051. If you have any additional requirements regarding this switch, please guide us on how we should modify it.
