### ISSUE TITLE
Question about grid size

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#1054]
Hi,
I see an option `--max-grid-size`, but I would like to know how that is controlled. With 0 it meas auto based on the graph input I guess. Assume I run bfs without specifying that option, I see maximum 512 blocks (grid_size). Is it beneficial now to specify `--max-grid-size=1000` in the command line?

**Comment by neoblizz** [comment]
What version of gunrock are you using?

**Comment by mahmoodn** [comment]
V1.1 or V1.0 I guess.

$ git show $(git rev-parse HEAD)
commit a7fc6948f397912ca0c8f1a8ccf27d1e9677f98f (HEAD -> master, origin/master, origin/HEAD)

**Comment by neoblizz** [comment]
First, that's unsupported code and had some relics of an even older version v0.5, which has not been touched in years.

The `max-grid-size` sets the `max_grid_size` parameter in the code, which you can `grep` or search for. When implemented properly the default (when max-grid-size = 0) sets the grid size to number of SMs in a GPU multiplied by the maximum active blocks allowed per SM.

It is not beneficial to change this parameter through CLI. If you're looking to optimize a particular application in that version,  you would need to modify the grid size manually most likely to see the impact of different grid sizes.

**Comment by mahmoodn** [comment]
As I grep the parameter, I see some instances in `app/cc/cc_enactor.cuh` or `app/enactor_base.cuh` but not in the BFS application. So does that mean the parameter is not used in BFS?

I profiled a graph, soc-twitter-2010, and see that the the maximum grid size is 5712 for this kernel:
```
void mgpu::launch_box_cta_k<mgpu::launch_box_t<mgpu::arch_30<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, 
mgpu::empty_t>, mgpu::arch_35<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_50<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_60<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_70<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_75<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>>, void 
mgpu::sorted_search<(mgpu::bounds_t)0, mgpu::launch_box_t<mgpu::arch_30<mgpu::launch_cta_t<(int)256, (int)7, (int)7, 
(int)0>, mgpu::empty_t>, mgpu::arch_35<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_50<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_60<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_70<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>, 
mgpu::arch_75<mgpu::launch_cta_t<(int)256, (int)7, (int)7, (int)0>, mgpu::empty_t>>, unsigned int *, unsigned int *, unsigned
 int *, mgpu::less_t<unsigned int>>(T3, int, T4, int, T5, T6, mgpu::context_t &)::[lambda(int, int) (instance 1)], >(T2, int, T3...)
```
The device is 3080 with SM_86 version and according to the documents, it has 68 SMs and 16 max resident blocks per SM. So that should be 1088.I was wondering what is that 5712.

**Comment by neoblizz** [comment]
> The device is 3080 with SM_86 version and according to the documents, it has 68 SMs and 16 max resident blocks per SM. So that should be 1088.I was wondering what is that 5712.

Max active * Num SMs is not the only way to assign the grid size, sometimes it is problem dependent (and correctness also depends on picking right number of total blocks to launch), i.e. it was removed as a configurable option in later versions. 5712 might be due to `number of elements + block_size - 1 / number of elements` as a grid size for a kernel launch that is dependent on the problem size, and number of elements (not sure exactly) but could mean number of vertices in the frontier. Or number of elements used for sorted search.

**Comment by mahmoodn** [comment]
I was wondering where `mgpu::arch_75` is implemented. I can not find it.

```
$ grep -r arch_75_cta externals/
$ grep -r arch_75_cta gunrock/
gunrock/util/sorted_search.cuh:      mgpu::arch_75_cta<256, 7>
gunrock/util/scan_device.cuh:      mgpu::arch_75_cta<256, 7>
$ grep -r arch_75_cta scripts/
$ grep -r arch_75_cta tools/
$ grep -r arch_75_cta unittests/
$ grep -r arch_75_cta examples/
$ grep -r arch_75_cta docker/
$ grep -r arch_75_cta build/
$ 

```

**Comment by neoblizz** [comment]
> I was wondering where `mgpu::arch_75` is implemented. I can not find it.
> 
> ```
> $ grep -r arch_75_cta externals/
> $ grep -r arch_75_cta gunrock/
> gunrock/util/sorted_search.cuh:      mgpu::arch_75_cta<256, 7>
> gunrock/util/scan_device.cuh:      mgpu::arch_75_cta<256, 7>
> $ grep -r arch_75_cta scripts/
> $ grep -r arch_75_cta tools/
> $ grep -r arch_75_cta unittests/
> $ grep -r arch_75_cta examples/
> $ grep -r arch_75_cta docker/
> $ grep -r arch_75_cta build/
> $ 
> ```

It is implemented: https://github.com/gunrock/gunrock/blob/v1.1/gunrock/util/cuda_properties.cuh#L64
