### ISSUE TITLE
How gunrock support edge advance?

### ISSUE THREAD

**Issue by Jangbao** [gunrock/gunrock#1057]
I don't understand how gunrock does edge advance. Vertex advance to get all neighbor edges of the vertex, but edge? One possibility is to get neighbor edges of the start point and end point of the edge, is that correct?

**Comment by neoblizz** [comment]
You basically queue an edge into the frontier, and look at what edges are connected to either the neighbor (end) or the source (start), and that is your new output frontier.

I think in the current version I have implemented it as only neighbor's edges. However, you can easily switch to get any variation out. Edge to source-edges or edge to neighbors-edges.

**Comment by Jangbao** [comment]
thank you!
