### ISSUE TITLE
Building failed when fetching RAPIDS

### ISSUE THREAD

**Issue by 04GARION** [gunrock/gunrock#1065]
**Describe the bug**
When --Cloning External Project: NVBench
Error occurs
CMake Error at externals/nvbench-src/cmake/NVBenchRapidsCMake.cmake:11 (include):
  include could not find requested file:

    rapids-cmake
Call Stack (most recent call first):
  externals/nvbench-src/CMakeLists.txt:15 (nvbench_load_rapids_cmake)

**To Reproduce**
This error occurs when I try to build gunrock on a linux virtual machine. 

**Environment (please complete the following information):**
- Linux
- CUDA version 10.1.243
- GCC version 9.4

**Comment by neoblizz** [comment]
Can you try using cmake with `-DESSENTIALS_BUILD_BENCHMARKS=OFF` option instead? You may have to delete the build directory and recreate and rerun the cmake.

**Comment by 04GARION** [comment]
This is really helpful and I successfully run the cmake command. Thank you fir your prompt reply.
