### ISSUE TITLE
test Windows build

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#107]
We don't know if Gunrock builds on Windows. We also don't know what compiler might work (MSVC being the most important). We hope cmake gives us what we need. Go to, @neoblizz!

**Comment by neoblizz** [comment]
Time to delve into the strange strange world of Windows OS! I will report back once I have a copy installed on the workstation.

**Comment by neoblizz** [comment]
Some progress on this, it was definitely an interesting ride! I used Windows 10 (x64). Things we need on Windows to generate build files:
- CUDA (I am running 7.5) & Visual Studio 2015 (MSVC)
- CMake GUI 3.4.3: [Cmake](https://cmake.org/download/)
- Boost 1.55.0: [Boost Installer](http://iweb.dl.sourceforge.net/project/boost/boost-binaries/1.55.0/boost_1_55_0-msvc-12.0-64.exe)
- Metis 5.0.2: [Metis Library](http://master.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/ray_linn/64bit-libraries/scientist/metis/METIS-5.0.2.7z)
- Git (to clone `gunrock`, `moderngpu` & `cub`)

Settings:
![Basic Settings](http://i.imgur.com/Fn0G2Pu.png)

![Basic Libraies](http://i.imgur.com/Sdvrlwj.png)

CMake Output:
```
The C compiler identification is MSVC 19.0.23506.0
The CXX compiler identification is MSVC 19.0.23506.0
Check for working C compiler using: Visual Studio 14 2015
Check for working C compiler using: Visual Studio 14 2015 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 14 2015
Check for working CXX compiler using: Visual Studio 14 2015 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Boost version: 1.55.0
Found the following Boost libraries:
  system
  filesystem
  timer
  chrono
Configuring done
Generating done
```
Some interesting things I found: You can get everything using Cygwin but there is no nvcc or the likes so cmake never finds the CUDA files on the system. I couldn't find a way to make that work but read up on stuff that said you can use Visual Studio to make it work with Cygwin.

I haven't run the generated project files yet, but this is what the build folder now looks like:
![Build DIR](http://i.imgur.com/nfljP7D.png)

**Comment by jowens** [comment]
it would be fair to require the user to install nvcc before running this (they will expect this). i agree with your inclination to use a package manager. i am *sure* that folks have used nvcc + cmake together before. anyway, this seems like very good progress, keep it goin'.

**Comment by neoblizz** [comment]
Visual Studio 2015 doesn't work, switching to 2013: `nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported`

**Comment by neoblizz** [comment]
Windows alternatives/versions of linux libraries:
https://github.com/Polyfun/libimobiledevice-windows/tree/master/libgen (dependency)
https://www.sourceware.org/pthreads-win32/ (dependency)

This might be something we can consider when we revisit the gunrock's code base, some of the dependencies can only be found in linux, but their alternatives, as far as I can tell right now, exist in windows. 

I couldn't find cuda libraries for MinGW or Cygwin, almost all answers seem to say that you have to stick with Visual Studio.

**Comment by neoblizz** [comment]
Windows build worked on in #213.
