### ISSUE TITLE
What is the main diffference between dawn_bfs and bfs ? 

### ISSUE THREAD

**Issue by kaanolgu** [gunrock/gunrock#1070]
Hi, 
I was searched at docs and was looking at source codes but couldn't find the difference between these algorithms `bfs`, `dawn` and `dawn_bfs`  and also 

when I modify examples/bfs/bfs.cu file and replace DAWN with BFS 

It erros out during the run stating that --src= flag is invalid option

**Comment by kkie02** [comment]
1. In this code, dawn_bfs is the implementation of dawn on unweighted graph. It runs faster than bfs in sparse graph.
1.1. Dawn is the name of a series algorithms, where you can view the detail under this link:[https://doi.org/10.1145/3650200.3656600](url)
1.2. Related PR of dawn in gunrock can be found under following links:
[https://github.com/gunrock/gunrock/issues/1052](url)
[https://github.com/gunrock/gunrock/pull/1068/](url)

2. You should use "--src flag" or "-s flag" instead of "--src= flag".

**Comment by kaanolgu** [comment]
1. Thank you @kkie02 , for the paper and the links to issue and PR they will be really helpful to understand the background  

2. Seems what you are suggesting works with `dawn` but not `regular bfs` since it doesn't have src option: 

```
$ ./build/bin/bfs --help
BFS example
Usage:
  ./build/bin/bfs [OPTION...]

      --help            Print help
      --export_metrics  export performance analysis metrics
  -m, --market arg      Matrix file
  -d, --json_dir arg    JSON output directory
  -f, --json_file arg   JSON output file
  -t, --tag arg         Tags for the JSON output; comma-separated string of 
                        tags
  -n, --num_runs arg    Number of runs
```
I looked at the outputs and the source is random in each run. Later searched with the code and found from this readme that they are actually not so random - https://gunrock.github.io/gunrock/gunrock.wiki/darpa_hive/phase_1/hive_vn.html 

I will try to find which part of the code triggers this and modify it manually but it could have been good to have src option with regular bfs too in order to test with specific node in each run

**Comment by lxrzlyr** [comment]
@kaanolgu I suspect that the issue might be related to the labels - "BFS" wasn't compatible with the original labeling. I have rectified this issue in a new pull request (PR), and now both BFS and DAWN can utilize the -s option. You can obtain the latest version from PR https://github.com/gunrock/gunrock/pull/1068. (Furthermore, we now provide a CPU implementation of DAWN, which will exhibit more differences compared to BFS.) In the latest version, annotations are included to assist you in switching between implementations, whether BFS or DAWN.
