### ISSUE TITLE
SSSP: predecessors vector not populated

### ISSUE THREAD

**Issue by 727yubin** [gunrock/gunrock#1076]
**Describe the bug**
In the SSSP implementation, the `predecessors` vector is not populated.

**To Reproduce**
1. Build the project, as written in the readme
2. Run the sssp example (`./bin/sssp -m ../datasets/chesapeake/chesapeake.mtx`) after adding code to copy the `predecessors` vector from GPU to CPU and print its contents

**Expected behavior**
The `predecessors` vector contains vertex indices of every vertex's predecessor.

**Screenshots**
<img width="900" alt="Screenshot 2024-11-06 at 9 47 31 AM" src="https://github.com/user-attachments/assets/eaf03f62-b2fd-4c24-9c5d-7490d478a509">

**Environment:**
- Linux version: Ubuntu 22.04
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```
- Driver Version: 540.4.0, CUDA Version: 12.6 
- G++ version 12.3.0

I can also reproduce it on another Fedora 41 machine with Driver Version 550.107.02, CUDA version 12.4, and G++ version 14.2.1.

**Additional context**
- If I try initializing the `predecessors` array with a non-zero value, those values don't change after SSSP runs.
- This bugs occurs with both DAWN and Single Source Shortest Path modes, and both when I specify and don't specify a start vertex (with `-s` flag).
- The CPU implementation it checks against (`examples/algorithms/sssp_cpu.hxx`) doesn't do anything with the `predecessors` argument either, is it not implemented?
- I've noticed that around 2022, the API for SSSP changed. Did the implementation change at that point as well?

**Comment by neoblizz** [comment]
I don't believe `predecessors` are being set at all. Probably because we were comparing to a variant that didn't output `predecessors`, just `distances`. It should be pretty easy, I think the logic should be updating this lambda:

https://github.com/gunrock/gunrock/blob/530f25443864d04c25286c053d6812a888b4d779/include/gunrock/algorithms/sssp.hxx#L109-L123

```cpp

    auto predecessors = P->result.predecessors; // outside the lambda
    auto shortest_path = [distances, single_source, predecessors] __host__ __device__(
                             vertex_t const& source,    // ... source
                             vertex_t const& neighbor,  // neighbor
                             edge_t const& edge,        // edge
                             weight_t const& weight     // weight (tuple).
                             ) -> bool {
      weight_t source_distance = thread::load(&distances[source]);
      weight_t distance_to_neighbor = source_distance + weight;

      // Check if the destination node has been claimed as someone's child
      weight_t recover_distance =
          math::atomic::min(&(distances[neighbor]), distance_to_neighbor);

      if (distance_to_neighbor < recover_distance) {
          predecessors[neighbor] = source;
      }
      return (distance_to_neighbor < recover_distance);
    };
```

**Comment by 727yubin** [comment]
It seems like the code works properly. Thank you so much! If possible, could this be added to a future release? From the API, it looked like the function already provides predecessors, and that got me confused for a while.
