### ISSUE TITLE
Improving gunrock's graphio...

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#108]
@yzhwang and I got together and came up with a design we'd like to go for when revamping the `graphio` of gunrock. The objective here is to improve the overall functionality allowing more ways to incorporate/import and generate graphs of different filetypes and formats.
- [x] `class GraphFormats` Stores all graphs in two formats `Coordinate list (COO)` and `Compressed Sparse Row (CSR)`. This allows us to have both formats available but use whichever one is necessary, and since all this is done in pre-compilation we don't lose performance.
- [x] Design a hierarchical structure of graph input, all this will be sent using command line arguments (maybe @wetliu can help me with this) or if it gets too complicated we may later have to branch to a config file.
  - [x] `GraphI/O` Takes input of `import` or `generate`; importing a graph allows users to choose from different file-types, currently we're planning on supporting 4, but with this structure more can easily be incorporated in.
    - `import` - File Types: `*.mtx` [Matrix Market](http://math.nist.gov/MatrixMarket/formats.html), `*.gr`, `*.SNAP` [Stanford Large Network Dataset Collection](https://snap.stanford.edu/data/) and `*.gml` [Graph Modeling Language](https://gephi.org/users/supported-graph-formats/gml-format/)
    - `generate` - Graph Types: This generates somewhat of a random graph controlled by elements such as how big the graph size will be, number of vertices, number of edges etc. (please let me know what more command args can go with this?).

At the end it all compiles down to the class GraphFormats with `coo` and `csr` formats. This design can replace the current `gunrock/graphio/`. @jowens Since we've gotten a lot of requests regarding the I/O, I thought we should merge it all into this one issue and tackle them as we go?

Addresses the following issues: #33, #73, #79, and #106.

**Comment by jowens** [comment]
This looks good. Yes, close the other issues after referencing them in this issue. I hope we can do this without a config file. I think we can.

Please also propose a command-line format for specifying imports and generates. Keep it simple so the simple case is easy. You might want to look at how other graph packages do this for inspiration (e.g., giraph, graphx), although when I take a quick look at those, I don't obviously see command-line interfaces.

**Comment by wetliu** [comment]
I am happy to help with this problem. Let's talk about the format today. @neoblizz

**Comment by neoblizz** [comment]
Yes I believe we can do this without config file, that is for later if the parameters and arguments get more and more complicated. I will look at some examples of how they implement it.

Thanks @wetliu.

**Comment by sgpyc** [comment]
Any reason we need to select CSR or COO at compile time? Well, we're not supporting BOTH CSR and COO for all algorithms, and the main kernels (advance / filter) will do different things depends on graph type. @yzhwang corrects me if that's indeed the plan.
 
Now the compile time is long enough that it shows down the development process (full package takes ~10min to build; single primitive also takes several minutes if debug flags are enabled). I think those flags, if they are on CPU (e.g., if passing COO to BFS, but BFS requires CSR, then whether to do the conversion is on CPU), only have very limited performance implication. I suggest do not make the compilation time any longer, if the template parameters do not cross the CPU-GPU boundary.

**Comment by neoblizz** [comment]
Just to document, after discussion with @sgpyc and @yzhwang it seems like compile time won't be an issue as my implementation only stores both CSR and COO ready for use but only one of them is initialized depending on which one is required for the job. So, we don't have to worry about this.

**Comment by neoblizz** [comment]
This has been taken care of in the new api.
