### ISSUE TITLE
Changing the mtx file does not change output

### ISSUE THREAD

**Issue by narayanan2004** [gunrock/gunrock#109]
I am trying out the gunrock pagerank benchmark and run it like this - 
./build/bin/pagerank market dummy.mtx 

where dummy.mtx is this -
4 4 5
1 2
2 1
3 4
4 3
2 3

However, if I change the file dummy.mtx to remove the last edge (which will change the pagerank values), the printed result does not change. It is clear that gunrock is caching the graph using the filename (instead of the value), which is just a really bad idea. How should one force gunrock to reload the graph from file everytime?

Thanks
Narayanan

**Comment by jowens** [comment]
Are you suggesting that if you run pagerank once with one version of dummy.mtx, end the pagerank run, change dummy.mtx, and then run pagerank again, pagerank will use the old version of the file? I don't see how that would happen; I don't think we maintain any state at all between different invocations of any of our programs.

**Comment by sgpyc** [comment]
Gunrock do use cache files to keep formatted data on .mtx files, as reading and converting .mtx files is time consuming.
They are located on the same directory of the .mtx file, using similar names, and maybe hidden.
Once written, those file will not be changed.
If this is not desired, please do either 1) change the directory containing the .mtx file to read-only; 2) delete the cache files.

**Comment by jowens** [comment]
Shows what I know. @narayanan2004, don't listen to me.

**Comment by jowens** [comment]
One thing we could consider—and this is frankly low-priority—is checking modification dates. If the source mtx file is newer than the cached file, we'd regenerate the cached file.

**Comment by sgpyc** [comment]
@jowens Good suggestion. Another way is to speed up the .mtx file reading routine, and don't use cache files at all (there are multiple version of the cache, depending on graph types, i.e. directed / undirected, 32bit / 64bit, etc., and can occupy quite large space on disk).

**Comment by narayanan2004** [comment]
That explains the behavior I was seeing. Since these generated graph files are hidden by default, it is hard to track them. Perhaps consider just printing a line to the output saying that you are reading from the cached file until other fixes become available (using modification date etc.). 

I agree with @sgpyc . These files can get quite large, so please make their management user-visible. 

Narayanan

**Comment by sgpyc** [comment]
@narayanan2004 When reading from cache files, "Reading directly from stored binary CSR arrays ..." are shown (most likely at the 2nd line of print out). But that may be easy to miss, since sometimes the print out can be quite long.

We haven't do anything involving file permissions. My personal guess is file permission control is tricky under multi-OS environment, but maybe my guess is wrong.

**Comment by narayanan2004** [comment]
Yes, I see the "Reading directly from stored binary CSR arrays ..." line in the output. Maybe it can unambiguously say something like "Reading stored binary CSR arrays from .test.mtx.di.1.bin". The user will now know that such a file exists on their system.
