### ISSUE TITLE
Support TinkerPop

### ISSUE THREAD

**Issue by dylanht** [gunrock/gunrock#111]
This is perhaps a stupid idea, and I am in no position to call if feasible. But here's the gist of it -

1) TinkerPop (https://tinkerpop.incubator.apache.org/) is an open standard and "stack" for graph processing, consisting of a Turing Complete query language (http://arxiv.org/pdf/1508.03843.pdf), a "Graph Server", and a console environment, which is supported by most graph database vendors. While the reference implementation is in Java, there are a lot of implementations in other languages, and "the dream" is that because it is implemented as an instruction set to a virtual machine that computes over graphs, it can actually compile down steps from any language into Gremlin steps/instructions and run the algorithm on any backend - this virtual machine is by design a distributed virtual machine capable of passing messages to other virtual machines. For now, the reference implementations of OLAP processing "graph computers" are SparkGraphComputer and GiraphGraphComputer - obviously, certain things aren't fast in OLTP and certain things don't work in OLAP, but one of TinkerPop's goals for their next version is to make their query language seamlessly transition from OLTP to OLAP queries depending on which is appropriate for that chunk of the query. My point here is that it would be really cool to pull your data from persistent storage in a graph database and run a query that is going to touch the whole graph on your GPU cluster with Gunrock.

2) Blazegraph has just announced a release of their graph database platform that supports multi-GPU cluster computing as a backend, and apparently have plans to support TinkerPop for querying the graph data model and executing the query on a GPU cluster later this year - so it is possible:
https://www.blazegraph.com/product/gpu-accelerated/

What do you think? Could your high level API and steps for manipulating frontiers be mapped to the Gremlin traversal language in an OLAP sense? Here is the mailing list if you guys wanted to connect:
dev@tinkerpop.incubator.apache.org

(And links to TinkerPop docs on doing this)
http://tinkerpop.apache.org/docs/3.1.2-SNAPSHOT/reference/#olap-implementations

**Comment by jowens** [comment]
TinkerPop is in fact very interesting to us. We've tried to identify the right high-level approach to graph analytics, under which Gunrock could be the substrate. (There are numerous contenders, e.g., GraphX). Thank you for pinging us on this. We do think it's worthwhile work.

**Comment by jowens** [comment]
(It's not a small project though. :) )

**Comment by dylanht** [comment]
I wouldn't think so - we have a GPU cluster in our lab, but the CUDA and conceptual barrier definitely deters people like me from using it for their work. From that perspective, I really like the accessibility and interoperability that comes with TinkerPop. I came across this older thread where the TinkerPop/Blazegraph guys have a brief exchange about getting the MapGraph GAS GPU model working with the TinkerPop3 APIs - it seems the consensus is an abstraction match but a difficult road bridging Java and CUDA:
https://groups.google.com/forum/#!searchin/gremlin-users/%22mapgraph%22/gremlin-users/wR9EBh4bCx0/8lC5Vz3ztmAJ

A quick google found this library for Java/CUDA:
http://www.jcuda.org/

What do you think would need to go into this with respect to the gunrock repo? I wouldn't mind taking a whack at it or reporting my findings should I fail.

**Comment by jowens** [comment]
We haven't worked with Java<->CUDA interoperability in our group before. I agree, it is an obstacle. We would probably be inclined to at least start by understanding how the TinkerPop abstraction matches the Gunrock abstraction so we can decide if it's a good match (by that, I mean "here's a few TinkerPop programs, here's how we'd map them to Gunrock, is that straightforward? difficult? what would the compiler need to do to make them efficient?).

**Comment by archenroot** [comment]
I suggest to get in touch with guys bytedeco guys, they work on Javoized API for C++ libs, they have already migrated quite large number of stuff into form of ready to use presets, mainly related to high performance computing. 

https://github.com/bytedeco/javacpp

This way, Gunrock can be wrapped as backend by Java API (better to work with then JCUDA for Java/Scala devs) and integration with ThinkerPop could become something more realistic

**Comment by neoblizz** [comment]
That's actually very exciting for us as well @archenroot, we have been thinking about some of these things for a while now just not enough resources to get to it. But definitely something for near future. 

Let me know if you have any questions, and we welcome pull requests!

**Comment by archenroot** [comment]
@neoblizz - I will discuss with bytedeco if they can help and will try to produce some dummy sample at first. Instead of this repository, this could become to be maintained and distributed from here (mainly, you can of course link it to your repo via docs for example):
https://github.com/bytedeco/javacpp-presets

There you can look what all c++ projects has been "javoized". As stated the good approach of javacpp is that they don't just dummily map as JNI does (although they use JNI underlying), but you get nice to use Java API ... will come back

**Comment by archenroot** [comment]
@neoblizz - do you plan some release, it is better to maintain in Java interfaces, but I will work with up-to-date git version in main branch for testing purposes

**Comment by neoblizz** [comment]
@archenroot I am not sure what you mean, we have 2 releases planned in future, one is in `dev` branch and the other is in `dev-refactor`. Refactored one is our main work right now, and dev just have some minor improvements over master.

**Comment by archenroot** [comment]
I mean what is downloadable under releases in github:

> Gunrock Version 0.4
@yzhwang yzhwang released this on Nov 11, 2016

@neoblizz - I have produced Java interface for Gunrock. Will try some basic sample as soon as I didn't try any real java project yet and will let you know how it goes, or you can track here:
https://github.com/archenroot/javacpp-presets

**Comment by neoblizz** [comment]
I like this! I am excited to see it work, we have plans to update gunrock.h which might require the java stuff to be updated as well. But at least for 0.4 and 0.5 the gunrock.h you have will work.

**Comment by neoblizz** [comment]
Also @archenroot if you are gonna actively develop some of this, feel free to open a new issue on jgunrock.

**Comment by archenroot** [comment]
@neoblizz - upgrade of gunrock.h shouldn't be a problem as soon as it is out, just release 0.6 and I can upgrade java bindings looks like out of the box :-)

I finished now some basic sample but realized on my machine I had CUDA not working related to this:
https://devtalk.nvidia.com/default/topic/1037521/linux/cuda-broken-in-396-24-02-and-396-24-10-vulkan-beta-drivers-on-linux/3

Looks like latest drivers need Numa to be enabled in kernel, just recompiling :-) Will post here once sample works haha

**Comment by archenroot** [comment]
@neoblizz - as suggested, jgunrock will be maintained and publicly available under:
https://github.com/bytedeco/javacpp-presets

As there are maintained 20-30 other C/C++ libs wrapped into Java....

**Comment by archenroot** [comment]
@neoblizz - So I finished rewriting sssp sample code from C to Java interfaces, but it is failing on execution:
https://github.com/bytedeco/javacpp-presets/issues/641

**Comment by jowens** [comment]
You're probably not going to get a great deal of help on Java-C interoperability issues from our team, I'm afraid. This would be a new topic for us. But we will support you as you work on this.

**Comment by archenroot** [comment]
@jowens - I know :-) I just put here reference for anyone interested/being able to help, I hope @saudet will help me :-) (bytedeco org)

**Comment by archenroot** [comment]
@jowens But you can help me understand actually with what this code is doing :-)

graphi->row_offsets = (void*)&row_offsets[0];

So I can try to replicate is as much as possible in Java

**Comment by jowens** [comment]
I didn't write that code, but it looks like it's using a void pointer to avoid any casting errors/warnings, and it's just assigning the pointer to `row_offsets`directly to the `row_offsets` pointer in the `graphi` structure/class.

**Comment by archenroot** [comment]
So, I didn't sleep much this night :-) more due to my stupidity of uinitialized variables, etc. even the sample are quite straighforward, but thx to help of saudet from bytedeco I finished my first Java code which runs gunrock from within Java.

The code looks (dirty at moment) like this, but I will probably remap the C method naming to Java names (minor cosmetic task):
```
import org.apache.commons.lang3.ArrayUtils;
import org.bytedeco.javacpp.IntPointer;
import org.bytedeco.javacpp.gunrock;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import static org.bytedeco.javacpp.gunrock.*;

public class Main {

    public static void main(String[] args) throws FileNotFoundException {
        //gunrock gunrock = new gunrock();
        gunrock.GRTypes grTypes = new gunrock.GRTypes();
        grTypes.VTXID_TYPE(VTXID_INT);
        grTypes.SIZET_TYPE(SIZET_INT);
        grTypes.VALUE_TYPE(VALUE_INT);
        int srcs[] = {0};

        gunrock.GRSetup grSetup = InitSetup(1, srcs);
        int num_nodes = 7; int num_edges = 15;
        int row_offsets[] =  readData("/home/zangetsu/proj/private/gpu/javacpp-presets_archenroot/gunrock/cppbuild/linux-x86_64/gunrock/python/toy_graph/row.txt");
        int col_indices[] = readData("/home/zangetsu/proj/private/gpu/javacpp-presets_archenroot/gunrock/cppbuild/linux-x86_64/gunrock/python/toy_graph/col.txt");
        int edge_values[] = readData("/home/zangetsu/proj/private/gpu/javacpp-presets_archenroot/gunrock/cppbuild/linux-x86_64/gunrock/python/toy_graph/val.txt");
        //int row_offsets[]  = {0, 3, 6, 9, 11, 14, 15, 15};
        //int col_indices[] = {1, 2, 3, 0, 2, 4, 3, 4, 5, 5, 6, 2, 5, 6, 6};
        //int edge_values[] = {39, 6, 41, 51, 63, 17, 10, 44, 41, 13, 58, 43, 50, 59, 35};

        //int row_offsets[]  = {0, 3, 6, 9, 11, 14, 15, 15};
        //int col_indices[] = {1, 2, 3, 0, 2, 4, 3, 4, 5, 5, 6, 2, 5, 6, 6};
        //int edge_values[] = {39, 6, 41, 51, 63, 17, 10, 44, 41, 13, 58, 43, 50, 59, 35};

        /**
        //Python sample based
        IntPointer row = new IntPointer(row_offsets.length);
        IntPointer col = new IntPointer(col_indices.length);
        IntPointer edg = new IntPointer(edge_values.length);
        int nodes = row_offsets.length -1;
        int edges = col_indices.length;

        IntPointer labels = new IntPointer(nodes);
        IntPointer preds = new IntPointer(nodes);
        IntPointer sources = new IntPointer(1);
        sssp(labels, preds, nodes, edges, row, col, edg, 1, sources, true);
        for (int index =0;index < nodes;index++){
            log("distance:" + labels.get(index));
        }

         */
        // Doesn't work due to memory access issues need to discuss with gunrock team
        // C sample based
        GRGraph grGraphO = new GRGraph();
        GRGraph grGraphI = new GRGraph();

        grGraphI.num_nodes(num_nodes);
        grGraphI.num_edges(num_edges);

        grGraphI.row_offsets(new IntPointer(row_offsets));
        grGraphI.col_indices(new IntPointer(col_indices));
        grGraphI.edge_values(new IntPointer(edge_values));


        gunrock_sssp(grGraphO, grGraphI, grSetup, grTypes);
        log("input number of nodes:" + grGraphI.num_nodes());
        //IntPointer labels = (IntPointer) IntPointer.malloc(grGraphI.num_nodes());
        //labels =  new IntPointer(grGraphO.node_value1());
        IntPointer intl = new IntPointer(grGraphO.node_value1());
        int nodes = row_offsets.length - 1;
        for (int index =0;index < nodes;index++){
            log("distance:" + intl.get(index));
        }
             }

    public static void log(Object obj){
        System.out.println(obj);
    }

    public static int[] readData(String file) throws FileNotFoundException {

        log("Current dir: " +  System.getProperty("user.dir"));
        List<Integer> num = new ArrayList<>();

        int i;
        i=0;


        Scanner s = null;
        s = new Scanner(new BufferedReader(new FileReader(file)));

        while (s.hasNext()) {
            if (s.hasNextInt())
            {

                num.add(s.nextInt());

                i++;
            }
        }
        // toArray() can return Integer array but not int array
        Integer[] integers = num.toArray(new Integer[num.size()]); // ArrayUtils of Apache Commons can change an Object array to primitive array
        int[] primitives = ArrayUtils.toPrimitive(integers);


        return primitives;
    }
}

```
And the result from JVM:
```
input number of nodes:7
distance:0
distance:3
distance:4
distance:5
distance:10
distance:13
distance:16
Round 1 of sssp.
0	 1	 0	 queue3 	 oversize :	 10 ->	 14
```
Possible issue or some misunderstanding, when I run the python sample code (which uses same input files from python data subfolder - toy), the result is different:
```
Round 1 of sssp.
0        1       0       queue3          oversize :      10 ->   14
 sssp labels (distance):
3
0
5
8
7
14
19

```
Thing is in Java I use the C gunrock_sssp method which has slightly different input parameters then sssp method called from within Python sample... would you be so kind and comment on this. I suspect this is some algorithm configuration (I need to dig more into gunrock documentation first).

**Comment by archenroot** [comment]
**Q**: I cover in current Java bridge only gunrock.h header file, but there are other files under util subfolder, should I work on creating bridge as well, or gunrock.h is enough for any kind of graph operations?

**Comment by neoblizz** [comment]
I think a well written gunrock.h should be more than enough to get most function out of gunrock. Things get tricky when you start talking about java <-> implementation of a primitive/operator/enactor/app/tests, but if there is a simple C API, java should work.

**Comment by neoblizz** [comment]
@archenroot this repository IS the code for this paper, and under scripts, we have a lot of different tests that we can run to benchmark all of this.

Looking forward to some numbers. :)

**Comment by archenroot** [comment]
@neoblizz - can you do dummy test of Java API for Gunrock? Your system is pure DEV (with supported versions of boost/gcc/cuda, I am doing some hacks...so ...)
```
git clone https://github.com/archenroot/javacpp-presets?organization=archenroot&organization=archenroot
cd in
cd gunrock (subfolder)
mvn clean install
```

Thank you.

**Comment by neoblizz** [comment]
Also see issue #231
