### ISSUE TITLE
Type warnings when running "make"

### ISSUE THREAD

**Issue by ffarhour** [gunrock/gunrock#112]
Build was completed successfully, but with type warnings. Log file attached.
Note: I followed the build directions [here](http://gunrock.github.io/gunrock/doc/latest/building_gunrock.html)
[make_2.8.16.log.txt](https://github.com/gunrock/gunrock/files/122329/make_2.8.16.log.txt)

**Comment by neoblizz** [comment]
I didn't get these warnings in the dev version, I believe the `printfs` were fixed. Instead now, after switching to c++ 11 I got the following warnings for `moderngpu` (This is just one set, it repeats throughout the installation) :

```
/home/muhammad/gunrock/externals/moderngpu/include/kernels/segreducecsr.cuh:394:8: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  CudaContext& context) {
        ^
/home/muhammad/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh:177:29: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  std::auto_ptr<ReduceByKeyPreprocessData>* ppData, CudaContext& context) {
                             ^
/home/muhammad/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh: In function ‘void mgpu::ReduceByKeyPreprocess(int, KeysIt, KeyType*, Comp, int*, int*, std::auto_ptr<mgpu::SegReducePreprocessData>*, mgpu::CudaContext&)’:
/home/muhammad/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh:186:45: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   data(new ReduceByKeyPreprocessData);
                                             ^
/home/muhammad/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh: In function ‘void mgpu::ReduceByKey(KeysIt, InputIt, int, ValType, Op, Comp, KeyType*, DestIt, int*, int*, mgpu::CudaContext&)’:
/home/muhammad/gunrock/externals/moderngpu/include/kernels/reducebykey.cuh:248:41: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  std::auto_ptr<ReduceByKeyPreprocessData> data;
                                         ^
/home/muhammad/gunrock/externals/moderngpu/include/kernels/spmvcsr.cuh: At global scope:
/home/muhammad/gunrock/externals/moderngpu/include/kernels/spmvcsr.cuh:423:8: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  CudaContext& context) {
        ^
/home/muhammad/gunrock/externals/moderngpu/include/kernels/spmvcsr.cuh:433:8: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.8/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
  CudaContext& context) {
```

http://stackoverflow.com/questions/29865638/how-to-resolve-g-warning-with-std-c11-auto-ptr-is-deprecated

**Comment by yzhwang** [comment]
I think this should be a moderngpu issue. They need to switch to shared_ptr

**Comment by neoblizz** [comment]
> sgpyc [3:17 PM] 
> It's modernGPU, I don't think we should fix that
> 
> mosama [3:17 PM] 
> Kk, then I believe that issue can be closed.
> 
> sgpyc [3:17 PM] 
> :thumbsup:

**Comment by yzhwang** [comment]
Actually I really want to know the future of moderngpu. It seems that the whole lib hasn't been updated for a while. I wish Duane could take it over and integrate some of it into cub.

**Comment by neoblizz** [comment]
Wow, last it was updated was 2 years.

**Comment by jowens** [comment]
They fixed a C++11 compile issue last fall that we found (https://github.com/NVlabs/moderngpu/commit/1c1cc9e23463bf4e82bad29a3ab34a4ddac99e3d) but I don't expect they'll go fix warnings.

**Comment by neoblizz** [comment]
Suppressed moderngpu warnings in PR #140, more detail in this [post](https://github.com/gunrock/gunrock/pull/140#issuecomment-202542219).
