### ISSUE TITLE
Null pointer exception caused by getlogin()

### ISSUE THREAD

**Issue by ptheywood** [gunrock/gunrock#113]
On my Ubuntu 14.04.3 system a null pointer exception is being caused by the call to `getlogin()` in `gunrock/util/sysinfo.h:109`

    terminate called after throwing an instance of 'std::logic_error'
      what():  basic_string::_S_construct null not valid

    #0  0x00007ffff6786cc9 in __GI_raise (sig=sig@entry=0x6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    #1  0x00007ffff678a0d8 in __GI_abort () at abort.c:89
    #2  0x00007ffff74be535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #3  0x00007ffff74bc6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #4  0x00007ffff74bc703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #5  0x00007ffff74bc922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #6  0x00007ffff750e1a7 in std::__throw_logic_error(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #7  0x00007ffff75199b1 in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #8  0x00007ffff7519d48 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #9  0x00000000004f2f2e in json_spirit::Value_impl<json_spirit::Config_map<std::string> >::Value_impl (this=0x7fffffffd970, value=0x0) at /home/ptheywood/code/gunrock/gunrock/util/json_spirit_value.h:266
    #10 0x00000000004f1cb7 in gunrock::util::Userinfo::getUserinfo (this=0x7fffffffd9d3) at /home/ptheywood/code/gunrock/gunrock/util/sysinfo.h:109
    #11 0x00000000004fe7af in gunrock::app::Info<int, int, int>::InitBase (this=0xa9b830, algorithm_name=..., args=...) at /home/ptheywood/code/gunrock/gunrock/app/enactor_base.cuh:248
    #12 0x00000000004f665b in gunrock::app::Info<int, int, int>::Init (this=0xa9b830, algorithm_name=..., args=..., csr_ref=...) at /home/ptheywood/code/gunrock/gunrock/app/enactor_base.cuh:469
    #13 0x00000000004d481a in main (argc=0x2, argv=0x7fffffffdee8) at /home/ptheywood/code/gunrock/tests/sssp/test_sssp.cu:660

[man getlogin](http://linux.die.net/man/3/getlogin) states that:

> getlogin()  returns  a  pointer  to  a  string  containing  the name of the user logged in on the controlling terminal of the process, or a NULL pointer if this information cannot be determined.

Either the result of `getlogin()` needs to be checked or an alternative implemented.

> For most purposes, it is more useful to use the environment variable LOGNAME to find out who the user is.  This is more flexible precisely because the user can set LOGNAME arbitrarily.

**Comment by yzhwang** [comment]
Thanks @ptheywood If you see an easy fix you can apply, could you try it and submit a pull request? If you prefer to wait a bit longer, we can fix it too. I see a relevant discussion here:
http://stackoverflow.com/questions/4785126/getlogin-c-function-returns-null-and-error-no-such-file-or-directory
@neoblizz @wetliu @shariiiyy could one of you guys take a look at this issue? Thank you!

**Comment by neoblizz** [comment]
I'll give it a try, seems like an easy fix.

**Comment by ptheywood** [comment]
I think that I tried the alternative from SO earlier and it did work, I can submit a PR when I get to my work machine tomorrow (~12h), I don't currently have a linux box at home.

**Comment by neoblizz** [comment]
Maybe something like this could be added in? Let us know how the test go, thank you!
```
json_spirit::mObject info;
        char * usernotfound = "Not Found";
        if (getlogin())
        {
          info["login"] = getlogin();
        } else
        {
          info["login"] = usernotfound;
        }

        return info;
```

**Comment by neoblizz** [comment]
Thank you for identifying and fixing this @ptheywood!
