### ISSUE TITLE
MST runs out of GPU memory for median datasets

### ISSUE THREAD

**Issue by sgpyc** [gunrock/gunrock#123]
`./bin/test_mst_7.5_x86_64 market /data/gunrock_dataset/large/delaunay_n21/delaunay_n21.mtx` gives out of memory on a K40c

> Loading Matrix-market coordinate-formatted graph ...
> Reading from /data/gunrock_dataset/large/delaunay_n21/delaunay_n21.mtx:
>   Parsing MARKET COO format (2097152 nodes, 6291408 directed edges)... Done parsing (2s).
>   Converting 2097152 vertices, 12582816 directed edges (unordered tuples) to CSR format...
> Done converting (0s).
> 
> Degree Histogram (2097152 vertices, 12582816 edges):
>     Degree   0: 0 (0.00%)
>     Degree 2^0: 0 (0.00%)
>     Degree 2^1: 23718 (1.13%)
>     Degree 2^2: 1803287 (85.99%)
>     Degree 2^3: 270102 (12.88%)
>     Degree 2^4: 45 (0.00%)
> 
> Using 1 GPU: [ 0 ].
> 
> MINIMUM SPANNING TREE TEST
> [../../gunrock/util/array_utils.cuh, 205 @ gpu 0] values cudaMalloc failed (CUDA error 2: out of memory)
> [../../gunrock/app/mst/mst_problem.cuh, 593 @ gpu 0] MSTProblem cudaMemcpy data_slices to d_data_slices failed (CUDA error 77: an illegal memory access was encountered)
> [test_mst.cu, 334 @ gpu 0] MST Problem Data Reset Failed (CUDA error 77: an illegal memory access was encountered)
> [../../gunrock/app/mst/mst_enactor.cuh, 193 @ gpu 0] Problem cudaMalloc d_scanned_edges failed (CUDA error 77: an illegal memory access was encountered)
> [test_mst.cu, 340 @ gpu 0] MST Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
> GPU - Computation Complete in 0.030994 msec.
> [../../gunrock/util/array_utils.cuh, 536 @ gpu 0] mst_output cudaMemcpy D2H failed (CUDA error 77: an illegal memory access was encountered)
> [test_mst.cu, 356 @ gpu 0] MST Problem Data Extraction Failed (CUDA error 77: an illegal memory access was encountered)
> 
> MST CPU REFERENCE TEST
> CPU - Computation Complete in 17189.384766 msec.
> INCORRECT.
> CPU Weight = 24471115
> GPU Weight = 0
> [../../gunrock/app/mst/mst_problem.cuh, 202 @ gpu 0] GpuSlice cudaFree data_slices failed (CUDA error 77: an illegal memory access was encountered)
> [../../gunrock/util/array_utils.cuh, 267 @ gpu 0] row_offsets cudaFree failed (CUDA error 77: an illegal memory access was encountered)
> [../../gunrock/util/array_utils.cuh, 267 @ gpu 0] column_indices cudaFree failed (CUDA error 77: an illegal memory access was encountered)
> [../../gunrock/util/array_utils.cuh, 267 @ gpu 0] out_degrees cudaFree failed (CUDA error 77: an illegal memory access was encountered)
> [../../gunrock/util/array_utils.cuh, 267 @ gpu 0] out_degrees cudaFree failed (CUDA error 77: an illegal memory access was encountered)
> [../../gunrock/util/array_utils.cuh, 267 @ gpu 0] column_indices cudaFree failed (CUDA error 77: an illegal memory access was encountered)
> [../../gunrock/util/array_utils.cuh, 267 @ gpu 0] row_offsets cudaFree failed (CUDA error 77: an illegal memory access was encountered)
> 
>  [MST] finished.
>  elapsed: 0.0310 ms
>  iterations: 0
>  load time: 2794.9820 ms
>  preprocess time: 74.9059 ms
>  postprocess time: 19643.9409 ms
>  total time: 22752.3580 ms

**Comment by yuduowu** [comment]
@sgpyc, MST uses multiple O(E) storages to keep intermediate results, so very likely it's out-of-memory (even with not extremely large dataset). Potentially it can be more optimal and reuse previous O(E) storages that no longer needed.

**Comment by ctcyang** [comment]
I talked to some computer vision researchers in NVResearch. It seems a popular way to do image segmentation uses MST application as a primitive, who would find it useful if this primitive were fixed.

Latest update on MST. It seems there are two bugs:
1) regression bug that causes MST to break on fairly small datasets like delaunay_10 that happened between Aug 7 2015 and Feb 12, 2016.

- I checked all commits in this time period pertaining to the MST enactor, functor and problem, and it seems refactoring from commit caa203b onwards never recovered the ability that let v0.3 (0b146a7)  run up to and including delaunay_16 without problem

2) device illegal address bug that happens only on 100K+ datasets (delaunay_n17)

dev (ed169fc) fails on delaunay_10 with:
```
[/home/ctcyang/gunrock/gunrock/app/mst/mst_enactor.cuh, 838 @ gpu 0] filter::Kernel failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/tests/mst/test_mst.cu, 343 @ gpu 0] MST Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
GPU - Computation Complete in 15.691042 msec.
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 550 @ gpu 0] mst_output cudaMemcpy D2H failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/tests/mst/test_mst.cu, 359 @ gpu 0] MST Problem Data Extraction Failed (CUDA error 77: an illegal memory access was encountered)
```

v0.3 (0b146a7) gets delaunay_15 incorrect, but gets everything else correct up to and including delaunay_16. However on delaunay_17, it gets the following error:
```
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 510 @ gpu 0] done_flags cudaMemcpy H2D failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/tests/mst/test_mst.cu, 312 @ gpu 0] MST Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
GPU - Computation Complete in 0.000000 msec.
[/home/ctcyang/gunrock/gunrock/util/array_utils.cuh, 527 @ gpu 0] mst_output cudaMemcpy D2H failed (CUDA error 77: an illegal memory access was encountered)
[/home/ctcyang/gunrock/tests/mst/test_mst.cu, 326 @ gpu 0] MST Problem Data Extraction Failed (CUDA error 77: an illegal memory access was encountered)
```

cuda-gdb gives:
```
Program received signal CUDA_EXCEPTION_10, Device Illegal Address.
[Switching focus to CUDA kernel 0, grid 289, block (9,0,0), thread (672,0,0), 
device 0, sm 5, warp 21, lane 0]
0x00000000011d4f98 in void 
gunrock::oprtr::edge_map_partitioned::RelaxLightEdges<gunrock::oprtr::edge_map_p
artitioned::KernelPolicy<gunrock::app::mst::MSTProblem<int, int, int, true, 
false, true>, 300, false, 1, 10, 8, 4096>, gunrock::app::mst::MSTProblem<int, 
int, int, true, false, true>, gunrock::app::mst::SuccFunctor<int, int, int, 
gunrock::app::mst::MSTProblem<int, int, int, true, false, true> > >(bool, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::VertexId, int, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::SizeT*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::SizeT*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::VertexId*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::VertexId*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::SizeT*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::VertexId*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::VertexId*, 
gunrock::app::mst::MSTProblem<int, int, int, true, false, true>::DataSlice*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::SizeT, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::SizeT*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::SizeT, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::SizeT, 
gunrock::util::CtaWorkProgress, gunrock::util::KernelRuntimeStats, 
gunrock::oprtr::advance::TYPE, bool, bool, 
gunrock::oprtr::advance::REDUCE_TYPE, gunrock::oprtr::advance::REDUCE_OP, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 4096>::Value*, 
gunrock::oprtr::edge_map_partitioned::KernelPolicy<gunrock::app::mst::MSTProblem
<int, int, int, true, false, true>, 300, false, 1, 10, 8, 
4096>::Value*)<<<(34,1,1),(1024,1,1)>>> ()
```
