### ISSUE TITLE
CUB warpers issue in util/scan_utils.cuh and select_utils.cuh

### ISSUE THREAD

**Issue by sgpyc** [gunrock/gunrock#124]
Gunrock advance and filter kernels are launched into GPU streams (most likely non-0 stream), and mgpu functions (which use context[]) are launched into GPU streams also. But the CUB wrappers in util/scan_utils.cuh and util/slect_utils.cuh do not have interface to support GPU stream. The main issue is in MST, which jumps between non-0 and 0 GPU streams. Now MST is correct, because cudaStreamSynchronize() is added when switching from non-0 to 0 stream, and cudaDeviceSynchronize() is added when switching from 0 to non-0 stream. This is too costly and troublesome, should add GPU-stream support for CUB wrappers.

The CUB wrappers also allocate + de-allocate large amount of temp GPU space for each call, should add a way to pass pre-allocate GPU memory pointer with size information to the calls, and avoid such costly operations.

**Comment by neoblizz** [comment]
Scan was updated: 
https://github.com/gunrock/gunrock/blob/pre-release/gunrock/util/scan_device.cuh
and https://github.com/gunrock/gunrock/tree/pre-release/gunrock/util/scan

Select still has some old code that needs this support, but the new additions have support for streams: https://github.com/gunrock/gunrock/blob/pre-release/gunrock/util/select_device.cuh#L46-L231
