### ISSUE TITLE
code in util/join.cuh

### ISSUE THREAD

**Issue by sgpyc** [gunrock/gunrock#129]
util/join.cuh defines functions under gunrock::util namespace that only used by SM, and named as mark, update, debug_0, debug_1, etc. If these functions are only used by SM, please put them in gunrock::app::sm namespace; if they are indeed utility functions, please give more descriptive names

**Comment by neoblizz** [comment]
Leyuan clarified:
> The original join operator is kinda abandoned now.

Removing it from `dev` branch. See commit 48e99b2.
