### ISSUE TITLE
current ctest on dev is failing on sssp and mst

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#131]
Ran this on Mario this morning.

```
 4/13 Test  #4: TEST_SSSP ........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.00 sec
 8/13 Test  #8: TEST_MST .........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.00 sec
```

**Comment by neoblizz** [comment]
@jowens this can be closed now.

**Comment by jowens** [comment]
I fetched latest from dev, rebuilt, and get the same errors. Can you look in my build directory to see what's up?

**Comment by neoblizz** [comment]
`Error: Input graph file /home/jowens/working/gunrock/dataset/small/chesapeake.mtx does not exist.` I think you manually somehow removed chesapeake.mtx dataset and pull is not fetching it. I don't have permission to add it to your directory, but just execute the following command and try the tests again:

```
wget -O /home/jowens/working/gunrock/dataset/small/ https://github.com/gunrock/gunrock/blob/master/dataset/small/chesapeake.mtx
```

**Comment by jowens** [comment]
I thought there was a message you were going to add to the end ... a message that said how to get more info in the case of a failure.

**Comment by jowens** [comment]
Anyway, yeah, it works now. Woo!

**Comment by neoblizz** [comment]
I am working on the message thing in case of failure for ctest, apparently it is not as simple because you have to add a custom target in CMakeLists.txt. I asked the mailing list to find a better/right way to do it. Will push the changes soon!

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/commit/bfc42812cf50e2d2b635903f252379ced896d950
