### ISSUE TITLE
JSON needs to output number of nodes/edges in the graph

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#132]
`{nodes,edges}_{queued,visited}` are useful but don't actually say how many nodes and edges are in the actual graph (what's read in from a file). Add `{nodes,edges}_in_graph`? 

Assigning to @neoblizz as a desirable output of the read-from-a-graph refactoring.

**Comment by neoblizz** [comment]
@jowens had some questions regarding this one. @yzhwang pointed me to [gunrock/util/info.cuh](https://github.com/gunrock/gunrock/blob/dev/gunrock/util/info.cuh) file to add these changes;

1. Is that the right file we're look at?
2. It currently does not have any original graph related statistics, it all primitive related info that is being worked on by the algorithm. So, I would need to pass `CSR` pointer to it, do you think that is the right approach or is there something I am missing (like maybe there already is graph statistics being passed to it)?

**Comment by jowens** [comment]
I know you're redoing the read-a-graph-file support, so I can't say where you should put it exactly. But it makes sense to me to compute that info when you first see a graph (read it from disk, generate it, etc.); you'll surely have the info you need at that point. Adding it to Info makes sense; you could set it in LoadGraph for instance, passing in info by reference? I don't want to make a suggestion as to how to implement it, though, others will offer better advice than I will.

**Comment by jowens** [comment]
BTW, right now we go through some pretty serious contortions to avoid using global variables anywhere. This is safe, of course, and allows us to not worry about multiple threads or processors etc. I frankly don't know best practices when it comes to "when does a global variable make sense and how do you expose it if so". The info structure would be a good candidate for a global structure if we could support it properly. But I think we need to understand best practices if we move in that direction.

**Comment by neoblizz** [comment]
Makes sense, while working on `graphio` support I have been running into a lot of discussions regarding security, global variables, public/private class variables etc. I will look into this a bit more and discuss it with other members to determine the best course of implementation. Right now, I already have the statistics stored that I'd like to pass, adding it to `info.cuh` shouldn't be too hard.

**Comment by jowens** [comment]
I can enlist outside help (from Actual Software Developers) if needed. I don't pretend that my academic-only-C++ experience qualifies me in any way to make the best decisions by myself.

**Comment by neoblizz** [comment]
This was included in `graphio` support, marking as done. Any json stats file now has num of edges and vertices and a lot more info!
