### ISSUE TITLE
CMakeLists.txt files should update based on root CMakeLists.txt...

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#139]
Thinking about separating the CMakeLists.txt stuff into `.cmake` modules and including them in all CMakeLists.txt.

**Comment by jowens** [comment]
Yes.

**Comment by neoblizz** [comment]
Findings; The structure we have right now is actually pretty good. I have been working on separating the modules into .cmake include files, which can easily be included in the root `CMakeLists.txt`. It generates a Makefile for the whole project and Makefiles for the tests primitives in the same build dir. 

Now, here's an issue. @jowens we were hoping you could ask cmake people if there is a better way to implement something like this. What is happening is if we want tests/primitives as separate sub-projects that can be compiled using the individual CMakeLists.txts in their folders we literally find ourselves copy pasting almost the entire root file CMakeLists.txt per primitive (even if it is with the includes). 

What @yzhwang and I were wondering was if there is a better way to have a main project and then sub-projects that get the shared dependencies from main project and can be compiled. Our directory structure is;

CMakeLists.txt (root project)
| __ bc
| __ | __ CMakeLists.txt (sub-project)
| __ bfs
| __ | __ CMakeLists.txt (sub-project)
| __ cc
| __ | __ CMakeLists.txt (sub-project)
...

Right now, if we include almost every necessary library at the end I get this error:
```
[100%] [100%] Building CXX object CMakeFiles/breadth_first_search.dir/home/muhammad/gunrock/externals/moderngpu/src/mgpuutil.cpp.o
Building C object CMakeFiles/breadth_first_search.dir/home/muhammad/gunrock/gunrock/util/gitsha1.c.o
Linking CXX executable breadth_first_search
/usr/bin/ld: CMakeFiles/breadth_first_search.dir/breadth_first_search_generated_test_bfs.cu.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/breadth_first_search.dir/build.make:422: recipe for target 'breadth_first_search' failed
make[2]: *** [breadth_first_search] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/breadth_first_search.dir/all' failed
make[1]: *** [CMakeFiles/breadth_first_search.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```
Meaning it still failed to find a math library; http://askubuntu.com/questions/527665/undefined-reference-to-symbol-expglibc-2-2-5

**Comment by jowens** [comment]
@neoblizz Please start by asking the cmake list (https://cmake.org/mailman/listinfo/cmake). I will happily call in the big cmake guns if necessary, but it's always better to try the list, since any answers written to the list will benefit everyone.

**Comment by neoblizz** [comment]
I will do that first then, thank you! :+1:
