### ISSUE TITLE
Build errors on Scientific Linux

### ISSUE THREAD

**Issue by michel-steuwer** [gunrock/gunrock#143]
Hi,

I'm trying to get gunrock running on our machine running Scientific Linux.
When I try to compile examples such as SSSP I get the following error message:

```
[charles05]msteuwer: make
[ 14%] Building NVCC (Device) object tests/sssp/CMakeFiles/single_source_shortest_path.dir/__/__/externals/moderngpu/src/single_source_shortest_path_generated_mgpucontext.cu.o
[ 28%] Building NVCC (Device) object tests/sssp/CMakeFiles/single_source_shortest_path.dir/single_source_shortest_path_generated_test_sssp.cu.o
/afs/inf.ed.ac.uk/user/m/msteuwer/gunrock/gunrock/graphio/rgg.cuh: In function ‘int gunrock::graphio::BuildRggGraph(SizeT, gunrock::Csr<VertexId, Value, SizeT>&, double, bool, double, double, int, bool)’:
/afs/inf.ed.ac.uk/user/m/msteuwer/gunrock/gunrock/graphio/rgg.cuh:220: error: expected end of line before ‘capture’
/afs/inf.ed.ac.uk/user/m/msteuwer/gunrock/gunrock/graphio/rgg.cuh:221: error: expected primary-expression before ‘{’ token
CMake Error at single_source_shortest_path_generated_test_sssp.cu.o.cmake:266 (message):
  Error generating file
  /afs/inf.ed.ac.uk/user/m/msteuwer/gunrock/build/tests/sssp/CMakeFiles/single_source_shortest_path.dir//./single_source_shortest_path_generated_test_sssp.cu.o


make[2]: *** [tests/sssp/CMakeFiles/single_source_shortest_path.dir/single_source_shortest_path_generated_test_sssp.cu.o] Error 1
make[1]: *** [tests/sssp/CMakeFiles/single_source_shortest_path.dir/all] Error 2
make: *** [all] Error 2
```

Any help on how to overcome this issue?

I'm happy to provide more information on our configuration if required.

**Comment by yzhwang** [comment]
Hi there. I think that issue is related to metis library. It is used only as one partitioning method for multi-GPU execution. We have changed the cmake module in our dev branch and added code to handle missing metis situation. But we haven't propagated that change back to master branch yet. The solution might be either checking whether you have metis library installed properly, or switch to our current dev branch and try build again. Let me know if these solutions work.

**Comment by neoblizz** [comment]
What might help recreate the error is initial `cmake ..` output. Just so we know what versions of different dependencies you're using. I am not sure if metis will cause this, but you could definitely try switching to the dev branch `git checkout dev` and try making it again.

**Comment by michel-steuwer** [comment]
Thanks for your suggestions.

I successfully compiled the `dev` branch on my machine.
For that I had to compile `boost 1.60` myself as well as `gcc 4.9` because the system wide gcc was too old.
Compiling the most reason `gcc 5.3` did not work, as cuda 7.5 seems to be unhappy with it.

**Comment by neoblizz** [comment]
Yeah, according to CUDA 7.5's [installation guide](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements) it only supports gcc 4.9 or less. But I found a cool hack that works pretty well:

### Hack CUDA to support GCC 5
By default, CUDA 7.5 does not support compling with GCC 4.10 or later versions. It will report the following errors when compiling.
```
In file included from /usr/local/cuda/include/cuda_runtime.h:76:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
 #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
  ^
```
To solve this problem we have to "hack" the CUDA toolkit by editing `/usr/local/cuda/include/host_config.h`. Comment line 115.
```
--- #error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
+++ //#error -- unsupported GNU version! gcc versions later than 4.9 are not supported!
```

Reference: https://gist.github.com/wangruohui/679b05fcd1466bb0937f
