### ISSUE TITLE
"lift" has cmake recipes for cub, does that make our life any easier?

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#145]
https://github.com/nsubtil/lift/tree/master/cmake

@neoblizz can you take a quick look and see if this is a good idea to use?

**Comment by neoblizz** [comment]
@jowens Not at all useful, they're just including the directory where cub is for their project. We put cub in a different directory and do a better job at including it (cache). I have it separated in https://github.com/gunrock/gunrock/blob/dev/cmake/FindCUB.cmake for gunrock already. :)

**Comment by jowens** [comment]
Niiiiice thx for looking
