### ISSUE TITLE
nvshmem

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#146]
After all papers are in, no hurry, @sgpyc can you look at the "nvshmem" API and report back to the team? Supports PGAS model across multiple GPUs, will be a good model for NVLink.

GTC talk:
S6378, Simplifying Multi-GPU Communication with SHMEM
Nathan Luehr
Sreeram Potluri

**Comment by neoblizz** [comment]
They have the talk online: 
S6378, Simplifying Multi-GPU Communication with SHMEM: http://on-demand.gputechconf.com/gtc/2016/video/S6378.html
S6418 - Bringing NVIDIA GPUs to the PGAS/OpenSHMEM World: Challenges and Solutions: http://on-demand.gputechconf.com/gtc/2016/video/S6418.html

**Comment by neoblizz** [comment]
@YuxinxinChen might be worth a look!

**Comment by YuxinxinChen** [comment]
@neoblizz Oh, only notice this now! Sorry, very useful recommendation!!! Thankssss~~~~
