### ISSUE TITLE
ctest is failing on mario in dev build, regexps are broken?

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#148]
```
mario 511$ ctest
Test project /home/jowens/working/gunrock-build
      Start  1: TEST_BFS
 1/13 Test  #1: TEST_BFS .........................   Passed    0.30 sec
      Start  2: TEST_BC
 2/13 Test  #2: TEST_BC ..........................   Passed    0.27 sec
      Start  3: TEST_CC
 3/13 Test  #3: TEST_CC ..........................   Passed    0.35 sec
      Start  4: TEST_SSSP
 4/13 Test  #4: TEST_SSSP ........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.00 sec
      Start  5: TEST_PAGERANK
 5/13 Test  #5: TEST_PAGERANK ....................   Passed    0.54 sec
      Start  6: TEST_DOBFS
 6/13 Test  #6: TEST_DOBFS .......................   Passed    0.30 sec
      Start  7: TEST_TOPK
 7/13 Test  #7: TEST_TOPK ........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.00 sec
      Start  8: TEST_MST
 8/13 Test  #8: TEST_MST .........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.00 sec
      Start  9: SHARED_LIB_TEST_BFS
 9/13 Test  #9: SHARED_LIB_TEST_BFS ..............   Passed    0.35 sec
      Start 10: SHARED_LIB_TEST_BC
10/13 Test #10: SHARED_LIB_TEST_BC ...............   Passed    0.35 sec
      Start 11: SHARED_LIB_TEST_CC
11/13 Test #11: SHARED_LIB_TEST_CC ...............   Passed    0.35 sec
      Start 12: SHARED_LIB_TEST_SSSP
12/13 Test #12: SHARED_LIB_TEST_SSSP .............   Passed    0.34 sec
      Start 13: SHARED_LIB_TEST_PAGERANK
13/13 Test #13: SHARED_LIB_TEST_PAGERANK .........   Passed    0.33 sec

77% tests passed, 3 tests failed out of 13

Total Test time (real) =   3.49 sec

The following tests FAILED:
	  4 - TEST_SSSP (Failed)
	  7 - TEST_TOPK (Failed)
	  8 - TEST_MST (Failed)
Errors while running CTest
```

@neoblizz, pls take a quick look?

**Comment by neoblizz** [comment]
@jowens Can you please post `Testing/Temporary/LastTest.log`? This file should be in the build directory after you have run ctest once.

**Comment by neoblizz** [comment]
Nvm, I was able to find it in your directory. Here's the reason why the tests failed:

SSSP: Input graph file /home/jowens/working/gunrock/dataset/small/chesapeake.mtx does not exist.
MST: Input graph file /home/jowens/working/gunrock/dataset/small/chesapeake.mtx does not exist.
TOPK: is a small bug, I am fixing it in the next push.

**Comment by jowens** [comment]
Oh, thx, great. The error message should tell me I'm missing the data set then!

**Comment by neoblizz** [comment]
It does! You can use commands like `ctest -V`, `ctest -VV` or `ctest --debug` for in depth information about the tests that were run. Also, fixed the topk bug with the last commit I just did.

**Comment by jowens** [comment]
Awesome! OK. We can go with that. Um, any way you could just print what you just said if any tests failed? All I'm trying to do is eliminate issues filed by external people who run `ctest`, have it fail, and don't know why. If at the end of a failed run it says "Run `ctest -V` or `ctest -VV` or `ctest --debug` for more detailed information about the failure", maybe that will eliminate problems down the road.

**Comment by jowens** [comment]
Also topk works great, thanks!

**Comment by neoblizz** [comment]
I will add that message at the end telling them about other commands for a detailed test. Because the general `ctest` command is suppose to be a very simple execution of all the tests and a clean output.

**Comment by jowens** [comment]
But only if it fails. (Hope that's possible.)

**Comment by neoblizz** [comment]
@jowens There is no neat way to add message (with if test_fails) condition for ctest, and the only way to add one is through a ctest script. But for it to properly work, users will have to run `ctest -S /path/to/script.cmake` instead of just ctest. That looks messy too. Instead, I have added a custom target `make check` which runs ctest with a special flag `--output-on-failure` it gives more information than just "Test Failed" and less information than the full verbose output. It seems to work best.

So, I was think in the documentation we can either replace `ctest` with `ctest --output-on-failure` or ask them to use `make check` for testing. We can also mention where the log is available and if they would like more information in the terminal output they can run `ctest -V` or `ctest -VV`.

**Comment by neoblizz** [comment]
Running `make check` is sufficient:

```
 4/13 Test  #4: TEST_SSSP ........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.00 sec
Loading Matrix-market coordinate-formatted graph ...
Input graph file /home/muhammad/gunrock/dataset/small/chesapeake.mtx does not exist.
```

**Comment by jowens** [comment]
Thanks for the update. I have no strong opinion on which option is best in the docs so will happily accept your judgment there. Update away!

**Comment by neoblizz** [comment]
I will add the [changes](https://github.com/gunrock/gunrock/commit/bfc42812cf50e2d2b635903f252379ced896d950) to documentation.
