### ISSUE TITLE
support graphs in binary format

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#149]
Text-based graph files become an I/O bottleneck in Gunrock's loading phase. We need to support our own binary format. Current proposed method is:
do memory dump for each graph-topology related array (row offsets, column indices, row indices, column offsets, node weights, edge weights). Create .tar files.
Things to be careful of: 32bit 64bit edge IDs. Keep both, or migrate 32b to 64b. Add a 64b flag.
Need to modify current writetobinaryfile() function and graph load pipeline.

**Comment by jowens** [comment]
Per @sgpyc's comment on slack: If we store only a 64b segment, then we assume the data doesn't fit into 32b. If we store only a 32b segment, we assume the data fits into 32b and that we can extend it if necessary. If we store both 32b and 64b, we assume that the 64b segment is the same data as the 32b segment except with a leading 32 0 bits. I'm not sure that I can think of any other interesting use cases.

**Comment by sgpyc** [comment]
I think only one of 32bit and 64bit will do, no need to store both of them, and do run-time conversion when required. That can save quite large disk space.

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/blob/15300c335688d0e9c4c599d8cc4a489fe8c61b52/gunrock/csr.cuh#L515 We can write to a binary file format as well.
