### ISSUE TITLE
PageRank and Personal PageRank CPU reference algorithms

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#15]
PageRank BGL reference algorithm fails to remove dangling nodes, causing inconsistent results with our GPU results. (Boost version 1.53.0). Also, need to find a personal PageRank reference algorithm (Currently no ref algorithm so the validity test will fail).

**Comment by ydwu** [comment]
when will " inconsistent results" happens?

**Comment by yzhwang** [comment]
BGL's PageRank seems to have a bug in their remove_dangling_nodes function. This happens in the directed graph since we need to get rid of any "black hole" node which only take in score but not distribute out. Undirected graphs won't have such problem. My other finding is all other graph libraries seems to assume undirected PageRank in their benchmark so as to avoid the time consuming dangling nodes removal (DNR) phase. @sgpyc implemented a CPU reference algorithm for his course project. I'm not sure if he takes DNR into account though.

**Comment by yzhwang** [comment]
@ydwu The current version gives me inconsistent results on ak2010 dataset. Both directed and undirected. A node which should get 0 score gets 47655 in the BGL implementation.

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/issues/243#issuecomment-301270446 It validates fine now.
