### ISSUE TITLE
add multi-GPU scripts to reproduce our results

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#153]
@sgpyc, 14 April: "I used .sh scripts to do the tests. Will push them to dev_debug and eventually dev and master."

No giant hurry; just making sure this gets done as the merge takes place. Nikolai and team would like to reproduce on their end.

**Comment by nsakharnykh** [comment]
We're moving forward with the single-GPU runs so if you can get us multi-GPU scripts we can do that as well!

**Comment by jowens** [comment]
@sgpyc possible?

Thanks @nsakharnykh.

**Comment by sgpyc** [comment]
I think they are in https://github.com/gunrock/gunrock/tree/master/dataset/test-scripts/ipdps17 . 
Let me know if it runs into bug(s) or anything strange.

The figure numbers are according to the IPDPS paper:
Figure 2: Performance impact of partitioners on 3 primitives x 3 datasets
Figure 3: Memory consumption using different allocation schemes on kron, soc-orkut, and uk-2002 running BFS.
Figure 4: mGPU speedup over 1GPU performance for BC, BFS, CC, DOBFS, PR and SSSP. All numbers shown are geometric means of runtime speedup over all datasets.
Figure 5: Scalability of DOBFS, BFS, and PR. {Strong, weak edge, weak vertex} scaling use rmat graphs with {2^24, 2^19, 2^19 * |GPU|} vertices and edge factor {32, 256 * |GPUs|, 256} respectively.

**Comment by neoblizz** [comment]
All scripts under https://github.com/gunrock/gunrock/tree/master/dataset/test-scripts
