### ISSUE TITLE
Martin Butscher issues with Gunrock install

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#154]
(Pasting in Martin's comments on his experience with installing Gunrock. Let's try to address these issues!)

1. Gunrock can only be installed via git hub. One of our test machines does not have git installed, making it pretty much impossible to install Gunrock on it.
2. Gunrock requires 4 other libraries (Boost, Metis, ModernGPU, CUB). These dependencies make it time intensive and cumbersome to install. Are they really all needed? If they are just used for performance comparisons or some unimportant features, maybe give the user the option to install Gunrock without (some of) those libraries.
3. Gunrock did not recognize our working installations of ModernGPU and CUB. They had to be re-installed for Gunrock to recognize them.
4. Though Boost was installed properly (correct version number and path), Gunrock does not recognize/find certain libraries of Boost.

**Comment by jowens** [comment]
1. I don't think we've ever seen a development machine without git. OK. On the gunrock main page (https://github.com/gunrock/gunrock) there's a "Download ZIP" link: https://github.com/gunrock/gunrock/archive/master.zip . Does that work? Of course we strongly recommend git, because as we fix stuff, you can easily update.

**Comment by jowens** [comment]
2. @neoblizz has been working on libraries and compilation. I believe in the dev branch, one can compile without metis—@neoblizz, can you comment? I am not sure about Boost. Our validation is against Boost. We do require both ModernGPU and CUB because we use them internally within Gunrock, but they are set up as external submodules, so when you fetch Gunrock and use --recursive, you'll get them automatically and our make scripts will build them automatically.

**Comment by jowens** [comment]
3\. Not sure if we've ever tried to compile with a separate ModernGPU and CUB. We should support this. Could you paste in the issues you had when you tried to compile this way?

**Comment by jowens** [comment]
4\. Definitely we use separate Boost libraries, usually installed through the OS's package manager. I know this works for both our Linux box and my Mac laptop. So please let us know what your compiler told you when this wasn't work and we'll look right at it.

**Comment by neoblizz** [comment]
1. Actually isn't true, you don't **need** git to install gunrock, it is sort of an engine to download gunrock. Other ways like you mentioned to download gunrock are click on the link on our main github page "Download ZIP" another way is if you have linux and I believe mac type: 

```
wget --no-check-certificate https://github.com/gunrock/gunrock/archive/master.zip

# better, if the certificate authorities are present:
wget https://github.com/gunrock/gunrock/archive/master.zip
```
([Source](http://stackoverflow.com/questions/8377081/github-api-download-zip-or-tarball-link))

And I believe [wget](https://www.gnu.org/software/wget/manual/wget.html) is a native command.

**Comment by neoblizz** [comment]
2. Gunrock does require 3 libraries, but out of these 3 two you just have to use wget (if not using git) to download CUB and MGPU and move them in the `externals` directory. Metis is now optional in dev branch, if you wish to not use metis partitioner it is not required. Boost I believe is required in several different things.

**Comment by neoblizz** [comment]
3. I am not sure how Martin is installing MGPU and CUB, but I don't think they really need to be installed. All you have to do is wget or git clone the two repositories into externals directory.

**Comment by neoblizz** [comment]
4: Installing boost most of the time installs only the main library, but gunrock also uses the following:
```
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
```
So maybe one of the above is missing that is causing that error?

**Comment by DhariniCool** [comment]
Hi,
I am working under Dr.Burtscher and it was me who was trying to install Gunrock and faced these issues.

About the 2nd one. We wanted to confirm if these benchmarks are mandatory for Gunrock. I believe it was not mentioned in the Gunrock build page that Metis is optional.

**Comment by DhariniCool** [comment]
3. Gunrock did not recognise already installed MGPU and CUBB. I got errors saying that CUBB and MGPU were not found. 

But cloning gunrock again (now recursively) solved the issue.

**Comment by jowens** [comment]
In the master (released) version, Metis is required. @neoblizz changed the makefiles in the dev version to make it optional. When we do our next release (0.4) in master, we will change the docs; thanks for making sure we do that!

**Comment by DhariniCool** [comment]
About the last one. I verified the installed Boost version (its path) and also that it has all the 4 required libraries installed. Still Gunrock couldn't recognise all the 4 libraries. 

This was the error message

  Boost version: 1.60.0

  Boost include path: /home/jayadharini/Gunrock/boost_1_60_0

  Could not find the following static Boost libraries:

          boost_system
          boost_filesystem
          boost_timer
          boost_chrono

Please let me know if I should verify anything else.

**Comment by neoblizz** [comment]
@DhariniCool Can you please tell us how you installed boost? I can try and recreate the issue on my end and see why it is not recognizing boost.

Also, for reference, my boost libraries are found in `/usr/lib/x86_64-linux-gnu`. 
If you can do a re-install, try running the shell [script](https://github.com/gunrock/gunrock/blob/dev/dep/install_boost.sh) provided in the dev version:

```
cd gunrock
git checkout dev
cd dep
./install_boost.sh
```

**Comment by DhariniCool** [comment]
@neoblizz For Boost installation, I followed the steps provided in the Boost installation page. (Its link is provided in Gunrock build page)

1.  tar -xvf boost_1_60_0_tar.bz2
2.  under tools/build/
    ./bootstrap.sh 
3. ./b2 install --prefix=DIRECTORY_PATH

I guess the boost installation is fine as I am able to run a sample application.

**Comment by neoblizz** [comment]
@DhariniCool If you have installed boost in `/home/jayadharini/Gunrock/boost_1_60_0` might be the reason gunrock isn't detecting boost. The FindBoostHeaders.cmake in cmake only looks in the default directories, mainly under `usr/` for boost headers.

I will recommend uninstalling boost from the directory you currently have and running the script as I mentioned above. I just tested it and that works. The installation will be in `/usr/local`. If you don't wish to do that you can either create an alias or add boost's path to your .bashrc (or .bash_profile) file.

Hope that fixes the problem!

**Comment by DhariniCool** [comment]
@neoblizz Installing Boost under /usr/local/ solved the issue! Thanks

**Comment by DhariniCool** [comment]
@neoblizz I had a similar issue with Metis (NOTFOUND METIS_LIBRARY). But adding its path to .bash_profile solved the issue. I successfully built Gunrock.
Thanks a lot @neoblizz and @jowens
