### ISSUE TITLE
Gunrock binaries

### ISSUE THREAD

**Issue by ranjanan** [gunrock/gunrock#157]
Hello, are there Gunrock binaries that you guys host somewhere? It would be good to have them and not build them from source every time. Also, it'd be convenient for CI.

**Comment by jowens** [comment]
Not really on our roadmap; building for different Linux distributions, different OSes, for particular versions of the (4) external libraries ... at least at this stage of Gunrock's development, probably not the best place where hardworking graduate students need to be spending our time.

In good news, my understanding is CUDA 8 will deliver significant compile-time speedups. :)

We would like to have CI (e.g., travis-ci) but have not located an external place that supports GPUs, suggestions welcome!
