### ISSUE TITLE
Path for cluster stuck with CUDA 5.5

### ISSUE THREAD

**Issue by dylanht** [gunrock/gunrock#158]
Hello,

Taking note of the recent commit describing the C++11 -> CUDA 7.0 and above dependency, where some primitives would require CUDA 7.5 due to the compiler bug your team discovered - 

https://github.com/gunrock/gunrock/commit/c0678c645c5d5175562ce329b8e6d40a4d977ebb

If we were stuck with CUDA 5.5 what kind of refactoring effort would be required on our part to get Gunrock running on our cluster?

**Comment by jowens** [comment]
Oh my. That would be ugly. Rip out all the C++11 constructs and replace them with C++98, I suppose? @sgpyc ? I can't think of any CUDA-7-specific features that we have used other than C++11 support. We ran with 6.5 for a long time.

**Comment by sgpyc** [comment]
Anything C++11 won't run, including the boost reference, and several multithread CPU / random number generator parts. Gunrock core wise, some optimizations (like __ldg?) and / or 64bit support may need to be disabled.

**Comment by jowens** [comment]
If you're really determined to do this, you can probably dig through the diffs to find non-C++11 equivalents for some of this. In particular the threading and random number generation was implemented in C++98 for a while, but that was not particularly multiplatform; the C++11 equivalents were much cleaner and nicely multiplatform. But the previous constructs did work.

**Comment by dylanht** [comment]
Thank you for the direction @jowens and @sgpyc - I will let you know how it goes if we make some progress on this.
