### ISSUE TITLE
Integration with other network analysis packages

### ISSUE THREAD

**Issue by smsaladi** [gunrock/gunrock#161]
Do you know if there is any development being done (either by the gunrock team or elsewhere) to integrate gunrock functionality into other network analysis packages like `igraph`, `networkx`, or `statnet`/`sna`? For example, the gunrock's sssp method with a GPU presumably could accelerate [`sna.geodist`](http://www.inside-r.org/packages/cran/sna/docs/geodist).

**Comment by yzhwang** [comment]
Thanks @smsaladi ! We do have noted this as one future direction of our research/development. Currently we have a student @shariiiyy working on integrating Gunrock into networkx. For now we do have python callable interfaces for each of our primary primitive. But as we refactoring and releasing the new version, we will sure start working on the integration with other packages. I will put updates here and I will have @shariiiyy also take a look at statnet/sna and especially sna.geodist. Thanks again!

**Comment by shariiiyy** [comment]
I will look into statnet/sna. Thanks

**Comment by smsaladi** [comment]
Thanks @yzhwang and @shariiiyy !

**Comment by smsaladi** [comment]
@shariiiyy , any thoughts about this? Currently, I avoid calculating centrality metrics involving geodesics on my networks because they are too large resulting in these calculations taking too long. I'd be happy to try contributing by submitting a PR if you have a suggestion/could point me in the right direction regarding how I might implement this within the existing code.

**Comment by yzhwang** [comment]
Hi @smsaladi ,

We have both Pagerank and betweenness centrality interfaces in Gunrock and they are callable from Python:
PR: https://github.com/gunrock/gunrock/blob/master/python/pagerank.py
https://github.com/gunrock/gunrock/blob/master/gunrock/app/pr/pr_app.cu
BC: https://github.com/gunrock/gunrock/blob/master/python/betweenness_centrality.py
https://github.com/gunrock/gunrock/blob/master/gunrock/app/bc/bc_app.cu

You can try that first and see if they work for you. 

There is a template for writing new graph primitives using Gunrock:
https://github.com/gunrock/gunrock/tree/master/gunrock/app/template
the driver code is here:
https://github.com/gunrock/gunrock/tree/master/tests/template

You can also try that if you want. We try to make developing new graph primitives easier, but if you have any confusion, question, or ideas for improvement, please do not hesitate filing issues or writing emails. We love feedback from outside developers!

**Comment by neoblizz** [comment]
See issue #231 (main issue).
