### ISSUE TITLE
Betweenness Centrality Run from All Sources Bug

### ISSUE THREAD

**Issue by ctcyang** [gunrock/gunrock#162]
I found a bug when running BC from all source nodes (setting --source=-1) in Master branch.

../../../gunrock_build/bin/betweenness_centrality market ../small/test_bc.mtx --src=-1 --iteration-num=10 --quick

**Comment by yzhwang** [comment]
This has been fixed in dev_debug branch. Will close this issue when we merge dev_debug back to master.
