### ISSUE TITLE
shared_lib_cc and mst do not pass CTEST on dev_debug branch

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#163]
Just figured out this as I was cleaning up the code this morning. Probably due to the inconsistency of old parameter class implementation and new info class implementation.

**Comment by neoblizz** [comment]
@yzhwang after running ctest, check the new folder created in build, it should say something like Test_result, it will have more detail on the test that failed. Alternatively you can also run `ctest -v`.
