### ISSUE TITLE
Use gonrock Bfs on my laptop?!Anyone can help me?

### ISSUE THREAD

**Issue by siamakgoudarzi** [gunrock/gunrock#164]
Hi i only want to run gunrock bfs and sssp function in my c++ program . 
I write my program in visual studio 2013 and i have cuda 7.5 on it.
My question about if i  only #include gunrock to my project and call BFS function and SSSP function so is it work for me or not?Or i need to migrate to Ubuntu and my application , some feature i use in my application must be re written again in Ubuntu?
Anyone can help me?
I read faq page and in this question :
> How would someone install it?
> 

- [x] For C/C++ programmer, integrating Gunrock into your projects is easy. Since it is a template based library, just add the include files in your code. The simple example and all the testrigs will provide detailed information on how to do this.

> 
> For programmers who use Python, Julia, or other language and want to call Gunrock APIs, we are building a shared library with binary compatible C interfaces. It will be included in the soon-to-arrive next release of Gunrock.
> 
Is it true?I only add it to my project and configure BFS and SSSP  functions?
Thanks

**Comment by neoblizz** [comment]
@siamakgoudarzi It is going to be somewhat difficult to install Gunrock on Windows, we have an issue #107 open for a Windows test build, but there has been some problems with it. Some dependencies used are linux only, so you will need to do some hacking to get it to work on Windows. If you attempt Windows installation, please let us know how it goes!

On Ubuntu it should be a fairly simple installation. We have already written very simple python and c interfaces which can be easily called from your applications to run bfs and sssp (check dev branch for most updated versions): 

https://github.com/gunrock/gunrock/tree/master/shared_lib_tests
https://github.com/gunrock/gunrock/tree/master/python

For example python call is as simple as:
```
### call gunrock function on device
gunrock.sssp(labels, nodes, edges, row, col, val, 0)
```

@yzhwang would you like to add anything?

**Comment by yzhwang** [comment]
Thanks @neoblizz ! If you only want to use gunrock's primitives in your C/C++ code, you need to build Gunrock and make the shared library (in linux it will generate libgunrock.so) Then you can call our primitives via functions in gunrock.h. Since the interface is C/C++, Python and other languages can also call it. The examples are given in the links @neoblizz provided. Let us know if you have any other question.

Also, @siamakgoudarzi  it would be really really helpful if you can report back your experience on installing Gunrock on Windows. Thank you!

**Comment by siamakgoudarzi** [comment]
Hi , i want to run example provided by  @neoblizz  , when i compile it , giv this error
What's wrong with me?

`bfs.c:7:29: fatal error: gunrock/gunrock.h: No such file or directory `
`#include <gunrock/gunrock.h>`
              .             ^
`compilation terminated.`

**Comment by jowens** [comment]
Presumably your include paths in your compiler command line do not include the parent directory of gunrock.h.

**Comment by siamakgoudarzi** [comment]
Where is the parent directory gunrock.h?
We add directory of libgonrock.so  to libconf !

**Comment by jowens** [comment]
Link paths and include paths are two different things.

**Comment by siamakgoudarzi** [comment]
Where is the parent directory of gunrock.h.?!

> Presumably your include paths in your compiler command line do not include the @parent directory of gunrock.h.

**Comment by siamakgoudarzi** [comment]
The gunrock.h file is directory gunrock/gunrock , It's true?

**Comment by jowens** [comment]
In the cloned repo, gunrock.h is in gunrock/gunrock.h.

```
$ j gunrock
/Users/jowens/Documents/working/gunrock
$ find . -name gunrock.h -print
./gunrock/gunrock.h
```

**Comment by siamakgoudarzi** [comment]
Hi dear @jowens 
1.Copy libgonrock.so to /usr/local/lib
` cp build/lib/libgunrock.so /usr/local/lib/ `

2.Add this line to bashrc
`export LD_LIBRARY_PATH=/home/siam/s/gunrock/build/lib/:/usr/local/lib:$LD_LIBRARY_PATH`

3.Download the  bfs.c test file that @neoblizz  [shared_lib_test ](https://github.com/gunrock/gunrock/tree/master/shared_lib_tests) 
and change #include "gunrock/gunrock.h"
then Complie it with this command 

`nvcc bfs.c -I/home/siam/s/gunrock/  -L/home/s/gunrock/build/lib -lgunrock`
 Or
`gcc bfs.c -I/home/siam/s/gunrock/  -L/home/s/gunrock/build/lib -lgunrock`

then `run ./a.out` and the result is 
`Node_ID [0] : Label [0]
Node_ID [1] : Label [1]
Node_ID [2] : Label [1]
Node_ID [3] : Label [1]
Node_ID [4] : Label [2]
Node_ID [5] : Label [2]
Node_ID [6] : Label [2]`

My steps is true or not????

Thanks

**Comment by yzhwang** [comment]
Hi @siamakgoudarzi ,

Looks like your results are correct. You can find the toy graph we use for bfs test here in the code:
https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_bfs.c#L19

**Comment by siamakgoudarzi** [comment]
siam@siam1404-2:~/s/gunrock$ nvcc shared_lib_bfs.c -I/home/siam/s/gunrock/ -L/home/s/gunrock/build/lib -lgunrock
siam@siam1404-2:~/s/gunrock$ ./a.out 

Node_ID [0] : Label [0]
Node_ID [1] : Label [1]
Node_ID [2] : Label [1]
Node_ID [3] : Label [1]
Node_ID [4] : Label [2]
Node_ID [5] : Label [2]
Node_ID [6] : Label [2]

**Comment by siamakgoudarzi** [comment]
I have some question about [ shared_lib_bfs.c](https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_bfs.c)

Assume that i want to run a huge graph (4.8milion(4847571) nodes and 68.9milion(68993773) edges) like as [liveJurnal in snap](https://snap.stanford.edu/data/soc-LiveJournal1.html)

I have a application read this data as from file  , and can load data to memory
In Line 12 - Line 15 some variables set in my case i think its same
`-L12 struct GRTypes data_t;                 // data type structure`
`-L13  data_t.VTXID_TYPE = VTXID_INT;         // vertex identifier`
`-L14 data_t.SIZET_TYPE = SIZET_INT;         // graph size type`
`-L15 data_t.VALUE_TYPE = VALUE_INT;         // attributes type`

‍‍‍`-L15‍‍‍‍ ‍struct GRSetup config = InitSetup();   // gunrock configurations `

But , what about row_indices and col_indices?
    `int num_nodes = 7, num_edges = 15;  // number of nodes and edges`
    `int row_offsets[8]  = {0, 3, 6, 9, 11, 14, 15, 15};`
    `int col_indices[15] = {1, 2, 3, 0, 2, 4, 3, 4, 5, 5, 6, 2, 5, 6, 6};`

Its true about the adjacency list representation of this graph
-0: => 1 ,  2 , 3
-1: => 0 , 2 , 4
-2: => 3 , 4  , 5
-3: => 5 ,6 
-4: => 2 ,5 , 6
-5: => 6
So I think its a directed graph ?true or not?

**Comment by jowens** [comment]
You should just read the graph in MatrixMarket format, which you can
download from the University of Florida repository (maybe SNAP too):

http://www.cise.ufl.edu/research/sparse/matrices/SNAP/soc-LiveJournal1.html

and then run

breadth_first_search market soc-livejournal.mtx

Reading the graph in MatrixMarket format builds all the graph data
structures for you.

If you want to run it as an undirected graph, add the --undirected flag.
Otherwise, it's treated as directed.

JDO

**Comment by siamakgoudarzi** [comment]
Hi dear @jowens 
This picture is an example graph , it's true for this values 
`int num_nodes  , num_edges ` and `int row_offsets[]`  and `int col_indices[]  `

![Easy Graph Example](https://cloud.githubusercontent.com/assets/7514876/16956763/ef6b9dc4-4dee-11e6-9083-88371feb0399.JPG)


Thanks

**Comment by jowens** [comment]
I'm not sure what you're asking. In general Gunrock is *only* going to be useful for large graphs, and you certainly don't want to enter those by hand. You want to read them into Gunrock in a standard matrix format (and let Gunrock build all the data structures for you); for us, that's MatrixMarket format.

**Comment by siamakgoudarzi** [comment]
I understand what you say. But I say assume that we have an application that use gonrock and don't have any MMx format.
Clearly My question is , in this link we have an example for using gonrock and in this example use `num_nodes  , num_edges , row_oofsets and col_indices ` , this variables set to graph data structure for input data called garphi , and create same graph for output data grapho.
So my question is , if we want to use graph in the above picture , so what about these two variables `row_oofsets` and `col_indices `.
This is a question for understanding concept  , And i know gunrock use for larj graphs
Thanks.

**Comment by yzhwang** [comment]
Hi @siamakgoudarzi ,
If you want to use Gunrock that way, you are doing exactly the right thing. In this case, you only have a small graph, so we manually input it. But if you have a very large graph you generated from other stage of the application, you need to present it using the CSR format:
https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29
And, in a CSR format, you need at least two arrays: one is row offsets array, another is column indices array. The edge weight array is optional. If you are familiar with sparse matrix, you will find it very easy to use. We currently don't support other graph representation format as input (internally, we sometimes use COO too).
So back to your question, what about these two arrays: you just use these two arrays to define a graph. And I think you are correct in the picture you showed in the previous comment. For larger graph, you just need to fill these two arrays and use them to initialize the graph. As for how you do it, you can choose to read it in from mtx file, or even your own file loader, or create it in memory with other program.
Does this answer your question?

**Comment by siamakgoudarzi** [comment]
Thanks My Answer is CSR format. Very Niceeeeeeeeeeeeeeeeeeeeeeeeeeeee ;)
Now i use ubuntu But If my work done in right time , I switch back to windows and test it on windows 
Thanks!

**Comment by siamakgoudarzi** [comment]
Node_ID [425839] : Label [2147483646]
Node_ID [425840] : Label [2147483646]
Node_ID [425841] : Label [2147483646]
Node_ID [425842] : Label [2147483646]
Node_ID [425843] : Label [2147483646]
Node_ID [425844] : Label [2147483646]
Node_ID [425845] : Label [2147483646]
Node_ID [425846] : Label [2147483646]
Node_ID [425847] : Label [2147483646]
Node_ID [425848] : Label [2147483646]
Node_ID [425849] : Label [2147483646]
Node_ID [425850] : Label [2147483646]
Node_ID [425851] : Label [2147483646]

Hi this number means 2147483646 Out of reach , for BFS_KERNEL ?
Thanks

**Comment by jowens** [comment]
That label is a curious number because it is at the boundary between 31 and 32 bits. So I'm guessing maybe you are overflowing? We have a 64b Gunrock (the base version is 32b) that will handle larger labels; @yzhwang can you offer commentary?

**Comment by siamakgoudarzi** [comment]
I check this result again  , I thinks it's because this node can not reach from source node .In the shared_lib_bfs , the source node for default is node by id 0?
Where i can change source node ?

**Comment by jowens** [comment]
Command-line option `--src=N`, where `N` is the starting node number.

**Comment by yzhwang** [comment]
Hi @siamakgoudarzi 

You are right that the label is unreachable (so they are set to Invalid, where it should be ther MAX_UINT in this case).

In our master branch, we actually provide an interface where you can set source:
https://github.com/gunrock/gunrock/blob/master/gunrock/app/bfs/bfs_app.cu#L496
But we didn't expose it in the shared lib example. 

In our dev_debug branch, you can see we actually changed that so that BFS can support multiple sources:
https://github.com/gunrock/gunrock/blob/dev_debug/shared_lib_tests/shared_lib_bfs.c
You can try using dev_debug branch for now or wait for our next release so that we can merge the new feature into master.

**Comment by yzhwang** [comment]
What @jowens suggested is also correct, setting source in the command line option is used when user include Gunrock's header files but not use the shared lib. All of those codes are here:
https://github.com/gunrock/gunrock/tree/master/tests

Which I don't think is what you want, but just in case you just want to run a BFS with a mtx file as the input, you can try running make in https://github.com/gunrock/gunrock/tree/master/tests/bfs/ and run the generated executable there.

**Comment by siamakgoudarzi** [comment]
Hi Dear @yzhwang  , Thanks 

> In our dev_debug branch, you can see we actually changed that so that BFS can support multiple sources:
https://github.com/gunrock/gunrock/blob/dev_debug/shared_lib_tests/shared_lib_bfs.c
You can try using dev_debug branch for now or wait for our next release so that we can merge the new feature into master.

This Link Help me  , But I have a Question , When i running this code with `int srcs[3] = {0,1,2};` array and setup config with   `struct GRSetup *config = InitSetup(3, srcs);   // gunrock configurations` 
What's about the result ?? The result of  print with this peace of code about witch source ? 0 or 1 or 2 ?
`    int node; for (node = 0; node < graphi->num_nodes; ++node)
printf("Node_ID [%d] : Label [%d]\n", node, labels[node]);`
