### ISSUE TITLE
Error In Build Gunrock -  cmake .. not found boost-include

### ISSUE THREAD

**Issue by siamakgoudarzi** [gunrock/gunrock#166]
Hi i am new to use this Library :8ball: 
[This Thread closed ](https://github.com/gunrock/gunrock/issues/165) But I can not Solve my problem and i can not use gonrock .
For build Gunrock I use this Link and step by step follow instruction ([Building Gunrock](http://gunrock.github.io/gunrock/doc/latest/building_gunrock.html))
For install boost i use this link ([Boost installation ] (http://www.boost.org/doc/libs/1_58_0/doc/html/bbv2/installation.html) ) : But some problem here accured
First step i download this file ( [Ubuntu 1.58 Boost](http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz) ) 
Step 2 : extract boost 
In Step 3 of installation of boost 
`./b2 install --prefix=PREFIX ` 
I run this command with this PREFIX
`./b2 install --prefix=/usr/local/boost`

what am i doing to install boost 1.58  correctly again?
I found some solution in google for installation boost from repository 
`sudo apt-get install  libboost-all-dev`
But now i have boost 1.54
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
After Install boost 1.54 and run cmake .. give these errors : 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
METIS_LIBRARY
    linked by target "gunrock" in directory /home/siamac/gunrock/gunrock
    linked by target "betweenness_centrality" in directory /home/siamac/gunrock/tests/bc
    linked by target "breadth_first_search" in directory /home/siamac/gunrock/tests/bfs
    linked by target "connected_component" in directory /home/siamac/gunrock/tests/cc
    linked by target "pagerank" in directory /home/siamac/gunrock/tests/pr
    linked by target "single_source_shortest_path" in directory /home/siamac/gunrock/tests/sssp
    linked by target "direction_optimizing_bfs" in directory /home/siamac/gunrock/tests/dobfs
    linked by target "HITS" in directory /home/siamac/gunrock/tests/hits
    linked by target "SALSA" in directory /home/siamac/gunrock/tests/salsa
    linked by target "minimum_spanning_tree" in directory /home/siamac/gunrock/tests/mst
    linked by target "who_to_follow" in directory /home/siamac/gunrock/tests/wtf
    linked by target "degree_centrality" in directory /home/siamac/gunrock/tests/topk

-- Configuring incomplete, errors occurred!
can i work with boost 1.54 ? 
For my work i want to use some graph algorithm in gpu and i want to run my dataset with gunrock single-gpu implementation , I don't know Boost is necessary  or not?
I couldn't find gunrock/repo when i run ls in gunrock :
`build           codesnaps  externals  LICENSE.TXT  README.md         tests`
`cmake           dataset    FAQ.md     output       shared_lib_tests  tools`
`CMakeLists.txt  doc        gunrock    python       simple_example`
When i ls in hunrock/gunrock : 
`app             coo.cuh  global_indicator  gunrock.h  priority_queue`
`CMakeLists.txt  csr.cuh  graphio           oprtr      util`

Thanks for supporting.

**Comment by jowens** [comment]
Yes, we do require Boost 1.58. I believe that you can run without Metis, but I would bet it's easier to simply install Metis and link against it.

I personally don't use Linux as my primary OS, but I would encourage you to use a package manager to install these packages (e.g., `apt-get`) if at all possible. 

We are generally going to be much more able to help you with Gunrock installation and issues than we are with installing Gunrock's prereqs.

**Comment by siamakgoudarzi** [comment]
You say linux is not your primary OS!But in [building Gunrock link](http://gunrock.github.io/gunrock/doc/latest/building_gunrock.html) Only Speak About Ubuntu  , Ubuntu And Ubuntu!!!!!
`Gunrock current release has been tested on Linux Mint 15 (64-bit), Ubuntu 12.04, 14.04 and 15.10` `with CUDA 7.5 installed, compute architecture 3.0 and g++ 4.8. We expect Gunrock to build and `
`run correctly on other 64-bit and 32-bit Linux distributions, Mac OS, and Windows.`

**Comment by siamakgoudarzi** [comment]
Hi dear  Jowens , Finally i install boost correctly 
When i run cmake .. command i give these follwing output 
<hr>
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
METIS_LIBRARY
    linked by target "gunrock" in directory /home/siamac/gunrock/gunrock
    linked by target "betweenness_centrality" in directory /home/siamac/gunrock/tests/bc
    linked by target "breadth_first_search" in directory /home/siamac/gunrock/tests/bfs
    linked by target "connected_component" in directory /home/siamac/gunrock/tests/cc
    linked by target "pagerank" in directory /home/siamac/gunrock/tests/pr
    linked by target "single_source_shortest_path" in directory /home/siamac/gunrock/tests/sssp
    linked by target "direction_optimizing_bfs" in directory /home/siamac/gunrock/tests/dobfs
    linked by target "HITS" in directory /home/siamac/gunrock/tests/hits
    linked by target "SALSA" in directory /home/siamac/gunrock/tests/salsa
    linked by target "minimum_spanning_tree" in directory /home/siamac/gunrock/tests/mst
    linked by target "who_to_follow" in directory /home/siamac/gunrock/tests/wtf
    linked by target "degree_centrality" in directory /home/siamac/gunrock/tests/topk

-- Configuring incomplete, errors occurred!
<hr>
I only want to use BFS and SSSP for now  , I will to give a dataset like livejurnal to Gunrock BFS and SSSP algorithms and give result and time on my system.
I don't know nothing about gunrock and i want to hands-dirty with using gonrock functions! I don't know whats it next step"?

How to use 
` linked by target "single_source_shortest_path" in directory /home/siamac/gunrock/tests/sssp`
`linked by target "breadth_first_search" in directory /home/siamac/gunrock/tests/bfs`
Sorry for my terrible English :(
Thanks

**Comment by jowens** [comment]
You need to install Metis. Hopefully it puts parmetis.h in /usr/local/include or /usr/include, and the parmetis library in /usr/local/lib or /usr/lib.

**Comment by siamakgoudarzi** [comment]
Thanks Dear jowens
Hi.
In your first comment of this issue you say 

> Yes, we do require Boost 1.58. I believe that you can run without Metis, but I would bet it's easier to simply install Metis and link against it.
...

But in last comment you say 

> You need to install Metis. Hopefully it puts parmetis.h in /usr/local/include or /usr/include, and the parmetis library in /usr/local/lib or /usr/lib.

!!!

**Comment by siamakgoudarzi** [comment]
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Configuring done
-- Generating done
-- Build files have been written to: /home/siamac/gunrock/build
I think Finally Done!
So i now will to start with gunrock , Thanks Thanks Dear jowens and all of your team members :)

**Comment by siamakgoudarzi** [comment]
[  1%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/./gunrock_generated_mgpucontext.cu.o
CMake Error at gunrock_generated_mgpucontext.cu.o.cmake:206 (message):
  Error generating
  /home/siamac/gunrock/build/gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/./gunrock_generated_mgpucontext.cu.o


make[2]: *** [gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/./gunrock_generated_mgpucontext.cu.o] Error 1
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
make: *** [all] Error 2
