### ISSUE TITLE
Undefined references error occurred when make the code

### ISSUE THREAD

**Issue by pkuwalter** [gunrock/gunrock#168]
Hi, I cloned the code to my laptop, there are some errors when I make the code, can you help me how can  solve this problem?

When I type `make -j16` the error occurs, which is list below:
`[ 90%] Linking CXX executable ../../bin/breadth_first_search
CMakeFiles/breadth_first_search.dir/__/__/externals/moderngpu/src/breadth_first_search_generated_mgpucontext.cu.o：Founction ‘mgpu::CudaDevice::DeviceString() const’
/home/walter/gunrock/externals/moderngpu/src/mgpucontext.cu:173：For ‘mgpu::stringprintf(char const*, ...)'Undefined references
collect2: error: ld returned 1 exit status
tests/bfs/CMakeFiles/breadth_first_search.dir/build.make:172: recipe for target 'bin/breadth_first_search' failed
make[2]: *** [bin/breadth_first_search] Error 1
CMakeFiles/Makefile2:445: recipe for target 'tests/bfs/CMakeFiles/breadth_first_search.dir/all' failed
make[1]: *** [tests/bfs/CMakeFiles/breadth_first_search.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by yzhwang** [comment]
Hi @pkuwalter ,
Could you let us know your OS, CUDA version so that we can better understand the issue?
Also, could you provide the sequence of your commands since the git clone?

**Comment by pkuwalter** [comment]
Hello, @yzhwang ,
Thank you for your quickly response.  The detailed information is as follow:
I run the code under ubuntu 16.04 with gcc 4.8.5. 
And the commands sequence are as follow:
`git clone https://github.com/gunrock/gunrock.git`
`cd gunrock`
`git submodule init && git submodule update`
`cd ../`
`mkdir gunrock_build && cd gunrock_build`
`cmake ../gunrock/`
`make -j16`

**Comment by yzhwang** [comment]
Hi @pkuwalter ,
We haven't tested our library on ubuntu 16.04 yet. AFAIK, it works fine on ubuntu 14.04 with the same gcc and CUDA version you are using.
Could you step in the gunrock directory: gunrock/tests/bfs/ and run make (or make -j16) from there and report the results? If it complains that gitsha1.c cannot be found, you can run:
cp gunrock/gunrock/util/gitsha1.c.in gunrock/gunrock/util/gitsha1.c
to create one.

Let me know the results. It looks like some dependency problem in moderngpu (the order of mgpuutil.cpp and mgpucontext.cu is messed up, but I'm not sure).
