### ISSUE TITLE
An error occurred while running direction_optimizing_bfs

### ISSUE THREAD

**Issue by huch159** [gunrock/gunrock#169]
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)

I hope someone can help me.

**Comment by yzhwang** [comment]
Hi @huch159 ,
Please provide more info so that we can help you.
We need your OS info, CUDA version, and the command lines you ran before you saw the error. And if possible, the complete output of the error. Thanks!

**Comment by huch159** [comment]
Thank you,
my system is ubuntu 16.04 and cuda version is 8.0
command lines is:../../gunrock_build/bin/direction_optimizing_bfs market ../large/roadNet-CAroadNet-CA.mtx --src=0 --undirected --idempotence --alpha=2 --beta=2 --iteration-num=10 --queue-sizing=1.5 --queue-sizing1=1.5
the result is :
       Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (425957 vertices, 2099732 edges):
    Degree   0: 108877 (25.56%)
    Degree 2^0: 43181 (10.14%)
    Degree 2^1: 108515 (25.48%)
    Degree 2^2: 92756 (21.78%)
    Degree 2^3: 45534 (10.69%)
    Degree 2^4: 18887 (4.43%)
    Degree 2^5: 6553 (1.54%)
    Degree 2^6: 1461 (0.34%)
    Degree 2^7: 188 (0.04%)
    Degree 2^8: 5 (0.00%)

Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (425957 vertices, 2099732 edges):
    Degree   0: 108877 (25.56%)
    Degree 2^0: 43181 (10.14%)
    Degree 2^1: 108515 (25.48%)
    Degree 2^2: 92756 (21.78%)
    Degree 2^3: 45534 (10.69%)
    Degree 2^4: 18887 (4.43%)
    Degree 2^5: 6553 (1.54%)
    Degree 2^6: 1461 (0.34%)
    Degree 2^7: 188 (0.04%)
    Degree 2^8: 5 (0.00%)

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)

**Comment by yzhwang** [comment]
You mean CUDA 8 RC right? Looks like a string is assigned to NULL. http://coliru.stacked-crooked.com/a/6abd8a3807f8a528
We haven't tested Gunrock on ubuntu 16.04 + CUDA 8 yet. Could you either try ubuntu 14.04 + CUDA 8 (that has been tested) or ubuntu 16.04 + CUDA 7.5? You could also dive into the code and figure out the string related bug, if not we will try to test ubuntu 16.04 + CUDA 8 when we have both OS and CUDA 8 installed (could be weeks from now).

**Comment by huch159** [comment]
thank you@yzhwang,I will try to test Gunrock again on ubuntu 16.04 +CUDA 8.0.AND if you  successfully test Gunrock on ubuntu 16.04 +CUDA 8.0 one day，I hope you can tell me how to do it.

**Comment by ptheywood** [comment]
This looks the same as #113 which I had on Ubuntu 14.04 a while ago, which has been fixed in the `dev` branch but has not yet been merged into master. 

PR #116 contains the fix for an issue with the same error message (Update the `getUserinfo` routine in `/gunrock/utils/sysinfo.h` to use `getpwuid` rather than `getlogin`)

**Comment by yzhwang** [comment]
Thanks @ptheywood !
@huch159 If this solves your problem, let me know so that I can close this issue.

**Comment by huch159** [comment]
@yzhwang，Yes,it really works!Thanks@ptheywood ！
