### ISSUE TITLE
mst invalid memory access bug in dev_debug branch

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#170]
When using LB_CULL as the advance method, MST will generate incorrect value in the EgRm functor during an advance call:
https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/app/mst/mst_enactor.cuh#L675
At first I thought it might be the V2E bug, but when I changed it into V2V it still exists. I could track it into Write_Global_Output function:
https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/oprtr/edge_map_partitioned_cull/kernel.cuh#L251
It's either there or here:
https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/oprtr/edge_map_partitioned_cull/kernel.cuh#L635
Since before this the s_id (u in edge_map_partitioned_cull/kernel.cuh) is correctly set.

The problem could be recreated just by using dataset/small/test_bc.mtx

When I switch to using LB advance method, the bug is gone but further in the code it won't step into CULL filter. I haven't debugged that yet. But I think @sgpyc may have some insights there since this commit:
https://github.com/gunrock/gunrock/commit/bf8a55861da0231fcbe3d84f800eb475518559fb

@sgpyc Is it OK for you to help look into this when you have time? Solving this may also solve another bug I'm currently debugging in label propagation in dev_debug branch. Thank you.

**Comment by sgpyc** [comment]
LB_CULL = LB advance + CULL filter, is that what the original code intended to do?

**Comment by yzhwang** [comment]
So LB_CULL fused advance+filter? And if I only want to use advance, I should not use LB_CULL?

**Comment by sgpyc** [comment]
Yes. Don't use LB_CULL if what you want is not advance + filter.
I think putting null filter (condFilter always true) should achieve the same effect of LB, but at this moment, just keep the traversal-mode of MST to LB_LIGHT, which was what it originally set, or LB if that pass all the tests.

**Comment by yzhwang** [comment]
Thanks for the reply @sgpyc !
I switched to LB advance, and advance worked fine. Currently the program will collapse before the second filter operator call:
https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/app/mst/mst_enactor.cuh#L818
If I step into the kernel call, it looks like in cta_work_progress's Reset_() function, there is a illegal mem access of p_counter:
https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/util/cta_work_progress.cuh#L222

The label propagation program will also collapse here, but only earlier (in the enactor initialization phase). With the same illegal mem access of p_counter.

One thing to notice is that for both mst and lp primitive, Yuduo and I are still using the old single-GPU enactor framework with updated interface but not the updated framework (fullqueue_core, stop_condition, etc.), would this be the matter too?

@yuduowu just mention you so that maybe you can provide some insights here too.

For mst, the latest dev_debug version with the following command line for tests/mst will recreate the problem:
bin/mst_executable market /data/gunrock_datasets/small/test_bc.mtx

**Comment by jowens** [comment]
@sgpyc just hopin' you can provide a little insight for @yzhwang, we'd like to get the release out the door. Thanks!

**Comment by sgpyc** [comment]
I just push a commit 0793e1d, changed mst traversal mode to LB and added a enactor.Reset().
It didn't solve the problem, now cuda-gdb complains about https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/oprtr/advance_base.cuh#L59 , called by https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/oprtr/edge_map_partitioned/kernel.cuh#L464 , called by https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/oprtr/edge_map_partitioned/kernel.cuh#L637 ; on the CPU side, the call stack stops at https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/oprtr/advance/kernel.cuh#L460 , called by https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/oprtr/advance/kernel.cuh#L1007 , called by https://github.com/gunrock/gunrock/blob/dev_debug/gunrock/app/mst/mst_enactor.cuh#L434 , which is the advance call of CyRmFunctor.

It's not a issue of Reset_() function of cat_work_progress, since that function is a host function, which can't caused device kernel to have illegal memory access.

The cuda-gdb reports illegal memory access in the advance call of MarkFunctor, I think that's where things went wrong.

**Comment by yzhwang** [comment]
Thanks @sgpyc ! I will look into that functor. I didn't think it went wrong at such early stage since the data flow has been correct until the very last filter call. I will see what happened in that MarkFunctor then.

**Comment by sgpyc** [comment]
I used cuda-gdb on the tests/mst/test_mst.cu (can't find bin/mst_executable) with -O0 -g -G flags. @yzhwang let me know if you have other method / version of code to test out.

**Comment by yzhwang** [comment]
@sgpyc  mst_executable just means any executable you generated from the latest dev_debug branch, so I think you are using the correct version. Will let you know when I have new findings. Thanks!

**Comment by yzhwang** [comment]
@sgpyc Could you check out the current head of dev_branch and try running the mst again? I committed my changes and now the code should be the same with the local version I'm using. With debug_info set to 1 in mst_enactor.cuh, the data flow before filter with EgRmFunctor is the same with the correct version in the master branch. cuda-gdb shows that the program still dies at:
oprtr/cull_filter/kernel.cuh:328
There is a D2H cudaMemcpy in the work_progress.Reset_() function. So still p_counter's problem.
Strange thing is the filter with PtrJmpFunctor, which is called earlier can run perfectly, and it seems that the input frontier of filter with EgRmFunctor is correct (I output it and it is the same with the master branch).
The reason I want you to try it is that you might spot the error easier/quicker than I do since the current filter framework is built by you. I will work on this more tomorrow.

**Comment by sgpyc** [comment]
@yzhwang please check whether 653b3fa fix the bug

**Comment by jowens** [comment]
:hushed:

**Comment by yzhwang** [comment]
Thanks @sgpyc . It did fix the bug. I didn't notice that the original version in master uses values for the latter two filter calls. Now when I go through the code, I think the reason is that the pointer jumping filter could get loaded multiple times with two key ping-pong arrays, and that will pollute the key array. It's good that now the bug is out of the way.

Unfortunately, it is not the last bug before release 0.4, I will now go ahead debugging label propagation, which has a bug in the Enactor Init function. Hopefully this bug will provide some useful info. I will now close this issue. Thanks again!

**Comment by jowens** [comment]
:stuck_out_tongue_winking_eye:
