### ISSUE TITLE
Benchmarking : Time of Shared Lib ( BFS and sssp) with socLiveJurnal DataSet

### ISSUE THREAD

**Issue by siamakgoudarzi** [gunrock/gunrock#171]
Hi dear i want to run BFS and SSSP in sharedLib 
I Use [socLiveJournal ](https://snap.stanford.edu/data/soc-LiveJournal1.html) with 4,847,571 nodes and 68,993,773 edges.

I want to give result from gunrock Library for two algorithms 
1.BFS 2.SSSP
I read data from txt file and copy them to row_offset and col_indice array  
I run gunrock_bfs(grapho, graphi, config, data_t); in a do _ while first time result is .4 sec and then result change from .174 sec to .164 sec

`

int stopValue=1;
	do{
	 clock_t cend = 0;
	clock_t cstart = clock();
         gunrock_bfs(grapho, graphi, config, data_t);
	 cend = clock();
	printf ("\n%.3f sec", ((double)cend - (double)cstart)* 1.0e-6);
	stopValue++;
	//scanf("%d",&stopValue);
	}while(stopValue<20);

`

# - 0.423  sec
- 0.174  sec
- 0.166  sec
- 0.164  sec
- 0.164  sec
- 0.163  sec
- 0.163  sec
- 0.161  sec
- 0.164  sec
- 0.168  sec
- 0.165  sec
- 0.166  sec
- 0.165  sec
- 0.163  sec
- 0.165  sec
- 0.166  sec
- 0.165  sec
- 0.167  sec
- 0.164  sec

My Question is Why first time 3x smaller than other time?

**Comment by yzhwang** [comment]
Hi @siamakgoudarzi 

I'd say this is because of the first time initialization overhead. You can refer to the documentation here:
http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#initialization
If you like, you can also find out more about the details of run time by using CUDA profiler. There are lots of resource out there.

**Comment by siamakgoudarzi** [comment]
how am i give serial time of BFS and SSSP and other algorithm  in gunrock paper?!
I wrote a serial version for SSSP and gives many time to execute !?

**Comment by yzhwang** [comment]
I've already answered the question in email, so will close this issue.
