### ISSUE TITLE
Question about gunrock running time nad speedup fo 7 graphs

### ISSUE THREAD

**Issue by bobper** [gunrock/gunrock#173]
Hi
I run SSSP and BFS with gunrock using Shared lib model for 7 graphs
these are my result:
DataSet   ---------- speedup against serail version for **[BFS ]**
1.[web-NotreDame](http://snap.stanford.edu/data/web-NotreDame.html) ------- : 6.1x
2.[roadNet-TX](http://snap.stanford.edu/data/roadNet-TX.html) ------------ : 36.97x
3.[roadNet-CA](http://snap.stanford.edu/data/roadNet-CA.html) -----------  : 47.08x
4.[soc-LiveJournal1](http://snap.stanford.edu/data/soc-LiveJournal1.html) ------- : 10.81x
5.[com-dblp.ungraph](http://snap.stanford.edu/data/com-DBLP.html) ----- : 6x
6.[com-youtube.ungraph](http://snap.stanford.edu/data/com-Youtube.html) - : 7.59x
7.[com-lj.ungraph](http://snap.stanford.edu/data/com-LiveJournal.html) ---------: 10.36x

-------DataSet   -------- speedup ------ against serail version for **[SSSP ]**
1.[web-NotreDame](http://snap.stanford.edu/data/web-NotreDame.html) ------- : 8.67x
2.[roadNet-TX](http://snap.stanford.edu/data/roadNet-TX.html) ------------ : 96.65x
3.[roadNet-CA](http://snap.stanford.edu/data/roadNet-CA.html) -----------  : 107.56x
4.[soc-LiveJournal1](http://snap.stanford.edu/data/soc-LiveJournal1.html) ------- : 17.84x
5.[com-dblp.ungraph](http://snap.stanford.edu/data/com-DBLP.html) ----- : 11.25x
6.[com-youtube.ungraph](http://snap.stanford.edu/data/com-Youtube.html) - : 11.19x
7.[com-lj.ungraph](http://snap.stanford.edu/data/com-LiveJournal.html) ---------: 19.32x

Before ask Question in mentioned : 
**My average time is computation time and transfer from cpu to gpu** 

My Question 
_1.For_ road network ( roadNet-TX and roadNet-CA) in BFS and SSSP the result is very good , Which optimization use to give these speedup?another way why for road network  these result are very good?

_2.For_ graph 1 webNotreDame and for graphs 5 and 6 dblp and youtube speedup is from 8.67x to 11.25x for SSSP and  6x to 7.59x for BFS , I think Because of these graphs are not very large and for time we have transfer time so for these graphs speedup is not very good as road networks is it true?
Or What happened for these graphs?  

_3. For_ social networks graph 4 and graph 7 speedup not good but these graphs have large graphs?

**Comment by jowens** [comment]
What is the serial code against which you are comparing?

**Comment by siamakgoudarzi** [comment]
I implemented my own BFS and SSSP single thread app 
For gunrock I use [Shared_lib model BFS](https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_bfs.c) nad [shared lib model SSSP](https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_sssp.c)

**Comment by jowens** [comment]
Without knowing anything about your code, it would be difficult to compare Gunrock to it. More meaningful is comparing against other published graph packages, which you will find in Section 5 of the Gunrock paper (http://escholarship.org/uc/item/6xz7z9k0#page-8).

**Comment by siamakgoudarzi** [comment]
I think for small-degree large-diameter graphs , the result of gunrock is so good? 
Which optimization techniques help to give these Speedup?
My code is single thread of these pseudocode
![This is BFS Algorithm](https://cloud.githubusercontent.com/assets/7514876/18411813/0fafc6ee-7795-11e6-97df-df0726d4913f.png)
And it's SSSP algorithm : 
![sssp1](https://cloud.githubusercontent.com/assets/7514876/18411820/266691ce-7795-11e6-8c4d-154db0892a04.png)
![sssp](https://cloud.githubusercontent.com/assets/7514876/18411824/380cf864-7795-11e6-9747-40f868f4e6ea.png)

I need to know about Speedup against These algorithm not about other graph packages !
Thanks

**Comment by siamakgoudarzi** [comment]
I think this issue can be open :(

**Comment by jowens** [comment]
In general, Gunrock looks better on small-diameter, large-degree graphs (as measured by edge traversals per second, for instance). Social networks would be representative examples. Road networks (low-degree, high-diameter) are ones where Gunrock does not do so well. The primary reason is there is more concurrency in social-network-type graphs and Gunrock does a good job of turning that into parallelism. (This would generally be true for any GPU implementation, not just Gunrock.) Section VI.B. here (http://escholarship.org/uc/item/2t69m5ht#page-4) goes into this analysis in detail; hopefully you will find that useful.

**Comment by siamakgoudarzi** [comment]
I read Gunrock ppop2016 paper many times:)
I think Road networks( small-degree large-diameters ) for all parallel algorithm is difficult parallelism , but for gunrock , Because use Thread-Warp CTA
![threadwarpcta](https://cloud.githubusercontent.com/assets/7514876/18412108/0e289434-779c-11e6-9cb0-793917ab317b.JPG)
But I think , I don't know and don't full understand concept of  Thread warp CTA correctly??!

**Comment by siamakgoudarzi** [comment]
And these good Performance for Road networks , Because of my sequential implementation not good at these networks.

**Comment by jowens** [comment]
At least in our comparisons, serial implementations are really good at road-network SSSP (for instance: http://escholarship.org/uc/item/8qr166v2#page-9, Figure 5).

**Comment by jowens** [comment]
Thread-warp CTA is the best strategy for road networks in our implementation, but it doesn't solve the larger problem of road networks simply not exposing enough parallelism to keep the whole GPU busy.

**Comment by siamakgoudarzi** [comment]
gunrock for single thread comparison uses boost , Where can i found  Boost BFS and Boost SSSP of your implementation?

**Comment by jowens** [comment]
http://www.boost.org/doc/libs/1_61_0/libs/graph/doc/breadth_first_search.html
http://www.boost.org/doc/libs/1_61_0/libs/graph/doc/dijkstra_shortest_paths.html

**Comment by siamakgoudarzi** [comment]
Thanks a lot

**Comment by neoblizz** [comment]
I am assuming your questions were answered. Just create a new issue or comment on this one if you have further questions regarding the comparison.

**Comment by tuandungdao** [comment]
Can you give me source code BFS solve roadNet-CA and roadNet_TX, please

**Comment by jowens** [comment]
All of our source code is on github. Here's how you get it:

https://gunrock.github.io/docs/#compilation
