### ISSUE TITLE
Thorough test of current graph primitives in dev_debug

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#174]
The basic set is bfs, sssp, cc, bc, and pr.
wtf/salsa/hits have no CPU references, but can test runtime errors instead of correctness.

**Comment by sgpyc** [comment]
current testing status:
**BFS**
Tested: {15 datasets} x {default, undirected} x {normal, idempotence} x {skip pred, mark pred} x {top_down, direction optimizing} x {32bit VertexId, 64bit SizeT, 64bit VertexId} x {default, LB, TWC, LB_CULL} x {GTX1070 x 1, K40c x 4}
Issues: 1. idempotence has illegal memory access on multiple GPUs 
 2. idempotence + direction optimizing produces incorrect results on single-GPU for directed graphs
 3. out of memory for some tests

**SSSP**
Tested: {15 datasets} x {default, undirected} x {skip pred, mark pred} x {32bit VertexId, 64bit SizeT} x {default, LB, TWC, LB_CULL} x {K40c x 4}
Issues: 1. a few random illegal memory access on multiple GPUs, regardless of options
  2. out of memory for some tests

**BC**
Tested: {15 datasets} x {32bit SizeT, 64bit SizeT} x {default, LB, LB_CULL, LB_LIGHT, LB_LIGHT_CULL} x {GTX 1070 x 1}
Issues : 1. LB_CULL does not work properly, as the backward phase uses the same advance policy as the forward phase, which performs extra filter when LB_CULL is used for advance-only operation
 2. out of memory for some tests

**CC**
Tested: {15 datasets} x {default, undirected} x {32bit SizeT, 64bit SizeT} x {default, LB, TWC, LB_LIGHT, ALL_EDGES} x {GTX 1070 x 1}
Issues: none

**PR**
Tested: {15 datasets} x {undirected + unnormalized + uncompensated, default + normalized + uncompensated, default + normalized + compensated, undirected + normalized + uncompensated, undirected + normalized + compensated} x {32bit Value, 64bit Value} x {32bit SizeT, 64bit SizeT, 64 bit VertexId} x {default, LB, TWC, LB_LIGHT} x {GTX 1070 x 1}
Issues: 1. a few double free error reported

**Comment by jowens** [comment]
@sgpyc can you file individual issues on the issues you name above? those all seem like they ought to get fixed before release ...

**Comment by sgpyc** [comment]
I will see whether can get them fixed soon (most trigger illegal memory access error, which is good), otherwise I will try to disable particular options

**Comment by yzhwang** [comment]
@sgpyc could you send me a log or let me know where the results sit on mario/luigi? I want to help with some of the above issues. Thanks!

**Comment by sgpyc** [comment]
I think now most bugs are about error handling when out of memory happens (test_xxx.cu will continue even errors are reported), and a few illegal memory access problems.

BC has few wrong labels for a few test cases, BFS marks wrong parents by LB_CULL, CC sometimes deadlocks for road-networks, and PR has memory-double-free issue (a few occurrences over thousand? and I don't know how to reproduce this error). The logs are under /home/sgpyc/Projects/gunrock/tests/*/eval/*/*.txt on mario. the run_real.sh script will test all combination of options (takes days), Don't run it unless necessary, but it lists the actual command line parameters to produce the logs.

**Comment by jowens** [comment]
Same comment above. If there are individual issues—wrong labels, wrong parents, deadlock, double-free—please file those as individual issues so that we can work in parallel on solving them.

**Comment by jowens** [comment]
In particular: "Here is a command-line that fails on <say> mario: ```bfs market graph.mtx --foo --bar```".

**Comment by yzhwang** [comment]
@sgpyc I will check the logs and file these as individual issues. So there should be 4 issues:
wrong label in BC,
deadlock in CC,
wrong predecessors in BFS,
double memory-free in PR.

I will post the links to the issues here, you can put comments there if there is anything inaccurate.
