### ISSUE TITLE
Update documentations

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#178]
For all the updated code, should update their doxygen docs. When finished and run doxygen, there should be zero warning.

**Comment by sgpyc** [comment]
how to show doxygen warnings? I run "doxygen gunrock.doxygen" within the doc directory, there is no warning in the output; when checking the generated documents, there is no sign pointing to warning or such things. But it's impossible that after so much interface changes, the warnings are not triggered.

**Comment by jowens** [comment]
I think there's a `warn.log` that's generated.

**Comment by sgpyc** [comment]
thanks, saw it and working on that

**Comment by yzhwang** [comment]
Commit 63165be60c1aaab0dbb401f6d4246cfe2342376d reduced all the warnings generated by code.
TODOs:
1) For some updated interfaces, make sure that the description is accurate.
2) Fix the missing link in release_notes.md.

**Comment by yzhwang** [comment]
Fixed all the doxygen warnings. @sgpyc If you think there is anything I need to add to the new interface, please specify the links here and reopen this, otherwise I will just close this for now.
