### ISSUE TITLE
bc algorithm

### ISSUE THREAD

**Issue by fvella** [gunrock/gunrock#18]
Hi,
I am trying to perform your bc implementation.
/bin/test_bc_6.5_x86_64 market ../../dataset/small/test_bc.mtx

I have several errors:
Computing reference value ...
CPU BC finished in 0.000000 msec.
[../../gunrock/app/bc/bc_enactor.cuh, 299] edge_map_forward::Kernel failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_enactor.cuh, 512] filter_forward::Kernel failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 437] BC Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_problem.cuh, 429] BCProblem cudaMemcpy data_slices to d_data_slices failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 436] BC Problem Data Reset Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_enactor.cuh, 109] BCEnactor cudaBindTexture row_offset_tex_ref failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 437] BC Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_problem.cuh, 429] BCProblem cudaMemcpy data_slices to d_data_slices failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 436] BC Problem Data Reset Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_enactor.cuh, 109] BCEnactor cudaBindTexture row_offset_tex_ref failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 437] BC Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_problem.cuh, 429] BCProblem cudaMemcpy data_slices to d_data_slices failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 436] BC Problem Data Reset Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_enactor.cuh, 109] BCEnactor cudaBindTexture row_offset_tex_ref failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 437] BC Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_problem.cuh, 429] BCProblem cudaMemcpy data_slices to d_data_slices failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 436] BC Problem Data Reset Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_enactor.cuh, 109] BCEnactor cudaBindTexture row_offset_tex_ref failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 437] BC Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_problem.cuh, 429] BCProblem cudaMemcpy data_slices to d_data_slices failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 436] BC Problem Data Reset Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_enactor.cuh, 109] BCEnactor cudaBindTexture row_offset_tex_ref failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 437] BC Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_problem.cuh, 429] BCProblem cudaMemcpy data_slices to d_data_slices failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 436] BC Problem Data Reset Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_enactor.cuh, 109] BCEnactor cudaBindTexture row_offset_tex_ref failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 437] BC Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/bc/bc_problem.cuh, 168] BCProblem cudaMemcpy d_bc_values failed (CUDA error 77: an illegal memory access was encountered)
[test_bc.cu, 452] BC Problem Data Extraction Failed (CUDA error 77: an illegal memory access was encountered)

Does your bc implementation  work ?
Thanks,

Flavio

**Comment by yzhwang** [comment]
Hi Flavio, the program passed the tests here. I'm meeting multiple paper deadlines right now. I will get back to you after two weeks time. Meanwhile, you probably can try this repo which also has a BC implementation on the GPU: https://github.com/Adam27X/graph-utils

**Comment by fvella** [comment]
Thanks!

**Comment by yzhwang** [comment]
Hi Flavio, I've just fixed a bug in BC and you can try it and see if it works now. Would love to help you with any comparisons.
