### ISSUE TITLE
Update the annotated code examples using new interface

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#182]
I will try a version and let @sgpyc do an editing pass afterwards.

**Comment by yzhwang** [comment]
For SALSA, I think we certainly support the old interface and we haven't ported that to new interface yet. For BFS, @sgpyc do you think we need to rewrite it using new interface?

**Comment by yzhwang** [comment]
@sgpyc I've updated the annotated code for SSSP using multi-GPU interface. Could you take a look at the enactor file and fill in some blanks? I'm not sure how to shrink the code size. Thanks!
The purpose of annotated code is to show how Gunrock's interface works, so it doesn't matter if it doesn't compile. The important thing is to cut off the unnecessary lines but still show the key framework of Gunrock primitives.

**Comment by yzhwang** [comment]
Also, see if the new sssp annotated code make sense?

**Comment by sgpyc** [comment]
Please check 98f00a5
