### ISSUE TITLE
some regexps appear to pass even if result is very very wrong

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#186]
[61.txt](https://github.com/gunrock/gunrock/files/468564/61.txt)

**Comment by yzhwang** [comment]
@neoblizz @jowens Could it be recreated in ctest on head of pre-release branch on mario/luigi/midas? Just want to recreate and try to fix it.

**Comment by jowens** [comment]
I'd like another pair of eyes on this. ctest runs fine on midas. I ran it
with a clean clone on mario and it gave compute_61 errors on build (using
cuda 8.0). So I disabled compute_61 and built and all tests fail; there's a
driver issue. Can we update the driver?

Anyway, it's the regexes in the above "61.txt" link that matter.

On the good side, all ctests with the driver failure fail properly. :)

```
[/home/jowens/working/gunrock/gunrock/util/info.cuh, 447 @ gpu 32767]
cudaGetDevice failed (CUDA error 35: CUDA driver version is insufficient
for CUDA runtime version)
[/home/jowens/working/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 0]
cudaSetDevice failed. (CUDA error 35: CUDA driver version is insufficient
for CUDA runtime version)
[/home/jowens/working/gunrock/gunrock/util/info.cuh, 461 @ gpu 0]
cudaStreamCreate failed. (CUDA error 35: CUDA driver version is
insufficient for CUDA runtime version)
```

**Comment by neoblizz** [comment]
In the 61.txt file, I see a lot of the following errors;

```
[/home/jowens/working/gunrock/gunrock/util/array_utils.cuh, 172 @ gpu 0] cuda_props cudaHostRegister failed. (CUDA error 30: unknown error)
[/home/jowens/working/gunrock/gunrock/util/array_utils.cuh, 172 @ gpu 0] work_progress cudaHostRegister failed. (CUDA error 30: unknown error)
[/home/jowens/working/gunrock/gunrock/util/array_utils.cuh, 172 @ gpu 0] enactor_stats cudaHostRegister failed. (CUDA error 30: unknown error)
[/home/jowens/working/gunrock/gunrock/util/array_utils.cuh, 172 @ gpu 0] frontier_attribute cudaHostRegister failed. (CUDA error 30: unknown error)
[/home/jowens/working/gunrock/gunrock/util/array_utils.cuh, 172 @ gpu 0] output_length cudaHostRegister failed. (CUDA error 30: unknown error)
```

Wasn't the `cudaHostRegister` bug in CUDA 8 and was later fixed? This has been update on midas by Kerry, but I don't think anyone updated CUDA 8 on mario or luigi.

**Comment by jowens** [comment]
Agreed, @neoblizz. I thought `cudaHostRegister` was a Pascal-only problem; maybe not. Anyway, driver version on mario is 352.79.

**Comment by jowens** [comment]
@neoblizz, the driver was updated on midas, so the regression is fixed. This issue, though, is because even though the run was failing everywhere, the regexes were still indicating passing, so we need better regexes for regression.

**Comment by yzhwang** [comment]
@neoblizz  Does the cudaHostRegister error only holds for Pascal architecture GPU?
As for the regex error, I think it is related to PASS_REGULAR_EXPRESSION. INCORRECT also matches CORRECT... so I guess we have to update the PASS_REGULAR_EXPRESSION. @neoblizz Could you try to look at it and see if it is the problem?

**Comment by neoblizz** [comment]
I got the `cudaHostRegister` on K40C as well with CUDA 8.0, but after the update it was fixed. I feel like the problem was with the driver-cuda relationship, and not the gpu itself. Because it worked fine on Yuechao's 1070, which is also pascal.

I'll take a look at the regex expression.

**Comment by sgpyc** [comment]
There is no available CUDA 8.0 driver for K40c on Linux 64bit system at the moment, on NVIDIA's driver website. I don't know what driver version comes with the official CUDA 8.0 toolkit release, and whether the cudaHostRegister issue has been fixed in that version.

**Comment by neoblizz** [comment]
@sgpyc we have the one for 1080 installed on midas and K40C recognizes that as well.

**Comment by sgpyc** [comment]
don't want to run into the "recognized" vs. "officially supported" issue. Upgrading luigi and installing CUDA 8; if all goes well, will do the same for mario too

**Comment by sgpyc** [comment]
CUDA 8 toolkit release 8.0.44 comes with driver 367.48, and pre-release branch has no issue running on luigi. midas has the same driver, and it seems okey on both device 0 (GTX 1080) and device 1 (K20c).

**Comment by neoblizz** [comment]
Regexps was fixed along with the issue https://github.com/gunrock/gunrock/issues/243, the error was because we look for expression "CORRECT" and say the test is passed, but the word "INCORRECT" has "CORRECT" in it, and that is how the regex marked the test as passed even though it clearly said "INCORRECT". I found this mildly amusing.
