### ISSUE TITLE
Reason for First initialization BFS smaller than SSSP

### ISSUE THREAD

**Issue by siamakgoudarzi** [gunrock/gunrock#187]
Why first Initialization Of BFS is very smaller than SSSP.
One of a reason I think in SSSP sent more data from host to device , Like Weight array within size of |E|.
in this [comment](https://github.com/gunrock/gunrock/issues/171#issuecomment-238045790) spoken about first initialization Cuda and Gunrock.
Someone give me Other reason for this behavior of SSSP

**Comment by yzhwang** [comment]
What is smaller? Run time? And by first initialization, do you mean loading time before the actual execution of the algorithm?

**Comment by siamakgoudarzi** [comment]
Yes Run time.
For SSSP First launch  is [ Time: 0.610935 sec ]
and other launch is [ Time: 0.383 ] sec  in average.

For BFS First launch is [ Time:  0.354 sec ]
and other launch is [ Time: 0.123 ]
Time: Loading time + execution of algorithms

**Comment by jowens** [comment]
You could probably run it through the profiler to see where the time is going. Assuming it's the same graph, I think "sends more data for SSSP" is a sensible explanation, since SSSP has to send edge weights.

**Comment by siamakgoudarzi** [comment]
Yes , Edge weights send and I think Gunrock need more data  for execute SSSP  , is it true? 
Maybe Some Local Updating distance Array |V| ?? Is it true?

**Comment by jowens** [comment]
I think the difference between {data needed for BFS, data needed for SSSP} is that SSSP needs edge weights for each vertex.

**Comment by siamakgoudarzi** [comment]
Thanks , I think i can not ask my question very well :(

**Comment by jowens** [comment]
I encourage you to run both programs through the profiler to understand where the difference in time is coming from.
