### ISSUE TITLE
pre-release branch edge bc incorrect results with --partition_method=random

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#188]
The problem can be repeated by running run.sh in gunrock/tests/bc.
When removes the flag --partition_method=random, the results of edge bc is correct.

**Comment by yzhwang** [comment]
remvoed edge bc solved this bug. Need to work on dev_debug to see how to properly implement edge BC under Brande's algorithm framework.

**Comment by jowens** [comment]
please add edge-bc + brandes as an issue for post-release.
