### ISSUE TITLE
Add changelog and known issues

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#189]
Now these are in a google doc:

https://docs.google.com/document/d/1GU3AfIy3vB8XZH7u2kd7pBo9lkbvdnHru_U5FHvKTGk/edit?usp=sharing

**Comment by yzhwang** [comment]
@sgpyc I have updated the known issues. Please confirm that they all make sense.

**Comment by yzhwang** [comment]
@sgpyc Could you take a look at the known issues in release_note.md?

**Comment by jowens** [comment]
For the new strategies, two things would be useful per strategy:
- When would a user want to use this strategy? The notes say what the strategies *are* but not *when they should be used*.
- Where are they used within the 0.4 release? 

For DOBFS w/ normal-BFS, it might be worth a line to say how this is used (e.g., "there's now just one executable, named X", "call it with the following command-line parameters")

**Comment by yzhwang** [comment]
@sgpyc @jowens Please take a look at the latest release note and see if there's still anything we need to change. Thanks!

**Comment by jowens** [comment]
Edits checked in, with a comment on @yzhwang's recent commit.

**Comment by yzhwang** [comment]
@sgpyc If you are happy with the content, please close this issue :-)

**Comment by sgpyc** [comment]
I'm happy with that
