### ISSUE TITLE
TC under new interface has illegal mem access for large graphs

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#194]

**Comment by Laurawly** [comment]
By running TC under dev branch on soc-LJ1 dataset, the code crashes here:
[../../gunrock/util/array_utils.cuh, 209 @ gpu 0] scanned_edges[] cudaMalloc failed (CUDA error 2: out of memory)

But if I turn on array_utils debug option, there's no more errors.

**Comment by Laurawly** [comment]
It turns out that max_queue_sizing and max_in_sizing is not correctly set initially in test_tc.cu. Bug fixed.

**Comment by yzhwang** [comment]
Thank you @Laurawly !!!
