### ISSUE TITLE
Wrong Label in BFS, top of pre-release branch 

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#197]
Here are the command lines that cause incorrect results for BFS.
It happens on 2 and 3 GPUs with direction optimal option on.

[bfs.txt](https://github.com/gunrock/gunrock/files/507695/bfs.txt)

**Comment by sgpyc** [comment]
Some of these "INCORRECT" labels are caused by running out of memory, which needs to change the run_real.sh script; others may be caused by illegal memory accesses in cull_filter::warp_cull, disabled by 23490d3

**Comment by yzhwang** [comment]
Closed. For OOM issue, I've added it as a known issue in ae9079f2044462d6fa9229dd95774ef4e5be6f3a
