### ISSUE TITLE
Possible CUDA memory allocation failure on huge datasets

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#2]
When running BFS (and possibly BC) on kron_g500-logn21 and soc-LiveJournal1 for undirected graph and choose to keep predecessor for each node, there is possible CUDA memory allocation failure if the device memory of the card you are using is not enough. Need to add free device memory detecting code.

**Comment by neoblizz** [comment]
This is a really old issue, I believe it has been resolved. If not, re-open and re-assign please.
