### ISSUE TITLE
Update building_gunrock.md

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#203]
Are some parts of the documentation outdated? @shariiiyy and @neoblizz could you guys make sure the current version works and if not, write up a new building guide for pre-release branch and then update the current version from pre-release branch?
https://github.com/gunrock/gunrock/blob/pre-release/doc/building_gunrock.md

**Comment by neoblizz** [comment]
@yzhwang everything is to-date. I updated this when I revamped CMakeLists.txt for dev_debug. And I just tested the MGPU command as well, it works! The only thing I can see that we may change is;

```
GUNROCK_GENCODE_SM<> (default: GUNROCK_GENCODE_SM30=ON) change to generate code for different compute capability.
```

Is Gen 3.0 default? If not, then what will be the default in the pre-release?

**Comment by yzhwang** [comment]
@neoblizz Thanks!
I think you can update that by saying that the users can choose to turn on/off compute capability versions by changing the following code:
https://github.com/gunrock/gunrock/blob/pre-release/CMakeLists.txt#L152
And indicate which compute capability versions are on for current build (which are 30,35,61).

**Comment by yzhwang** [comment]
Thanks @neoblizz for your commit! Could I consider this issue resolved?

**Comment by neoblizz** [comment]
Yes! Building Gunrock doc is also updated.
