### ISSUE TITLE
Error during gunrock installation

### ISSUE THREAD

**Issue by faerbena** [gunrock/gunrock#204]
Hi,

I am very new to CUDA and gunrock, and I don't really know what I am doing wrong during the installation. Here are my specs:
- Ubuntu 14.04.4
- CUDA 7.5
- GeForce GTX TITAN Black

Here is the output when I run `make`:
```
[  8%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at gunrock_generated_mgpucontext.cu.o.cmake:207 (message):
  Error generating
  /home/nadja/Documents/gunrock/build/gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/./gunrock_generated_mgpucontext.cu.o


make[2]: *** [gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o] Error 1
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
make: *** [all] Error 2
```

Can somebody give me a hint what I am doing wrong?
Thank you.
Nadja

**Comment by neoblizz** [comment]
This is fixed in `pre-release` branch, if you don't wish to switch branches please turn this option to `OFF`: https://github.com/gunrock/gunrock/blob/master/CMakeLists.txt#L139

**Comment by faerbena** [comment]
Thank you very much, this little trick did the job!

**Comment by neoblizz** [comment]
You're welcome, let us know how your experience goes with using Gunrock!
