### ISSUE TITLE
defaults for BC

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#206]
I note that in @sgpyc's tests, he uses `--src=randomize2 --in-sizing=1.1 --queue-sizing=1.2` (plus a traversal mode). Should we make these defaults?

**Comment by sgpyc** [comment]
These parameters are more like "best for 1st try", especially the sizing factors. They may work well for most graphs, but for huge graphs reaching the GPU memory limit, specially sizing factors (less than 1.1 and 1.2) are needed to get them pass the OOM error.

The default now is --queue-sizing=1.0 and --in-sizing=1.0. I have not checked the traversal mode differences. Should be able to made them default when the best values are figured out.

Same for #207 and #208, plus BFS and SSSP

**Comment by jowens** [comment]
So probably we should make the "best for 1st try" the defaults then.

**Comment by sgpyc** [comment]
addressed in ff9a410

**Comment by neoblizz** [comment]
@sgpyc can these default issues be closed?
