### ISSUE TITLE
JSON filenames for BFS/rmat should indicate rmat params

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#214]
Right now if "dataset" is empty, the filename just has BFS_date.json. Should instead map something like this `--rmat_scale=21 --rmat_edgefactor=128` to a dataset name like `rmat_s21_e128`.

**Comment by yzhwang** [comment]
Since this is the bottleneck of creating plot, I'll take care of this. (I submitted the first draft of dissertation last night)

**Comment by yzhwang** [comment]
@sgpyc I've added scale and edgefactor info for rmat files in json filename. For rgg file it's gonna be a oneliner too. My question here is, what info do we need to compute edge number for rgg file? would thfactor be the one? I read BuildRggGraph() and there seems to be no direct equation to compute the edge number.

**Comment by yzhwang** [comment]
@sgpyc Nevermind, I think it's gonna be impossible to compute edge number from equation. But I can add that edge number info after BuildRggGraph() is called. All good here.

**Comment by yzhwang** [comment]
@sgpyc Saw your commit for adding edge/node number in json info. @jowens Now generated rmat and rgg datasets will have some parameters in their json file names. See the latest two commits on pre-release by YC and me.

**Comment by jowens** [comment]
Love it!
