### ISSUE TITLE
[Plot] Impact of Avg. Degree on the performance of different advance methods

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#216]
How performance (GTEPS) of LB, LB_CULL, and TWC changes over avg. degree.

@sgpyc You mentioned we have that kind of results in Gunrock already. Are they results on various rgg and rmat graphs? Could we keep the number of nodes fixed while changing the number of edges so as to increase/decrease the avg. degree? I assume we can.

@jowens My mental picture for this is a line chart with one line per advance method, y axis is GTEPs and x axis is avg. degree.

**Comment by jowens** [comment]
Straightforward to do this from the JSONs we have already, _but_ I will need to figure out average degrees for different graphs, that's the hard part. 

We want to put them in `gunrock/io/datasets_info/datasets.json`.

**Comment by sgpyc** [comment]
Yes, we can keep other rmat / rgg parameters, and change the edge factors.
@yzhwang Let the know what parameters you want (e.g. rmat scale = 19, edge factors = {1, 2, 4, 8, 16...}), and I can do write a script to do that

**Comment by jowens** [comment]
@sgpyc That script would be really useful, thanks. Also please address https://github.com/gunrock/gunrock/issues/214 before you or @yzhwang runs that script.

**Comment by jowens** [comment]
I think median degree is probably more meaningful than mean degree, but you're right, mean degree is much easier, so let's start with that, good call.

**Comment by jowens** [comment]
I would likely try to do one graph that incorporates both rmat/rgg and real-world cases. I think we'd all be interested to see how they differ.

**Comment by yzhwang** [comment]
Hi guys, so I've run some tests and here's my plan:

**Comment by yzhwang** [comment]
Hi guys, I've run some tests and here is my plan:

**Comment by jowens** [comment]
That seems reasonable for starters ... we want to see the output graph and then decide if we need more. Please check in whatever script you use to do this so it's easy for, say, me to run more.

**Comment by yzhwang** [comment]
Just had a discussion with YC and here's the updated version for you @sgpyc 
First we switched to always add --undirected flag so that we will have larger frontier, hence better perf.
rgg --rgg_scale=21 --rgg_thfactor={0.2,0.3,0.4,0.6,0.8} so that the avg degree would be roughly {4,8,15,34,61}
rmat --rmat_scale=21 --rmat_edgefactor={1,2,4,8,16} so that the avg degree would be roughly {4,8,16,32,64}
This way, the avg degree on x axis will match so that we can plot both rgg and rmat on a single plot.

**Comment by sgpyc** [comment]
Added a script run_avgDegree.sh in 9a09fd8 . @yzhwang please try whether that works or not

**Comment by yzhwang** [comment]
Thank @sgpyc I've updated the script and have run it. So I realized that this is not testing the avg degree, but the degree distribution's impact to performance.
Yes with the increasing of avg degree, the performance increases, but that's more because of the increasing size of frontier. Instead, if we put an rgg graph and an rmat graph together, because we have carefully set the parameters so that they have exactly same number of nodes, roughly same number of edges, so they have the same avg degree. Now I still see a huge performance difference between this two graphs. Why? I think it's because of their degree distributions are different. For LB, with the same avg degree and roughly same size graphs, rmat will always outperform rgg by the factor of 5. I assume for TWC, things will likely be the opposite.
Anyway, I just think the avg degree vs performance line chart are still necessary, but we should interpret it from the perspective of degree distribution difference, rather than avg degree difference.

**Comment by jowens** [comment]
![bfs_avg_node_degree](https://cloud.githubusercontent.com/assets/976970/20031484/635c1a38-a335-11e6-8032-e6f4230ffb62.png)

This is "everything YC ran last month", with x axis = edges visited / nodes visited. (It's the latest run for every individual command line, 32b SizeT, undirected, mark_preds = false.)

**Comment by jowens** [comment]
So, it's pretty noisy, and I'd be happy to get guidance as to how I can make this more meaningful. (Note this is all the real-world datasets, no RGG or RMAT.)

**Comment by jowens** [comment]
![bfs_avg_node_degree](https://cloud.githubusercontent.com/assets/976970/20031510/1ae88ede-a336-11e6-9fd4-543723086351.png)
![sssp_avg_node_degree](https://cloud.githubusercontent.com/assets/976970/20031513/1ae9fa08-a336-11e6-8c38-36cc24dc4b19.png)
![cc_avg_node_degree](https://cloud.githubusercontent.com/assets/976970/20031511/1ae8a4a0-a336-11e6-93e7-4e979f88c1fa.png)
![pagerank_avg_node_degree](https://cloud.githubusercontent.com/assets/976970/20031512/1ae8fbc6-a336-11e6-9672-8faddbf0f0f9.png)

**Comment by yzhwang** [comment]
I think this proves that with the same average node degree but different degree distribution, you can still get very different performance for LB and TWC. CC's performance behaves that way because it doesn't use any advance. PR's LB and TWC performance differs, that's good, and I think the reason LB and LB_LIGHT perform differently is LB is doing load balancing on the output frontier (each block gets same number of edges), while LB_LIGHT is doing load balancing on the input frontier (each block gets same number of neighbor lists).
I think to observe better, we should only use BFS with no idempotence, or a modified version of PR (sample a sub frontier, and always use that frontier. The reason to sample a sub frontier is to force sorted search to work, or the all edge frontier will make lb too easy, the reason to keep using that sub frontier is to eliminate the impact of changing frontier over iteration). I feel that the major reason of noise is that we have too many choices, and we must limit our choices.
@jowens Could you try with rmat and rgg? I have run the script on BFS and have generated the output, how should I provide the json output to you? A dir in gunrock.io repo?

**Comment by jowens** [comment]
Just dump them into the root directory. Do they have a tag in the JSON? If not I'll special-case it.

**Comment by jowens** [comment]
Er, check them into "gunrock-output".

**Comment by yzhwang** [comment]
gotcha.

**Comment by yzhwang** [comment]
@jowens please see my latest commit in io repo.

**Comment by jowens** [comment]
is everything Nov 7? That will help with my filtering. (This is why we have tags now. :) )

**Comment by yzhwang** [comment]
Yes.

**Comment by jowens** [comment]
![rgg rmat_bfs_avg_node_degree](https://cloud.githubusercontent.com/assets/976970/20078086/fc020cce-a4f3-11e6-8f97-58ade77ba588.png)

**Comment by sgpyc** [comment]
@yzhwang has the script to generate rgg and rmat results.
I think the things we see here are too many factors come together, so a lot of noises.
To see a clear trend of different traversal modes, we may consider these:

1. Only focus on graph that with large frontiers, so per-iteration overhead can be neglected. Maybe no rgg or road network for BFS, they are testing on many kernel launches vs. actual compute performance, if @yzhwang don't want to cover that extreme end.

2. For large frontiers, the per-advance performance is related to degree distribution of the vertices in the active frontier. What we see here are the avg. effects of all advance and all vertices. We may need to consider the cases of the same avg. degree but different distributions. For example, a rmat / social network like graph will have different performance from the one (e.g. small-world) with almost even distribution. 
Fixing graph type and changing some parameters may help here, but the explanation need to touch on how those ideal cases related to real world graphs as plot above.

**Comment by jowens** [comment]
probably better if I have separate tick marks for RGG vs. RMAT, stay tuned.

**Comment by sgpyc** [comment]
I can tell RGG and RMAT apart for LB, but not TWC.

**Comment by jowens** [comment]
![rgg rmat_bfs_avg_node_degree](https://cloud.githubusercontent.com/assets/976970/20079019/bc02c5ba-a4f7-11e6-8c78-395435639b43.png)

**Comment by yzhwang** [comment]
I agree @sgpyc , what we need here is an advance run for only one iteration. With the same number of nodes with different degree distributions. Perhaps we could create a primitive that only does this? Like I said before, it samples a sub frontier from the graph and do one iteration of advance. What do you guys think?

**Comment by jowens** [comment]
Can we record timing per iteration and store it in the JSON? I could see that would be useful in other contexts. I would understand if it would make the overall primitive run slower b/c of increased synchronization.

**Comment by yzhwang** [comment]
Do we have other per-iteration data? like edge/node-visited per-iteration? I just want an example. It not we can start having some, I agree that they are very useful data.

**Comment by jowens** [comment]
It does not appear that we do. The `process_times` field is an example of a list in JSON. I think maybe making `iteration_info` a dict at the top level, and having fields within it that are `nodes_visited`, `edges_visited`, `iteration_time`, etc., would make sense.

**Comment by yzhwang** [comment]
@jowens I will create an issue and assign myself for this.
