### ISSUE TITLE
[Plot] The impact of alpha value in the push-pull switching heuristic

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#217]
For rgg, rmat, real-world scale-free, and real-world roadmap, choose one graph per category, generate line chart for performance (GTEPs) vs. different alpha values.

I decide to leave out the beta value here, @sgpyc would agree that the performance is insensitive to the change of beta value for GPU.

**Comment by sgpyc** [comment]
The latest DOBFS doesn't use alpha and beta values (as what they are in Beamer's original DOBFS algorithm). The similar ones are do_a and do_b (I guess should give them better names).

The beta (or do_b) value controls when to switch back from pull to push, and matters when the graph is web-graph-like. The performance differences of difference beta (do_b) are not too much, as I remember.

**Comment by jowens** [comment]
@sgpyc Helpful if you can hack together a script for this. It does seem like simply varying `do_a` is the right thing to do here. I think we can do this on many datasets, though, we can just put `do_a` on the x axis and MTEPS on the y axis and have several lines, one per dataset.

**Comment by yzhwang** [comment]
@sgpyc Do you have a good feeling of a good set of do_a we should choose? (Suppose we want to do this experiment on scale-free graphs)
