### ISSUE TITLE
[Plot] Group bar chart to show the impact of different parameter switch on performance

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#218]
These parameter switches are:
For BFS: idempotence/LB/TWC/pull-enabled vs. baseline. I'm not sure whether we need to do this one by one or do it cumulatively.
For SSSP: PQ vs baseline (@sgpyc is enabling PQ as easy as uncomment that piece of code in SSSP enactor?)
Other switches include mark_pred, dir/undir, but when I come to think of it, dir/undir will change the graph topology so maybe we shouldn't show that?
What other parameters do we need guys?

**Comment by sgpyc** [comment]
32bit vs. 64bit VertexId / SizeT?

The PQ part haven't been touched for a long time (since the beginning of mGPU framework), and may need sometime to get it running for 1GPU. But most likely that only requires interface matching, and data preparation, not the core algorithm / implementation itself.

**Comment by jowens** [comment]
@sgpyc Do you think the BFS runs that you already did are a good start here? Seems like it to me.

**Comment by yzhwang** [comment]
I have idempotence vs non-idempotence, LB vs TWC (both non-idempotence), and push-only vs. push-and-pull (both non-idempotence and LB) already, that experiments I used two social networks and two road networks. We can repeat the experiment with more datasets.  @sgpyc thinks bring back PQ for current version is not as simple as uncomment that piece of code, so maybe we start with BFS first? We can also add pred/no-pred here, the difference is number of memory access (pred will double it) per iteration.

**Comment by jowens** [comment]
@yzhwang is there more to do here? reassign me if so.

**Comment by neoblizz** [comment]
Closing this issue, does not seem relevant now. Reopen if needed.
