### ISSUE TITLE
__any / __all conflicts / please only include the std:: things we need

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#22]
@ydwu @yzhwang Can you narrow down the "using namespace std" directive? Import only the symbols we need, not the whole namespace? 

https://isocpp.org/wiki/faq/coding-standards#using-namespace-std

e.g. "using std::cout" ?

Cliff says:

> Hi John,
> 
> Further insight from our compiler team:
> 
> This ambiguity occurs because the user code introduces names from the std namespace in global scope with a "using" directive:
> 27 "/Users/jowens/Documents/working/gunrock/gunrock/csr.cuh" 2
> using namespace std;
> 
> To avoid the ambiguity error, the user can explicitly qualify the use of __any and __all with scope resolution operator ("::").
> i.e. old code:
> 599 "/Users/jowens/Documents/working/gunrock/externals/cub/cub/block/../util_ptx.cuh"
>    return __any(cond);
> 
> 573 "/Users/jowens/Documents/working/gunrock/externals/cub/cub/block/../util_ptx.cuh"
>    return __all(cond);
> 
> code with fix:
> 599 "/Users/jowens/Documents/working/gunrock/externals/cub/cub/block/../util_ptx.cuh"
>    return ::__any(cond);
> 
> 573 "/Users/jowens/Documents/working/gunrock/externals/cub/cub/block/../util_ptx.cuh"
>    return ::__all(cond);
> 
> Can you please try this out and let us know if that takes care of it?  If so, I'll ask Duane to apply the same fix to CUB as well.
> 
> Thanks,
> Cliff

**Comment by jowens** [comment]
@ydwu So I know it'll *work* if you ::__any instead of __any, but I don't think that's the right option; someone's going to add code in 6 months, not know that rule, and break it again. I think it's safer if we just import only the std stuff we actually need/use, rather than the whole namespace. Other opinions? @yzhwang ?

**Comment by jowens** [comment]
@ydwu Also if you only change our __all and __any calls, you will not get the CUB __all and __any calls, and that's a lot harder for us to patch.

**Comment by jowens** [comment]
@ydwu of course CUB does the same thing—using namespace std—not helpful, @dumerrill. :)

**Comment by ydwu** [comment]
Perhaps I didn't understand the problem well, I eliminated importing whole namespace std in the commit: [1380f62e6e746f3bf5e7011e4dc19fc80844fcdb](https://github.com/gunrock/gunrock/commit/1380f62e6e746f3bf5e7011e4dc19fc80844fcdb), does this corresponding to "rather than the whole namespace"?

**Comment by jowens** [comment]
Great. Thank you. I think this fixes up my issues. I appreciate it!

Now to track down tr1/random errors.
