### ISSUE TITLE
fix up --help and documentation with respect to adding new command-line params

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#220]
"Current way of adding things to usage() / --help is quite troublesome (need to change all test_xxx.cu files), and they haven't been updated for some time. May go through them all together after the release and pulling @wetliu 's parameter class."

see: https://github.com/gunrock/gunrock/commit/6bd85476c58bcfe2c429c6979f8e189a9091da8b#commitcomment-19702837

No hurry.

**Comment by wetliu** [comment]
Let's work it out after release @sgpyc

**Comment by neoblizz** [comment]
Addressed in dev_refactoried.
