### ISSUE TITLE
[Plot] Add per-iteration data for JSON output

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#221]
https://github.com/gunrock/gunrock/issues/216#issuecomment-258990203

**Comment by sgpyc** [comment]
the EnactorStats has nodes_queued and edges_queued counters. But they are accumulation values, and have one version on CPU and another version on GPU. Still thinking where / how to combine them for per-iteration stats.

Timing wise, the CPU timer should be good to provide precision of tens of microseconds.

**Comment by neoblizz** [comment]
Closing this issue, does not seem relevant now. Reopen if needed.
