### ISSUE TITLE
Optional Dependencies: METIS

### ISSUE THREAD

**Issue by olauq** [gunrock/gunrock#225]
In the building instrcutions METIS is listed under 'Optional Dependencies', yet there is no way given of how to get cmake to stop looking for it. How is this done?

http://gunrock.github.io/gunrock/doc/latest/building_gunrock.html

**Comment by neoblizz** [comment]
@olauq it is optional, so, after installation if you don't have `metis` and use the metis partitioner, it will just tell you that metis was not found and you cannot use the said partitioner. You don't have to do anything in cmake to make it stop looking for it.

**Comment by olauq** [comment]
In my case cmake does not seem to finish generating setup unless I comment out all link targets:

"CMake Warning at cmake/FindMetis.cmake:47 (MESSAGE):
  Metis was requested but support was not found,

    run `sudo apt-get install metis` or `/dep/install_metis.sh` for installation.
Call Stack (most recent call first):
  CMakeLists.txt:41 (include)


-- Project Added: bfs
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
METIS_LIBRARY
    linked by target "gunrock" in directory ..../gunrock/gunrock
    linked by target "bfs" in directory ..../gunrock/tests/bfs

-- Configuring incomplete, errors occurred!
See also "..../gunrock/build/CMakeFiles/CMakeOutput.log"."

**Comment by neoblizz** [comment]
It shouldn't fail, can you please post the full `CMakeOutput.log`?

**Comment by neoblizz** [comment]
@olauq I pushed some changes, can you please pull the latest commits and try again? It should be optional now. https://github.com/gunrock/gunrock/commit/419544a4cae749f2847ecc1b01cd4c9a36fdfd63

**Comment by olauq** [comment]
Thanks, @neoblizz, that seems to have fixed it. (I was going to post that log before, but then cmake stopped producing it, weirdly.)

**Comment by olauq** [comment]
Hm. But now it seems to fail to compile instead.
[ 11%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/bfs/gunrock_generated_bfs_app.cu.o
In file included from ~/gunrock2/gunrock/gunrock/app/problem_base.cuh:51:0,
                 from ~/gunrock2/gunrock/gunrock/oprtr/advance/kernel.cuh:13,
                 from ~/gunrock2/gunrock/gunrock/app/bfs/bfs_enactor.cuh:23,
                 from ~/gunrock2/gunrock/gunrock/app/bfs/bfs_app.cu:20:
~/gunrock2/gunrock/gunrock/app/metisp/metis_partitioner.cuh:18:21: fatal error: metis.h: No such file or directory
   #include <metis.h>
                     ^
compilation terminated.

**Comment by olauq** [comment]
This is caused (somehow) by the line
`gunrock/CMakeLists.txt(41): include(${CMAKE_SOURCE_DIR}/cmake/FindMetis.cmake)`
It must cause 'METIS_FOUND' to be defined regardless of the outcome.

**Comment by neoblizz** [comment]
@olauq I am looking into this bug, thank you for pointing it out. If you want to use gunrock meanwhile you can run the script in `/dep/install_metis.sh` to install metis. I will report back here once it is fixed.

**Comment by neoblizz** [comment]
@olauq fixed in commit; https://github.com/gunrock/gunrock/commit/d79585d7f163ea193235fc4ccea8d21403fb4aa6 can you please confirm?

**Comment by olauq** [comment]
Yes, seems to work as expected now.
