### ISSUE TITLE
documentation page that describes how we measure MTEPS for each primitive

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#226]

**Comment by jowens** [comment]
Various notes on this issue:

For BFS and BC (on non-weighted graph), we consider the visited edges to be the same as Gunrock. For BC this is accurate since we are using the same algorithm. For BFS, In Gunrock we use the same edge expansion count for both push-based and pull-based traversal, and I noticed that the only other BFS implementation which also uses push-based and pull-based traversal, Enterprise, (they call it top-down and bottom-up) also just simply accumulate the sum of neighbor list sizes for each node in the current level of frontier as traversed edges, while actually due to early exit, the actual visited edges number could be smaller (if we consider visiting an edge as the following process: visiting the destination node ID stored in column_indices array, and then call Cond and.or Apply functor for that edge). No good way to accurately count this on GPU without hurting the performance I guess.

I think for PageRank, I actually want to *multiply* `m_teps` by `search_depth` to get per-iteration MTEPS.

Oh cool! Info.cuh have it so for BC it doubles the edges, and it has if statements for every alg., I'll add this to txt2json.py. -> You are right. For BC we double the edge_queued in the forward phase, for PR one iteration it's the edge number (although for multiple iteration it may be smaller because we will filter out nodes as their PR value converged). For SSSP we just use edge_queued.
Now for computing PR and SSSP's MTEPS, I think if other algorithm is running one iteration PR, then you can just use edge number, if they are using multi-iteration PR, then we need to figure out whether there is any filtering, we cannot simply use edge number, but instead should use total_queued_edge/number_iteration if we can get that total_queued_edge number.
For SSSP, either Bellman-Ford or Dijkstra's algorithm, if the code doesn't keep queued edge number for each iteration, we cannot compute it as in either situation, an edge could be relaxed multiple times as long as its destination node ID's distance keep getting smaller.

**Comment by jowens** [comment]
In the current paper draft, I see the following: 

[@sgpyc] For BFS, tt
should use the number of edges touched, i.e. the sum of neighbor list lengths of all visited vertices, not the total number of edges in the graph [@yzhwang] agreed. changed. 

What are we actually doing in our results (and what did we do in the PPoPP paper)? Are there primitives where we don't visit all vertices? If we do visit all vertices, than doesn't "the sum of neighbor list lengths of all visited vertices" just mean the number of edges in the graph? (assuming one connected component)

**Comment by jowens** [comment]
When we convert all graphs to undirected, does that imply 2 edges stored per actual edge, one in each direction?

**Comment by yzhwang** [comment]
@jowens For undirected graphs, yes that is true, and we have already double the edge count in our dataset description. (and I believe everyone does this) For edges touched vs. edge count. The difference comes from two places: (1) In several graphs, especially r-mat graphs, there are zero degree nodes, also there are several connected components that only have 2 nodes in them. A BFS that covers most part of the graph will actually have less edge touched than edge count, here the difference is small; (2) If we enable idempotence (which we do for BFS), we will have redundant nodes, and hence more edges touched than the number of edges in the graph.

We have always been using number of edges touched (or visited edge number as I commented before, same thing) to compute MTEPS and I think everyone else is doing that too.

**Comment by jowens** [comment]
@yzhwang can you do a pass over this, perhaps assign it to @sgpyc after you're done?

https://github.com/gunrock/gunrock/commit/674d3407f031f7851eab2a61197e2048e2389c43
