### ISSUE TITLE
Procedure to set up graph/io under /doc/graph_io_setup.md

### ISSUE THREAD

**Issue by shariiiyy** [gunrock/gunrock#229]
I just uploaded the procedure to set up graph_io. Please leave comments so that I can fix anything that's not right Thank!

**Comment by jowens** [comment]
@shariiiyy Super. So it's set up on mario and midas right now? Have you been able to run the scripts in gunrock/io/scripts? (Specifically, from scripts, `make -f plots2doc.Makefile`. You should have an `output` directory in scripts, and it assumes the gunrock repo is `../../gunrock` from the scripts directory.

**Comment by jowens** [comment]
Start by just running `altair_engines.py` from the scripts directory; it should put a bunch of plots into `output`.

**Comment by shariiiyy** [comment]
Yes I can run scripts. I have pulled the latest files and modified altair_test locally to test output. I will try running altair_engines.py now.

**Comment by jowens** [comment]
Cool. The makefile should do everything Altair-related, so if it is doing the right thing (copying a bunch of stuff into gunrock/doc/stats, I think), then we're golden.

The doc you wrote was about how to install what Altair needs, but you should also have a section about how to set up / run scripts assuming everything is installed correctly.

**Comment by shariiiyy** [comment]
I will add that section now.

**Comment by shariiiyy** [comment]
I am getting a dbus connection error when inkscape is converting svg to pdf that causing python to crash. If I run the inkscape conversion command in terminal, it will produce the pdf and it looks right although the connection error is still thrown. I haven't figured out a good way to fix it. It's kinda weird. I didn't had this problem before. If I revert graph_io to earlier version which has altair_ppopp_v03_v04.py file, python script will not crash. I am still digging how to turin the dbus connection off. It looks like it's not necessary. Do you have any thoughts on it?

**Comment by jowens** [comment]
I can't reproduce this on my Mac. Inkscape works for me. It looks horrible, but it works. The other option on unix machines is using 'rsvg' on node.js (https://github.com/altair-viz/altair/issues/279#issuecomment-265640244). I couldn't get this installed on my Mac, hence using inkscape, but maybe Linux's nice package manager will be able to run it ...

**Comment by jowens** [comment]
(Perhaps my inkscape does not use dbus on OS X, dunno.)

**Comment by jowens** [comment]
What do you mean "revert graph_io"? Do you mean reverting it before there was inkscape used at all? I'm sure that would work fine, since it's inkscape that's the problem.

**Comment by shariiiyy** [comment]
I found the problem. In fileops.py, [https://github.com/gunrock/io/blob/master/scripts/fileops.py#L118](url), it should be check_output(['inkscape', '--file=%s.svg' % (base).

Sorry I didn't make clear of what my problem is. If I ran other python scripts to generate .pdf file with earlier graph_io from a few days ago, it won't crash. But with all the files up to date, script would crash when generating pdf from svg. That dbus connection was really just a warning not an error. 

I am able to run altair_engine.py now and also the make file.

**Comment by jowens** [comment]
Ohhhh yes. You're absolutely right, please check that fix in. I'm a bad man. My error.

Can you try rsvg and see if it looks better/worse than inkscape?

**Comment by shariiiyy** [comment]
I installed librsvg2-dev (which is version 2.40.9). This is what node-rsvp under the hood. 
[engines_topc_elapsed.pdf](https://github.com/gunrock/gunrock/files/676069/engines_topc_elapsed.pdf)
[test.pdf](https://github.com/gunrock/gunrock/files/676067/test.pdf)

**Comment by jowens** [comment]
IMHO test's marks look better, but I don't like its choice of default font as much. I think neither looks as good as my OS-X-specific solution (again IMHO). @yzhwang?

(FWIW opening test.pdf in OS X's Preview crashes Preview.)

**Comment by jowens** [comment]
@shariiiyy What are the command-line options for rsvg that you're using?

**Comment by jowens** [comment]
(the fact it is so difficult to convert from one vector format to another baffles me)

**Comment by shariiiyy** [comment]
That's weird. I used my mac laptop to open both pdfs as well but they are fine.

I didn't use any option. There are only options to set resolution, zoom factor x and y,  image width and height and output format. That's it.

**Comment by jowens** [comment]
Yeah, it's not reliably crashing for me, but it does crash more than a few times. OK. There doesn't appear to be any font control with rsvg-convert, got it.

**Comment by jowens** [comment]
Can you append to your doc on what a *user* needs to do to run the scripts? I see that you're noting that users need to install pandas and numpy, but what about, say, Altair or Vega/Vega-lite? I'm looking at "local user need" at the bottom.
