### ISSUE TITLE
Who-To-Follow cudaMemcpy d_rank_curr[src] failed

### ISSUE THREAD

**Issue by ydwu** [gunrock/gunrock#23]
[yuduo@mario]build$ bin/who_to_follow market /data/gunrock_dataset/small/chesapeake.mtx 
Reading from /data/gunrock_dataset/small/chesapeake.mtx:
  Parsing MARKET COO format (39 nodes, 170 directed edges)... Done parsing (0s).
  Converting 39 vertices, 170 directed edges (unordered tuples) to CSR format...
Done converting (0s).

Degree Histogram (39 vertices, 170 edges):
    Degree   0: 4 (10.26%)
    Degree 2^0: 1 (2.56%)
    Degree 2^1: 13 (33.33%)
    Degree 2^2: 15 (38.46%)
    Degree 2^3: 6 (15.38%)

PPR Time: 0.539072
CoT Time: 0.765632
[/home/yuduo/lab_project/gunrock/gunrock/app/wtf/wtf_enactor.cuh, 458] WTFProblem cudaMemcpy d_rank_curr[src] failed (CUDA error 11: invalid argument)
[/home/yuduo/lab_project/gunrock/tests/wtf/test_wtf.cu, 424] HITS Problem Enact Failed (CUDA error 11: invalid argument)

GPU result.Top 10 Page Ranks:
Vertex ID: 16, Page Rank: 0.000000
Vertex ID: 6, Page Rank: 0.000000
Vertex ID: 7, Page Rank: 0.000000
Vertex ID: 10, Page Rank: 0.000000
Vertex ID: 11, Page Rank: 0.000000
Vertex ID: 12, Page Rank: 0.000000
Vertex ID: 21, Page Rank: 0.000000
Vertex ID: 22, Page Rank: 0.000000
Vertex ID: 34, Page Rank: 0.000000
Vertex ID: 13, Page Rank: 0.000000
[GPU Who-To-Follow] finished.  elapsed: 2.265 ms

**Comment by ydwu** [comment]
due to lack of default settings.

**Comment by yzhwang** [comment]
I haven't fixed this Yuduo. So I will reopen this for now. Will fix this tonight.

**Comment by yzhwang** [comment]
fixed.
