### ISSUE TITLE
[A*, LP, WTF, HITS, SALSA, TC] Add run script

### ISSUE THREAD

**Issue by sgpyc** [gunrock/gunrock#233]
Any way to add the run script (like the ones in {bfs, sssp, cc, bc, pr}/run.sh) for these primitives?

**Comment by neoblizz** [comment]
See PR #369 #371 #374.

**Comment by neoblizz** [comment]
- [x] A*
- [x] HITS
- [ ] SALSA
- [x] TC
- [x] LP
- [ ] SM

**Comment by neoblizz** [comment]
SM removed from this issue and `dev` branch.

**Comment by neoblizz** [comment]
Commit for SALSA: ea63f18
