### ISSUE TITLE
***Failed  Required regular expression not found.Regex=[CORRECT]

### ISSUE THREAD

**Issue by cwlseu** [gunrock/gunrock#236]
Hello,
     When I finished building the program and make test, the program throw the following question.
My system is CentOS 7.

`Running tests...
Test project /home/limin/research/gunrock/build
      Start  1: TEST_BFS
 1/11 Test  #1: TEST_BFS .........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.01 sec
      Start  2: TEST_BC
 2/11 Test  #2: TEST_BC ..........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.01 sec
      Start  3: TEST_CC
 3/11 Test  #3: TEST_CC ..........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.01 sec
      Start  4: TEST_SSSP
 4/11 Test  #4: TEST_SSSP ........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.01 sec
      Start  5: TEST_PAGERANK
 5/11 Test  #5: TEST_PAGERANK ....................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.01 sec
      Start  6: TEST_TOPK
 6/11 Test  #6: TEST_TOPK ........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.01 sec
      Start  7: SHARED_LIB_TEST_BFS
 7/11 Test  #7: SHARED_LIB_TEST_BFS ..............***Failed  Required regular expression not found.Regex=[Node_ID.*2.*: Label.*1
]  0.01 sec
      Start  8: SHARED_LIB_TEST_BC
 8/11 Test  #8: SHARED_LIB_TEST_BC ...............***Failed  Required regular expression not found.Regex=[Node_ID.*0.*: Score.*0.5000
]  0.00 sec
      Start  9: SHARED_LIB_TEST_CC
 9/11 Test  #9: SHARED_LIB_TEST_CC ...............***Failed  Required regular expression not found.Regex=[Node_ID.*1.*: Component.*0
]  0.00 sec
      Start 10: SHARED_LIB_TEST_SSSP
10/11 Test #10: SHARED_LIB_TEST_SSSP .............***Failed  Required regular expression not found.Regex=[Node_ID.*1.*: Label.*39.*
]  0.01 sec
      Start 11: SHARED_LIB_TEST_PAGERANK
11/11 Test #11: SHARED_LIB_TEST_PAGERANK .........***Failed  Required regular expression not found.Regex=[Node_ID.*2.*: Score.*1.2*
]  0.01 sec

0% tests passed, 11 tests failed out of 11

Total Test time (real) =   0.07 sec

The following tests FAILED:
	  1 - TEST_BFS (Failed)
	  2 - TEST_BC (Failed)
	  3 - TEST_CC (Failed)
	  4 - TEST_SSSP (Failed)
	  5 - TEST_PAGERANK (Failed)
	  6 - TEST_TOPK (Failed)
	  7 - SHARED_LIB_TEST_BFS (Failed)
	  8 - SHARED_LIB_TEST_BC (Failed)
	  9 - SHARED_LIB_TEST_CC (Failed)
	 10 - SHARED_LIB_TEST_SSSP (Failed)
	 11 - SHARED_LIB_TEST_PAGERANK (Failed)
Errors while running CTest
make: *** [test] Error 8
`

**Comment by jowens** [comment]
Can you paste in the result of `ctest -V` ?

**Comment by shariiiyy** [comment]
@cwlseu, I have had a similar problem before. It was because the cmake version was outdated. I updated it from cmake 3.0 to cmake 3.6 which fixed the problem.  Can you please try update your cmake to the latest version, build gunrock again and try running ctest again.

**Comment by cwlseu** [comment]
I have find the problem. thanks@jowens.
When I execute `ctest -V`, the following information throw:
11: Test command: /home/limin/research/gunrock/build/bin/shared_lib_pr
11: Test timeout computed to be: 9.99988e+06
11: [/home/limin/research/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 32599] cudaSetDevice failed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
**11: [/home/limin/research/gunrock/gunrock/app/pr/pr_app.cu, 342 @ gpu 0] cudaStreamCreate fialed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
11: ERROR ENUMERATING CUDA DEVICES.**
11: Exiting.
11/11 Test #11: SHARED_LIB_TEST_PAGERANK .........***Failed  Required regular expression not found.Regex=[Node_ID.*2.*: Score.*1.2*
]  0.00 sec

0% tests passed, 11 tests failed out of 11

So, I think I should link correct CUDA toolkit when running test.

**Comment by jowens** [comment]
Yes, very definitely do that!
