### ISSUE TITLE
Query regarding result reported for SSSP on soc-livejournal dataset

### ISSUE THREAD

**Issue by tanujkr** [gunrock/gunrock#237]
Why in the following output, for SSSP on soc-livejournal, #edges is 85702474 when the graph actually has 68993773 edges only? soc-LJ is already a directed graph.
https://github.com/gunrock/io/blob/master/gunrock-output/topc/SSSP_soc-LiveJournal1_Thu%20Nov%2017%20233705%202016.json

**Comment by jowens** [comment]
"If the undirected flag is set, we convert the input graph to undirected. When we do so, that implies one edge in each direction, and we report edges for that graph accordingly."

http://gunrock.github.io/gunrock/doc/latest/md_methodology.html

**Comment by sgpyc** [comment]
When `--undirected` is given as command line argument, or `symmetric` is present in the .mtx header, for each undirected edge pair <u, v> in the .mtx file, the reader will produce 2 directed edges <u, v> and <v, u> in the resulted graph https://github.com/gunrock/gunrock/blob/master/gunrock/graphio/market.cuh#L399 .

The COO -> CSR  converter also removes duplicate edges https://github.com/gunrock/gunrock/blob/master/gunrock/csr.cuh#L581 , so the reported number of edges (85702474 here) will be more than the number of edges in the .mtx file (68993773 here) but less than or equal to 2X of that.

This comes from how we interpret the meaning of "undirected". The .mtx format says in that case "only entries in the lower triangular portion need be supplied". But for the graphs that "forced to be" undirected, we don't think edges that are not in the lower triangle are invalid, and won't remove them. One simple example, a graph only contains two vertices V1 & V2, and one directed edge V2 -> V1; the "forced" undirected version can have edges: 1) V2 -> V1 & V1 -> V2, 2) none. At lease to myself, 1) makes more sense.

In our papers, we did try our best to indicate whether the graphs have been converted to the undirected version (other paper may simply refer this as "edge doubling" method).

**Comment by tanujkr** [comment]
Thank you @jowens and @sgpyc for the detailed explanation.
