### ISSUE TITLE
Is it possible to compile Gunrock on OSX?

### ISSUE THREAD

**Issue by elalish** [gunrock/gunrock#239]
I've been attempting to compile gunrock on OSX (my macbook pro has an NVIDIA GPU), but it seems impossible because 1) gunrock requires OpenMP, 2) NVCC requires Apple LLVM 8.0.0 on OSX, and 3) Apple LLVM does not support OpenMP. Is there any way around this?

**Comment by jowens** [comment]
I have the same machine as you do. The cmakefile supports a build if you install MacPorts's "libomp".

**Comment by elalish** [comment]
Thanks, that got me to 10%. Now mgpuutil is complaining that it can't find tr1/random. What's the best way to fix that?

**Comment by jowens** [comment]
You're using cmake? I definitely rigged up cmake to work with OS X out of the box.

**Comment by elalish** [comment]
Indeed I am. Is there anything I can send you to help narrow down the issue? I'm on OS 10.12.4 and I'm using the latest CUDA toolkit. I didn't install METIS since it's optional. Is there anything else I might be missing from macports? I usually use homebrew, so libomp is all I have from macports right now.

**Comment by jowens** [comment]
I'm rebuilding myself, seeing `nvcc fatal   : The version ('80100') of the host compiler ('Apple clang') is not supported`. Doh!

**Comment by neoblizz** [comment]
@elalish did you do `git clone --recursive`? Make sure your https://github.com/gunrock/gunrock/tree/master/externals contains `mgpu` and `cub`.

**Comment by elalish** [comment]
yeah, that one sucks; you have to manually get apple's slightly older command line tools to replace clang down to 8.0.0. I did do recursive and all of cub and mgpu are there (I can see the line that's complaining).

**Comment by neoblizz** [comment]
Could you post the entire output please?

**Comment by elalish** [comment]
This is after it got through the NVCC compling:

```
Scanning dependencies of target gunrock
[  1%] Building CXX object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/mgpuutil.cpp.o
/Users/Emmett/Documents/omnivor/developers/Emmett-scratch/boolean3D/gunrock/externals/moderngpu/src/mgpuutil.cpp:45:10: fatal error: 
      'tr1/random' file not found
#include <tr1/random>
         ^
1 error generated.
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/mgpuutil.cpp.o] Error 1
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by jowens** [comment]
Can you look at externals/moderngpu/src/mgpuutil.cpp? Here's the code I have in mine:

```
#define MGPU_RAND_NS std::tr1

#ifdef _MSC_VER
#include <random>
#else
#ifdef __clang__
#include <random>
#undef MGPU_RAND_NS
#define MGPU_RAND_NS std
#define uniform_int uniform_int_distribution
#define uniform_real uniform_real_distribution
#else
#include <tr1/random>
#endif
#endif
```

Note it specifically checks for clang (e.g., clang should never see a tr1/random include).

**Comment by elalish** [comment]
weird, I have this

```

#define MGPU_RAND_NS std::tr1

#ifdef _MSC_VER
#include <random>
#else
#include <tr1/random>
#endif
```

I just downloaded this a few days ago; is this a very recent commit?

**Comment by jowens** [comment]
It looks like this is a change that is in my local version only. I am a bad person. So just delete that chunk of yours and paste this in.

```
$ git diff -w src/mgpuutil.cpp
diff --git a/src/mgpuutil.cpp b/src/mgpuutil.cpp
index db34bea..290b171 100644
--- a/src/mgpuutil.cpp
+++ b/src/mgpuutil.cpp
@@ -42,8 +42,16 @@
 #ifdef _MSC_VER
 #include <random>
 #else
+#ifdef __clang__
+#include <random>
+#undef MGPU_RAND_NS
+#define MGPU_RAND_NS std
+#define uniform_int uniform_int_distribution
+#define uniform_real uniform_real_distribution
+#else
 #include <tr1/random>
 #endif
+#endif

 namespace mgpu {
```

**Comment by elalish** [comment]
working much better now! I'll put a note when I get to 100%. Thanks!

**Comment by elalish** [comment]
Not a big deal, but is there a way to compile the library without all the tests? Seems like the tests take most of the compile time and dependencies, and if they fail, there's not much I can do about it anyway...

**Comment by neoblizz** [comment]
`cmake -D GUNROCK_MGPU_TESTS=OFF`

**Comment by elalish** [comment]
thanks!

**Comment by neoblizz** [comment]
@elalish quickest will be building just one primitive: `cmake -DGUNROCK_BUILD_APPLICATIONS=OFF -DGUNROCK_APP_BFS=ON ..`

**Comment by elalish** [comment]
Alright, 100% built, and connected components is already working inside of my own code. Thanks for the help!

**Comment by jowens** [comment]
Fantastic!
