### ISSUE TITLE
incorrect number of components returned on Linux

### ISSUE THREAD

**Issue by elalish** [gunrock/gunrock#240]
I'm getting different results using cc() on OSX and Ubuntu. I get the same results for the node components vector, but OSX also correctly returns the total number of components, while on Linux I'm always getting zero returned. Here is a simple example:

```
    thrust::host_vector<int> host_col_indices(col_indices);    
    thrust::host_vector<int> host_row_offsets(row_offsets);
    thrust::host_vector<int> host_col_indices(A.endV);
    thrust::host_vector<int> components(A.num_vert());
    int n_comp = cc(components.data(), A.num_vert(), A.num_edge(),
        host_row_offsets.data(), host_col_indices.data());
    std::cout << n_comp << " components" << std::endl;
```
Where my input tetrahedron is:
```
A.num_vert = 4
A.num_edge = 6
host_row_offsets = {0, 3, 5, 6, 6}
host_col_indices = {1, 2, 3, 2, 3, 3}
```
components correctly comes out as {0, 0, 0, 0}, but on OSX n_comp = 1 and on Linux n_comp = 0. This trend is true of more complex graphs I've tried as well.

**Comment by elalish** [comment]
I should mention, on the more complex graphs I've gotten more complex (multi-component) results, and the components vector still matches, just the n_comp is zero for Linux inexplicably. Any ideas? This is part of a larger C++11 project.

**Comment by elalish** [comment]
Actually, I fear there may be a bigger problem here. The larger problem I was testing (a triangle mesh that Meshlab confirms is manifold, has only a single component and no unreferenced vertices) not only has the problem shown above, but also shows two unreferenced vertices out of ~14,000 (single-node components). This result is identical between OSX and Linux, but after several tests on the inputs, I'm convinced it's an error. Is there any particular format you would prefer for me to upload the input so you can repro?

**Comment by sgpyc** [comment]
Matrix Market, . mtx format?

**Comment by elalish** [comment]
I can do that, though cc() takes input in CRS, while .mtx is COO. Seems like the conversion could potentially confuse the repro.

**Comment by elalish** [comment]
Actually, I take back the second part of this; I did find an oddity in my input, so I'll track that down first. Can someone at least tell me if they can repro the n_comp = 0 on Linux issue? I want to make sure I didn't just call this incorrectly.

**Comment by sgpyc** [comment]
I can try. The number of components is calculated based on the labels. It should not be difficult to figure out what happens, providing the labels are correct.

**Comment by elalish** [comment]
Thanks, in any case the result should always be strictly greater than zero, right? Unless the input is zero length?

**Comment by sgpyc** [comment]
It seems the result is correct on our Linux system (ubuntu 14.04 LTS, with nvcc 8.0 and NVIDIA driver 367.57).

I converted the simple test graph into .mtx as:
`
4 4 6
1 2
1 3
1 4
2 3
2 4
3 4
`

and the program reported there is one component.
`
sgpyc@luigi:~/Projects/gunrock_build$ ./bin/cc market ../gunrock/tests/cc/simple_test.mtx
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (4 vertices, 12 edges):
    Degree   0: 0 (0.00%)
    Degree 2^0: 0 (0.00%)
    Degree 2^1: 4 (100.00%)

Using 1 GPU: [ 0 ].
graph #nodes : 4 -> 4
Computing reference value ...
CPU CC finished in 0.021935 msec.

Using traversal mode TWC
_________________________
-------------------------
iteration 0 elapsed: 0.351906 ms
CORRECT. Component Count: 1
Label Validity:
CORRECT
[0:0, 1:0, 2:0, 3:0, ]

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 4194304	 0	 0
	 queue_sizing =	 0.000000 	 0.000000

 [CC] finished.
 avg. elapsed: 0.3519 ms
 iterations: 2
Fewer than 5 vertices visited.
`

If you are not using more than one GPU, the component counting process is simply a mark-and-count process (https://github.com/gunrock/gunrock/blob/master/gunrock/app/cc/cc_problem.cuh#L388 ).

**Comment by elalish** [comment]
Another question: does cc() consider its input as a directed or undirected graph? If the matrix is not symmetric, does it actually return only strongly connected components? I was assuming it was undirected and so didn't duplicate the edges...

**Comment by elalish** [comment]
Can you try calling cc() directly using the vectors I specified? I think the error may be in the C API's conversion somewhere (since it does not take a .mtx).

**Comment by sgpyc** [comment]
The CC() implementation do assume the input graph is undirected (via. edge doubling).
I think that may be the issue.

**Comment by elalish** [comment]
when you say it assumes it is undirected, does that mean I am expected to do the edge doubling before I input it? Or does that mean it will always double the edges to cause it to be undirected? I was assuming the second, but if it's really the first, then I need to change my code.

**Comment by sgpyc** [comment]
I'm afraid it's the first. We do that in our code before calling the CC() routine.

**Comment by elalish** [comment]
Okay, good to know. So probably getting a number of components equal to zero is something like an error return on the input? Thanks for your help, though a little documentation on this would probably solve this for others. Part of the reason for my confusion is that the example here appears to put non-symmetric input into cc(): https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_cc.c

**Comment by elalish** [comment]
I can confirm that by sending in symmetric matrices I'm now getting the output I expect. Considering that with asymmetric input we're getting different results on different architectures, it seems like this might be a precondition worth testing and throwing an error if it's not met. Thanks for your swift help.

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/commit/cdab20bdba782dec57da1f5a68000d9a9a63d6d4 added a little comment for this issue in `shared_lib_cc.c`.
