### ISSUE TITLE
Incorrect results generated by TC

### ISSUE THREAD

**Issue by Laurawly** [gunrock/gunrock#241]
When running mouse_gene dataset which includes redundant edges and self loops, the result is incorrect.

./bin/test_tc_8.0_x86_64 market ../../dataset/large/mouse_gene/mouse_gene.mtx
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (45101 vertices, 28922190 edges):
    Degree   0: 1975 (4.38%)
    Degree 2^0: 1351 (3.00%)
    Degree 2^1: 1693 (3.75%)
    Degree 2^2: 1931 (4.28%)
    Degree 2^3: 2163 (4.80%)
    Degree 2^4: 2711 (6.01%)
    Degree 2^5: 3166 (7.02%)
    Degree 2^6: 3802 (8.43%)
    Degree 2^7: 4291 (9.51%)
    Degree 2^8: 4946 (10.97%)
    Degree 2^9: 5910 (13.10%)
    Degree 2^10: 7420 (16.45%)
    Degree 2^11: 3495 (7.75%)
    Degree 2^12: 247 (0.55%)

Using 1 GPU: [ 0 ].
size: 14461095

TC TEST
tc_total:372364271
, tc_count:-675869434
tc count:-1
GPU - Computation Complete in 7314.548969 msec.

 [TC] finished.
 avg. elapsed: 7314.5490 ms
 iterations: 0
 load time: 621.2220 ms
 preprocess time: 80.8280 ms
 postprocess time: 15342.8750 ms
 total time: 23384.1012 ms

The result is still incorrect when I increase tc_count's limit to unsigned long.
Correct result should be 3,619,097,862.

**Comment by Laurawly** [comment]
Both mgpu::Reduce and cub::Sum is wrong when output variable becomes int unsigned long. Tested using a host-side reduce and the result is correct.

**Comment by jowens** [comment]
Can you reproduce this using not-Gunrock (with a simple standalone test case)? This seems ... anomalous ...; I just worry we've configured it wrong as opposed to it actually gives the wrong answer.

**Comment by Laurawly** [comment]
Yeah definitely, should I commit the reproduced error somewhere?

**Comment by jowens** [comment]
Wow, good question. Well, the most important thing to do is to make reproducing it as simple as possible, so ideally a single source file that computes both CPU and GPU results and clearly shows the discrepancy. If it's simple enough, just put it on pastebin (or make a gist on github). If you want to put it in source control, just make a public repo under your own github id for this repro case. I don't have a pat answer for you but this makes sense to me ...

**Comment by Laurawly** [comment]
It turns out that mgpu doesn't have the option of having different input and output types for reduce. And our submodule cub version is outdated. I tested the most updated version 1.6.2, and its reduce doesn't have that bug anymore. Going to update cub's submodule version and change our use of moderngpu's reduce to cub's reduce.

**Comment by Laurawly** [comment]
Bug resolved by using latest version of cub for reduce and changing tc count data type to long long.

**Comment by jowens** [comment]
super! please feed back the latest results to our NVIDIA colleagues.
