### ISSUE TITLE
Is it possible to run Gunrock on gpgpu-sim through some modification?

### ISSUE THREAD

**Issue by fishflag** [gunrock/gunrock#245]
In current release, gunrock runs on real GPUs with CUDA 7.5 (or higher). I wonder if it is possible to run gunrock on gpugpu-sim (support cuda 4.0) through modifying the source code. If so, can anyone tell me how to? Thanks very much.

**Comment by jowens** [comment]
We have no experience with gpgpu-sim at all. You might be better off asking the gpgpu-sim community ... ?

**Comment by sgpyc** [comment]
The earliest Cuda version Gunrock had supported was 6.0, as I can remember, and the lowest compute capability is 3.0. While the core ideas are independent of the Cuda version, it would be very difficult and time consuming to port the library backwards.

If you are more interested in the data accessing patterns and less focus on performance, @yzh's mini-Gunrock achieved 80+% of the performance, and has a much lighter footprint (in terms of code size). But mini-Gunrock is based on ModernGPU,  I don't think that can run with Cuda 4.0 either. But it will be easier to do the porting.

But getting latter Cuda version support on gpgpu-sim is really the way to go.

**Comment by neoblizz** [comment]
Let us know if you have any updates on this @fishflag!
