### ISSUE TITLE
no shared_lib_mf in dev branch on OS X

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#248]
```
      Start 13: SHARED_LIB_TEST_MF
Could not find executable shared_lib_mf
Looked in the following places:
shared_lib_mf
shared_lib_mf
Release/shared_lib_mf
Release/shared_lib_mf
Debug/shared_lib_mf
Debug/shared_lib_mf
MinSizeRel/shared_lib_mf
MinSizeRel/shared_lib_mf
RelWithDebInfo/shared_lib_mf
RelWithDebInfo/shared_lib_mf
Deployment/shared_lib_mf
Deployment/shared_lib_mf
Development/shared_lib_mf
Development/shared_lib_mf
Unable to find executable: shared_lib_mf
```

**Comment by jowens** [comment]
(Also see https://github.com/gunrock/gunrock/issues/249, it just might not be working yet.)

**Comment by neoblizz** [comment]
@agalup I will use bfs as an example. Here's an explanation for adding the shared library (+test);

1. Your bfs_app.cu file should be defined and should have a function for example `gunrock_bfs();` (see https://github.com/gunrock/gunrock/blob/dev/gunrock/app/bfs/bfs_app.cu#L393)
2. Include the decelerations in `gunrock\gunrock.h` (see https://github.com/gunrock/gunrock/blob/f011bb033669091a8c3a6c6c3b0910e20287c615/gunrock/gunrock.h#L173)
3. Write up your `shared_lib_bfs.c` file (see https://github.com/gunrock/gunrock/blob/dev/shared_lib_tests/shared_lib_bc.c)
4. Include the shared_lib in the `shared_lib_tests/CMakeLists.txt` (see https://github.com/gunrock/gunrock/blob/dev/shared_lib_tests/CMakeLists.txt)
5. Add the test for the shared library in the main CMakeLists.txt (see https://github.com/gunrock/gunrock/blob/dev/CMakeLists.txt#L378)

I think that's it. If you have questions let me know!

**Comment by jowens** [comment]
@neoblizz somewhere can you put this in an internal-documentation file? Eventually we want a "So you want to write a new Gunrock primitive" doc.

**Comment by neoblizz** [comment]
@jowens Will add it to the docs. Just a note, I am not sure if we absolutely need the shared libraries for every primitive, because the tests just seem to show that we can do it, but you don't have to. More importantly, we need test driver under `tests/<primitive>/test_<primitive>.cu`.

**Comment by neoblizz** [comment]
Just a reminder to self: There is a need of heavy commenting in the sample/template files so they are easy to replicate, this can be taken care of with #195 .

**Comment by agalup** [comment]
I make some changes but this code is still not completed.

**Comment by jowens** [comment]
@agalup OK. It shouldn't be in dev if it doesn't work yet. It should be either commented out in ctest, or it should be in a different branch.

**Comment by neoblizz** [comment]
@agalup yeah, the changes were fine you are missing just one component now: Your test_mf.cu needs to print `CORRECT` if the result is correct and `INCORRECT` if it fails. So, basically, your reference code needs to be there or a way of checking algorithm's correctness. Refer to: 

https://github.com/gunrock/gunrock/blob/4ace54365ec5cd724ee1f2e8a51cdc3fbe568dc0/tests/pr/test_pr.cu#L169

Prints correct: https://github.com/gunrock/gunrock/blob/4ace54365ec5cd724ee1f2e8a51cdc3fbe568dc0/tests/pr/test_pr.cu#L169

That is what tells the regex that the primitive successfully passed.

**Comment by neoblizz** [comment]
Goes under issue #309.
