### ISSUE TITLE
Incorrect BC Results from Library

### ISSUE THREAD

**Issue by LeonHeTheFirst** [gunrock/gunrock#251]
Using the code and example graph in shared_lib_bc.c, the results for betweenness centrality do not match the results produced by other tools, which match each other.

​igraph/snap:
0,0.5
1,0.5
2,2.33
3,1.83
4,1.83
5,0.67
6,0.33

​gunrock:
0,0
1,0.25
2,0.5
3,0.75
4,0
5,0
6,0

I have included a visualization of the sample graph along with the file. You can clearly see that the scores for nodes 0, 4, 5, and 6 should not be zero.
![test_graph](https://user-images.githubusercontent.com/11202340/27554532-b3d30392-5a7c-11e7-8eed-78a095f792b8.png)

[test-simplified.txt](https://github.com/gunrock/gunrock/files/1103154/test-simplified.txt)

**Comment by neoblizz** [comment]
@LeonHeTheFirst how did you input your `test-simplified.txt` into `shared_lib_bc.c`?

**Comment by LeonHeTheFirst** [comment]
@neoblizz Sorry, I should have explained myself a bit more clearly. I created a separate program using the code from shared_lib_bc.c and tried running it with a file ingest on test-simplified.txt. When that produced an incorrect output, I switched to using hard-coded arrays just like what shared_lib_bc.c has. That still produced the same erroneous results I gave above.

**Comment by neoblizz** [comment]
@LeonHeTheFirst could you please share your edits with us? Because the results you posted for gunrock's `shared_lib_bc.c` are for the default graph:

```
    int num_nodes = 7, num_edges = 26;
    int row_offsets[8]  = {0, 3, 6, 11, 15, 19, 23, 26};
    int col_indices[26] = {1, 2, 3, 0, 2, 4, 0, 1, 3, 4, 5, 0, 2,
                           5, 6, 1, 2, 5, 6, 2, 3, 4, 6, 3, 4, 5};
```

**Comment by LeonHeTheFirst** [comment]
@neoblizz That was the graph I used. The edits I was referring to were for something else and didn't influence the results even after I took them out. The issue is that the betweenness centrality values gunrock gives for that default graph are entirely different from other tools and from my hand calculations.

**Comment by neoblizz** [comment]
@LeonHeTheFirst so, I investigated it. It is not that gunrock's bc produces incorrect result, it is actually just a partial bc run with sources set only to node=0: https://github.com/gunrock/gunrock/blob/master/gunrock/gunrock.h#L135 as you can see here if you pass in `NULL` in the 2nd parameter of `InitSetup(1, NULL)` it will only run partial bc.

To run the full bc, send `-1` as the 2nd parameter: https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_bc.c#L17

```
int test[1] = {-1};
struct GRSetup *config = InitSetup(1, test);   // gunrock configurations
```

The following is my output after doing so:
```
mosama@mario:~/gunrock/build$ ./bin/shared_lib_bc 
0	 1	 0	 queue3 	 oversize :	 9 ->	 14
0	 1	 0	 queue3 	 oversize :	 14 ->	 20
Node_ID [0] : Score [0.5000]
Node_ID [1] : Score [0.5000]
Node_ID [2] : Score [2.3333]
Node_ID [3] : Score [1.8333]
Node_ID [4] : Score [1.8333]
Node_ID [5] : Score [0.6667]
Node_ID [6] : Score [0.3333]
```

Finally, if you wanna see where the code is for all that (why -1), it is here: https://github.com/gunrock/gunrock/blob/master/gunrock/app/bc/bc_app.cu#L161

**Comment by jowens** [comment]
Thanks @neoblizz, good sleuthin'!

@sgpyc perhaps in the API redesign we can have a more intuitive API here than passing in -1?

**Comment by LeonHeTheFirst** [comment]
@neoblizz Thanks for the help! It worked for me.
