### ISSUE TITLE
Enumerate triangles

### ISSUE THREAD

**Issue by alexperrone** [gunrock/gunrock#253]
Enumerate triangles as list of vertices.

Note: the current roadmap mentions triangle counting but not enumerating the actual triangles. 

https://github.com/gunrock/gunrock/blob/master/doc/road_map.md

**Comment by Laurawly** [comment]
The current TC implementation doesn't do the enumeration but the subgraph matching implementation does! And you can find the app here under dev branch: https://github.com/gunrock/gunrock/tree/dev/gunrock/app/sm

**Comment by neoblizz** [comment]
Reopen the issue if something else is needed on this, but I feel like @Laurawly answered this! Thanks!
