### ISSUE TITLE
Integration with sparse matrix from scipy

### ISSUE THREAD

**Issue by SkBlaz** [gunrock/gunrock#255]
Hello. I don't know if this is exactly issue material, but still. I'm trying to run your python examples (i.e., https://github.com/gunrock/gunrock/blob/master/python/pagerank.py). I see the input for this is standard sparse matrix CSR, if I understand the CSR correctly, there are three output arrays, yet you only take first two and manually asign the pointers for rows and columns individually. If I understand correctly, this is due to GPU's input requirements. My question is, if I obtain row and column values from the CSR.toArray() from scipy, is this the same type of rows and columns as the one in examples? Do I only need to manually assign pointers then?

Sorry if this is basic material, I've only recently started with GPU-graph based operations.

Thanks!

**Comment by jowens** [comment]
We haven't touched python code for quite some time. @yzhwang any guidance here?

**Comment by neoblizz** [comment]
@SkBlaz, I can answer your question. So, as you said there are three segments of a CSR format:
- Column indices: https://github.com/gunrock/gunrock/blob/master/python/toy_graph/col.txt
- Row offsets: https://github.com/gunrock/gunrock/blob/master/python/toy_graph/row.txt
- Data: https://github.com/gunrock/gunrock/blob/master/python/toy_graph/val.txt

Notice, the algorithm doesn't need the data to determine graph's nodes and edges: https://github.com/gunrock/gunrock/blob/master/gunrock/gunrock.h#L329
```
/**
 * @brief PageRank simple public interface.
 *
 * @param[out] node_ids Return top-ranked vertex IDs.
 * @param[out] pagerank Return top-ranked PageRank scores.
 * @param[in] num_nodes Input graph number of nodes.
 * @param[in] num_edges Input graph number of edges.
 * @param[in] row_offsets Input graph row_offsets.
 * @param[in] col_indices Input graph col_indices.
 * @param[in] normalized Whether to perform a normalized PageRank
 */
void pagerank(
    int*       node_ids,      // Return top-ranked vertex IDs
    float*     pagerank,      // Return top-ranked PageRank scores
    const int  num_nodes,     // Input graph number of nodes
    const int  num_edges,     // Input graph number of edges
    const int* row_offsets,   // Input graph row_offsets
    const int* col_indices,   // Input graph col_indices
    bool       normalized);   // normalized pagerank flag
```
Now, coming to your question regarding SciPy: 
**Q: Will `csr_matrix.toarray()` work in this case?**
**A:** No! `.toarray()` does exactly the opposite of what we need, it converts the csr_matrix format back to a traditional array.

```
Muhammad_Osama@Blizzard-M:~$ python
Python 3.5.2 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from scipy import sparse
>>> A = np.array([[1,2,0],[0,0,3],[1,0,4]])
>>> B = np.matrix([[1,2,0],[0,0,3],[1,0,4]])
>>> A
array([[1, 2, 0],
       [0, 0, 3],
       [1, 0, 4]])
>>> sA = sparse.csr_matrix(A)
>>> sA.toarray()
array([[1, 2, 0],
       [0, 0, 3],
       [1, 0, 4]], dtype=int64)
>>> sA
<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>
>>> print(sA)
  (0, 0)	1
  (0, 1)	2
  (1, 2)	3
  (2, 0)	1
  (2, 2)	4
```
What you need are the two things I mentioned above, row offsets and column indices. And after you have them you can cast them to a pointer and send them to gunrock. 

**Q: Do I only need to manually assign pointers then?**
**A:** Yes, and it is very simple: Here's where the cast happens: https://github.com/gunrock/gunrock/blob/master/python/pagerank.py#L13 As the pagerank function suggests, it takes in four pointers: node_ids, pagerank (top scores), row_offsets and col_indices.

I think I addressed everything here.

**Comment by SkBlaz** [comment]
Great, I figured it out meanwhile, it is nice to see we came to the same
conclusion. I didn't quite understand the pointer, so thank you for
additional clarification!

**Comment by neoblizz** [comment]
Awesome, let us know if you have any issues using gunrock!
