### ISSUE TITLE
CSR representation for directed graphs 

### ISSUE THREAD

**Issue by robinyancey** [gunrock/gunrock#258]
The CSR as described in the paper _To Push or To Pull: On Reducing Communication and Synchronization in Graph Computations_ says that (the normal way is that) "A CSR representation stores each row of A contiguously. The ith row of A contains all vertices with an edge to vertex i" while "A CSC representation stores each column of A contiguously. The ith row of A contains all vertices with an edge from vertex i." (The paper also says that in algorithms with matrix vector multiplication such as PR and BFS, the CSR is used for the pull method, while the CSC is used for the push method.) 

In the beginning of section 4.0 of _Gunrock: GPU Analytics_ it says and shows in the figure that outgoing edges to vertices from a source i are stored contiguously using the "row offsets" and "column indices" arrays. (I also saw a couple online CSR examples set up this way, and this makes sense since it from row i to column j- [i,j].) Gunrock's primitive set up right now using pull is BFS and only this uses the "inverse CSR," "inverse row offsets," and "inverse column indices" in the module called "Inverse_Expand" which is specified in _Gunrock: GPU Analytics_ that it is the module that implements the pull method. 

The CSR of the graph in Gunrock is set up opposite than as described in the push/pull paper right?

**Comment by jowens** [comment]
@yzhwang @sgpyc our CSR is outbound, right? a row contains all outbound edges for a particular vertex?

@dumerrill yours too, yeah?

**Comment by sgpyc** [comment]
For DOBFS, the CSR contains outgoing edges, and the inverse CSR is actually the CSC, containing incoming edges. It should be safe to say "row = source vertex, column = destination vertex", but @yzhwang can point out if any special case exists.

**Comment by robinyancey** [comment]
Perfect. Thank you. Exactly what I wanted to confirm.

**Comment by yzhwang** [comment]
I believe both Gunrock and Merrill's b40c record outgoing edges in CSR format. It is difficult to say which is the normal way though (to record outgoing edges, or the incoming edges). At least all the high performance graph libraries I'm aware of seem to store outgoing edges in CSR for directed graphs. 
 @ctcyang can comment more on how CSR and CSC are interpreted in the world of GraphBLAS.

**Comment by ctcyang** [comment]
That matches my understanding too. I can see reasons why Scott Beamer used CSC to store outgoing edges. It's because in matrix multiplication notation with x being the input frontier vector, A adjacency matrix and y being the output frontier vector, y = x * A (eqn 1) represents a single graph traversal. If you want the frontier vector to come after the matrix, then you would need y = A^T * x (eqn 2). 

Gunrock is storing the A in CSR and using eqn 1. Scott Beamer is storing A^T in CSC (which is equivalent to storing A in CSR) and using eqn 2. Fundamentally both are doing the same thing.

**Comment by jowens** [comment]
Maciej Besta: "Actually, the last comment seems to have summarized properly the
matter (whether one uses A or A^T). Edgar thinks similarly." Presumably referring to the nice summary by @ctcyang, thanks Carl and Maciej.
