### ISSUE TITLE
[CC] Segmentation fault on roadnet-CA

### ISSUE THREAD

**Issue by septicmk** [gunrock/gunrock#260]
I tried to run cc on [roadNet-CA](https://snap.stanford.edu/data/roadNet-CA.html) with
```
./cc market ~/data/roadNet-CA/roadNet-CA.txt.mtx
```

here is the output.(Segmentation fault)
```
Loading Matrix-market coordinate-formatted graph ...
Reading from /home/septicmk/data/roadNet-CA/roadNet-CA.txt.mtx:
  Parsing MARKET COO format (1971281 nodes, 11066428 directed edges)... Done parsing (3s).
  Converting 1971281 vertices, 11066428 directed edges (unordered tuples) to CSR format...
Done converting (0s).

Degree Histogram (1971281 vertices, 5533214 edges):
    Degree   0: 6076 (0.31%)
    Degree 2^0: 321027 (16.29%)
    Degree 2^1: 1176029 (59.66%)
    Degree 2^2: 468115 (23.75%)
    Degree 2^3: 34 (0.00%)

Using 1 GPU: [ 0 ].
graph #nodes : 1971281 -> 1965205
Segmentation fault (core dumped)
```
but this graph is ok for BFS,PR,BC,SSSP.

**Comment by jowens** [comment]
Did a clean build on our "mario" machine. CUDA 9, gcc 5.4. It passes. What versions are you running?

```
jowens@mario:~/working/gunrock/dataset/large/roadNet-CA$ ~/working/gunrock-build/bin/cc market roadNet-CA.mtx
Loading Matrix-market coordinate-formatted graph ...
Reading from roadNet-CA.mtx:
  Parsing MARKET COO format (1971281 nodes, 5533214 directed edges)... Done parsing (2s).
  Converting 1971281 vertices, 5533214 directed edges (unordered tuples) to CSR format...
Done converting (0s).

Degree Histogram (1971281 vertices, 5533214 edges):
    Degree   0: 6075 (0.31%)
    Degree 2^0: 321027 (16.29%)
    Degree 2^1: 1176030 (59.66%)
    Degree 2^2: 468115 (23.75%)
    Degree 2^3: 34 (0.00%)

Using 1 GPU: [ 0 ].
graph #nodes : 1971281 -> 1965206
Computing reference value ...
CPU CC finished in 4036.005127 msec.

Using traversal mode TWC
_________________________
-------------------------
iteration 0 elapsed: 6.524801 ms
CORRECT. Component Count: 2638
Label Validity:
CORRECT
Top 10 largest components:
CC ID: 0, CC Root: 0, CC Size: 1957027
CC ID: 1, CC Root: 534123, CC Size: 586
CC ID: 2, CC Root: 533848, CC Size: 340
CC ID: 3, CC Root: 1554985, CC Size: 329
CC ID: 4, CC Root: 1554979, CC Size: 178
CC ID: 5, CC Root: 1939295, CC Size: 112
CC ID: 6, CC Root: 829269, CC Size: 48
CC ID: 7, CC Root: 1555566, CC Size: 38
CC ID: 8, CC Root: 314204, CC Size: 25
CC ID: 9, CC Root: 991491, CC Size: 22

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 88080384	 0	 0
	 queue_sizing =	 0.000000 	 0.000000

 [CC] finished.
 avg. elapsed: 6.5248 ms
 iterations: 2
 min. elapsed: 6.5248 ms
 max. elapsed: 6.5248 ms
 rate: 848.0280 MiEdges/s
 src: 0
 nodes_visited: 1965206
 edges_visited: 5533214
 nodes queued: 76643034
 edges queued: 38732498
 nodes redundance: 3800.00%
 edges redundance: 600.00%
 load time: 1920.2788 ms
 preprocess time: 83.1840 ms
 postprocess time: 285.5759 ms
 total time: 11523.2570 ms
```

**Comment by septicmk** [comment]
The gunrock version is `312c14f31516a4b7d9bd6d2b0fb6029de6d5797c`, Cuda 7.5, GCC 4.9.2. Both K40 and K20 failed.

**Comment by neoblizz** [comment]
@septicmk could you do a fresh `git clone --recursive https://github.com/gunrock/gunrock.git` and report the `cmake` output as well? Just want to see if it is the environment you are working in or gunrock itself.

**Comment by septicmk** [comment]
Did a clean build on our K40 machine with the lastest version of gunrock.
cmake output:
```
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/local/bin/cc
-- Check for working C compiler: /usr/local/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda-7.5 (found suitable version "7.5", minimum required is "7.5")
-- Boost version: 1.58.0
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Found OpenMP
CMake Warning at cmake/FindMetis.cmake:47 (MESSAGE):
  Metis was requested but support was not found, run `sudo apt-get install
  metis` or `/dep/install_metis.sh` for installation.
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)


-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Configuring done
-- Generating done
-- Build files have been written to: /home/septicmk/project/gunrock/build
```
and the CC also failed on roadNet-CA and the [soc-LiveJournal1](https://snap.stanford.edu/data/soc-LiveJournal1.html).

**Comment by jowens** [comment]
Not seeing where things went wrong here ...

**Comment by septicmk** [comment]
Passed com-orkut, hollywood-2009, indochina-2004, and msdoor.
Failed on roadNet-CA, roadNet-TX, soc-LiveJournal1, and wiki-talk. (All Segmentation Fault )

It is so weird ...

**Comment by neoblizz** [comment]
@septicmk I think the downloaded dataset from SNAP are not in proper mtx format. I just downloaded it directly from that site and (for example roadNet-CA) and it is missing the following line:
`1971281 1971281 2766607` which is total number of `nodes nodes edges`.

```
muhammad@blizzard:~/gunrock/build/bin (master)*$ ./cc market ../../dataset/large/roadNet-CA/roadNet-CA.txt
Loading Matrix-market coordinate-formatted graph ...
Reading from ../../dataset/large/roadNet-CA/roadNet-CA.txt:
  Parsing MARKET COO formatError parsing MARKET graph: invalid problem description.
Using 1 GPU: [ 0 ].
Segmentation fault
```
SNAP has graphs as edgelists, gunrock uses matrix market format. You can download roadNet-CA by running `make` in `path/to/gunrock/dataset/large/roadNet-CA/`.

**Comment by neoblizz** [comment]
The only other thing I see is you are missing metis, but that is optional and it shouldn't cause this bug.

**Comment by septicmk** [comment]
I did notice that the dataset from SNAP are not in `.mtx` format. I wrote a script to add the missing header line like this:
```
nodes = max_vid - min_vid + 1;
nedges = number of lines; (except blank line and comments)
```
I also generated random weight(0~999) for each edge for SSSP benchmark, but I believe it shouldn't cause the Segmentation Fault.

You can see the output in my first post, I think that gunrock could recognize the dataset.

> Reading from /home/septicmk/data/roadNet-CA/roadNet-CA.txt.mtx:
      Parsing MARKET COO format (1971281 nodes, 11066428 directed edges)... Done parsing (3s).
      Converting 1971281 vertices, 11066428 directed edges (unordered tuples) to CSR format...
   Done converting (0s).



here is the first 10 lines of the `roadNet-CA`:
```
1971281 1971281 5533214
0 1 384
0 2 887
0 469 778
1 0 916
1 6 794
1 385 336
2 0 387
2 3 493
469 0 650
```

**Comment by jowens** [comment]
Please use the `make` script that @neoblizz referenced just so we can all be sure we're using the same dataset with testing. If it's the dataset, we'll figure out why it doesn't work. If it's our code, well, we'll concentrate on that.

**Comment by septicmk** [comment]
Hey, I know what is the problem. try this graph：
```
2 2 2
1 1
2 2
```
Segmentation fault.

however:
```
2 2 2
1 2
2 1
```
will pass.

**Comment by neoblizz** [comment]
@septicmk yeah, I believe your script to convert edge list to mtx is causing this. I will recommend you look at `path/to/gunrock/dataset/large` for the datasets we have available in mtx format. And you can just run make in the folder for the dataset that you would want to try out. We have tested most of the datasets that you mentioned and they should be available in the datasets directory. I am closing this, but if you have other issues with gunrock let us know (file a new issue)!

**Comment by jowens** [comment]
That being said, we shouldn't be segfaulting in our code. I'd like to know why.

**Comment by neoblizz** [comment]
@jowens one thing I can clearly see in what @septicmk generated initially is that it starts at 0, and mtx format specs requires to be started at 1: http://math.nist.gov/MatrixMarket/formats.html

```
%%MatrixMarket matrix coordinate real general
%=================================================================================
%
% This ASCII file represents a sparse MxN matrix with L 
% nonzeros in the following Matrix Market format:
%
% +----------------------------------------------+
% |%%MatrixMarket matrix coordinate real general | <--- header line
% |%                                             | <--+
% |% comments                                    |    |-- 0 or more comment lines
% |%                                             | <--+         
% |    M  N  L                                   | <--- rows, columns, entries
% |    I1  J1  A(I1, J1)                         | <--+
% |    I2  J2  A(I2, J2)                         |    |
% |    I3  J3  A(I3, J3)                         |    |-- L lines
% |        . . .                                 |    |
% |    IL JL  A(IL, JL)                          | <--+
% +----------------------------------------------+   
%
% Indices are 1-based, i.e. A(1,1) is the first element.
%
%=================================================================================
  5  5  8
    1     1   1.000e+00
    2     2   1.050e+01
    3     3   1.500e-02
    1     4   6.000e+00
    4     2   2.505e+02
    4     4  -2.800e+02
    4     5   3.332e+01
    5     5   1.200e+01
```

**Comment by jowens** [comment]
I'm not saying it's a legit graph. I'm saying that even with a totally messed up graph, we shouldn't be segfaulting, but instead should exit gracefully with a sensible error message ("you have a totally messed up graph").

**Comment by neoblizz** [comment]
@jowens oh, fair enough. I can file an issue for that so we can add that in.
