### ISSUE TITLE
Pagerank Associate Values 

### ISSUE THREAD

**Issue by robinyancey** [gunrock/gunrock#263]
It seems as if the VERTEX_ASSOCIATES and VALUE__ASSOCIATES in Gunrock algorithms are used to hold data associated with vertices (such as the current, original, or new rank for Pagerank or whether the neighbor has a parent for BFS).  Why does MAX_NUM_VERTEX_ASSOCIATES = 0 in the PR problem base when in Expand_Incoming_PR we increment the offset of the s_value_associate_org and s_value_associate_in by NUM_VALUE_ASSOCIATES and NUM_VERTEX_ASSOCIATES? What exactly is stored in s_values_associate and these NUM_VERTEX/VALUE associates and how are they stored for Pagerank?

**Comment by sgpyc** [comment]
NUM_VERTEX_ASSOCIATES = 0 for PR (https://github.com/gunrock/gunrock/blob/master/gunrock/app/pr/pr_enactor.cuh#L1109, the first number here), and NUM_VALUE__ASSOCIATES = 1 (as the second number). In Expand_Incoming_PR_Kernel (https://github.com/gunrock/gunrock/blob/master/gunrock/app/pr/pr_enactor.cuh#L147), NUM_VALUE__ASSOCIATES and NUM_VERTEX_ASSOCIATES are not used, and it's assumed only one value__associate number per vertex is in the input, which is the ranking value. The caller is here (https://github.com/gunrock/gunrock/blob/master/gunrock/app/pr/pr_enactor.cuh#L769), which only uses value__associate_in, but not vertex_associate_in.

In general, value/vertex_associate_in/out are used for multi-GPU communications, to move data together with remote frontier vertex ids. For PR, there is 1 data with type ValueT to move with the vertex ids, which is the partial ranking value of the vertex. There is no data with type VertexT to move around, so NUM_VERTEX_ASSOCIATES and MAX_NUM_VERTEX_ASSOCIATES are both 0. https://github.com/gunrock/gunrock/blob/master/gunrock/app/pr/pr_enactor.cuh#L1101 tells the value_associates to move around the rank_next array. 

The s_* prefix is just telling the pointers are stored in shared GPU memory. Together with d_* (device), h_* (host), l_* (local), they are mostly standard way of telling where the content located.

**Comment by robinyancey** [comment]
That answers my question. Thank you!
