### ISSUE TITLE
Breadth First Search Inverse_Expand Function

### ISSUE THREAD

**Issue by robinyancey** [gunrock/gunrock#264]
Where and how is the inverse matrix (and inverse_row_offsets and inverse_column_indices) implemented in the BFS algorithm?

**Comment by sgpyc** [comment]
It's the inverse of CSR, i.e. the CSC format of the same matrix.
Are you asking the data structure definition or how the content is prepared?

**Comment by robinyancey** [comment]
I was wondering where the graph is prepared since I thought both the CSR and CSC are used in the direction optimized BFS.

**Comment by sgpyc** [comment]
here is the function that prepare both Csr and Csc representation of graphs,
https://github.com/gunrock/gunrock/blob/master/gunrock/util/info.cuh#L547.
The actual conversion happens at CsrToCsc() function, https://github.com/gunrock/gunrock/blob/master/gunrock/csr.cuh#L127.

The refactored code use similar idea (read in Csr or Coo, then convert to Csc), but the actual place of implementation may be different.

**Comment by neoblizz** [comment]
Thanks for answering @sgpyc. @robinyancey let us know if you have any further questions!

**Comment by robinyancey** [comment]
OK. Thank you so much! This is good to know
