### ISSUE TITLE
Possible Bug with Direction-Optimized BFS

### ISSUE THREAD

**Issue by ctcyang** [gunrock/gunrock#27]
Hey guys, I was running some tests with direction-optimized BFS and I noticed a problem with kron scale20 from source nodes 1 and 3. Strangely enough, the other nodes seem to be fine. 
 
./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=0 --idempotence
./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=1 --idempotence
[../../gunrock/app/dobfs/dobfs_enactor.cuh, 525] BFSEnactor cudaEventSynchronize throttle_event failed (CUDA error 77: an illegal memory access was encountered)
[test_dobfs.cu, 399] DOBFS Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 186] DOBFSProblem cudaMemcpy d_labels failed (CUDA error 77: an illegal memory access was encountered)
[test_dobfs.cu, 410] DOBFS Problem Data Extraction Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 145] GpuSlice cudaFree d_labels failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 146] GpuSlice cudaFree d_preds failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 147] GpuSlice cudaFree d_frontier_map_in failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 148] GpuSlice cudaFree d_frontier_map_out failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 149] GpuSlice cudaFree d_index_queue failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 150] GpuSlice cudaFree d_index_queue failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 151] GpuSlice cudaFree data_slices failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 126] GpuSlice cudaFree d_row_offsets failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 127] GpuSlice cudaFree d_column_indices failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 128] GpuSlice cudaFree d_column_offsets failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 129] GpuSlice cudaFree d_row_indices failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 131] GpuSlice cudaFree frontier_queues.d_keys failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 131] GpuSlice cudaFree frontier_queues.d_keys failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_enactor.cuh, 150] DOBFSEnactor cudaFreeHost done failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_enactor.cuh, 153] DOBFSEnactor cudaEventDestroy throttle_event failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/enactor_base.cuh, 120] EnactorBase cudaFree d_node_locks failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/enactor_base.cuh, 121] EnactorBase cudaFree d_node_locks_out failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/util/kernel_runtime_stats.cuh, 143] KernelRuntimeStatsLifetime cudaFree d_stat failed:  (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/util/kernel_runtime_stats.cuh, 143] KernelRuntimeStatsLifetime cudaFree d_stat failed:  (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/util/cta_work_progress.cuh, 230] CtaWorkProgress cudaFree d_counters failed:  (CUDA error 77: an illegal memory access was encountered)
kron_g500-logn20
./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=2 --idempotence
kron_g500-logn20
./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=3 --idempotence
[../../gunrock/app/dobfs/dobfs_enactor.cuh, 525] BFSEnactor cudaEventSynchronize throttle_event failed (CUDA error 77: an illegal memory access was encountered)
[test_dobfs.cu, 399] DOBFS Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 186] DOBFSProblem cudaMemcpy d_labels failed (CUDA error 77: an illegal memory access was encountered)
[test_dobfs.cu, 410] DOBFS Problem Data Extraction Failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 145] GpuSlice cudaFree d_labels failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 146] GpuSlice cudaFree d_preds failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 147] GpuSlice cudaFree d_frontier_map_in failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 148] GpuSlice cudaFree d_frontier_map_out failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 149] GpuSlice cudaFree d_index_queue failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 150] GpuSlice cudaFree d_index_queue failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_problem.cuh, 151] GpuSlice cudaFree data_slices failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 126] GpuSlice cudaFree d_row_offsets failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 127] GpuSlice cudaFree d_column_indices failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 128] GpuSlice cudaFree d_column_offsets failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 129] GpuSlice cudaFree d_row_indices failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 131] GpuSlice cudaFree frontier_queues.d_keys failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/problem_base.cuh, 131] GpuSlice cudaFree frontier_queues.d_keys failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_enactor.cuh, 150] DOBFSEnactor cudaFreeHost done failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/dobfs/dobfs_enactor.cuh, 153] DOBFSEnactor cudaEventDestroy throttle_event failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/enactor_base.cuh, 120] EnactorBase cudaFree d_node_locks failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/app/enactor_base.cuh, 121] EnactorBase cudaFree d_node_locks_out failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/util/kernel_runtime_stats.cuh, 143] KernelRuntimeStatsLifetime cudaFree d_stat failed:  (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/util/kernel_runtime_stats.cuh, 143] KernelRuntimeStatsLifetime cudaFree d_stat failed:  (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/util/cta_work_progress.cuh, 230] CtaWorkProgress cudaFree d_counters failed:  (CUDA error 77: an illegal memory access was encountered)
kron_g500-logn20
./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=4 --idempotence
kron_g500-logn20
./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=5 --idempotence
kron_g500-logn20
./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=6 --idempotence

Regards,
Carl

**Comment by ydwu** [comment]
Strangely, It's actually work for me:

[yuduo@mario]dobfs$ ./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=1 --idempotence
Reading from /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx:
  Parsing MARKET COO format (1048576 nodes, 44620272 directed edges)... Done parsing (16s).
  Converting 1048576 vertices, 44620272 directed edges (unordered tuples) to CSR format...
Done converting (5s).
Reading from /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx:
  Parsing MARKET COO format (1048576 nodes, 44620272 directed edges)... Done parsing (15s).
  Converting 1048576 vertices, 44620272 directed edges (unordered tuples) to CSR format...
Done converting (6s).

Degree Histogram (1048576 vertices, 44619402 edges):
    Degree   0: 383165 (36.54%)
    Degree 2^0: 130872 (12.48%)
    Degree 2^1: 123131 (11.74%)
    Degree 2^2: 104657 (9.98%)
    Degree 2^3: 94087 (8.97%)
    Degree 2^4: 65886 (6.28%)
    Degree 2^5: 52976 (5.05%)
    Degree 2^6: 43377 (4.14%)
    Degree 2^7: 17652 (1.68%)
    Degree 2^8: 18180 (1.73%)
    Degree 2^9: 7207 (0.69%)
    Degree 2^10: 4188 (0.40%)
    Degree 2^11: 2372 (0.23%)
    Degree 2^12: 463 (0.04%)
    Degree 2^13: 281 (0.03%)
    Degree 2^14: 71 (0.01%)
    Degree 2^15: 11 (0.00%)

Computing reference value ...
CPU BFS finished in 192.065536 msec. Search depth is: 8

Validity:
CORRECT
First 40 labels of the GPU result.
[0:-1 1:0 2:-1 3:-1 4:-1 5:-1 6:-1 7:-1 8:-1 9:-1 10:-1 11:-1 12:-1 13:-1 14:-1 15:-1 16:-1 17:-1 18:-1 19:-1 20:-1 21:-1 22:-1 23:-1 24:-1 25:-1 26:-1 27:-1 28:-1 29:-1 30:-1 31:-1 32:-1 33:-1 34:-1 35:-1 36:-1 37:-1 38:-1 39:-1 ]
[GPU DOBFS] finished.
 elapsed: 7.7424 ms, rate: 4527.6889 MiEdges/s, search_depth: 8
 src: 1, nodes_visited: 577120, edges_visited: 35055035

[yuduo@mario]dobfs$ ./bin/test_dobfs_7.0_x86_64 market /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx --src=3 --idempotence
Reading from /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx:
  Parsing MARKET COO format (1048576 nodes, 44620272 directed edges)... Done parsing (15s).
  Converting 1048576 vertices, 44620272 directed edges (unordered tuples) to CSR format...
Done converting (5s).
Reading from /data/gunrock_dataset/large/kron_g500-logn20/kron_g500-logn20.mtx:
  Parsing MARKET COO format (1048576 nodes, 44620272 directed edges)... Done parsing (14s).
  Converting 1048576 vertices, 44620272 directed edges (unordered tuples) to CSR format...
Done converting (7s).

Degree Histogram (1048576 vertices, 44619402 edges):
    Degree   0: 383165 (36.54%)
    Degree 2^0: 130872 (12.48%)
    Degree 2^1: 123131 (11.74%)
    Degree 2^2: 104657 (9.98%)
    Degree 2^3: 94087 (8.97%)
    Degree 2^4: 65886 (6.28%)
    Degree 2^5: 52976 (5.05%)
    Degree 2^6: 43377 (4.14%)
    Degree 2^7: 17652 (1.68%)
    Degree 2^8: 18180 (1.73%)
    Degree 2^9: 7207 (0.69%)
    Degree 2^10: 4188 (0.40%)
    Degree 2^11: 2372 (0.23%)
    Degree 2^12: 463 (0.04%)
    Degree 2^13: 281 (0.03%)
    Degree 2^14: 71 (0.01%)
    Degree 2^15: 11 (0.00%)

Computing reference value ...
CPU BFS finished in 242.751984 msec. Search depth is: 11

Validity:
CORRECT
First 40 labels of the GPU result.
[0:-1 1:-1 2:-1 3:0 4:-1 5:-1 6:-1 7:-1 8:-1 9:-1 10:-1 11:-1 12:-1 13:-1 14:-1 15:-1 16:-1 17:-1 18:-1 19:-1 20:-1 21:-1 22:-1 23:-1 24:-1 25:-1 26:-1 27:-1 28:-1 29:-1 30:-1 31:-1 32:-1 33:-1 34:-1 35:-1 36:-1 37:-1 38:-1 39:-1 ]
[GPU DOBFS] finished.
 elapsed: 10.5392 ms, rate: 3896.4161 MiEdges/s, search_depth: 11
 src: 3, nodes_visited: 634106, edges_visited: 41065234

**Comment by ctcyang** [comment]
Yeah, it works for me too now. I think possible explanations are: 1) I was using outdated commit for gunrock, 2) someone else was using GPU at the same time.
