### ISSUE TITLE
Branch Cleanup: jowens-osx-random-omp

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#270]
Branch Owner: @jowens 
Please let me know if the branch can be deleted, you can transfer the branch over to your personal fork using the following steps:

```
git clone --recursive https://github.com/gunrock/gunrock.git
git checkout jowens-osx-random-omp
git remote set-url --push origin https://github.com/jowens/gunrock.git
git push
```

After doing so, check https://github.com/jowens/gunrock to see if the branch now exists there, and if the latest commits match your branch in gunrock/gunrock. Questions? Ask me here, when the branch is transferred, I will get rid of it in gunrock/gunrock.

**Comment by jowens** [comment]
I think I committed this branch long ago, right? Anyway, yes, delete it. I don't think we need it any more at all. (It was a branch to support OS X, which required figuring out how to use macports's OpenMP and clang's `<random>`.)

**Comment by neoblizz** [comment]
Yeah, the last commit is 2 years old. Got it! Deleting.
