### ISSUE TITLE
Branch Cleanup: mgpu-dev, dev_io, mgpu-cq

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#271]
Branch Owner: @sgpyc 
Please let me know if the branch can be deleted, you can transfer the branch over to your personal fork using the following steps:

```
git clone --recursive https://github.com/gunrock/gunrock.git
git checkout mgpu-dev
git remote set-url --push origin https://github.com/sgpyc/gunrock.git
git push
```

After doing so, check https://github.com/sgpyc/gunrock to see if the branch now exists there, and if the latest commits match your branch in gunrock/gunrock. Questions? Ask me here, when the branch is transferred, I will get rid of it in gunrock/gunrock.

**Comment by neoblizz** [comment]
Some other branches that are also yours @sgpyc: dev_io, mgpu-cq

**Comment by sgpyc** [comment]
I think the "fork" button forks every branches to my personal repo, and now I have all the branches

**Comment by neoblizz** [comment]
Perfect! Can I go ahead and delete the dev_io, mgpu-cq and mgpu-dev? @sgpyc
