### ISSUE TITLE
Branch Cleanup: dev-sm

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#272]
Branch Owner: @Laurawly 
Please let me know if the branch can be deleted, you can transfer the branch over to your personal fork using the following steps:

```
git clone --recursive https://github.com/gunrock/gunrock.git
git checkout dev-sm
git remote set-url --push origin https://github.com/laurawly/gunrock.git
git push
```

After doing so, check https://github.com/laurawly/gunrock to see if the branch now exists there, and if the latest commits match your branch in gunrock/gunrock. Questions? Ask me here, when the branch is transferred, I will get rid of it in gunrock/gunrock.

**Comment by Laurawly** [comment]
I think this version has YZH's TC fixed. I'll try to move it after the IPDPS deadline.

**Comment by neoblizz** [comment]
Thank you! 👍

**Comment by Laurawly** [comment]
@neoblizz Please feel free to remove this branch. I've had everything in dev now. Thanks!
