### ISSUE TITLE
Issues with the python samples

### ISSUE THREAD

**Issue by Akodiat** [gunrock/gunrock#275]
Hi, first of all, the python files seem to have an outdated lib file path:
`~/repo/gunrock/python$ python pagerank.py`
```
Traceback (most recent call last):
  File "pagerank.py", line 6, in <module>
    gunrock = cdll.LoadLibrary('../../build/lib/libgunrock.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ../../build/lib/libgunrock.so: cannot open shared object file: No such file or directory
```

The path seem to have been updated in the commit https://github.com/gunrock/gunrock/commit/93e7bb976a658e6e1683ace1d232cbe2a3dfbd2b, but I need to change the path from:
```python
### load gunrock shared library - libgunrock
gunrock = cdll.LoadLibrary('../../build/lib/libgunrock.so')
```
to:
```python
### load gunrock shared library - libgunrock
gunrock = cdll.LoadLibrary('../build/lib/libgunrock.so')
```
...in order to get them to run.

After the change, the samples seem to work fine, **except for the one I need; SSSP**:
`~/repo/gunrock/python$ python single_source_shortest_path.py`
```
Segmentation fault (core dumped)
```
...Any ideas on how I could fix this?

**Comment by Akodiat** [comment]
...actually breath_first_search.py doesn't work either (with correct lib path), but at least it is providing CUDA errors:

`~/repo/gunrock/python$ python breath_first_search.py`
```
[/home/akodiat/repo/gunrock/gunrock/util/array_utils.cuh, 532 @ gpu 0] column_indices cudaMemcpy H2D failed (CUDA error 11: invalid argument)
[/home/akodiat/repo/gunrock/gunrock/app/bfs/bfs_app.cu, 202 @ gpu 0] Problem BFS Initialization Failed (CUDA error 11: invalid argument)
Segmentation fault (core dumped)
```
Right now I'm using CUDA 9.0, perhaps I should try older versions?

**Comment by neoblizz** [comment]
@Akodiat our library interface for both bfs and sssp were changed a while ago, and the python scripts do not reflect the updated call to the functions. This was fixed in the `dev` branch from where you can copy the fixed files: https://github.com/gunrock/gunrock/tree/dev/python

Let me know if these work.

**Comment by neoblizz** [comment]
@Akodiat fixes are now live in the master branch as well, you don't have to switch, just do `git pull`.

**Comment by Akodiat** [comment]
Thanks so much for your help! Now it works perfectly ☺️
