### ISSUE TITLE
Branch Cleanup: single-gpu, dev-intersection-op

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#276]
Branch Owner: @yzhwang 
Please let me know if the branch can be deleted, you can transfer the branch over to your personal fork using the following steps:

```
git clone --recursive https://github.com/gunrock/gunrock.git
git checkout single-gpu
git remote set-url --push origin https://github.com/yzhwang/gunrock.git
git push
```

After doing so, check https://github.com/yzhwang/gunrock to see if the branch now exists there, and if the latest commits match your branch in gunrock/gunrock. Questions? Ask me here, when the branch is transferred, I will get rid of it in gunrock/gunrock.

**Comment by neoblizz** [comment]
Branch `dev-intersection-op` seems really old too and is 62 commits behind.

**Comment by yzhwang** [comment]
Sorry for the delay. I've transferred both branches to my fork.
This branch is even with gunrock:single-gpu.
This branch is even with gunrock:dev-intersection-op.
You can get rid of both now.
single-gpu is not useful now. I think for dev-intersection-op, @Laurawly has put all the features into her branch or master. She is also doing more dev, so this one is safe to remove.
Thanks for the work Muhammad!

**Comment by neoblizz** [comment]
Thank you! Removing now. 👍
