### ISSUE TITLE
Improve Gunrock's Documentation

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#28]
Need to add details on how to create new graph primitives with problem, functor, and enactor. Proposed method: Add functionality and interface explanation for app/template (the empty sample template graph primitive) so that users can create a minimal running graph primitive by walking through the template code.

**Comment by neoblizz** [comment]
I believe this was resolved in commit#: 2067b1826e8c4c55ead03eabf6eb185a217e266d (reopen and reassign if needed).
