### ISSUE TITLE
Boost custom path

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#281]
I want to give a custom path for my Boost to the cmake. Where exactly should I add that path? It seems that FindBoost.cmake only searches for apt-get installed packages.

**Comment by neoblizz** [comment]
```
set(Boost_NO_SYSTEM_PATHS TRUE) 
if (Boost_NO_SYSTEM_PATHS)
  set(BOOST_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../../3p/boost")
  set(BOOST_INCLUDE_DIRS "${BOOST_ROOT}/include")
  set(BOOST_LIBRARY_DIRS "${BOOST_ROOT}/lib")
endif (Boost_NO_SYSTEM_PATHS)
find_package(Boost REQUIRED regex date_time system filesystem thread graph program_options)
include_directories(${BOOST_INCLUDE_DIRS})
```
Reference: https://stackoverflow.com/questions/3016448/how-can-i-get-cmake-to-find-my-alternative-boost-installation

You can also append `_boost_INCLUDE_SEARCH_DIRS` with your path @ https://github.com/gunrock/gunrock/blob/master/cmake/FindBoostHeaders.cmake#L236

**Comment by neoblizz** [comment]
Since you were able to build gunrock, I am assuming this issue is solved. Closing it, please reopen/comment if you need further help with boost stuff.
