### ISSUE TITLE
make check failed

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#282]
I have exactly the same problem describe [here](https://github.com/gunrock/gunrock/issues/236). However, I didn't understand how the error has been resolved!
The system specs are
    **ubuntu 16.04
    gcc 4.8
    cmake 3.5.1
    CUDA 7.5
    nvidia-384-dev (installed via apt-get)**

Using `ctest -V`, I get

**test 7
      Start  7: SHARED_LIB_TEST_BFS

7: Test command: /home/mahmood/gunrock/build/bin/shared_lib_bfs
7: Test timeout computed to be: 9.99988e+06
7: [/home/mahmood/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 32610] cudaSetDevice failed. (CUDA error 30: unknown error)
7: [/home/mahmood/gunrock/gunrock/app/bfs/bfs_app.cu, 424 @ gpu 0] cudaStreamCreate fialed. (CUDA error 30: unknown error)
7: ERROR ENUMERATING CUDA DEVICES.
7: Exiting.
 7/11 Test  #7: SHARED_LIB_TEST_BFS ..............***Failed  Required regular expression not found.Regex=[Node_ID.*2.*: Label.*1
]  0.01 sec**

**Comment by jowens** [comment]
Can you build and run non-Gunrock GPU programs? Say, from the CUDA distribution, the sample apps? It looks like you have a problem with your CUDA setup / how it's talking to the GPU.

**Comment by mahmoodn** [comment]
Well actually there is no physical GPU on the system!
I am planning to run gunrock on a GPU simulator. So, what should I actually do is to feed the run command to the simulator. 
From your reply, I think the job has been finished here. I have successfully built gunrock and I can see the binaries (bc, bfs, cc, ...) in the bin folder.
I didn't see how to run a dataset in the documents. It has been stated how to generate them. If you know where it is, please let me know.

**Comment by jowens** [comment]
Here's a full Gunrock command line for BFS on the "hollywood-2009" dataset:

https://github.com/gunrock/io/blob/master/gunrock-output/topc/BFS_hollywood-2009_Thu%20Nov%2017%20114443%202016.json

`bfs market /data/Compare/topc-datasets/hollywood-2009.mtx --src=0 --undirected --idempotence --queue-sizing=6.5 --in-sizing=4 --iteration-num=10 --direction-optimized --device=0 --traversal-mode=LB_CULL --do_a=0.006 --do_b=0.1 --jsondir=./eval/`

Much simpler to just do

`bfs market /data/Compare/topc-datasets/hollywood-2009.mtx --src=0 --undirected`

if you want to treat hollywood-2009 as an undirected data set and start at vertex 0.

**Comment by neoblizz** [comment]
Adding to that there are some small datasets in `/path/to/gunrock/dataset/small` and if you would like to build the larger ones you can run `make` in `/dataset/large`.

**Comment by jowens** [comment]
Here's a full run with the command line above (on our 'mario' system):

```
jowens@mario:~/working/gunrock-build$ bin/bfs market ../gunrock/dataset/large/hollywood-2009/hollywood-2009.mtx --src=0 --undirected
Loading Matrix-market coordinate-formatted graph ...
Reading from ../gunrock/dataset/large/hollywood-2009/hollywood-2009.mtx:
  Parsing MARKET COO format (1139905 nodes, 115031232 directed edges)... Done parsing (20s).
  Converting 1139905 vertices, 115031232 directed edges (unordered tuples) to CSR format...
Done converting (7s).

Degree Histogram (1139905 vertices, 112751422 edges):
    Degree   0: 32662 (2.87%)
    Degree 2^0: 24445 (2.14%)
    Degree 2^1: 50032 (4.39%)
    Degree 2^2: 99398 (8.72%)
    Degree 2^3: 174673 (15.32%)
    Degree 2^4: 231414 (20.30%)
    Degree 2^5: 219393 (19.25%)
    Degree 2^6: 139586 (12.25%)
    Degree 2^7: 78822 (6.91%)
    Degree 2^8: 44379 (3.89%)
    Degree 2^9: 25905 (2.27%)
    Degree 2^10: 13729 (1.20%)
    Degree 2^11: 5233 (0.46%)
    Degree 2^12: 230 (0.02%)
    Degree 2^13: 4 (0.00%)

Source vertex: 0
Using 1 GPU: [ 0 ].
Using traversal-mode LB
__________________________
0	 4	 0	 queue3 	 oversize :	 7409384 ->	 52557065
0	 5	 0	 queue3 	 oversize :	 52557065 ->	 56516755
--------------------------
iteration 0 elapsed: 20.668030 ms, src = 0, #iteration = 11
Computing reference value ...
CPU BFS finished in 562.651855 msec. cpu_search_depth: 11

Label Validity:
CORRECT

First 40 labels of the GPU result:
[0:0 1:1 2:1 3:1 4:5 5:5 6:5 7:5 8:6 9:6 10:6 11:6 12:6 13:6 14:6 15:6 16:6 17:6 18:6 19:6 20:6 21:6 22:6 23:6 24:6 25:6 26:5 27:6 28:6 29:6 30:6 31:6 32:6 33:6 34:6 35:6 36:6 37:6 38:6 39:6 ]

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 1247805440	 7409384	 56516755
	 queue_sizing =	 6.500001 	 49.580233

 [BFS] finished.
 avg. elapsed: 20.6680 ms
 iterations: 11
 min. elapsed: 20.6680 ms
 max. elapsed: 20.6680 ms
 rate: 5448.6714 MiEdges/s
 src: 0
 nodes_visited: 1069126
 edges_visited: 112613306
 nodes queued: 1069126
 edges queued: 112613306
 load time: 27806.3750 ms
 preprocess time: 610.8100 ms
 postprocess time: 44.2581 ms
 total time: 29439.2700 ms
```

**Comment by mahmoodn** [comment]
Many thanks for the quick replies.
I have noticed that there is also a [hollywood-2011](http://law.di.unimi.it/webdata/hollywood-2011/) dataset with larger nodes. This is just a suggestion...

May I know which part of the code starts the GPU section?

**Comment by jowens** [comment]
Oh, we run all sorts of datasets. There are bigger ones there too. I just picked that one randomly.

@sgpyc probably can instantly tell you what the entry point is. I can't.

**Comment by ctcyang** [comment]
Our BFS runs two kernels: an advance and a filter. For advance, we give the user a choice of 8 kernels that provide different load-balancing characteristics and the option of direction-optimized traversal (postfixed `_BACKWARD`). The first advance strategy `TWC_FORWARD` is [here](https://github.com/gunrock/gunrock/blob/master/gunrock/oprtr/advance/kernel.cuh#L274). The kernel entrypoint is within each struct. For example, for TWC_FORWARD, kernel entry begins at `Line 284`. If you do a find and search for `, gunrock::oprtr::advance::`, you should be able to find the other 7 advances. There is a nice table in the Gunrock paper that summarizes the differences of each strategy [1].

The other component of our BFS is in this [file](https://github.com/gunrock/gunrock/blob/master/gunrock/oprtr/filter/kernel.cuh). Similarly for Filter, he different choices for the filter kernel are located in each `Dispatch` struct. The strategy is found as the last template parameter e.g. CULL.

[1] Gunrock paper: https://arxiv.org/pdf/1701.01170

**Comment by mahmoodn** [comment]
Thanks. I am reading that. 
I will close this topic now.
