### ISSUE TITLE
Device check issue

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#283]
I want to feed the bfs to a simulator. So, I have to remove the "device check" in the gunrock code. Currently, when I run the application with the simulator command, I get:

```
Done converting (0s).
Source vertex: 0
Using 1 GPU: [ 0 ].
[/home/mahmood/gunrock/gunrock/util/info.cuh, 470 @ gpu 32766] cudaGetDevice failed (CUDA error 38: no CUDA-capable device is detected)
[/home/mahmood/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 0] cudaSetDevice failed. (CUDA error 38: no CUDA-capable device is detected)
[/home/mahmood/gunrock/gunrock/util/info.cuh, 484 @ gpu 0] cudaStreamCreate failed. (CUDA error 38: no CUDA-capable device is detected)
CODE REQUESTED INVALID CUDA DEVICE -841064104

```
I looked at the code for that messages. In multiple parts, this is checked and I doubt if simply commenting those part is the trick. Is it possible to bypass the existence check of the cuda device? 
Any idea for that?

**Comment by jowens** [comment]
It's not a "device check", it's actually figuring out which device we're targeting and setting it appropriately. Also we do use CUDA streams. These are legit and useful CUDA calls. I think this needs to be something you take up with the simulator authors.

**Comment by sgpyc** [comment]
@mahmoodn If you are only running on single "device", then can replace `util::SetDevice()` https://github.com/gunrock/gunrock/blob/master/gunrock/util/test_utils.cu#L58 with something else. It's also safe to bypass any `cudaSetDevice()` calls, when using only single "device"; and bypass any 'cudaGetDevice()' to always return 0. If still failing at `cudaStreamCreate()`, then the GPU simulator you use is not complete; using the 0 stream might get Gunrock running, but it's not designed to run on stream 0, and the program may hang.

But as a long term solution, a simulator should also handle `cudaSetDevice()`, it's a common way to select which GPU to use.

**Comment by neoblizz** [comment]
This was very well answered, it seems like the simulator problem if it doesn't handle `cudaSetDevice()`, which has been around for a while now. Please let us know if you have more questions regarding this, closing the issue for now.
