### ISSUE TITLE
Gunrock app writing guide

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#285]
How do you write a Gunrock app? We need a documentation page that answers this question.

@neoblizz Assigning this to you, cc @sgpyc. I think it's important this be written by someone who is not @sgpyc. I will edit this and make comments for you. Assign it to me when you need a read.

This does not have to be very polished at this point. It can be rough. Do not let the perfect be the enemy of the good here. Something is better than nothing.

**Comment by agalup** [comment]
Can you add me here. I want to write based on my experience.

**Comment by jowens** [comment]
We have nothing beyond what you see in gunrock/docs and the talks that @neoblizz / @sgpyc gave earlier this year at GTC. So whatever you want to write is very welcome.

**Comment by zawadisvela** [comment]
Hello. I'm currently trying to learn Gunrock and found this issue. Is there any tutorial or guide for writing Gunrock programs that is up to date with the 1.0 interface? By googling I found one annotated example from 0.2 but not much else.

**Comment by neoblizz** [comment]
> Hello. I'm currently trying to learn Gunrock and found this issue. Is there any tutorial or guide for writing Gunrock programs that is up to date with the 1.0 interface? By googling I found one annotated example from 0.2 but not much else.

Extremely late, but I just saw this. I hope this helps if you're still looking to experiment with gunrock: https://github.com/gunrock/essentials/wiki/How-to-write-a-new-graph-algorithm
