### ISSUE TITLE
Gunrock app porting guide

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#286]
How do you port a Gunrock app from old-API to new-API? We need a documentation page that answers this question.

Assigning this to @sgpyc, cc: @neoblizz. I will edit this and make comments for you. Assign it to me when you need a read. I would also like to port one app and will be the guinea pig (at least I hope I can). PageRank maybe.

This does not have to be very polished at this point. It can be rough. Do not let the perfect be the enemy of the good here. Something is better than nothing.

**Comment by sgpyc** [comment]
The porting guide is drafted at https://github.com/gunrock/gunrock/blob/dev-refactor/doc/v0.5_portingguide.md

**Comment by neoblizz** [comment]
Not relevant now.
