### ISSUE TITLE
Converting from .graph to .mtx

### ISSUE THREAD

**Issue by bharathbs93** [gunrock/gunrock#293]
Is there any way to convert .graph input files(DIMACS) or .txt(SNAP) to a .mtx format which is accepted by GUNROCK?

**Comment by neoblizz** [comment]
@bharathbs93 could you link me to this .graph format? Is it .gr format, if so we have a tool to convert it into .mtx under `gunrock/tools` (see https://github.com/gunrock/gunrock/tree/master/tools).

**Comment by bharathbs93** [comment]
@neoblizz I think the 9th Dimacs challenge had(.gr) format and the 10th had .graph format. Are .gr and .graph the same for GUNROCK?. Here is the link to both the .txt and .graph format(see:https://github.com/bharathbs93/Graph-Theory-Project).

**Comment by neoblizz** [comment]
@bharathbs93 sorry about the late reply, I looked into the .graph format and it seems different from the .gr format. I couldn't find specs on how the formatting happens and what each row means (and the cols). I think if you can find the spec it shouldn't be hard to write it into an mtx format as the specs for mtx are well defined and available here: http://math.nist.gov/MatrixMarket/formats.html

I don't know if this is the right question for us, maybe stackoverflow could help you figure out if a tool for .graph to .mtx already exist? .gr to .mtx is under gunrock/tools, like I mentioned before.

Another thing I noted was the graph500 challenge graphs can be generated, they gave all the parameters and told us that it was an rmat graph. So, that should be fairly easy to generate. They also have python generators on the graph500.org website. Hope this helped, let us know if you have  further questions on gunrock.

**Comment by neoblizz** [comment]
Ok, so on further investigation `.graph` format is actually METIS graph format available here: http://people.sc.fsu.edu/~jburkardt/data/metis_graph/metis_graph.html

**Comment by bharathbs93** [comment]
Thanks for the help @neoblizz !
