### ISSUE TITLE
PR Shared Library Test: Inconsistent Node IDs

### ISSUE THREAD

**Issue by shivampdesai** [gunrock/gunrock#295]
Every run of shared_lib_pr gives multiple inconsistent ID values for the top ranked nodes. However, running pr on a different graph is giving consistent results in terms of node id and pagerank.

**Comment by neoblizz** [comment]
Yuechao answered this:
> PR’s result is more complex than CORRECT vs. WRONG. I normally check the PR value differences, the relative differences, and the order of rankings
