### ISSUE TITLE
gmock error when compiling

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#296]
When I compile the Gunrock using teh dev branch, errors are reported when Itype make command.
(I have installed gmock using yum install gmock-devel, but I do not find libgmock in my system)
```
[ 98%] Built target topk
Linking CXX executable ../bin/unit_test
/usr/bin/ld: cannot find -lgmock
collect2: 错误：ld 返回 1
make[2]: *** [bin/unit_test] 错误 1
make[1]: *** [tests/CMakeFiles/unit_test.dir/all] 错误 2
make: *** [all] 错误 2
```

**Comment by jowens** [comment]
We're adding Google Test support. Can you install it and try again?

https://github.com/google/googletest

**Comment by jowens** [comment]
(gmock has been absorbed into google test)

**Comment by neoblizz** [comment]
Please try this again after turning this option off: https://github.com/gunrock/gunrock/blob/dev/CMakeLists.txt#L69

**Comment by bookug** [comment]
Thanks a lot. I try to change the option from ON to OFFin CMakeLists.txt, but it still does not work.
What can I do now?

**Comment by bookug** [comment]
I used to compile the master branch , it works well. 
It seems the master branch does not use the Google Test framework.
Is the problem located in GoogleTest framework?

**Comment by neoblizz** [comment]
I am guessing the install you already have on your system is conflicting with our download method. Could you please switch back to dev and try `git pull` to update the repo and build again? It should be fixed after you turn the option back to OFF.

**Comment by bookug** [comment]
yes, it works, thank you:)
