### ISSUE TITLE
The edgeweight used for web graph in SSSP benchmark

### ISSUE THREAD

**Issue by septicmk** [gunrock/gunrock#299]
I download the soc-orkut graph(using the script in your dataset/large/soc-orkut) but it has no weights for SSSP benchmark. I found you generate the weights in the range of 0~63？ 

https://github.com/gunrock/gunrock/blob/master/gunrock/graphio/market.cuh#L363

Is it the same in your PPoPP'16 paper? I just want to reproduce the SSSP experiment. 
Thanks a million.

**Comment by jowens** [comment]
Here's what we used:

https://github.com/gunrock/io/blob/master/gunrock-output/topc/SSSP_soc-orkut_Thu%20Nov%2017%20234030%202016.json

but I don't actually know where the weights come from. @sgpyc? @yzhwang?

**Comment by sgpyc** [comment]
When asking for edge values and if they don't exist, the .mtx reader will generate from [0, 63] (https://github.com/gunrock/gunrock/blob/master/gunrock/graphio/market.cuh#L363 ). After generation, the graph (together with the edge weights) may be stored as hidden binary files in the same directory as the .mtx file, for speeding up the reading process.
