### ISSUE TITLE
On the sample_example directory, 'cpu_graph_lib.cpp' file is missing.

### ISSUE THREAD

**Issue by allenkim0129** [gunrock/gunrock#300]
Anyone know where I can find this file? I cannot run cmake, because this file was missing.

**Comment by jowens** [comment]
Which branch are you running? master? dev?

**Comment by allenkim0129** [comment]
Its master branch.

**Comment by jowens** [comment]
So that got deleted evidently more than 2 years ago. @yzhwang, any wisdom for us?

https://github.com/gunrock/gunrock/commit/d217070b3cff9056282965591d48c16a83b2a44b

**Comment by jowens** [comment]
Also @neoblizz, building this (if not running it) ought to be part of the Jenkins runs.

**Comment by yzhwang** [comment]
@allenkim0129 Are you trying to build from the head? In the commit @jowens referred to I did a refactoring and moved functions in cpu_graph_lib to test_utils.h. I've also updated the reference CPU algorithms from RefCPU{BC,CC,BFS} to Reference{BC,CC,BFS}. Anyway, that was an old refactoring. I'd ve surprised that if this doesn't build using the head of master branch.

**Comment by jowens** [comment]
I'm pretty sure that the cmakefile still wants `cpu_graph_lib.cpp`.

**Comment by ctcyang** [comment]
I just did a clean pull from master branch into an empty folder and Gunrock built correctly. So my recommendation would be doing that.

The most common CMake error I get has to do with CMake caching an old folder structure or changing `CMakeLists.txt`. That can lead to CMake requesting files that no longer exist. If you want to build into the same folder as before, you can try doing:
```
rm CMakeCache.txt
rm -rf CMakeFiles
cmake .
```

**Comment by jowens** [comment]
Just checking, @ctcyang, _Gunrock_ built correctly or _sample\_example_ built correctly?

**Comment by ctcyang** [comment]
Oops, I thought it was Gunrock you guys were talking about. I made a CMakeLists.txt that gets past the `cmake .` phase: https://gist.github.com/ctcyang/8d94004da377a526a8cd014662188096

However, typing `make` generates a bunch of errors having to do with the interface.

```
simple_example.cu(674): error: too many arguments for class template "gunrock::app::cc::CCProblem"
          detected during:
            instantiation of "VertexId RunCC_size_check<VertexId,Value,SizeT,INSTRUMENT,DEBUG>(gunrock::util::Info<VertexId, Value, SizeT> *) [with VertexId=int, Value=int, SizeT=int, INSTRUMENT=true, DEBUG=true]"
(962): here
            instantiation of "VertexId RunCC_debug<VertexId,Value,SizeT,INSTRUMENT>(gunrock::util::Info<VertexId, Value, SizeT> *) [with VertexId=int, Value=int, SizeT=int, INSTRUMENT=true]"
(987): here
            instantiation of "VertexId RunCC_instrumented(gunrock::util::Info<VertexId, Value, SizeT> *) [with VertexId=int, Value=int, SizeT=int]"
(1889): here

simple_example.cu(677): error: too many arguments for class template "gunrock::app::cc::CCEnactor"
          detected during:
            instantiation of "VertexId RunCC_size_check<VertexId,Value,SizeT,INSTRUMENT,DEBUG>(gunrock::util::Info<VertexId, Value, SizeT> *) [with VertexId=int, Value=int, SizeT=int, INSTRUMENT=true, DEBUG=true]"
(962): here
            instantiation of "VertexId RunCC_debug<VertexId,Value,SizeT,INSTRUMENT>(gunrock::util::Info<VertexId, Value, SizeT> *) [with VertexId=int, Value=int, SizeT=int, INSTRUMENT=true]"
(987): here
            instantiation of "VertexId RunCC_instrumented(gunrock::util::Info<VertexId, Value, SizeT> *) [with VertexId=int, Value=int, SizeT=int]"
(1889): here
```

**Comment by jowens** [comment]
Fixing this example might want to wait for @sgpyc's API rewrite.

**Comment by neoblizz** [comment]
@allenkim0129 does this happen on a regular gunrock build or are you trying to add the simple_example directory in the cmake file and then attempting a compile?

**Comment by neoblizz** [comment]
Closing this, because this is a template and this issue will be addressed in the dev_refactored.
