### ISSUE TITLE
When can we use the subgraph isomorphsim program on GPU?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#301]
Which algorithm are you using to solve the subgraph isomorphism problem on GPU?

**Comment by jowens** [comment]
That work is very much in progress so we don't have any sort of firm answer yet. This at least gives some of our approaches to triangle-counting, which has some similarities to what we hope to eventually do with subgraph isomorphism ... https://escholarship.org/uc/item/9hf0m6w3
