### ISSUE TITLE
Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"

### ISSUE THREAD

**Issue by aicampbell** [gunrock/gunrock#302]
I'm currently trying to compile Gunrock with Cuda 9 and Boost 1.65.1 from my home directory.

While building, I get to:
 [5%]  Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o 

and get this error:
Error: Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"

CMake Error at gunrock_generated_pr_app.cu.o.cmake:279 (message):
  Error generating file
  /home/acampbell/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o

gunrock/CMakeFiles/gunrock.dir/build.make:84: recipe for target 'gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o' failed
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'gunrock/CMakeFiles/gunrock.dir/all' failed
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

Is there any way to fix this?

**Comment by jowens** [comment]
Wow. "Internal compiler error" is kind of hard to work out.

@neoblizz what version of Boost are we using? I seem to recall some issues with newest Boosts.

@aicampbell you should include stuff like "compiler version" and "OS" in your bug report.

**Comment by aicampbell** [comment]
I'm running Debian 9, cmake 3.10.1 with the following compilers:
g++       4:6.3.0-4                                                
 g++-6   6.3.0-18                                                  
gcc       4:6.3.0-4                                                  
gcc-6    6.3.0-18                                                   

I had this compiling a few weeks ago but all of the nodes I'm using got upgraded to Debian 9 and CUDA 9 which has broken everything for me.

I tried using an earlier version of Boost e.g 1.64 but I get this problem almost immediately:
#define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."

**Comment by neoblizz** [comment]
This was reported to be an nvcc problem, I have seen this in past in another project. Could you try using gcc/g++ 5 with CUDA 9? And the boost version we recommend and have tested for is 1.58.

**Comment by jowens** [comment]
Oh, yes, if you're not using a compiler version listed here (http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html), you're gonna have a bad time, not just with Gunrock but with any CUDA code.

**Comment by aicampbell** [comment]
I changed the compiler to gcc 5.5, used Boost 1.58 and everything worked.
Thanks for your help
