### ISSUE TITLE
Connecting a java app to gunrock

### ISSUE THREAD

**Issue by imanima** [gunrock/gunrock#308]
Hi Gunrock team,

we are working on a graph data processing platform written in Java (connected to Neo4j db) and we are planning on using Gunrock to do the heavy graph processing. What is the best way to connect to Gunrock from a java application ?

**Comment by jowens** [comment]
Gunrock has C/C++ bindings. Does Java have any way to call these? You can look at the Gunrock-python code for examples.

We have no experience with Java+C in our group.

**Comment by neoblizz** [comment]
As John mentioned, I will look into bindings to call C or Python functions, here's an example: https://stackoverflow.com/a/5963294 there are similar calls for python as well and you can find these interface in gunrock/tests. Hope this helps!
