### ISSUE TITLE
Max Flow Primitive

### ISSUE THREAD

**Issue by shivampdesai** [gunrock/gunrock#309]
Running MF on any graph input returns an array of inaccurate flow values (array of only 0s). I tried to return an array of flows rather than excess values but it produced the same result. The changes were made in test_mf.cu to the RunTests() function which makes calls to MF_Enactor and MF_Problem. 

For the sample graph below, the expected result of maxflow is 23:

6 6 10
1 2 16
1 3 13
2 3 10
3 2 14
2 4 12
4 3 9
3 5 14
5 4 7
5 6 4
4 6 20

But the generated output is: 
flow[0]: 0
flow[1]: 0
flow[2]: 0
flow[3]: 0
flow[4]: 0
flow[5]: 0
An amount of flow pushed from the source towards the sink: [0]

**Comment by neoblizz** [comment]
This issue is also addressing the previously created issue regarding MF #249 #248. @agalup can we get some eyes on this? Any comment will be helful, we are looking for the host variable with the MF results.

**Comment by neoblizz** [comment]
Merging the MaxFlow issues into one issue. We should be able to address this soon.
