### ISSUE TITLE
CMake warnings under OS X

### ISSUE THREAD

**Issue by gangliao** [gunrock/gunrock#316]
CMake warnings under OS X: MACOSX_RPATH is not specified for the following targets.

**Comment by jowens** [comment]
Since upgrading my laptop (👍 ) I no longer have NVIDIA graphics in it (👎 ). No one's actively developing anything on OS X any more, sadly.

**Comment by gangliao** [comment]
Yeah, I still use the old laptop with GTX 750M.

**Comment by gangliao** [comment]
@jowens  We can install cuda in travis ci, then it can help to check the building process of Mac OS X with GPU [no test]. https://docs.travis-ci.com/user/reference/osx/

**Comment by neoblizz** [comment]
PR merged.

**Comment by jowens** [comment]
@gangliao We don't exactly have a Mac in our server rack. :) 

Please help me continue to harass NVIDIA employees to take a huge loss to put NVIDIA graphics in every MacBook Pro. Actually, my understanding is that we'll someday soon be able to buy a standalone GPU that plugs through USB-C , e.g., Razer Core, and hopefully use that.

**Comment by gangliao** [comment]
@jowens  My former colleague in Baidu also plugs GPU on MacBook use that way since he likes coding in the modern editors e.g., VS CODE and QT.

**Comment by jowens** [comment]
@gangliao I'll try to get some feedback on this. A little googling suggests that Apple is moving in this direction (spring 2018) for more eGPU support. For me, I want something that requires minimal/no hacking to make it work, I just want to plug something in and it works. Don't even care if I get graphics output. CUDA only.

**Comment by jowens** [comment]
@gangliao https://developer.apple.com/development-kit/external-graphics/

The Sonnet boxes appear what I want here, though the OS release that puts them into support isn't out yet. Hopefully soon!
