### ISSUE TITLE
Better way to handle kernel call parameters

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#32]
CUDA stores kernel parameters in shared memory. The limit is 256 bytes total. If using 64-bit, that's only 32 pointers/ints/floats. Currently Gunrock's number of arguments for kernel calls are getting more and more. Putting them all together in a struct and passing a handle would make the interface much cleaner.

**Comment by sgpyc** [comment]
The refactored API has cleaner interface for the operators, e.g. https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/sssp/sssp_enactor.cuh#L129.
Now it only takes in 6 parameters.
@yzhwang consider closing this issue?
