### ISSUE TITLE
What is the maximum dataset in the experiments?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#322]
Is there any datasets with tens of thousands of nodes?

**Comment by sgpyc** [comment]
We did test Gunrock with graphs in the range of hundred million vertices and billions of edges. The GPU memory size is the limiting factor in terms of how big the graph can be.

The following databases may be the starting point to look for them:
https://www.cise.ufl.edu/research/sparse/matrices/list_by_dimension.html
http://networkrepository.com/networks.php

**Comment by limadm** [comment]
Hi! I got a Titan Xp with 12G G5X memory. Are 1.4G nodes and 13G edges filling up all my memory? (The log says market cannot parse more than 388M)

```
  Parsing MARKET COO format (1413511393 nodes, 13273201558 directed edges)... Error parsing MARKET graph:encountered more than 388299670 edges
[/home/dan/gunrock/gunrock/util/array_utils.cuh, 532 @ gpu 0] row_offsets cudaMemcpy H2D failed (CUDA error 11: invalid argument)
[/home/dan/gunrock/tests/pr/test_pr.cu, 641 @ gpu 0] PR Problem Init failed (CUDA error 11: invalid argument)
```

**Comment by jowens** [comment]
13G edges at 4 bytes per edge is 52 GB. If you have a GPU with 52 GB of memory, we'd sure like to hear about it. :)

**Comment by limadm** [comment]
Thanks for the clarification, I'm working in a sparse matrix solver for GPU and wanted to import (or maybe complement) gunrock so I'll be back in some weeks, bye!
