### ISSUE TITLE
Generating large Rmat graphs fails

### ISSUE THREAD

**Issue by jwyles** [gunrock/gunrock#328]
When running bfs generating an rmat graph  setting the rmat_scale greater than 25 gives errors. Either something like, for scale = 26:
```
Generating R-MAT graph ...
Invalid graph size: nodes=67108864, edges=-1073741824  Converting 0 vertices, 0 directed edges (unordered tuples) to CSR format...
```
or for larger, scale 30:

```
Generating R-MAT graph ...
rmat_seed = 1521742355
  Converting 1073741824 vertices, 0 directed edges (unordered tuples) to CSR format...
Done converting (1s).
```

**Comment by sgpyc** [comment]
You need the `--64bit-SizeT` command line argument.
In default settings, SizeT (the type of EdgeId) is 32bit signed, rmat with scale 26 and default edge factor 48 will have the number of edges larger than 2^31, which overflows 32bit signed integers.

For Scale 30, you need at least (2^30 * 48 * 4 Bytes / per-GPU memory size) GPUs to store the graph, double that if you use DOBFS or `--undirected`. I don't think it should be tried on a single node, and such graph takes forever to generate.

**Comment by jwyles** [comment]
Thanks that fixes it for me.
