### ISSUE TITLE
how to generate R-MAT graphs?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#329]
Does this project include this function?

**Comment by sgpyc** [comment]
If you want to use R-MAT graphs within Gunrock, `rmat` or `grmat` command line parameters will generate them.

**Comment by bookug** [comment]
Where is the grmat command?

**Comment by neoblizz** [comment]
@bookug I believe you can just use the following parameter for your primitive: `grmat --rmat_scale=22 --rmat_edgefactor=64`, all rmat configs apply to grmat as well.
