### ISSUE TITLE
Conversion from Boost Graph boost::adjacency_list

### ISSUE THREAD

**Issue by NaniBird** [gunrock/gunrock#332]
Hi,

I have a `boost::adjacency_list` and would like to convert it to a gunrock-compatible object.
Is there any API allowing that ?

 Thank you

**Comment by NaniBird** [comment]
So, should I convert it first to a `GRGraph` type beforehand ?

**Comment by neoblizz** [comment]
@NaniBird we have two calls, gunrock_bfs which uses GRGraph struct or bfs which uses CSR format (therefore pointers to row_offsets and col_indices), you can decide which one to use.

```
float gunrock_bfs(
    struct GRGraph*       grapho,   // Output graph / results
    const struct GRGraph* graphi,   // Input graph structure
    const struct GRSetup* config,   // Flag configurations
    const struct GRTypes  data_t);  // Data type Configurations
```

```
float bfs(
    int*       bfs_label,
    int*       bfs_pred,
    const int  num_nodes,
    const int  num_edges,
    const int* row_offsets,
    const int* col_indices,
    const int  num_iters,
    int* source,
    enum SrcMode source_mode,
    const bool mark_predecessors,
    const bool enable_idempotence);
```

We have a C and Python example of these too if you'd like to look at that:
https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_bfs.c#L31
https://github.com/gunrock/gunrock/blob/master/python/breadth_first_search.py#L26

**Comment by NaniBird** [comment]
Ok, So no direct support for boost::adjacency_list. 
Could be convenient to have a converter in gunrock between boost graph types and GRGraph. 
Thanks anyway.

**Comment by neoblizz** [comment]
With the new refactored code we have the ability to easily add support for this, but not in the master branch version. We will consider, thanks!
