### ISSUE TITLE
How is the shortest path algorithm implemented on GPU?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#333]
Does there exist any mature papers or systems?

**Comment by jowens** [comment]
Most graph frameworks on GPUs have some sort of shortest-path algorithm. The Gunrock paper talks a bit about how we implement ours, and this paper (https://escholarship.org/uc/item/8qr166v2) ought to be among the best algorithms (we're moving toward implementing this on Gunrock).

**Comment by neoblizz** [comment]
Not a paper, but we also discuss Gunrock's SSSP implementation in the GTC 2018 talk. It was a tutorial on how to write a graph primitive in Gunrock with SSSP as an example: https://github.com/gunrock/gunrock/blob/master/doc/Writing-Gunrock-Primitives.pdf, there is also a video available for this and the slides include the pseudocode of the algorithm.
