### ISSUE TITLE
Compilation issue - cannot compile Pagerank project

### ISSUE THREAD

**Issue by kf4ayt** [gunrock/gunrock#334]
Greetings all,

In attempting to compile Gunrock, I have hit a 'snag' when 'make' attempts to compile the Pagerank project. Below is the command line output. For the record, I'm running Debian 9.4 with gcc 6.3.0, CUDA 9.1, Boost 1.67, and Metis 5.1. When going to install Gunrock, I cloned it from the Github site recursively.

Any help would be greatly appreciated as I've hit a dead-end in troubleshooting this.

Charles Johnson

~~~~~~~

charles@xxxxxxx:~/gunrock/build$ sudo cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found suitable version "9.1", minimum required is "7.5") 
-- Boost version: 1.67.0
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenMP
-- Found Metis
-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Configuring done
-- Generating done
-- Build files have been written to: /home/charles/gunrock/build
charles@xxxxxxx:~/gunrock/build$ sudo make
[  1%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o
[  2%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/bfs/gunrock_generated_bfs_app.cu.o
[  3%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/bc/gunrock_generated_bc_app.cu.o
[  4%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/cc/gunrock_generated_cc_app.cu.o
[  5%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o
Error: Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"

CMake Error at gunrock_generated_pr_app.cu.o.cmake:279 (message):
  Error generating file
  /home/charles/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o


gunrock/CMakeFiles/gunrock.dir/build.make:84: recipe for target 'gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o' failed
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'gunrock/CMakeFiles/gunrock.dir/all' failed
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jowens** [comment]
CUDA is very specific on the compiler versions it requires. I don't even see Debian on the list here:

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

but my strong suspicion is that you need the right combination of OS/CUDA/gcc to avoid this error.

**Comment by kf4ayt** [comment]
@jowens,

I installed the CUDA 9.1 toolkit (and the 390.48 display driver) via the Debian package system and have been compiling and running SSSP and APSP programs with success. I've also installed cuDNN v7.1 and it passed the post-install test (the MNIST example). Is Gunrock particularly OS-picky?

Regards,

Charles Johnson

PS For Debian, you can usually select Ubuntu and be OK if they don't have Debian. I know that for cuDNN, I selected Ubuntu 16.04 and was good to go.

**Comment by jowens** [comment]
I wouldn't say Gunrock is "OS-picky" as much as it uses modern CUDA constructs that might not be present in other packages. We have in the past identified CUDA compiler bugs via Gunrock. In our experience, the error you're seeing is a CUDA compiler bug.

I will ping someone at NVIDIA about what to do here, but I expect the answer will be one of these three:
1. We don't support Debian.
2. We do support Debian, but you need to use (other compiler version X) and/or (other OS version Y)
3. That sounds like a CUDA compiler bug. Could you please file that bug in our developer system?

**Comment by jowens** [comment]
So I think the answers are 1 and 3. Unnamed NVIDIA person who's in a position to know notes

> We haven’t validated CUDA 9.1 on Debian (so it's not a supported OS). However, I would have expected gcc 6.x to work as a host compiler to nvcc 9.1.

The Gunrock team is using Ubuntu 16.04 with gcc 5.4 (and we do not see this bug). If we saw this bug on our own systems, we would file a bug report with NVIDIA, since this appears to be an NVIDIA compiler bug.

**Comment by kf4ayt** [comment]
@jowens,

My apologies for the delay in responding. What is the procedure for reporting a compiler bug to NVIDIA? I've looked through the developer part of their website, but couldn't find anything that looked appropriate.

In the meantime, do you think installing gcc 5.4 and attempting to compile Gunrock with that might fix the problem?

Regards,

Charles Johnson

**Comment by jowens** [comment]
https://developer.nvidia.com/developer-program   <- apply there

**Comment by jowens** [comment]
I can't offer any particular insight on what software versions are appropriate with Debian. All of our experience is Ubuntu, sorry.

**Comment by neoblizz** [comment]
@kf4ayt were you able to resolve this issue?

**Comment by kf4ayt** [comment]
@neoblizz,

Unfortunately, I've yet to be able to resolve the issue. Life took me off on a tangent, such that I've been unable to work on the problem further. I meant to close this thread some time ago, but time got away from me :-\

Later this summer, if I can either cobble together the pieces for a Ubuntu machine or set up one of my Debian machines with an SSD loaded with Ubuntu as an alternate boot device, I'll explore the matter further.

Charles Johnson

**Comment by neoblizz** [comment]
@kf4ayt I hope you figure it out. I asked because I just noticed that you are using `Boost 1.67` and we found that `1.58` is the most stable with gunrock. That with upgrading your cuda to 9.2 would be something worth exploring.

I am going to close this issue for now, but feel free to return to it when you are working on it again. We would like to help you get it working!
