### ISSUE TITLE
How to develop other graph algorithms based on Gunrock framework?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#335]
The interface is not so clear, I need help:)  
I read your paper titled "Fast Parallel Subgraph Matching on the GPU", and I want to compare the subgraph isomorphism algorithm in thsi paper. 
Can you give me some advice on how to implement it? It is also ok to give me the code of that paper:)

**Comment by jowens** [comment]
We're still actively developing this code so it's not really in the shape to share as any sort of completed project. Looks like the most recent version is here:

https://github.com/gunrock/gunrock/tree/dev/gunrock/app/sm

@Laurawly ?

**Comment by sgpyc** [comment]
@bookug Take a look at the new (refactored) API in the dev-refactor branch? It should make things easier.
Mohammad and I gave a talk at GTC for how to write graph primitives in Gunrock, you can find it at https://github.com/gunrock/gunrock/blob/master/doc/Writing-Gunrock-Primitives.pdf and http://on-demand.gputechconf.com/gtc/2018/video/S8586/ .
