### ISSUE TITLE
Hang in BC, observed only on mgpu dev/merge branch

### ISSUE THREAD

**Issue by ydwu** [gunrock/gunrock#35]
using graph: `test_bc.mx` when setting `--src=-1` no matter whether add `undirected` or setting `device`.

    [yuduo@mario]bc$ bin/test_bc_7.0_x86_64 market /data/gunrock_dataset/small/test_bc.mtx --src=-1 --device=0,1
    Using 2 gpus:  0  1
    src = -1
    partition_method = random
    Partition begin. seed=1436459662
    1	   	   	 out_offsets = 0, 4, 7  
    0	   	   	 out_offsets = 0, 3, 7
    0	   	   	 out_counter = 3, 4, 7
    0	   	   	 in_counter  = 3, 3, 6
    1	   	   	 out_counter = 4, 3, 7
    1	   	   	 in_counter  = 4, 4, 8
    partition end. (0.350617 ms)
    Computing reference value ...
    CPU BC finished in 0.017811 msec.
    0	   	   	 in_counter = 3, 3, 6
    1	   	   	 in_counter = 4, 4, 8
    __________________________
    0	   	   	 in_counter = 3, 3, 6
    1	   	   	 in_counter = 4, 4, 8
    Iteration entered
    Iteration entered
    1	 0	 0	 queue3 	 oversize :	 6 ->	 9
    1	 1	 0	 queue3 	 oversize :	 6 ->	 9
    0	 1	 0	 queue3 	 oversize :	 5 ->	 11 
    0	 1	 0	 queue3 	 oversize :	 5 ->	 9
    1	 2	 0	 queue3 	 oversize :	 9 ->	 10
    Iteration entered
    Iteration entered
    0	   	   	 in_counter = 3, 3, 6
    1	   	   	 in_counter = 4, 4, 8

and hang here. didn't try to add other flag to debug through. 

`master` branch works fine:

    [yuduo@mario]bc$ bin/test_bc_7.0_x86_64 market /data/gunrock_dataset/small/test_bc.mtx --src=-1
    Computing reference value ...
    CPU BC finished in 0.000000 msec.
    Validity BC Value: 
    CORRECT
    [0:1.000000,0.500000 1:1.000000,0.500000 2:3.000000,2.333333 3:1.000000,1.833333        4:1.000000,1.833333 5:1.000000,0.666667 6:1.000000,0.333333 ]
    GPU BC finished in 4.603424 msec.

**Comment by sgpyc** [comment]
mgpu dev/merge currently do not support running multiple times of the same algorithm

**Comment by ydwu** [comment]
got it. Developing in `mgpu-cq` branch.
