### ISSUE TITLE
Update doxygen markdown paths, submodule gunrock/docs in gunrock/gunrock repository

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#352]
The following markdown paths must be updated for doxygen to use slate (gunrock/docs) paths instead:
https://github.com/gunrock/gunrock/blob/0e707e8c97bd226d92460ddbd26a933b4faddbca/doc/gunrock.doxygen#L790-L801

Make `gunrock/docs` a submodule under `gunrock/` and remove `gunrock/doc` directory. Include all doxygen files inside `gunrock/docs`.

**Comment by neoblizz** [comment]
Link README.md -> index.html.md:
https://github.com/gunrock/docs/blob/master/deploy.sh#L24

**Comment by neoblizz** [comment]
Don't forget to update https://github.com/gunrock/gunrock/blob/dev/doc/releasedoc.sh!

**Comment by jowens** [comment]
@neoblizz was that last note a note to you?

**Comment by neoblizz** [comment]
@jowens yes, all of this is my todo.

**Comment by neoblizz** [comment]
Saving this here:
```
7 files changed, 967 insertions(+)
 create mode 100644 source/includes/gunrock_io_setup.md
 create mode 100644 source/includes/gunrock_to_json.md
 create mode 100644 source/includes/mini_gunrock.md
 create mode 100644 source/includes/vega/graphs/group_bar.json
 create mode 100644 source/includes/vega/graphs/vertical_bar.json
 create mode 100644 source/includes/vega/vegademo.md
 create mode 100644 source/pdfs/GTC 2016_Gunrock- a Fast and Programmable Multi-GPU Graph Processing Library.pdf
```

**Comment by neoblizz** [comment]
This is in the issues for documentation purposes, we need to test everything out for first release using `dev` and then finally `dev-refactor`. All these changes should work though.
