### ISSUE TITLE
.mtx to .gr file conversion

### ISSUE THREAD

**Issue by May989** [gunrock/gunrock#36]
Hi,
      The input to the Gunrock code is .mtx file . However we got boost Parallel Boost Graph Library which takes input in the form of .gr file. We wanted help from you in this regards.

   1. How can I convert file from .mtx format to .gr format ?

   2. How can I convert file from .gr format to .mtx format ?

   3. Can I get some performance numbers of performance of gunrock implementations on various GPU hardwares?

I would be grateful if you could help me in this,
Awaiting your reply,
Best regards,
-Mayank

**Comment by yzhwang** [comment]
Hi Mayank,

Thanks for the interest of trying out our tool. Please refer to the scripts located here:
https://github.com/gunrock/gunrock/tree/mgpu-merge/tools

**Comment by ydwu** [comment]
@May989 For 3, we are developing and testing mostly on K40c, you can find out some numbers in our arXiv papers.
