### ISSUE TITLE
Check whether the result of the wrapper function is indeed atomicExch, not atomicMin as claimed here 

### ISSUE THREAD

**Issue by sgpyc** [gunrock/gunrock#361]
https://github.com/gunrock/gunrock/blob/f57653327000bbebe157161045134be857f843a6/gunrock/util/device_intrinsics.cuh#L170

It seems to me the wrapper is doing atomicExch, not atomicMin

**Comment by neoblizz** [comment]
This should just be for older architectures, right? @sgpyc

**Comment by sgpyc** [comment]
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomic-functions
No, there is no atomicMin or atomicMax for float.
The wrapper seems not functionally correct to me.

**Comment by neoblizz** [comment]
That seems correct to me, I can write a small unit test for this. This is choosing the minimum and storing that into the address and returning the old value.

atomicExch would always store the new value back into the address and return the old value.

**Comment by sgpyc** [comment]
I see, fminf do the trick. Sorry, my bad.
