### ISSUE TITLE
[branch dev-refactor] Incorrect IO for COO format

### ISSUE THREAD

**Issue by bkj** [gunrock/gunrock#366]
`graphio::LoadGraph` appears to have a bug for COO format.

To reproduce -- compile `tests/pr` on `dev-refactor`: 
```
$ cd tests/pr
$ make
$ ./bin/test_pr_9.1_x86_64 --graph-type market --graph-file ../../dataset/small/chesapeake.mtx
```
you get the incorrect message that 20 duplicate edges have been removed:
```
Loading Matrix-market coordinate-formatted graph ...
Reading from ../../dataset/small/chesapeake.mtx:
  Parsing MARKET COO format
 (39 nodes, 340 directed edges)... 
Done parsing (0 s).
Removed 20 duplicate edges.
Computing reference value ...
```
If you run w/ `--remove-duplicate-edges=false`, you get the incorrect message that 20 self-loops have been removed:
```
$ ./bin/test_pr_9.1_x86_64 --graph-type market --graph-file ../../dataset/small/chesapeake.mtx --remove-duplicate-edges=false

Loading Matrix-market coordinate-formatted graph ...
Reading from ../../dataset/small/chesapeake.mtx:
  Parsing MARKET COO format
 (39 nodes, 340 directed edges)... 
Done parsing (0 s).
Removed 20 self circles.
Computing reference value ...
```

`chesapeake.mtx` doesn't have any self-loops or duplicate edges.

__EDIT:__
Bug appears to be here: 
  https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/graph/coo.cuh#L441

`thread_num == thread_num -1` should read `thread_num == num_threads - 1`

I'll open a PR

**Comment by neoblizz** [comment]
Good catch, thanks! 👍
