### ISSUE TITLE
Does gunrock's betweenness centrality results correct? 

### ISSUE THREAD

**Issue by WANG-lp** [gunrock/gunrock#373]
For the example graph in [shared_lib_bc.c](https://github.com/gunrock/gunrock/blob/b3416cbcd59c393e3bb9a7fccc81810acf5f04d5/shared_lib_tests/shared_lib_bc.c),

what does gunrock's betweenness centrality results mean?

here is the results of gunrock:
```
Node_ID [0] : Score [0.0000]
Node_ID [1] : Score [0.2500]
Node_ID [2] : Score [0.5000]
Node_ID [3] : Score [0.7500]
Node_ID [4] : Score [0.0000]
Node_ID [5] : Score [0.0000]
Node_ID [6] : Score [0.0000]
```

however, NetworkX gives this results:
```
{0: 0.5,
 1: 0.5,
 2: 2.333333333333333,
 3: 1.833333333333333,
 4: 1.833333333333333,
 5: 0.6666666666666666,
 6: 0.3333333333333333}
```

and here is the NetworkX scripts:
```python
import networkx as nx
g2 = nx.Graph()
g2.add_edges_from([(0,1),(0,2),(0,3),
                   (1,0),(1,2),(1,4),
                   (2,0),(2,1),(2,3),(2,4),(2,5),
                   (3,0),(3,2),(3,5),(3,6),
                   (4,1),(4,2),(4,5),(4,6),
                   (5,2),(5,3),(5,4),(5,6),
                   (6,3),(6,4),(6,5)])
nx.betweenness_centrality(g2, normalized=False)
```

Does gunrock's results correct?

**Comment by neoblizz** [comment]
Hi @WANG-lp, this question was discussed/addressed in issue: https://github.com/gunrock/gunrock/issues/251 in the new branch/api, we plan to make this more intuitive. Hope this answers your question.
