### ISSUE TITLE
CUDA error running PageRank 

### ISSUE THREAD

**Issue by zronaghi** [gunrock/gunrock#376]
BFS and SSSP are working but fails with PageRank: Driver Version: 396.44, Cuda 9.1.85 on V100 

./pr market  ../../../twitter/twitter.mtx:
Loading Matrix-market coordinate-formatted graph ...
Reading from ../../../twitter/twitter.mtx:
  Parsing MARKET COO format (41652230 nodes, 2936730364 directed edges)... Error parsing MARKET graph:coo allocation failed, sizeof(EdgeTupleType) = 12, edges = -1358236932, allo_size = -16298843184
Using 1 GPU: [ 0 ].
[/home/zronaghi/gunrock/gunrock/util/array_utils.cuh, 532 @ gpu 0] row_offsets cudaMemcpy H2D failed (CUDA error 11: invalid argument)
[/home/zronaghi/gunrock/tests/pr/test_pr.cu, 641 @ gpu 0] PR Problem Init failed (CUDA error 11: invalid argument)

 [PageRank] finished.
 avg. elapsed: 0.0000 ms
 iterations: 0
 load time: 891.9270 ms
 preprocess time: 0.0000 ms
 postprocess time: 0.0000 ms
 total time: 892.9489 ms

**Comment by jowens** [comment]
Are you running from the master branch? We can try to reproduce this.

@sgpyc a negative value for edges and allo_size seems ... concerning.

**Comment by zronaghi** [comment]
Yes I'm running from master and it's a fairly large graph

**Comment by neoblizz** [comment]
@zronaghi which twitter dataset are you using for this run? It is possible that PR is using more memory than SSSP or BFS (which work in this case) and therefore you see this error.

But to add to this, the issue #358 also discusses the same problem and I have also seen this during my runs. @sgpyc definitely worth inspecting and addressing soon.

**Comment by zronaghi** [comment]
@neoblizz we're using a 23GB local dataset on V100 32GB. That's my guess too that PR is using more memory

**Comment by jowens** [comment]
yeah, hard to have a lot of scratch space when more than half of the memory is taken up by the dataset. for many apps (e.g., BFS, SSSP), the size of the frontier is relatively small, so it might fit, but for PR, usually at the beginning, the whole graph is in the frontier. so i could imagine that PR would have more challenges.

@sgpyc I think if the graph is too big for us to handle, we should explicitly say that in the error message.

**Comment by zronaghi** [comment]
@jowens makes sense, thanks! Is there a multi-gpu version? (running on a DGX-1)

**Comment by jowens** [comment]
Yes, though @sgpyc and @neoblizz will be better able to comment on what the right configuration of Gunrock would be (e.g., "use this branch")

**Comment by neoblizz** [comment]
@zronaghi you should be able to run the multi-gpu version with `--devices=0,1,2,3` parameter in the command line. I also recommend looking at the run scripts we have for pagerank for right configuration: https://github.com/gunrock/gunrock/tree/master/tests/pr there are some examples of social network datasets in there ( for twitter: https://github.com/gunrock/gunrock/blob/master/tests/pr/run.sh#L73 ).

@sgpyc will be able to comment on post-processing times.

**Comment by sgpyc** [comment]
The issue is 2.9 billion is larger than 2^31-1, and needs to be represent by 64bit number. So `--64bit-SizeT` is needed in the command line. PR on the twitter_rv.net dataset can run using 12GB memory, but we removed some self circles and duplicated edges. 32GB should be pretty sufficient.

```
./bin/test_pr_9.2_x86_64 market /data/gunrock_dataset/huge/twitter_rv.net/twitter_rv.net.mtx --64bit-SizeT --quick
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays from /data/gunrock_dataset/huge/twitter_rv.net/.twitter_rv.net.mtx.ud.0.64bSi.bin ...
Done reading (9s).

Degree Histogram (41652230 vertices, 2405026092 edges):
    Degree   0: 0 (0.00%)
    Degree 2^0: 1901556 (4.57%)
    Degree 2^1: 4821551 (11.58%)
    Degree 2^2: 9157794 (21.99%)
    Degree 2^3: 7648224 (18.36%)
    Degree 2^4: 7794711 (18.71%)
    Degree 2^5: 6060403 (14.55%)
    Degree 2^6: 1957542 (4.70%)
    Degree 2^7: 1055131 (2.53%)
    Degree 2^8: 633251 (1.52%)
    Degree 2^9: 329753 (0.79%)
    Degree 2^10: 183840 (0.44%)
    Degree 2^11: 81279 (0.20%)
    Degree 2^12: 17126 (0.04%)
    Degree 2^13: 6192 (0.01%)
    Degree 2^14: 2434 (0.01%)
    Degree 2^15: 795 (0.00%)
    Degree 2^16: 285 (0.00%)
    Degree 2^17: 82 (0.00%)
    Degree 2^18: 68 (0.00%)
    Degree 2^19: 153 (0.00%)
    Degree 2^20: 56 (0.00%)
    Degree 2^21: 4 (0.00%)

Using 1 GPU: [ 0 ].
Using traversal mode LB
-1       -1      -1      scanned_edges   oversize :      2 ->    41652232
__________________________
--------------------------
iteration 0 elapsed: 21319.458008 ms
Total rank : 40958212.8222686648

Top 10 Ranked Vertices and PageRanks:
Vertex ID: 1037947, PageRank: 5.38583477e+04
Vertex ID: 5925042, PageRank: 5.01825547e+04
Vertex ID: 1803884, PageRank: 4.78978984e+04
Vertex ID: 5874843, PageRank: 4.42874336e+04
Vertex ID: 1436, PageRank: 3.64480391e+04
Vertex ID: 1829998, PageRank: 3.49290977e+04
Vertex ID: 1652, PageRank: 3.26326484e+04
Vertex ID: 1025810, PageRank: 3.11354023e+04
Vertex ID: 22635042, PageRank: 2.97064473e+04
Vertex ID: 1811268, PageRank: 2.96980859e+04

        Memory Usage(B)  #keys0,0        #keys0,1
GPU_0    11469324288     2       2
         queue_sizing =  0.000000        0.000000

 [PageRank] finished.
 avg. elapsed: 21319.4580 ms
 iterations: 24
 min. elapsed: 21319.4580 ms
 max. elapsed: 21319.4580 ms
 rate: 112.8090 MiEdges/s
 src: 0
 nodes_visited: 41652230
 edges_visited: -1889941204
 nodes queued: 958001290
 edges queued: 1886051360
 nodes redundance: 2200.00%
 edges redundance: 2300.00%
 load time: 5602.5181 ms
 preprocess time: 4099.1931 ms
 postprocess time: 276.6631 ms
 total time: 31305.8221 ms
```

**Comment by sgpyc** [comment]
@zronaghi If you want the more standard normalized PR, add `--normalized --compensated` to the command line, that will almost guarantee the sum of rankings to be 1.

**Comment by jowens** [comment]
@sgpyc can we do a quick check for `(edge_size_too_big && 32_bit_edge_indexes)` and error out with a helpful message?

**Comment by neoblizz** [comment]
If we can detect this, why don't we automatically switch to 64bit SizeT?

**Comment by jowens** [comment]
I don't think that is the right behavior for our graph library. If the default is 32b, we shouldn't automatically switch to something else. We should error and make sure the caller knows why. I would philosophically be opposed to automatically switching away from a default in favor of an error. Explicitness is more important to me here than smoothness.

**Comment by sgpyc** [comment]
It's not easy (~impossible) to switch `64bit-SizeT` based on num edges: the switch is set at the very beginning of the program, before calling `LoadGraph`, where `graph.edges` got its value.
