### ISSUE TITLE
Style guide/code linter

### ISSUE THREAD

**Issue by bkj** [gunrock/gunrock#377]
I notice there is a lot of use of whitespace to align operations across lines -- Is there a style guide or code linter for contributions to Gunrock code?

~ Ben

**Comment by jowens** [comment]
We haven't used lint before (not sure how it works with CUDA). I would personally be happy to see a consistent style (I think clang-format was suggested before, and with gnu indent we can obviously set up anything we want), but I'm not the one writing code so I don't want to impose this on the folks who do. @sgpyc, thoughts?

**Comment by bkj** [comment]
I don't have much preference on the specifics, but haveing _somethingit might make code review a little easier by reducing the number of diffs.

**Comment by sgpyc** [comment]
I don't have preference on specific styles. We did try some formatting tools long time ago, but there were a few issues, the main one I remembered is when function parameters are too long, the standard format indentation on following lines are way too much. For example:
`someVeryLongLongLongLongLongLongLongLongFunction(
                                                                                                                       parameter1, parameter2, parameter3,
                                                                                                                       parameter4, parameter5...)`
Long function names happen more often in cuda, so the following looks better:
`someVeryLongLongLongLongLongLongLongLongFunction(
              parameter1, parameter2, parameter3,
              parameter4, parameter5...)`
Maybe it's just we didn't get the formatting configuration correct.

For the white spaces, most of them are used for alignment: common parts of continuous lines  can align, so it's more easy to read and check the code. This is mostly for memory allocation and alias setup.

**Comment by jowens** [comment]
@bkj if you have specific suggestions, we're all ears. I'd prefer something that could be enforced on the command line (I automatically do this to any python code I write, for instance, for pep8 compliance). gnu indent? clang-format?

**Comment by bkj** [comment]
I don't have specific suggestions -- I haven't used C++ linters before, just the standard python ones.  I can poke around a bit, but open to suggestions from anyone who has an opinion.   I agree that something w/ a command line autoformatter would be ideal.

**Comment by neoblizz** [comment]
Was discussing this with @sgpyc today, I will ask around at NVIDIA as well because their code formatting stuff is very neat and printable.

**Comment by neoblizz** [comment]
I think this is something we can get help from professionals -- I just thought @yzhwang had something in place, but I think it was just something we tried a while back that didn't work as nicely. Will report my findings soon.

**Comment by ctcyang** [comment]
At Amazon, we use pylint and cpplint for MXNet. I love how neat it makes the code and how it pinpoints the formatting problems for you--all you need to do is type `make lint`. The way the automation works is the CI system performs a `make lint` check each time you submit a PR, and it will fail if your code does not follow the Lint guideline.

However for Gunrock, there will need to be a one-time massive formatting to make it adhere to the formatting requirements.

**Comment by bkj** [comment]
Yeah I was going to say -- it's worth thinking about how/whether we'd apply
this retrospectively. It may be the most reasonable thing is just to use
the linter on new apps as they're written, rather than applying it to the
entire codebase.

**Comment by jowens** [comment]
I'd probably be inclined to just apply it to the whole codebase, or at least do so gradually. For the tiny number of files I touch, I'd probably have my editor do it automatically. Also this is the kind of project we could assign to an undergrad wandering through who wants a little experience.

**Comment by bkj** [comment]
Re @sgpyc 's comments above -- most linters should let you enable/disable rules as you like, to fix the kinds of problems you're talking about.  

While we're on the subject of aesthetics, I'll note I _really_ don't like the 80 character line limits. :)

**Comment by jowens** [comment]
@bkj you're on thin ice there, don't get fired

**Comment by neoblizz** [comment]
Talked to John Hubbard at Nvidia, he recommended us to look at [indent](https://www.gnu.org/software/indent/manual/indent.html) and clang-format for cpp. He suggested similar things to what @ctcyang pointed out they do for amazon. We can leverage Jenkins to suggest if the pull request followed our styling guidelines.

Also, these programs provide very fine control of how you want the code to look like, and also solves @sgpyc's concern. We can make it look like how he wants it to be (something that also looks good printed).

**Comment by neoblizz** [comment]
Yes, I agree, and we can make minor changes to suit what looks good for gunrock as well. After my internship I will try to get the auto fix thing working with clang and see how it goes.

**Comment by neoblizz** [comment]
In issue 00d425925c005c5a5548141ab297eb811665ab75, I have added a basic clang format using Google's formatting scheme: https://github.com/gunrock/gunrock/blob/dev-refactor/.clang-format This can be further improved, the results it produces are shown in geolocation's committed files:

https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/geo/geo_enactor.cuh

It is as simple as `clang-format -i path/to/file.cc`, currently I didn't deploy this to the whole repository, because the diff will screw everyone who is working on HIVE or are still making progress on that stuff in `dev-refactor`.

**Comment by neoblizz** [comment]
All branches now have support for this, command: `clang-format --style=file -i path/to/file.cc`. I think its best if this command is run from the root directory where the clang-format file exits ([.clang-format](https://github.com/gunrock/gunrock/blob/master/.clang-format)).
