### ISSUE TITLE
[dev-refactor] Speeding up app compilation

### ISSUE THREAD

**Issue by bkj** [gunrock/gunrock#379]
Compiling eg. `tests/bc` takes >30 seconds, even when you're only making changes to `tests/bc/test_bc.cu`.  It seems like there may be an opportunity to precompile some of the dependencies.  

I tried briefly to precompile the headers using a `stdafx.h`file, but learned that this doesn't place nice with `nvcc`.

I spoke with @neoblizz and he thinks it should be possible (potentially using `ninja`) but will take a bit of work.  Opening this issue as a record of the conversation.

**Comment by neoblizz** [comment]
See issue #473
