### ISSUE TITLE
[dev-refactor] Random edge weights?

### ISSUE THREAD

**Issue by bkj** [gunrock/gunrock#382]
https://github.com/gunrock/gunrock/blob/a8307014372a0cfb5411e4e2103c7c091e069c71/gunrock/graphio/market.cuh#L238

Is this block randomly generating edge weights when no edge weights are present in the input file?

If so, I'd strongly recommend that the default behavior be changed so that edge weights are set to 1 when missing.

**Comment by sgpyc** [comment]
Yes, when the program asks for edge weights, but the weights are not present in the mtx file, they will be randomly generated. `edge-value-min` and `edge-value-range` controls how the edge values are generated; if weights should have 1 as default, I can set the `edge-value-min=1` and `edge-value-range=0` as defaults.

**Comment by bkj** [comment]
That's super unexpected behavior -- every other graph library I've ever seen sets edge weights to 1 unless otherwise defined.

I can do a PR that exposes the random edge weight behavior via an explicit `--random-weights` flag, and sets edge weights to 1 otherwise.  Does that sound reasonable to you?

**Comment by sgpyc** [comment]
I guess change the edge-value-min and edge-value-range defaults may be better? That has the same effect of assigning 1 as default weights.

If not remembered wrongly, the pervious default [0, 64] was for SSSP. That maybe the only time we have edge weights

**Comment by neoblizz** [comment]
Solved in PR #383
