### ISSUE TITLE
gitsha1.c: should not be in repo

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#40]
I'm not 100% sure I did this right, but I think I did: gitsha1.c is generated by CMake and should not be in the repo. However, in the merge, it *is* in the repo and I believe it should not be. (The header and .in files SHOULD be in the repo, and are.) Whoever added it to the repo, please check that you did the right thing, and remove it if it shouldn't be there.

http://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake

**Comment by ydwu** [comment]
deleted in 577d05ef287de0a39f7950f40f2a0cb4a7e77831.
