### ISSUE TITLE
How can I help to improve this project?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#402]
It seems not easy to understand the structure of this project. Can you provide more detailed documents? How can I develop new graph algorithms based on the operators provided by Gunrock?

**Comment by neoblizz** [comment]
I will highly recommend working on our `dev-refactor` branch, we have slides and a video of "How to write a primitive in gunrock?", the talk goes through SSSP as an example, and there are several active pull requests and new applications added to `dev-refactor` that you could also use as reference.

http://on-demand.gputechconf.com/gtc/2018/video/S8586/

https://github.com/gunrock/gunrock/blob/master/doc/Writing-Gunrock-Primitives.pdf

I hope this helps!

**Comment by bookug** [comment]
Thank you very much! 
How can I implement the subgraph matching algorithm in the paper below:
http://www.hpdc.org/2016/posters/poster/O13-HPDC16_Posters_paper_17.pdf

**Comment by neoblizz** [comment]
@bookug maybe @Laurawly can comment on that, but a good place to start will be to look at `dev` implementation of subgraph matching and help us port to `dev-refactor`, the new API.

You'll find it way easier to represent that algorithm in refactored branch.

Link to current implementation:
`app` : https://github.com/gunrock/gunrock/tree/dev/gunrock/app/sm
`tests/examples` : https://github.com/gunrock/gunrock/tree/dev/examples/sm

Link to `dev-refactor` template:
https://github.com/gunrock/gunrock/tree/dev-refactor/gunrock/app/hello
https://github.com/gunrock/gunrock/tree/dev-refactor/tests/hello

I will start by addressing the `<TODO>` tags in the template, and slowly filling everything in. The main implementation is the `enactor/functor` files, and the data structure initialization and declaration is in `problem`.
