### ISSUE TITLE
[HIVE] random_walks OOM error?

### ISSUE THREAD

**Issue by bkj** [gunrock/gunrock#406]
When I run
```
cd tests/rw
LARGE_DATASET="../../dataset/large/hollywood-2009/hollywood-2009.mtx"
./bin/test_rw_9.1_x86_64 --graph-type market \
    --graph-file $LARGE_DATASET \
    --walk-mode 0 \ 
    --walk-length 10 \
    --walks-per-node 2 \
    --quick --quiet
```
I get the following output:
```
num_nodes=1139905
0	 0	 0	 queue3 	 oversize :	 6839430 ->	 225502846
0	 0	 0	 queue3 	 oversize :	 6839430 ->	 225502846
0	 1	 0	 queue3 	 oversize :	 225502846 ->	 922038469
0	 1	 0	 queue3 	 oversize :	 225502846 ->	 922038469
0	 2	 0	 queue3 	 oversize :	 922038469 ->	 1050089409
0	 2	 0	 queue3 	 oversize :	 922038469 ->	 1050089409
0	 3	 0	 queue3 	 oversize :	 1050089409 ->	 1160703413
0	 3	 0	 queue3 	 oversize :	 1050089409 ->	 1160703413
0	 4	 0	 queue3 	 oversize :	 1160703413 ->	 1238629737
0	 4	 0	 queue3 	 oversize :	 1160703413 ->	 1238629737
0	 5	 0	 queue3 	 oversize :	 1238629737 ->	 1302136305
0	 5	 0	 queue3 	 oversize :	 1238629737 ->	 1302136305
0	 6	 0	 queue3 	 oversize :	 1302136305 ->	 1351281930
0	 6	 0	 queue3 	 oversize :	 1302136305 ->	 1351281930
0	 7	 0	 queue3 	 oversize :	 1351281930 ->	 1395555590
0	 7	 0	 queue3 	 oversize :	 1351281930 ->	 1395555590
[../../gunrock/util/array_utils.cuh, 474 @ gpu 0] t_array cudaMalloc failed (CUDA error 2: out of memory)
```
However, when I run 
```
./bin/test_rw_9.1_x86_64 --graph-type market \
    --graph-file $LARGE_DATASET \
    --walk-mode 0 \ 
    --walk-length 20 \
    --walks-per-node 1 \
    --quick --quiet
```
the app completes as expected.

The outputs of these two parameter settings have the same memory usage, so presumably the error is getting thrown because of some intermediate data structure.  Any thoughts on how best to hunt this down?

**Comment by jowens** [comment]
@bkj would like your thoughts here ... I rather prioritize at this point "let the user know what has happened, clearly" over "try to fix it". Might not be fixable. But we can do a much better job with notifications. The `queue3 oversize` notes may be useful for @sgpyc but not sure anyone else knows what they mean.

**Comment by bkj** [comment]
@jowens Definitely agree -- given certain inputs graphs / parameter settings, this app will definitely run out of memory, so better logging is always going to be useful.

It'd be good to know if I've done something particularly stupid memory-management wise here as well, since I don't see anything obviously wrong.  Could help us see if there's somewhere we should put guard rails in place for people like me.

**Comment by jowens** [comment]
The magic feature I'd like to have is a memory allocator that recorded call info for every, say, allocation over 100 MB and could dump that list.

@bkj it seems exceedingly likely to me that you're not doing anything dumb, that it's either just that the data set is too big or that our intermediate data structures are too big and not under your control. I will say that both @sgpyc and @yzhwang went to a lot of effort to minimize our data footprint—we can often run datasets that don't fit when run in a different framework.

**Comment by neoblizz** [comment]
@bkj can you run the 2nd command multiple times to check with the "randomness" factor and see if that actually finishes every time?

Yes, you are right that at some point we won't have enough memory for some dataset. Here's why the first one passes and second doesn't:

```
            GUARD_CU(walks.Allocate(sub_graph.nodes * walk_length * walks_per_node, target));
            GUARD_CU(rand.Allocate(sub_graph.nodes * walks_per_node, target));
```
Your `rand` is:
- 1st one: `2 x nodes`
- 2nd one: `1 x nodes`

Where as your `walks` is the same for both:
- 1st: `nodes* 10 * 2`
- 2nd: `nodes * 20 * 1`


One note here, do we need the `rand` to be a `Array1D` of `floats`? Is it possible to get by using `int`?

**Comment by bkj** [comment]
This is fixed by https://github.com/gunrock/gunrock/pull/413
