### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by May989** [gunrock/gunrock#41]
I am working on cuda implementation of breadth first search using gunrock.
Can you explain how the cuda threads are distributing their work among each other and the algorithmic details. 
Also which are the relevant files to explore for getting to understand the 'gunrock bfs' implementation.

**Comment by jowens** [comment]
First, we are preparing for a 0.3 release of Gunrock, which might actually happen today but certainly within the next week. You should use the "dev" branch for a preview of that release, and you should start with tests/bfs/test_bfs.cu and the files in gunrock/app/bfs.
