### ISSUE TITLE
BFS Algorithm Detail

### ISSUE THREAD

**Issue by May989** [gunrock/gunrock#42]
Hi,
I am exploring the BFS algorithm implementation in cuda gunrock, in this regards I read the paper "High Performance and Scalable GPU Graph Traversal". However the paper lists a number of algorithms. Could you please let me know the exact algorithm that is used in gunrock. Where can I get more details about this algorithm?

Thanks

**Comment by jowens** [comment]
In terms of work distribution, we use two strategies. One is (broadly) Merrill's; the one he calls "scan+warp+cta"; you read his paper. The other is Davidson's; http://escholarship.org/uc/item/8qr166v2; he calls it "load-balanced partitioning".
