### ISSUE TITLE
Can gunrock support subgraph isomorphism now?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#424]
If not, when can it support graph-subgraph isomorphism?

**Comment by jowens** [comment]
We're actively working on this. Stay tuned.

**Comment by bookug** [comment]
is the subgraph isomorphism done now? I see the `sm` command after I compile the Gunrock project...

**Comment by jowens** [comment]
We continue to be actively working on this. But no.

**Comment by neoblizz** [comment]
Talked to @Laurawly, possible release planned with `dev-refactor` branch. Closing this right now, will create a new issue for SM.
