### ISSUE TITLE
Warnings with Boost 1.67.0

### ISSUE THREAD

**Issue by archenroot** [gunrock/gunrock#425]
There are some warnings when building with latest boost, could be useful for developers:
`zangetsu@venus ~/proj/private/gpu/gunrock/build $ cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "9.2", minimum required is "7.5") 
-- Boost version: 1.67.0
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  cmake/FindBoost.cmake:6 (FIND_PACKAGE)
  CMakeLists.txt:43 (include)

CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  cmake/FindBoost.cmake:6 (FIND_PACKAGE)
  CMakeLists.txt:43 (include)

CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  cmake/FindBoost.cmake:6 (FIND_PACKAGE)
  CMakeLists.txt:43 (include)

CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  cmake/FindBoost.cmake:6 (FIND_PACKAGE)
  CMakeLists.txt:43 (include)

-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenMP.cmake:200 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "c" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  cmake/FindOpenMP.cmake:70 (FIND_PACKAGE)
  CMakeLists.txt:49 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP
-- Found Metis
-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Project Added: grmat
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zangetsu/proj/private/gpu/gunrock/build
`

**Comment by neoblizz** [comment]
We recommend using Boost version 1.58.0, this is being addressed in later release where Boost will be optional. For master branch, please install 1.58 instead.
