### ISSUE TITLE
Run command

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#427]
Although I searched the manuals, I still haven't find out the correct run command for the binaries. For example, `bfs market /data/Compare/topc-datasets/hollywood-2009.mtx --src=0 --undirected` works while `bfs market /data/Compare/topc-datasets/hollywood-2009.mtx --src=0 --undirected` doesn't work.

Is there any document which explains what options should be used for dataset inputs?

**Comment by neoblizz** [comment]
@mahmoodn aren't those two the same command lines? And it works for me:

```
mosama@mario:~/gunrock/build$ ./bin/bfs market /data/gunrock_dataset/large/hollywood-2009/hollywood-2009.mtx --src=0 --undirected
Loading Matrix-market coordinate-formatted graph ...
Reading from /data/gunrock_dataset/large/hollywood-2009/hollywood-2009.mtx:
  Parsing MARKET COO format (1139905 nodes, 115031232 directed edges)... Done parsing (19s).
  Converting 1139905 vertices, 115031232 directed edges (unordered tuples) to CSR format...
Done converting (8s).

Degree Histogram (1139905 vertices, 112751422 edges):
    Degree   0: 32662 (2.87%)
    Degree 2^0: 24445 (2.14%)
    Degree 2^1: 50032 (4.39%)
    Degree 2^2: 99398 (8.72%)
    Degree 2^3: 174673 (15.32%)
    Degree 2^4: 231414 (20.30%)
    Degree 2^5: 219393 (19.25%)
    Degree 2^6: 139586 (12.25%)
    Degree 2^7: 78822 (6.91%)
    Degree 2^8: 44379 (3.89%)
    Degree 2^9: 25905 (2.27%)
    Degree 2^10: 13729 (1.20%)
    Degree 2^11: 5233 (0.46%)
    Degree 2^12: 230 (0.02%)
    Degree 2^13: 4 (0.00%)

Source vertex: 0
Using 1 GPU: [ 0 ].
Using traversal-mode LB
__________________________
0        4       0       queue3          oversize :      7409384 ->      52557065
0        5       0       queue3          oversize :      52557065 ->     56516755
--------------------------
iteration 0 elapsed: 17.761946 ms, src = 0, #iteration = 11
Computing reference value ...
CPU BFS finished in 569.851135 msec. cpu_search_depth: 11

Label Validity:
CORRECT

First 40 labels of the GPU result:
[0:0 1:1 2:1 3:1 4:5 5:5 6:5 7:5 8:6 9:6 10:6 11:6 12:6 13:6 14:6 15:6 16:6 17:6 18:6 19:6 20:6 21:6 22:6 23:6 24:6 25:6 26:5 27:6 28:6 29:6 30:6 31:6 32:6 33:6 34:6 35:6 36:6 37:6 38:6 39:6 ]

        Memory Usage(B)  #keys0,0        #keys0,1
GPU_0    1245708288      7409384         56516755
         queue_sizing =  6.500001        49.580233

 [BFS] finished.
 avg. elapsed: 17.7619 ms
 iterations: 11
 min. elapsed: 17.7619 ms
 max. elapsed: 17.7619 ms
 rate: 6340.1445 MiEdges/s
 src: 0
 nodes_visited: 1069126
 edges_visited: 112613306
 nodes queued: 1069126
 edges queued: 112613306
 load time: 53129.6861 ms
 preprocess time: 866.2610 ms
 postprocess time: 19.4170 ms
 total time: 54612.5391 ms
```

**Comment by jowens** [comment]
https://gunrock.github.io/docs/engines_topc.html has linked https://gunrock.github.io/docs/tables/engines_topc_table.html with a JSON output for every data point, where the JSON outputs include the command-line used to generate each of them.

**Comment by mahmoodn** [comment]
Excuse me, there was a problem with with the pasted data. Please see the output below
```
mahmood@orca:ak2010$ bfs market ak2010.mtx --src=0 --undirected
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (45292 vertices, 217098 edges):
    Degree   0: 16 (0.04%)
    Degree 2^0: 1809 (3.99%)
    Degree 2^1: 17300 (38.20%)
    Degree 2^2: 21069 (46.52%)
    Degree 2^3: 4037 (8.91%)
    Degree 2^4: 875 (1.93%)
    Degree 2^5: 136 (0.30%)
    Degree 2^6: 38 (0.08%)
    Degree 2^7: 10 (0.02%)
    Degree 2^8: 2 (0.00%)

Source vertex: 0
Using 1 GPU: [ 0 ].
Using traversal-mode TWC
__________________________
--------------------------
iteration 0 elapsed: 8.358002 ms, src = 0, #iteration = 54
Computing reference value ...
CPU BFS finished in 5.786896 msec. cpu_search_depth: 54

Label Validity: 
CORRECT

First 40 labels of the GPU result:
[0:0 1:6 2:7 3:4 4:9 5:5 6:4 7:4 8:4 9:5 10:4 11:5 12:4 13:6 14:9 15:6 16:5 17:5 18:4 19:4 20:5 21:2147483647 22:2147483647 23:2147483647 24:6 25:7 26:8 27:9 28:9 29:10 30:10 31:10 32:11 33:10 34:8 35:5 36:5 37:4 38:5 39:8 ]

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 10878976	 294400	 294400
	 queue_sizing =	 6.500044 	 6.500044

 [BFS] finished.
 avg. elapsed: 8.3580 ms
 iterations: 54
 min. elapsed: 8.3580 ms
 max. elapsed: 8.3580 ms
 rate: 24.4295 MiEdges/s
 src: 0
 nodes_visited: 42381
 edges_visited: 204182
 nodes queued: 42381
 edges queued: 204182
 load time: 152.8580 ms
 preprocess time: 4.8649 ms
 postprocess time: 3.5419 ms
 total time: 176.5959 ms
mahmood@orca:ak2010$ cd ../arabic-2005/
mahmood@orca:arabic-2005$ bfs market arabic-2005.mtx --src=0 --undirected
Loading Matrix-market coordinate-formatted graph ...
Reading from arabic-2005.mtx:
  Parsing MARKET COO format (22744080 nodes, 1279998916 directed edges)... Error parsing MARKET graph:coo allocation failed, sizeof(EdgeTupleType) = 12, edges = 1279998916, allo_size = 15359986992
Source vertex: 0
Using 1 GPU: [ 0 ].
[/home/mahmood/gunrock/gunrock/util/array_utils.cuh, 532 @ gpu 0] row_offsets cudaMemcpy H2D failed (CUDA error 11: invalid argument)
[/home/mahmood/gunrock/tests/bfs/test_bfs.cu, 382 @ gpu 0] BFS Problem Init failed (CUDA error 11: invalid argument)

 [BFS] finished.
 avg. elapsed: 0.0000 ms
 iterations: 0
 load time: 146.6980 ms
 preprocess time: 0.0000 ms
 postprocess time: 0.0000 ms
 total time: 147.2149 ms
```
I think there is an out-of-memory problem as noted. But I also see an invalid argument error. So, I wonder what is the problem?

**Comment by mahmoodn** [comment]
@jowens:
IN the json files you mentioned, some of the contain the command line [1] and some of them don't have that [2].

[1] https://github.com/gunrock/io/blob/master/gunrock-output/topc/SSSP_road_usa_Fri%20Nov%2018%20004204%202016.json
[2] https://github.com/gunrock/io/blob/master/Ligra-output/topc/BC-indochina-2004.json

**Comment by jowens** [comment]
The Gunrock ones contain the Gunrock command lines. If you see any Gunrock ones that don't, please let us know.

**Comment by mahmoodn** [comment]
You are right. They have the command line.
Still the reason for the error is unclear for me.

I also have another question. I see that all large datasets that are finished without memory error, have small runtime. For example,  indochina-2004  with 2.3GB memory usage has about 0.6ms! All runtimes are in the range of ten and hundreds of miliseconds except the asia_osm which is about 4 seconds. Other that I am not able to run are out-of-memory as far as I see.

The GPU is M2000 which is not a high end device. Is there any input with longer runtime on gpu?

**Comment by jowens** [comment]
The largest dataset sizes we can handle are ones that fit on the GPU, and so we're then limited in terms of the length of runtime we can support. And the primitives that are currently in the repos are relatively simple in terms of computation. If you wanted a real long one, then doing a full BC run (from all vertices, not just the default of from-one-vertex) on a large dataset would tend to take a very long time ... @sgpyc maybe you can suggest a command-line there?

**Comment by neoblizz** [comment]
@mahmoodn I think M2000 has 4GB global memory, and in the command-line above you are trying to run a graph with the allocation size of: `15359986992 B`. You'll either need a V100 with 32GB or run in a multi-GPU environment with the flag `--device=0,1,2,3`.

**Comment by mahmoodn** [comment]
@jowens 
Do you mean that for my purpose, I have to run bc command and not bfs or other commands? Also, can you point the right direction on how to define such an option (bc on all nodes).
I need that for some tests. Thank you.

**Comment by jowens** [comment]
You can run bfs, of course, but on any graph that fits in GPU memory, bfs finishes very quickly and may not be long enough for whatever your reasons are for needing a longer run. As you note, road network graphs will be the slowest (because of their high diameters).

For how to do a "full" BC run, check out this issue:

https://github.com/gunrock/gunrock/issues/251

**Comment by neoblizz** [comment]
Closing this for now, let us know if you encounter any other issues regarding the command line.

**Comment by mahmoodn** [comment]
@neoblizz:
I read your post at [1] however, I am not sure if I understand that correctly. It seems that I have to modify one of the source files to perform a full BC test. I expected to see an option in bc command for that. Can you explain more what should I do to run full BC?


[1] https://github.com/gunrock/gunrock/issues/251#issuecomment-311839910

**Comment by mahmoodn** [comment]
Hi again
I saw that shared_lib_* binaries are there in the bin/
This is the output I get 
```

mahmood@orca:bin$ ./shared_lib_bc 
0	 1	 0	 queue3 	 oversize :	 9 ->	 14
0	 1	 0	 queue3 	 oversize :	 9 ->	 14
Node_ID [0] : Score [0.0000]
Node_ID [1] : Score [0.2500]
Node_ID [2] : Score [0.5000]
Node_ID [3] : Score [0.7500]
Node_ID [4] : Score [0.0000]
Node_ID [5] : Score [0.0000]
Node_ID [6] : Score [0.0000]

```
And the execution is very very quick. Sounds like an error.
