### ISSUE TITLE
PageRank incorrect output on soc-Livejournal1

### ISSUE THREAD

**Issue by AjayBrahmakshatriya** [gunrock/gunrock#430]
Running 

    /pr market ~/scratch/gunrock/dataset/large/soc-LiveJournal1/soc-LiveJournal1.mtx --quick --device=3

produces the output - 

    Run 0 elapsed: 1756.908894 ms, src = 4294967295, #iterations = 34
    Total_rank = 0.999995
    Top 10 Ranked vertices and PageRanks:
    Vertex ID: 10009, PageRank: 0.000162
    Vertex ID: 8737, PageRank: 0.000144
    Vertex ID: 2914, PageRank: 0.000142
    Vertex ID: 18964, PageRank: 0.000113
    Vertex ID: 87, PageRank: 0.000095
    Vertex ID: 37356, PageRank: 0.000077
    Vertex ID: 10029, PageRank: 0.000076
    Vertex ID: 39295, PageRank: 0.000072
    Vertex ID: 1220, PageRank: 0.000070
    Vertex ID: 2409, PageRank: 0.000067

The top ranked node doesn't seem to match the top node when run with other tools. Same output on both master and dev-refactor branch.  Not sure if this is a misconfiguration or bug with the application. The highest rank node we get in Graphit is 8737 which is the second in the above result. There are other mismatches in the rank too.

**Comment by jowens** [comment]
I don't exactly know what's going on here, but in a previous issue (https://github.com/gunrock/gunrock/issues/376) @sgpyc suggested `--normalized --compensated` as command-line flags ...

**Comment by AjayBrahmakshatriya** [comment]
Doesn't seem like an issue with `--normalize` because the Total_rank does sum up to ~1. 
I tried all combinations with and without normalization and compensate, but still the results remain the same.

**Comment by sgpyc** [comment]
@AjayBrahmakshatriya can you check whether the graph used by GraphIT is directed or undirected?
When taken as it is, `soc-LiveJournal1` is a directed graph, and the top ranking vertices are:
```
Vertex ID: 4847571, PageRank: 0.035685
Vertex ID: 8737, PageRank: 0.000167
Vertex ID: 2914, PageRank: 0.000147
Vertex ID: 18964, PageRank: 0.000103
Vertex ID: 1220, PageRank: 0.000089
Vertex ID: 2409, PageRank: 0.000084
Vertex ID: 10029, PageRank: 0.000081
Vertex ID: 214538, PageRank: 0.000076
Vertex ID: 7343, PageRank: 0.000072
Vertex ID: 38283, PageRank: 0.000068
```
Vertex 4847571 is the one added to compensate the zero-degree vertices.

When the graph is treated as undirected via edge doubling, the top ranking vertices are:
```
Vertex ID: 10009, PageRank: 0.000162
Vertex ID: 8737, PageRank: 0.000144
Vertex ID: 2914, PageRank: 0.000142
Vertex ID: 18964, PageRank: 0.000113
Vertex ID: 87, PageRank: 0.000095
Vertex ID: 37356, PageRank: 0.000077
Vertex ID: 10029, PageRank: 0.000076
Vertex ID: 39295, PageRank: 0.000072
Vertex ID: 1220, PageRank: 0.000070
Vertex ID: 2409, PageRank: 0.000067
```
These are the same from the results you reported. I think somehow the `undirected` flag is set to `true` when you run the code. Top of the `dev-refactor` branch should treat the `soc-LiveJournal1` graph as directed.

**Comment by sgpyc** [comment]
And also, Gunrock removes self loops and duplicated edges (there are 518382 self loops / duplicated edges in the directed version of `soc-LiveJournal1`, and 52285072 of them in the undirected version) by the graph loader. This can also create some mismatches in the result.

**Comment by neoblizz** [comment]
I believe this was answered, if the issue persists please re-open and post an update.
