### ISSUE TITLE
discussion/question - offload compressed data into GPU to speedup

### ISSUE THREAD

**Issue by archenroot** [gunrock/gunrock#433]
On large graphs would it be some possible performance improvement to save both disk IO and memory trougput to offload data in highly compressed form, GPUs are known to compress/decompress superior quickly in parallel... just something which could potentially improve results a lot on multigpu higher vram systems... 

I think this could be simple candidate to integrate - ok for multigpu version it will requires some chunk splitter, etc.
http://libbsc.com/

It could be supported on future streaminggraph as well.

**Comment by neoblizz** [comment]
There has been some past work on compression, but gunrock doesn't deploy any of the compression schemes currently. This is definitely a trade-off to consider, because you are leveraging some compute to do compression instead of computation on the graph. Would be interesting to further analyze this.

**Comment by archenroot** [comment]
@neoblizz - Actually I have found another library for multiGPU processing called Lux: https://github.com/LuxGraph/Lux

They claim to be using:
> compressed sparse column (CSC) graph in binary format

Maybe it is something to look at or just adopt :-)

**Comment by neoblizz** [comment]
@archenroot we actually have `CSC` representation already, we have native support for `CSR`, `CSC` and `COO` representations and allow ability to add more.

**Comment by archenroot** [comment]
@neoblizz - I need to dig more into gunrock more, I was focused on algo only so far, thx for explanation.
