### ISSUE TITLE
Running a full BC

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#437]
Hi
In order to run a full BC, I saw that shared_lib_* binaries are there in the bin/
This is the output I get

```
mahmood@orca:bin$ ./shared_lib_bc 
0	 1	 0	 queue3 	 oversize :	 9 ->	 14
0	 1	 0	 queue3 	 oversize :	 9 ->	 14
Node_ID [0] : Score [0.0000]
Node_ID [1] : Score [0.2500]
Node_ID [2] : Score [0.5000]
Node_ID [3] : Score [0.7500]
Node_ID [4] : Score [0.0000]
Node_ID [5] : Score [0.0000]
Node_ID [6] : Score [0.0000]

```
And the execution is very very quick. Sounds like an error.

Even I modified similar to what is said in https://github.com/gunrock/gunrock/issues/251#issuecomment-311839910

```
    int test[1] = {-1};
    struct GRSetup *config = InitSetup(1, test);   // gunrock configurations

```
And I get
```

mahmood@orca:build$ ./bin/shared_lib_bc 
0	 1	 0	 queue3 	 oversize :	 9 ->	 14
0	 1	 0	 queue3 	 oversize :	 9 ->	 14
0	 1	 0	 queue3 	 oversize :	 14 ->	 20
0	 1	 0	 queue3 	 oversize :	 14 ->	 20
Node_ID [0] : Score [0.5000]
Node_ID [1] : Score [0.5000]
Node_ID [2] : Score [2.3333]
Node_ID [3] : Score [1.8333]
Node_ID [4] : Score [1.8333]
Node_ID [5] : Score [0.6667]
Node_ID [6] : Score [0.3333]

```
Again the execution time is very very small

**Comment by mahmoodn** [comment]
So, may I know how can I feed the large datasets?

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_bc.c#L19-L22 instead of this, load your graph as a CSR: row_offsets, col_indices.

**Comment by mahmoodn** [comment]
@neoblizz 
For a 1M node graph, I can create something like this

```
    int num_nodes = 10000, num_edges = 60000;
    int row_offsets[1000]  = {0, 10, 100, 200, ...., 10000};   
    int col_indices[1000] = {1, 2, 3, 0, ..., 300, 9000, 8000,  ...., 6, 3, 4, 5};

```
However, I wasn't able to find how to feed in the input file. Didn't find any example. Please let me know if there is a example for that?

**Comment by jowens** [comment]
Our input format is MatrixMarket. Executables usually run as:

`executable market filename.mtx ...`

There's a `dataset` directory with small and large datasets at the root level of the repo.

**Comment by mahmoodn** [comment]
Guys, something is going messy here... It seems that I couldn't point to the problem correctly.

I can run the market format. For example

```
$ ~/gunrock/build/bin/bc market hollywood-2009.mtx 
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (1s).

Degree Histogram (1139905 vertices, 112751422 edges):
    Degree   0: 32662 (2.87%)
    Degree 2^0: 24445 (2.14%)
    Degree 2^1: 50032 (4.39%)
    Degree 2^2: 99398 (8.72%)
    Degree 2^3: 174673 (15.32%)
    Degree 2^4: 231414 (20.30%)
    Degree 2^5: 219393 (19.25%)
    Degree 2^6: 139586 (12.25%)
    Degree 2^7: 78822 (6.91%)
    Degree 2^8: 44379 (3.89%)
    Degree 2^9: 25905 (2.27%)
    Degree 2^10: 13729 (1.20%)
    Degree 2^11: 5233 (0.46%)
    Degree 2^12: 230 (0.02%)
    Degree 2^13: 4 (0.00%)

Using 1 GPU: [ 0 ].
Using traversal-mode LB
__________________________
0	 4	 0	 queue3 	 oversize :	 1367888 ->	 52557065
0	 4	 0	 queue3 	 oversize :	 1367888 ->	 52557065
0	 5	 0	 queue3 	 oversize :	 52557065 ->	 56516755
0	 5	 0	 queue3 	 oversize :	 52557065 ->	 56516755
--------------------------
iteration 0 elapsed: 259.870052 ms, src = 0
Computing reference value ...
CPU BC finished in 4328.223145 msec. Search depth: 11

Validity BC Value: 
CORRECT
Validity Sigma: 
CORRECT
Validity labels: 
CORRECT

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 960626688	 56516755	 1367888
	 queue_sizing =	 49.580233 	 1.200002

 [BC] finished.
 avg. elapsed: 259.8701 ms
 iterations: 0
 min. elapsed: 259.8701 ms
 max. elapsed: 259.8701 ms
 rate: 866.6893 MiEdges/s
 src: 0
 nodes_visited: 1069126
 edges_visited: 225226612
 nodes queued: 2138251
 edges queued: 112613306
 nodes redundance: 100.00%
 load time: 628.0119 ms
 preprocess time: 71.0821 ms
 postprocess time: 128.9201 ms
 total time: 5439.7891 ms

```

As you can see, the execution time is very small. I was seeking a way to run for a larger amount of time. In my previous post, you said, I may have to run full BC for that purpose (at least that is what I understood). 

So, the question was, how to run a full BC?  Then I have been redirected to the shared_lib_bc.c and not I have stuck since have no idea how to feed the mtx file.

What I understand is that, I have to manually define a sparse graph in the shared_lib_bc.c. Is that correct?

**Comment by neoblizz** [comment]
I see, I am sorry, I misunderstood. If you just wanna run a long BC on a large graph, just pick a fairly large graph, build gunrock, and call the BC command line as follows:

```
./path/to/bin/bc market /path/to/dataset/name.mtx --src=-1
```
with `--src=-1` to run the full BC. Note that this will be a long run.

--

You can do the same thing using `shared_lib_bc.c` or the python interface by passing in the mtx file as two arrays: row_offsets and col_indices as files. If not, just use the command line.

**Comment by mahmoodn** [comment]
@neoblizz:
Thanks. I got it. That is very very large for even moderate graphs, e.g hollywood
!
