### ISSUE TITLE
check with stjones re: iterate over kernel with a global barrier (but not kernel boundary) at end of each iteration

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#438]
Placeholder since @neoblizz is gonna look into this.

**Comment by neoblizz** [comment]
> Hi Stephen,
> 
> As discussed with you last week at SC, I tried different ways of launching the same kernel consecutively many many times. CUDA Graph is ~5% faster than natively launching the kernels one after another, but grid.sync() is ~3X slower. Do you have any suggestion regarding the best way to kernel launches like this?
> 
> The test code is at https://github.com/gunrock/gunrock/blob/dev-refactor/tests/unit_tests/test_for.cu , and the actual implementation is at https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/oprtr/1D_oprtr/for.cuh . Our use case in Gunrock is a GPU push-relabel implementation for max-flow, at https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/mf/mf_enactor.cuh#L256.
> I run the unit test on a GV100 with CUDA 10.0.130 and NVIDIA driver 410.72 on ubuntu 18.04. The running times in ms are as following:
> 
> CPU OpenMP : PASS, time = 2026.71
> GPU Cooperactive Group : PASS, time = 375.927
> GPU CUDA Graph : PASS, time = 104.635
> GPU stacked kernels : PASS, time = 110.885
> 
> Each test launches a kernel that read-modify-write ~1 million elements, for 20x1000 times (i.e. 20k kernel launches in total). While the kernel has some workload, the timing from CUDA Graph and stacked launches are about 5 us per kernel, not much more than the launching overhead.
> 
> Thanks and best regards,
> Yuechao

Waiting for Stepehen's reply, documenting stuff here.

**Comment by neoblizz** [comment]
> Hi Yuechao, I’m sorry I didn’t reply earlier – this and your ping got lost in the email deluge which always follows a conference ;) Thanks for re-pinging me, Muhammad.
> 
>  
> 
> I must admit, your numbers surprise me. Looking at your CUDA version, we updated CUDA 10.0 in October and have reduced some of the graph overheads and I’d recommend retesting with that. Also, CUDA 10.1 (coming in Q1 next year) has many more optimizations for graphs so your numbers will change yet again. In particular, in CUDA 10.0 graph launch is O(num_kernels) cost while in CUDA 10.1 it will be O(1).
> 
>  
> 
> The first thing I see is that your runtimes are large. Graphs will save you a microsecond or two on every launch, so if your runtimes are in the milliseconds then you won’t see a large percentage gain. I’m actually quite impressed that you’re seeing 5ms – you must have a lot of kernel launches.
> 
>  
> 
> Looking at your test code, I’m intrigued that RepeatFor1() is using explicit graph-node creation to generate the work, instead of just capturing the sequence from RepeatFor2(). It also appears you have only a single kernel node in your graph, unless I’m misreading things, and that limits most of the efficiency gains. You really want a single graph of 20k kernel launches, instead of 20k graphs of 1 launch. The reason for this is that performance comes from two places:
> 
> CPU-side performance gains come from reducing the number of steps needed to launch work. The more kernels you get in a single launch, the more savings you make.
> GPU-side inter-kernel overhead (the time it takes to get threads on and off the SM) can be reduced by pre-fetching caches etc, but only if the graph knows what’s coming next. When you have a graph of one node, there’s no pre-fetching possible.
>  
> 
> I strongly suggest, therefore, trying out a single giant graph of 20k nodes and seeing what that does for your performance. It should be pretty easy to test: you can just capture the operations from your normal stream test, then do the graph launch. Note that graph instantiation is expensive (~3x stream launch) so you might want to time with and without including instantiation, just to compare the difference.
> 
> Stephen
