### ISSUE TITLE
Running algorithms by providing a source list

### ISSUE THREAD

**Issue by ajaleel123** [gunrock/gunrock#442]
Hi, 

We have been running Gunrock sssp with the following command 

```
sssp market soc-LiveJournal1.mtx --src=list --undirected --quick --jsonfile=sssp-soc-LiveJournal1-1.json --source_list=13720650,21936990,19088974,19088973,21936989,21936992,21936993,21936991,21936996,21936998,21936994,21936999,21936995,21936997,11820875,19622229,19622231,19622233,19622235,19622232,19622237,19622234,19622230,21936622,20336646,19622236,8317910,20336647,132315,17726633,20869207,22234053,16052694
```

On Pascal, the above command was running fine, though we get a random number in the output for "Source vertex" see beow.

Source vertex: 3184103447833097273

Interesting, the same command no longer runs on Volta, in fact it crashes.

Any suggestions would be helpful.

Thanks,
  Aamer (and the NVIDIA team)

**Comment by neoblizz** [comment]
@porumbes were you able to reproduce this?

**Comment by ajaleel123** [comment]
Can you let me know which version of Gunrock you are using?  Perhaps we
need to upgrade our Gunrock version.

**Comment by porumbes** [comment]
I've tried on both `master` (which should be version 0.4) and on `dev-refactor` (unlikely that you're working from here, but correct me if I'm wrong). The Quadro GV100 and the GTX 970 were on "Ubuntu 18.04.1 LTS" systems. 

What system are you running on? Have you made any changes to cmake/make files?

**Comment by neoblizz** [comment]
May be related to #498, but I am unable to reproduce this issue or issue 498. Need more information.

**Comment by neoblizz** [comment]
Not reproducible, shouldn't come up in the new release as we handle parameters differently.
