### ISSUE TITLE
ERROR ENUMERATING CUDA DEVICES.

### ISSUE THREAD

**Issue by ychmc** [gunrock/gunrock#443]
I have some problems when I make test. However, I didn't understand how the error has been resolved! 
I'm Strange some tests is passed, but others are failed.The failed tests's problem is the same.
      Start  1: TEST_BFS
 1/11 Test  #1: TEST_BFS .........................   Passed    0.01 sec
      Start  2: TEST_BC
 2/11 Test  #2: TEST_BC ..........................   Passed    0.01 sec
      Start  3: TEST_CC
 3/11 Test  #3: TEST_CC ..........................   Passed    0.01 sec
      Start  4: TEST_SSSP
 4/11 Test  #4: TEST_SSSP ........................   Passed    0.01 sec
      Start  5: TEST_PAGERANK
 5/11 Test  #5: TEST_PAGERANK ....................   Passed    0.01 sec
      Start  6: TEST_TOPK
 6/11 Test  #6: TEST_TOPK ........................   Passed    0.01 sec
      Start  7: SHARED_LIB_TEST_BFS
 7/11 Test  #7: SHARED_LIB_TEST_BFS ..............***Failed  Required regular expression not found.Regex=[Node_ID.*2.*: Label.*1
]  0.00 sec
[/home/dbci/chgy/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 10981] cudaSetDevice failed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
[/home/dbci/chgy/gunrock/gunrock/app/bfs/bfs_app.cu, 424 @ gpu 0] cudaStreamCreate fialed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
ERROR ENUMERATING CUDA DEVICES.
Exiting.

      Start  8: SHARED_LIB_TEST_BC
 8/11 Test  #8: SHARED_LIB_TEST_BC ...............***Failed  Required regular expression not found.Regex=[Node_ID.*0.*: Score.*0.5000
]  0.00 sec
[/home/dbci/chgy/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 11129] cudaSetDevice failed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
[/home/dbci/chgy/gunrock/gunrock/app/bc/bc_app.cu, 370 @ gpu 0] cudaStreamCreate fialed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
ERROR ENUMERATING CUDA DEVICES.
Exiting.

      Start  9: SHARED_LIB_TEST_CC
 9/11 Test  #9: SHARED_LIB_TEST_CC ...............***Failed  Required regular expression not found.Regex=[Node_ID.*1.*: Component.*0
]  0.00 sec
[/home/dbci/chgy/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 11090] cudaSetDevice failed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
[/home/dbci/chgy/gunrock/gunrock/app/cc/cc_app.cu, 282 @ gpu 0] cudaStreamCreate fialed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
ERROR ENUMERATING CUDA DEVICES.
Exiting.

      Start 10: SHARED_LIB_TEST_SSSP
10/11 Test #10: SHARED_LIB_TEST_SSSP .............***Failed  Required regular expression not found.Regex=[Node_ID.*1.*: Label.*39.*
]  0.00 sec
[/home/dbci/chgy/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 11063] cudaSetDevice failed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
[/home/dbci/chgy/gunrock/gunrock/app/sssp/sssp_app.cu, 382 @ gpu 0] cudaStreamCreate fialed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
ERROR ENUMERATING CUDA DEVICES.
Exiting.

      Start 11: SHARED_LIB_TEST_PAGERANK
11/11 Test #11: SHARED_LIB_TEST_PAGERANK .........***Failed  Required regular expression not found.Regex=[Node_ID.*2.*: Score.*1.2*
]  0.00 sec
[/home/dbci/chgy/gunrock/gunrock/util/test_utils.cu, 61 @ gpu 11063] cudaSetDevice failed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
[/home/dbci/chgy/gunrock/gunrock/app/pr/pr_app.cu, 342 @ gpu 0] cudaStreamCreate fialed. (CUDA error 35: CUDA driver version is insufficient for CUDA runtime version)
ERROR ENUMERATING CUDA DEVICES.
Exiting.

55% tests passed, 5 tests failed out of 11

Total Test time (real) =   0.07 sec

The following tests FAILED:
	  7 - SHARED_LIB_TEST_BFS (Failed)
	  8 - SHARED_LIB_TEST_BC (Failed)
	  9 - SHARED_LIB_TEST_CC (Failed)
	 10 - SHARED_LIB_TEST_SSSP (Failed)
	 11 - SHARED_LIB_TEST_PAGERANK (Failed)
Errors while running CTest
make[3]: *** [CMakeFiles/check] Error 8
make[2]: *** [CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2

**Comment by neoblizz** [comment]
`CUDA driver version is insufficient for CUDA runtime version` I am not sure if the tests that pass really passed. If you can share the output of cmake verbose, we will be able to see if that's true.

Also, you need to update your nvidia driver. That is why this is failing.
