### ISSUE TITLE
Integration with Spark via RAPIDS

### ISSUE THREAD

**Issue by archenroot** [gunrock/gunrock#445]
I see big potential for Gunrock to integrate with RAPIDS:
https://github.com/RAPIDSai

RAPIDS implements GPU DataFrame (one of Spark base objects). Spark itself implements also extensions of DataFrame for graph processing in form of GraphX project, where Edge and Vertex DataFrame extended classes implemented. If RAPIDS support GraphX it could use Gunrock as raw engine for graph processing.

I opened issue about this on RAPIDS side:
https://github.com/rapidsai/cudf/issues/438

**Comment by jowens** [comment]
Kindly note "community contributors" at https://rapids.ai/community.html .
