### ISSUE TITLE
Gunrock implementation

### ISSUE THREAD

**Issue by May989** [gunrock/gunrock#45]
I have gone through the Gunrock paper "Gunrock: A High-Performance Graph Processing Library on the GPU", but still unable to understand the implementation of Gunrock sssp algorithm. Can you please tell details about the implementation of cuda version of sssp(gunrock).

**Comment by jowens** [comment]
Sorry, didn't see this. Here's the latest text we wrote on it: 

>  We start from a single source vertex in the frontier. To compute a distance value from the source vertex, we need one advance and one filter operator. On each iteration, we visit all associated edges in parallel for each vertex in the frontier and relax the distance's value (if necessary) of the vertices attached to those edges. We use an AtomicMin to atomically find the minimal distance value we want to keep and a bitmap flag array associated with the frontier to remove redundant vertices. After each iteration, we use a priority queue to reorganize the vertices in the frontier.

**Comment by jowens** [comment]
I believe ```Subqueue_Core``` in ```gunrock/app/sssp/sssp_enactor.cuh``` has the core of the logic (@ychpan?).

**Comment by sgpyc** [comment]
Yes, SubQueue_Core in gunrock/app/sssp/sssp_enactor.cuh is the core logic,
with actual computation in SSSPFunctor in gunrock/app/sssp/sssp_functor.cuh.

It basically contains two steps: 1) advance: visit the neighbors (d_id) of
the vertices (s_id) in a frontier, and update the neighbors' weight if new
ones (labels[s_id] + weights[e_id]) are smaller than the old ones
(labels[d_id]); 2) filter: form a new frontier using the vertices that have
weight recently updated.

Start with the source vertex in a frontier, run the two steps until the
resulted frontier is empty, then all vertices reachable from the source
will be labeled with the correct weights.
