### ISSUE TITLE
possible divergence and data race between block

### ISSUE THREAD

**Issue by Stefanlyy** [gunrock/gunrock#452]
Hello there!

Currently I am learning gunrock source code and may find a barrier divergence and  a read-write data race for kernel function in gunrock/util/join.cuh.
For kernel function Join
```
template <
    typename VertexId,
    typename SizeT>
__global__ void Join(
    const SizeT                 edges,
    const SizeT 		iter,
    const SizeT*    const       pos,
    const SizeT*    const	counts,
          SizeT*    	        flag,
    const VertexId* const	intersect,
    const VertexId* const       froms,
    const VertexId* const       tos,
          VertexId*             froms_out,
          VertexId*             tos_out)
{
    SizeT x = blockIdx.x * blockDim.x + threadIdx.x;
    SizeT size = ((iter==0) ? pos[iter]:counts[0]) * (pos[iter+1]-pos[iter]);
    if(x>=0 && x<size*edges)
    {
	SizeT a = (x/edges%((iter==0)?pos[iter]:counts[0]))*edges;
	SizeT b = pos[iter]+x/(edges*((iter==0)?pos[iter]:counts[0]));

	if(iter==0){ 
	    	froms_out[a]=froms[x/edges%pos[iter]];
	    	tos_out[a]=tos[x/edges%pos[iter]]; 
	}
	    __syncthreads();
	VertexId c = intersect[iter*2];
	VertexId d = intersect[iter*2+1];
	{if(c!=0)  
 	{
	    SizeT edge = c/2; 
	    if(c%2==1){{flag[x/edges]=0; return;}}
		if(froms_out[a+edge]!=froms[b]) {flag[x/edges]=0; return;}}
	    else{ 
		if(tos_out[a+edge-1]!=froms[b]) {flag[x/edges]=0; return;}}
	}
	else 
	{
		for(SizeT edge = 0; edge<iter+1; edge++){
		    if(froms[b]==froms_out[a+edge] || froms[b]==tos_out[a+edge])
		    {
		    	flag[x/edges]=0;
		      	return;
		    }    
		}
	}}
...
}
```
In line 140, there is an if statement ```if(x>=0 && x<size * edges)``` ,but what confuses me is that line 150 Join calls _ syncthreads(), in other words, this barrier function in the branch will lead to a barrier divergence. Additionally, for the global memory *froms _ out* and *tos _ out* , use block barrier *_ syncthread* is not appropriate, which can not avoid data race between block.
Thanks very much.

**Comment by eagleShanf** [comment]
I found it is the same as line 228's function Collect(). Did we try to use it in a wrong way?

**Comment by sgpyc** [comment]
only @Laurawly 's subgraph matching app uses the join operator.
I do see what @Stefanlyy / @eagleShanf  mean for the divergence issue, and surprise the code didn't hang.

There is a different implementation under the dev-refactor branch, https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/util/join.cuh#L120 , and it doesn't use `__syncthreads()`. It should work better, but I'm not 100% sure.

**Comment by neoblizz** [comment]
@Laurawly some comments on this will be appreciated! Since we don't plan on supporting SM in `dev` branch, you think this will not be an issue in `dev-refactor`? (something to keep an eye on while you finish up your SM app. 👍

**Comment by Laurawly** [comment]
Just as @neoblizz said, I'll keep the dev-refactor branch up-to-date with my subgraph matching implementation. The original join operator is kinda abandoned now. Please refer to the other branch. Thanks!
