### ISSUE TITLE
How to use gunrock to solve constraint shortest path

### ISSUE THREAD

**Issue by lushl9301** [gunrock/gunrock#457]
I wonder how should I use gunrock framework to develope a solver for resource constrained shortest path.

Quote from https://www.boost.org/doc/libs/1_69_0/libs/graph/doc/r_c_shortest_paths.html
The shortest path problem with resource constraints (SPPRC) seeks a shortest (cheapest, fastest) path in a directed graph with arbitrary arc lengths (travel times, costs) from an origin node to a destination node subject to one or more resource constraints. For example, one might seek a path of minimum length from s to t subject to the constraints that 

- the total travel time must not exceed some upper bound and/or
- the total amount of some good that has to be picked up at the vertices along the path be less than or equal to some capacity limit and/or
- if two vertices i and j are visited on a path, then i must be visited before j
- etc

The problem is NP-hard in the strong sense. If the path need not be elementary, i.e., if it is allowed that vertices are visited more than once, the problem can be solved in pseudopolynomial time. A central aspect is that two (partial) paths in an SPPRC can be incomparable, contrary to the SPP without resource constraints. This makes the SPPRC similar to a multi-criteria decision problem.
A recent survey on the problem is:
Irnich, S.; Desaulniers, G. (2005):
Shortest Path Problems with Resource Constraints
in:
Desaulniers, G.; Desrosiers, J.; Solomon, M. (eds.) (2005):
Column Generation
Springer, New York, pp. 33–65
(available online here)

**Comment by jowens** [comment]
So it seems like a large time investment to just understand the space of these algorithms, but I might start by seeing if there's a way to go from Gunrock's SSSP implementation (which seems to have some of the right ingredients) to something that solves at least the flavor of SPPRC in which you're interested. It may be that the decision procedure by which we accept/reject paths in SSSP can be changed to solve your problem

**Comment by lushl9301** [comment]
There will be a lot of labels generated during the processing of SPPRC.  I wonder if Gunrock could handle the huge size of search space.

**Comment by jowens** [comment]
Gunrock won't go beyond GPU core memory. I suppose it could be hacked to use unified memory to CPUs, but it would run terribly since we haven't looked at that case at all. So if the label size is in fact bigger than aggregate GPU memory on a single node, we're a bad fit.

**Comment by lushl9301** [comment]
thanks. I will be looking into how to implement SPPRC using gunrock with the assumption that it won't go beyond the GPU memory.

**Comment by neoblizz** [comment]
@lushl9301 the SSSP implementation in `dev-refactor` branch is a good start: https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/sssp/sssp_enactor.cuh#L87-L147

**Comment by lushl9301** [comment]
> @lushl9301 the SSSP implementation in `dev-refactor` branch is a good start: https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/sssp/sssp_enactor.cuh#L87-L147

thanks :D. I am looking at it since it is illustrated during GTC.
