### ISSUE TITLE
Cmake error configuring v0.3

### ISSUE THREAD

**Issue by anshumang** [gunrock/gunrock#46]
I copied the cmake output [here](https://gist.github.com/anshumang/f4f3eca1b91e65f8a31f).

**Comment by anshumang** [comment]
@yzhwang is there any update on this?

**Comment by jowens** [comment]
a) what version of cmake are you running? It's odd that an included cmake file would fail.
b) @ydwu commented on your gist that you need to manually install Metis.

**Comment by anshumang** [comment]
Ah, my bad...I didn't see the followup comment on my gist...cmake version 2.8.12.2

**Comment by jowens** [comment]
Oddly, I don't even see that cmake include file in my current snapshot. Anyway, 2.8.12 is pretty old. I'm using 3.3.2. Could you upgrade your cmake and see if the problem is still there?

**Comment by anshumang** [comment]
The following errors do not appear with 3.1.0

CMake Error: Error in cmake code at
/opt/data2/anshuman/gunrock-repos/gunrock-0.3/cmake/FindPackageHandleStandardArgs.cmake:3:
Parse error.  Expected "(", got newline with text "
".
CMake Error at cmake/FindOpenMP.cmake:229 (include):
  include could not find load file:

    /opt/data2/anshuman/gunrock-repos/gunrock-0.3/cmake/FindPackageHandleStandardArgs.cmake
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)

**Comment by jowens** [comment]
Your problem is solved then with a new cmake version (and a manual install of Metis)?

**Comment by anshumang** [comment]
Only a install of Metis was necessary...cmake 2.8.12.2 works fine.
