### ISSUE TITLE
subgraph matching 

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#465]
Can Gunrock support subgraph macthing now? 
Which kind is provided by default, subgraph isomorphism or homophism?
In subgraph matching, the edge label is important, how do you store a data graph with edge labels?
(teh edge label is different from weights in SSSP, because we may do operation like N(v,l) to extract the neighbors of a vertex with given edge label)

**Comment by jowens** [comment]
Our work here is still in progress. No updates at this time.

**Comment by Laurawly** [comment]
@bookug Currently, a version developing subgraph matching is available at dev branch. And I'm working on a refactored version of it.
It supports subgraph isomorphism. We didn't target on homomorphism.
The edge labels are stored in key value format corresponding to edge ids. Could you elaborate more on operation N(v,l)?

**Comment by bookug** [comment]
the operation of N(v,l) is: given a vertex v and a edge label l, I want to extract the neighbors of v whose edge label is l.
It seems Gunrock uses CSR structure for storage?(row offset, column index, edge value)

**Comment by jowens** [comment]
@sgpyc can check me on this, but `N(v,l)` appears to me to be Gunrock's V-to-E advance operator with an advance operation ("The advance operation is a function that runs on a potential vertex in the output frontier. It returns true or false, and only if it returns true is that potential vertex placed in the output frontier. It can also modify data stored in the output vertex.").

**Comment by bookug** [comment]
Another question: for directed graphs with edge labels, how large can Gunrock support now? tens of millions of nodes or edges?

**Comment by jowens** [comment]
Whatever fits into GPU memory (including any temporary data structures we need to perform the computation).

**Comment by neoblizz** [comment]
We can report back here once SM application is working.

**Comment by neoblizz** [comment]
See issue #501 for updates on this.
