### ISSUE TITLE
HITS GPU Result Incorrect

### ISSUE THREAD

**Issue by jdwapman** [gunrock/gunrock#467]
The HITS GPU implementation under gunrock/dev appears to be incorrect. (gunrock/examples/hits)

OS: Linux Ubuntu 16.04
GPU: Tested with GTX 1060 and 970 individually
CUDA Version: 9.0
branch: dev

First, start with a simple directed graph, where nodes 1 and 2 both point to node 3.

testMatrix:
[0, 0, 1;
 0, 0, 1;
 0, 0, 0]

```
cat testMatrix.mtx
%%MatrixMarket matrix coordinate integer general                                                           
%
3 3 2
1 3 1
2 3 1
```

For this graph, it is simple to see that both node 1 and node 2 should have authority scores of 0 (since no nodes link to them), and node 3 should have a hub score of 0, since it points to no other nodes. Furthermore, since the graph is symmetrical, both node 1 and node 2 should have identical hub scores. This can be confirmed in MATLAB using the following commands:

```
simpleGraph = [0, 0, 1; 0, 0, 1; 0, 0, 0];
G = digraph(simpleGraph);
 
hub_ranks = centrality(G, 'hubs', 'MaxIterations', 1000)
auth_ranks = centrality(G, 'authorities', 'MaxIterations', 1000)
```
Output:
```
hub_ranks =

    0.5000
    0.5000
         0

auth_ranks =

     0
     0
     1

```
One important note is that the Matlab implementation uses the 1-norm rather than the 2-norm to normalize the hub and authority rank vectors.

However, the GPU HITS implementation outputs asymmetrical and incorrect hub scores. The number of iterations is set to 1000 in this example to match the Matlab implementation, but the GPU results do not appear to converge further as the number of iterations is increased. Notice that the hub rank of Vertex 0 is significantly higher than Vertex 1. In general, the source vertex used in the GPU implementation is always the highest hub score regardless of the graph input (as seen several times when using rgg to randomly generate a matrix).
 
```
./test_hits_9.0_x86_64 market testMatrix.mtx 
Loading Matrix-market coordinate-formatted graph ...
Reading from testMatrix.mtx:
  Parsing MARKET COO format (3 nodes, 2 directed edges)... Done parsing (0s).
  Converting 3 vertices, 2 directed edges (unordered tuples) to CSR format...
Done converting (0s).

Degree Histogram (3 vertices, 2 edges):
    Degree   0: 1 (33.33%)
    Degree 2^0: 2 (66.67%)

  Converting 3 vertices, 2 directed edges (unordered tuples) to CSR format...
Done converting (0s).
Using 1 GPU: [ 0 ].
Top 3 Ranks:
Vertex ID: 0, Hub Rank: 0.925000
Vertex ID: 2, Authority Rank: 1.000000
Vertex ID: 1, Hub Rank: 0.075000
Vertex ID: 0, Authority Rank: 0.000000
Vertex ID: 2, Hub Rank: 0.000000
Vertex ID: 1, Authority Rank: 0.000000

 [HITS] finished.
 avg. elapsed: 2.3842 ms
 iterations: 0
 load time: 135.1511 ms
 preprocess time: 6.3069 ms
 postprocess time: 49.2380 ms
 total time: 193.2840 ms
```

More comparisons will be added once the CPU reference implementation (which currently correctly matches Matlab) is merged.

**Comment by jdwapman** [comment]
Fixed in dev-refactor

**Comment by neoblizz** [comment]
New implementation of HITS in PR #499, see commits: 91bf87d, fb4820b and 5c8cc75. Regression test added in CMake for release as well. Tested chesapeake, bips, hollywood. See `dev-refactor` branch for all future optimizations.
