### ISSUE TITLE
Support for Nvidia Tesla C2075 Fermi architecture

### ISSUE THREAD

**Issue by May989** [gunrock/gunrock#48]
Hi,

I have installed gunrock-v0.2-145-g57842ba on Nvidia Tesla C2075, while running the test: $GUNROCK_ROOT/tests/bfs after make, it gets hanged although process consumes memory on gpu seen from "nvidia-smi". May I know whether this particular GPU which has Fermi arch with compute capability 2.0 supports this version of gunrock or not? If not, is there any way to make gunrock running for this architecture? Or is there any other version of gunrock which is compatible to this architecture?

**Comment by yzhwang** [comment]
Could you try pulling our latest release (v0.3) and try to use CMake for build?
Instruction here:
http://gunrock.github.io/gunrock/doc/0.3/building_gunrock.html
