### ISSUE TITLE
BFS kernels

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#482]
This is not a bug though...
With nv profiler, I see a kernel nam as `void gunrock::oprtr::edge_map_forward::Kernel<gunrock::oprtr::edge_map_forward::KernelPolicy<gunrock::app::bfs::BFSProblem<int, int, int, bool=0, bool=0>, int=300, int=1, int=7, int=1, int=0, int=5, int=32, int=512, int=7>`

What is the actual name of the kernel? I grepped edge_map_forward or BFSProblem and found many instances. Can you help?

**Comment by mahmoodn** [comment]
@jowens 
Excuse me... Can you help?

**Comment by neoblizz** [comment]
It is difficult to decipher the kernel names, the one you are looking at is in gunrock -> oprtr -> an edge_map_forward kernel launch: https://github.com/gunrock/gunrock/tree/master/gunrock/oprtr/edge_map_forward

**Comment by neoblizz** [comment]
If you are deep-diving into the code, I will highly recommend to switch to dev-refactor branch: `git checkout dev-refactor`. BFS is not refactored yet, so that will only be in `master` or `dev` branches.
