### ISSUE TITLE
python SSSP float weights

### ISSUE THREAD

**Issue by SphagnumMoss** [gunrock/gunrock#487]
It would be great if gunrock called from python could handle float values for edge weights.

e.g.
```
# call gunrock on device
        gunrock.sssp(labels, preds, nodes, edges, row, col, val, 1, sources, 0)
```

where: 
**`val`**

is a list of float values.

**Comment by neoblizz** [comment]
@SphagnumMoss This will be officially addressed in the later releases, but few small simple changes will allow you to use floats for edge weights;

```
mosama@bowser:~/forks/main/gunrock/python (master)*$ git diff
diff --git a/gunrock/app/sssp/sssp_app.cu b/gunrock/app/sssp/sssp_app.cu
index 9c27ceaa3..a6d51ce05 100644
--- a/gunrock/app/sssp/sssp_app.cu
+++ b/gunrock/app/sssp/sssp_app.cu
@@ -410,7 +410,7 @@ float sssp(
     const int           num_edges,
     const int*          row_offsets,
     const int*          col_indices,
-    const unsigned int* edge_values,
+    const float*       edge_values,
     const int           num_iters,
     int*                source,
     const bool          mark_preds)
diff --git a/gunrock/gunrock.h b/gunrock/gunrock.h
index f15fed3c5..be8c9abdc 100644
--- a/gunrock/gunrock.h
+++ b/gunrock/gunrock.h
@@ -307,7 +307,7 @@ float sssp(
     const int           num_edges,    // Input graph number of edges
     const int*          row_offsets,  // Input graph row_offsets
     const int*          col_indices,  // Input graph col_indices
-    const unsigned int* edge_values,  // Input graph edge weight
+    const float*       edge_values,  // Input graph edge weight
     const int           num_iters,
     int*                source,
     const bool          mark_preds);
diff --git a/python/single_source_shortest_path.py b/python/single_source_shortest_path.py
index 5b6589462..188389e84 100644
--- a/python/single_source_shortest_path.py
+++ b/python/single_source_shortest_path.py
@@ -8,12 +8,12 @@ gunrock = cdll.LoadLibrary('../build/lib/libgunrock.so')
 ### read in input CSR arrays from files
 row_list = [int(x.strip()) for x in open('toy_graph/row.txt')]
 col_list = [int(x.strip()) for x in open('toy_graph/col.txt')]
-val_list = [int(x.strip()) for x in open('toy_graph/val.txt')]
+val_list = [float(x.strip()) for x in open('toy_graph/valf.txt')]

 ### convert CSR graph inputs for gunrock input
 row = pointer((c_int  * len(row_list))(*row_list))
 col = pointer((c_int  * len(col_list))(*col_list))
-val = pointer((c_uint * len(val_list))(*val_list))
+val = pointer((c_float * len(val_list))(*val_list))
 nodes = len(row_list) - 1
 edges = len(col_list)
```

I didn't check for correctness.

**Comment by neoblizz** [comment]
Also, note that I am using `valf.txt` instead of `val.txt`, it is just a new file with 26 random floats.

**Comment by neoblizz** [comment]
Download the file: [sssp.txt](https://github.com/gunrock/gunrock/files/2876771/sssp.txt) into the main directory of gunrock repository, then do:

```
patch -p1 < sssp.txt
```

**Comment by SphagnumMoss** [comment]
that is fantastic, thank you so much!

is there any way to determine/extract the path of nodes that sssp took to achieve the shortest path?

**Comment by SphagnumMoss** [comment]
> @SphagnumMoss This will be officially addressed in the later releases, but few small simple changes will allow you to use floats for edge weights;
> 
> ```
> mosama@bowser:~/forks/main/gunrock/python (master)*$ git diff
> diff --git a/gunrock/app/sssp/sssp_app.cu b/gunrock/app/sssp/sssp_app.cu
> index 9c27ceaa3..a6d51ce05 100644
> --- a/gunrock/app/sssp/sssp_app.cu
> +++ b/gunrock/app/sssp/sssp_app.cu
> @@ -410,7 +410,7 @@ float sssp(
>      const int           num_edges,
>      const int*          row_offsets,
>      const int*          col_indices,
> -    const unsigned int* edge_values,
> +    const float*       edge_values,
>      const int           num_iters,
>      int*                source,
>      const bool          mark_preds)
> diff --git a/gunrock/gunrock.h b/gunrock/gunrock.h
> index f15fed3c5..be8c9abdc 100644
> --- a/gunrock/gunrock.h
> +++ b/gunrock/gunrock.h
> @@ -307,7 +307,7 @@ float sssp(
>      const int           num_edges,    // Input graph number of edges
>      const int*          row_offsets,  // Input graph row_offsets
>      const int*          col_indices,  // Input graph col_indices
> -    const unsigned int* edge_values,  // Input graph edge weight
> +    const float*       edge_values,  // Input graph edge weight
>      const int           num_iters,
>      int*                source,
>      const bool          mark_preds);
> diff --git a/python/single_source_shortest_path.py b/python/single_source_shortest_path.py
> index 5b6589462..188389e84 100644
> --- a/python/single_source_shortest_path.py
> +++ b/python/single_source_shortest_path.py
> @@ -8,12 +8,12 @@ gunrock = cdll.LoadLibrary('../build/lib/libgunrock.so')
>  ### read in input CSR arrays from files
>  row_list = [int(x.strip()) for x in open('toy_graph/row.txt')]
>  col_list = [int(x.strip()) for x in open('toy_graph/col.txt')]
> -val_list = [int(x.strip()) for x in open('toy_graph/val.txt')]
> +val_list = [float(x.strip()) for x in open('toy_graph/valf.txt')]
> 
>  ### convert CSR graph inputs for gunrock input
>  row = pointer((c_int  * len(row_list))(*row_list))
>  col = pointer((c_int  * len(col_list))(*col_list))
> -val = pointer((c_uint * len(val_list))(*val_list))
> +val = pointer((c_float * len(val_list))(*val_list))
>  nodes = len(row_list) - 1
>  edges = len(col_list)
> ```
> 
> I didn't check for correctness.

`
 sssp labels (distance):
3166850515
4051470165
3124693733
3047988302
3008087720
3047436667
3086687970`

I'm getting strange results, I've tried also with **`labels`** as float and the returned values do not make sense, is there something I'm overlooking?

**Comment by neoblizz** [comment]
Hm, I'll take a look. That seems odd.

**Comment by neoblizz** [comment]
Still looking into this, the problem you saw with the output is because distance array needs to be float as well. I will post a fix for this with dev-refactor branch instead (much easier to work with types there).

**Comment by SphagnumMoss** [comment]
Thank you for your help,

I have tried with the distance array as float:

**sssp_app.cu**

```
float sssp( 
    float*       distances, 
    int*                preds,
    const int           num_nodes,
    const int           num_edges,
    const int*          row_offsets,
    const int*          col_indices,
    const float* 		edge_values,
    const int           num_iters,
    int*                source,
    const bool          mark_preds)
{
```

and  **gunrock.h**

```
float sssp(
    float*       distances,    // Return shortest distances
    int*                preds,
    const int           num_nodes,    // Input graph number of nodes
    const int           num_edges,    // Input graph number of edges
    const int*          row_offsets,  // Input graph row_offsets
    const int*          col_indices,  // Input graph col_indices
    const float* 		edge_values,  // Input graph edge weight
    const int           num_iters,
    int*                source,
    const bool          mark_preds);
```

and my returned values with **single_source_shortest_path.py** is:
```
Round 1 of sssp.
0	 1	 0	 queue3 	 oversize :	 10 ->	 14
-1	 -1	 -1	 scanned_edges 	 oversize :	 7 ->	 10
0	 3	 0	 queue3 	 oversize :	 14 ->	 32
 sssp labels (distance):
3166850515
4051470165
3124693733
3047988302
3008087720
3047436667
3086687970
```

**Comment by neoblizz** [comment]
Supported in next release: #529
