### ISSUE TITLE
Cannot find source file externals/moderngpu/src/mgpucontext.cu

### ISSUE THREAD

**Issue by rachelglenn** [gunrock/gunrock#488]
Hi i get the following output when building:

-- Boost version: 1.65.1
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Found OpenMP
-- Found Metis
-- Project Added: bc
-- Project Added: bfs
-- Project Added: cc
-- Project Added: pr
-- Project Added: sssp
-- Project Added: hits
-- Project Added: salsa
-- Project Added: wtf
-- Project Added: topk
-- Configuring done
CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1801 (add_library):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  gunrock/CMakeLists.txt:34 (cuda_add_library)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/bc/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/bfs/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/cc/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/pr/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/sssp/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/hits/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/salsa/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/wtf/CMakeLists.txt:6 (include)

CMake Error at /usr/share/cmake-3.10/Modules/FindCUDA.cmake:1851 (add_executable):
  Cannot find source file:

    /home/jackie/Desktop/workspace/gunrock-0.4/externals/moderngpu/src/mgpucontext.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/SetSubProject.cmake:26 (CUDA_ADD_EXECUTABLE)
  tests/topk/CMakeLists.txt:6 (include)

-- Generating done
-- Build files have been written to: /home/jackie/Desktop/workspace/gunrock-0.4/build

When doing a build it fails:

CMakeFiles/shared_lib_bc.dir/shared_lib_bc.c.o: In function `main':
shared_lib_bc.c:(.text+0x3a6): undefined reference to `gunrock_bc'
collect2: error: ld returned 1 exit status
shared_lib_tests/CMakeFiles/shared_lib_bc.dir/build.make:102: recipe for target 'bin/shared_lib_bc' failed
make[2]: *** [bin/shared_lib_bc] Error 1
CMakeFiles/Makefile2:182: recipe for target 'shared_lib_tests/CMakeFiles/shared_lib_bc.dir/all' failed
make[1]: *** [shared_lib_tests/CMakeFiles/shared_lib_bc.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas as to why?
I am on Ubuntu 18.04 and Cuda 10 and gcc 7.3.0

**Comment by neoblizz** [comment]
Check if `externals` directory is empty. If so;
```
git submodule init
git submodule update
```

**Comment by rachelglenn** [comment]
Thanks, it makes sense now why the files were missing. I ran those commands.

Can I ask for help when running. It seems to be with moderngpu.

[  1%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o
cc: error: unrecognized command line option ‘-fopenmp=libomp’; did you mean ‘-fopenmp-simd’?
CMake Error at gunrock_generated_mgpucontext.cu.o.cmake:219 (message):
  Error generating
  /home/jackie/Desktop/workspace/gunrock/build/gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/./gunrock_generated_mgpucontext.cu.o


gunrock/CMakeFiles/gunrock.dir/build.make:119: recipe for target 'gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o' failed
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/gunrock_generated_mgpucontext.cu.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'gunrock/CMakeFiles/gunrock.dir/all' failed
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by neoblizz** [comment]
@rachelglenn can you try removing everything in that directory, then run:
```
cmake /path/to/gunrock/root
make
```
again?

**Comment by rachelglenn** [comment]
Yes, that is a good idea. I started over. i have it building now. Thank you. 

I am working on getting it to pass make test now. I will close this.
