### ISSUE TITLE
Interpretation of test failing

### ISSUE THREAD

**Issue by rachelglenn** [gunrock/gunrock#491]
Hi, I was able to compile Gunrocks. Boost 1_58, NVCC 9, GCC-5.5, Ubuntu 18.04. The make check tests are failing. It would be really helpful if could get some help understanding the output. Here is a summary of the test failing. 

Test project /home/jackie/Desktop/workspace/gunrock/build
      Start  1: TEST_BFS
 1/11 Test  #1: TEST_BFS .........................***Failed    0.04 sec
      Start  2: TEST_BC
 2/11 Test  #2: TEST_BC ..........................   Passed    0.04 sec
      Start  3: TEST_CC
 3/11 Test  #3: TEST_CC ..........................   Passed    0.04 sec
      Start  4: TEST_SSSP
 4/11 Test  #4: TEST_SSSP ........................***Failed    0.03 sec
      Start  5: TEST_PAGERANK
 5/11 Test  #5: TEST_PAGERANK ....................***Failed    0.04 sec
      Start  6: TEST_TOPK
 6/11 Test  #6: TEST_TOPK ........................***Exception: SegFault  0.16 sec
      Start  7: SHARED_LIB_TEST_BFS
 7/11 Test  #7: SHARED_LIB_TEST_BFS ..............***Exception: SegFault  0.16 sec
      Start  8: SHARED_LIB_TEST_BC
 8/11 Test  #8: SHARED_LIB_TEST_BC ...............***Exception: SegFault  0.16 sec
      Start  9: SHARED_LIB_TEST_CC
 9/11 Test  #9: SHARED_LIB_TEST_CC ...............***Exception: SegFault  0.15 sec
      Start 10: SHARED_LIB_TEST_SSSP
10/11 Test #10: SHARED_LIB_TEST_SSSP .............***Exception: SegFault  0.15 sec
      Start 11: SHARED_LIB_TEST_PAGERANK
11/11 Test #11: SHARED_LIB_TEST_PAGERANK .........***Failed  Required regular expression not found.Regex=[Node_ID.*2.*: Score.*1.2*
]  0.04 sec

18% tests passed, 9 tests failed out of 11

Total Test time (real) =   1.00 sec

The following tests FAILED:
	  1 - TEST_BFS (Failed)
	  4 - TEST_SSSP (Failed)
	  5 - TEST_PAGERANK (Failed)
	  6 - TEST_TOPK (SEGFAULT)
	  7 - SHARED_LIB_TEST_BFS (SEGFAULT)
	  8 - SHARED_LIB_TEST_BC (SEGFAULT)
	  9 - SHARED_LIB_TEST_CC (SEGFAULT)
	 10 - SHARED_LIB_TEST_SSSP (SEGFAULT)
	 11 - SHARED_LIB_TEST_PAGERANK (Failed)
Errors while running CTest
Makefile:83: recipe for target 'test' failed
make: *** [test] Error 8

From other posts, I decided to run a single test. Here is the command and output:

./bin/bfs market ..//simple_example/bips98_606.mtx --undirected --device=0 --src=0
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (0s).

Degree Histogram (7135 vertices, 30380 edges):
    Degree   0: 541 (7.58%)
    Degree 2^0: 626 (8.77%)
    Degree 2^1: 2181 (30.57%)
    Degree 2^2: 3085 (43.24%)
    Degree 2^3: 621 (8.70%)
    Degree 2^4: 80 (1.12%)
    Degree 2^5: 0 (0.00%)
    Degree 2^6: 1 (0.01%)

Source vertex: 0
Using 1 GPU(s): [ 0 ].
NOT COMPILED WITH COMPATIBLE PTX VERSION FOR DEVICE 0
Not yet tuned for this architecture
[/home/jackie/Desktop/workspace/gunrock/tests/bfs/test_bfs.cu, 388 @ gpu 0] BFS Enactor Init failed (CUDA error 8: invalid device function)

 [BFS] finished.
 avg. elapsed: 0.0000 ms
 iterations: 0
 load time: 38.4879 ms
 preprocess time: 0.0000 ms
 postprocess time: 0.0000 ms
 total time: 42.9902 ms

I am wondering what I should set PTX to. I have a GF-675M.

**Comment by neoblizz** [comment]
@rachelglenn GF-675M is of compute architecture 20 or 30, that's a pretty old card. Try removing everything in your build directory and setting these two in the CMakeLists.txt file to `ON`:

https://github.com/gunrock/gunrock/blob/master/CMakeLists.txt#L183-L189

And then build again like you did last time.

**Comment by neoblizz** [comment]
Closing this, I am guessing the above changes worked for you?
