### ISSUE TITLE
Possible missing file cpu_graph_lib.cpp

### ISSUE THREAD

**Issue by rachelglenn** [gunrock/gunrock#492]
Awesome code, by the way. Hey, I saw the simple example folder and am trying to compile it. It is missing the file cpu_graph_lib.cpp and cpu_graph_lib.hpp.

**Comment by neoblizz** [comment]
Thank you, we haven't done a lot to keep the simple_example updated. It is actually just 3 primitives combined using one test driver script, and not very informative. I would recommend you try out one of the individual tests instead.

1) Use `cmake` to build the whole project and try out different binaries for yourself, the binaries will be found in `/path/to/build/directory/bin`, let me know if the suggested solution fixed issue #491, and if this works.

If you wanna try just one primitive: bfs, cc, sssp, pr, etc. you can do so by going into the individual test directory (lets take bfs for example):
2) `/path/to/gunrock/tests/bfs` and running `make` in there. And then you should see the binary of `bfs` in the `bin` directory where you ran make.

**Comment by neoblizz** [comment]
We tried to do a better job by creating a simple example called `hello` in our `dev-refactor` branch, which also uses simpler and better APIs, and is easier to write your own primitive in. Code is a lot cleaner there, a release is scheduled for this new stuff in near future. Note that not all algorithms from `master` branch are ported to `dev-refactor` yet. To try out the dev-refactor branch, do the following:

```
git checkout dev-refactor
git submodule init
git submodule update
```
And then go in the `tests` directory, choose your primitive out of several new ones and run `make` in it.

**Comment by neoblizz** [comment]
Final note; since you are running an old GPU, make sure you choose the right architecture before running `make`: https://github.com/gunrock/gunrock/blob/dev-refactor/tests/BaseMakefile.mk#L27-L41 for dev-refactor and master branch.

**Comment by rachelglenn** [comment]
Thank you very much. I am going to go test the #491 as soon as I can. Probably some time during the week this next week.
