### ISSUE TITLE
Use case SSSP: Custom Functor Values

### ISSUE THREAD

**Issue by rachelglenn** [gunrock/gunrock#494]
Hi, I am wondering if it would be possible to do run a sssp with a custom functor function that we could apply to the edges. SSSP would use the custom functor value first and then distance associated with the edge to evaluate an filter operation. After reading your paper, I think that filter operation is the correct terminology. Please correct me if I am incorrect. Can we get it to return:

1) the predecessor for each path
2) the cost associated with each path

**Comment by neoblizz** [comment]
Can you give me an example of what those custom values would look like? Maybe a pseudo-algorithm for this enhancement?

Also, I will **highly** recommend making these changes in our new API under `dev-refactor`, it will be a lot easier and will be supported with future releases. To try `SSSP` for `dev-refactor`, do the following (like I explained in the issue #492.

```
git checkout dev-refactor
git submodule init
git submodule update
```

Here;s the code that you will modify to make these changes in `dev-refactor`:
https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/sssp/sssp_enactor.cuh#L87-L125

**Comment by neoblizz** [comment]
just to reiterate, this is done through lambda functions in the next release and is already available. See the previous post. Closing issue, re-open if unresolved.
