### ISSUE TITLE
SSSP: --src=largestdegree is using 0?

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#498]
**Summary:**
"For SSSP, we also found that Gunrock is using root=0 even when the –src=largestdegree  is given."

@ogreen can you help fill this in? Ask Euna to help?

@sgpyc @neoblizz @porumbes can you help?

**Reproducibility:**
Always or Sometimes

**To Reproduce:**
Detail the steps necessary to reproduce the behavior.

For example:
1. Clone gunrock
2. Switch to the dev-refactor branch

Make sure to:
$ git submodule init
$ git submodule update
etc.
etc.

**Expected Behavior:**

**Actual Results:**
A clear and concise description of what you actually experienced.

**System Configuration:**

GPU: GTX 970
CPU: Intel(R) Xeon(R) CPU E3-1280 v5 @ 3.70GHz
OS: Ubuntu 18.04.1 LTS
Cuda compilation tools, release 10.0, V10.0.130
NVIDIA-SMI 415.13
Driver Version: 415.13
CUDA Version: 10.0
gcc (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424

**Comment by neoblizz** [comment]
Can't reproduce for the dataset being used for the paper (using the script under `/dataset/test-scripts/grapl19/`):

```
./cit-Patents.sssp.output.txt:18:Using highest degree (770), vertex: 3569341
./kron_g500-logn21.sssp.output.txt:26:Using highest degree (213904), vertex: 1930586
./rmat_n24_e16.sssp.output.txt:28:Using highest degree (238942), vertex: 0
./soc-LiveJournal1.sssp.output.txt:23:Using highest degree (20292), vertex: 10009
./soc-twitter-2010.sssp.output.txt:28:Using highest degree (698112), vertex: 10119000
./twitter_rv.net.sssp.output.txt:30:Using highest degree (2997469), vertex: 1037947
./uk-2002.sssp.output.txt:20:Using highest degree (2449), vertex: 15353974
./uk-2005.sssp.output.txt:21:Using highest degree (5213), vertex: 21049532
```

**Comment by jowens** [comment]
@ogreen can you clarify?

**Comment by ogreen** [comment]
I will ping Euna.

**Comment by eunaeuna** [comment]
I believe I've seen that phenomenon for myself as well but I can not reproduce it now....
Instead, I am sharing Zahra's script and log files.
---------------------------------------------------------------------------------------------------------
For example, run sssp with cit-Patents.mtx graph.
1. SET[0]: sssp market ../../dataset/large/cit-Patents/cit-Patents.mtx --src=0 --iteration-num=10 --queue-sizing=1 --in-sizing=1 --traversal-mode=LB --quick --device=0 --jsondir=./evalsssp/
2. SET[1]: sssp market ../../dataset/large/cit-Patents/cit-Patents.mtx --src=largestdegree --iteration-num=10 --queue-sizing=1 --in-sizing=1 --traversal-mode=LB --quick --device=0 --jsondir=./evalsssp/

The log shows as below:
1. cit-Patents.sssp.0.output.txt ==> correct!
Source vertex: 0
Using 1 GPU(s): [ 0 ].
Using traversal mode LB
2. cit-Patents.sssp.1.output.txt
Using highest degree (0), vertex: 0 ==> the largest degree node should be "3569341"
Source vertex: 0
Using 1 GPU(s): [ 0 ].

We used the same script above and found the same results for all graphs in all machines we tested (P100_PCI_16GB, P100_SXM_16GB, V100_PCI_16GB, V100_SXM_16GB, V100_PCI_32GB, V100_SXM_32GB). Attachment is sssp logs in P100. 
---------------------------------------------------------------------------------------------------------
[script.txt](https://github.com/gunrock/gunrock/files/2908351/script.txt)
[SSSP_P100_PCI_16G.zip](https://github.com/gunrock/gunrock/files/2908352/SSSP_P100_PCI_16G.zip)

**Comment by neoblizz** [comment]
Seems really odd, I ran 10 tests on `cit-Patents` and other datasets:

```
mosama@mario:~/forks/main/gunrock/dataset/test-scripts/grapl19/eval$ grep -nr "Using highest" ./
./cit-Patents.sssp.0.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.8.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.6.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.5.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.4.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.1.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.9.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.3.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.2.output.txt:18:Using highest degree (770), vertex: 3569341
./cit-Patents.sssp.7.output.txt:18:Using highest degree (770), vertex: 3569341
```

Not sure why the `--src=largestdegree` is `0`, because it is **trying** to find the highest degree node when it says:
```
Using highest degree (0), vertex: 0
```

in all my test it chooses the right node. Will look into this more if I get some free time over the weekend.

**Comment by neoblizz** [comment]
Not reproducible. Parameters are handled differently in the next release, so this problem really shouldn't come up.
