### ISSUE TITLE
refine documentation creation, document it

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#51]
I'm a little unclear on how to generate documentation. I understand we can use Jekyll, which I haven't used. But our docs are split between three places: (1) the gunrock-docs repo; (2) the README in the gunrock repo (which produces nice HTML on gunrock.github.io); and (3) the "doc" directory, which also generates the doxygen documentation (but does not appear to produce nice HTML on gunrock.github.io). 

The proximate reason for this request is that I want to start putting Vega graphs into our docs, and that means I really need to understand how to put them in since they need JS and HTML hackery, and I don't know how/where the source files ought to go.

I'd like to see/understand:
- [x] A brief set of internal instructions on how/where to put docs. ("If you want to add a page to the documentation, here's where you put it, and here's how you make sure it's included in the {doxygen, gunrock.github.io's HTML} produced docs."
- [x] Non-hardcoded links for the web-hosted docs. Currently we have .md files which should render nicely as HTML files, but we link to them directly into the doc repo with a hardcoded version number (e.g., `http://gunrock.github.io/gunrock/doc/0.3/programming_model.html`). That should definitely be cleaner.
- [x] Jekyll. Should we be using this?

Assigning YZH simply because I think he built the initial bits here, but anyone can chime in.

**Comment by shubho** [comment]
I recommend Jekyll - we are moving towards Jekyll + Github. It is a
lightweight wordpress and suits our needs.

Shubho

**Comment by jowens** [comment]
I'll take a peek. We've internally discussed it before and we think it's just fine, but it's a question of figuring out a workflow to answer the questions above.

**Comment by jowens** [comment]
This seems to be useful: http://rickfoosusa.blogspot.com/2011/10/howto-use-doxygen-with-github.html
Also: https://github.com/smartell/APIDemo (derives from the above)

The problem it solves is how to put doxygen output into github-pages.

**Comment by yzhwang** [comment]
Currently the steps of updating docs are as follows:
1) Write new pages in markdown under gunrock/doc/;
2) In gunrock.doxygen file, append newly added file names to INPUT;
3) Run doxygen gunrock.doxygen to generate all html pages (including documentation and all other markdown files);
4) git checkout gh-pages, manually update documentations and links in index.html (I know this looks silly and I think we should use a full automatic pipeline).

**Comment by jowens** [comment]
I could imagine this is probably a solved problem. I don't mind adding new file names to doxygen files, although it seems like it's probably better to keep .md documentation outside of doxygen entirely (the top-level Gunrock doc is at gunrock.github.io and is outside of doxygen) and have doxygen docs point to it. But manually updating docs/links is ugly. Hm. This might be an initial project for a new MS student, figure out how to integrate doxygen with github pages (and hopefully jekyll) (and then vega).

**Comment by neoblizz** [comment]
I believe all requirements were met, this was taken care of by Huan! Thanks!
