### ISSUE TITLE
Need raw data for comparison against other engines

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#52]
I've now recreated several graphs using vega-lite and Gunrock data (input is Gunrock json files). This is good. I now would like to start using non-Gunrock data. I am not finding the raw data from which we
made the tables in the current version of the Gunrock paper, except for a "wee-table.xlsx", which isn't exactly what I want anyway.

Specifically, I'd like to be able to get runtime data (elapsed time, possibly MTEPS) for a given combination of {engine, algorithm, dataset}. Where do the scripts that generated runtime numbers live?

Seems likely I'll either rewrite the .sh scripts that generate them as python scripts that output JSON, or write a short python script that inputs the output of the sh script and outputs JSON.

Also, if these engines are on mario or luigi, I'll need to be able to get to their binaries, so hopefully those are runnable as me.

**Comment by yzhwang** [comment]
List of engines/hardwired algorithms binaries:
Hardwired binaries:
  BFS: /data/Compare/b40c/test/bfs/ppopp-test-b40c.sh
  BC: /data/Compare/gpu_BC/ppopp-test.sh
  CC: /data/Compare/conn/ppopp-test.sh
  SSSP: Currently N/A.
Galois: /data/Compare/Galois-2.2.1/results
PowerGraph: /data/Compare/graphlab/release/toolkits/graph_analytics/{cc,pagerank,sssp}.sh
Ligra: /data/Compare/ligra_may22-2014/{BC,BFS,CC,PR,SSSP}.sh
MapGraph: /data/Compare/MapGraph/Algorithms/results/{bfs-test,cc-test,pr-test,sssp-test}.sh
Medusa: /data/Compare/Medusa/MedusaTemplate/results/{bfs,pg,sssp}.sh
CuSha: /data/Compare/CuSha/cusha-test.sh
Gunrock: /home/yzh/Projects/gunrock_build/bin/ppopp16/{bc-test,bfs-test,cc-test,pr-test,sssp-test}.sh
These are all very messy. I think writing a giant shell with engine/dataset/algorithm as input, and generating unstructured output first (as different engine has different output formats), then integrating it to JSON outputs should be one possible way to do it.

We can start by gathering all binaries into one directory and modifying these scripts.

**Comment by jowens** [comment]
Yow. OK. That is messy. Maybe make another repo under gunrock that's "scripts" and put all *input* scripts into it, including Gunrock scripts. (Other engines should be built/maintained separately, outside of any repos that we maintain.) I agree with the idea of having a "giant shell" (would Python be OK?) and that shell might take a JSON file as input that says where the {binaries, datasets} are. The shell would also convert the output of any engine into JSON. We could then nicely ask the authors of the other engines if we're using the right input parameters even.

**Comment by jowens** [comment]
You can totally veto this effort, btw, if what we currently have is totally working. I'm not the one who's on the front lines of collecting results. I just tend to be fairly organized in result-collection and automation, since I'm lazy and only want to write and collect stuff automatically and not have to do a bunch of manual stuff the next time I need to gather results again.

**Comment by yzhwang** [comment]
No you are right. What you suggested seems to be the right thing to do in the long term. I will start working on this when I have time. I really like the way @sgpyc handles script, I guess I will first write a skeleton script. I think Python is a good choice for 1) its good JSON support, and 2) easiness of calling *nix commands by import os and subprocess.

**Comment by jowens** [comment]
What does @sgpyc do with scripts?

I wrote gunrock/bfs in Python here: https://github.com/gunrock/gunrock/blob/master/output/bfs.py

**Comment by yzhwang** [comment]
He handles datasets and running parameters very well (better than me, for lots of those scripts I just made them quick and dirty). His used bash though.
The python code looks nice. Let's use python.

**Comment by neoblizz** [comment]
I don't think we need this issue anymore, https://github.com/gunrock/io exists for this purpose. We ended up using bash for all the tests ran for TOPC, and output per engine is recorded in gunrock/io. I am closing this issue for now, but if we need to work on this I will take care of it (open and reassign if needed @jowens).
