### ISSUE TITLE
CUDA 10.1 support

### ISSUE THREAD

**Issue by Rickyboy320** [gunrock/gunrock#527]
Hi,

Currently trying to build with CUDA 10.1 on the latest master (efaf39c55f36a17212c880397b0b0654b57a7de3) results a lot of error messages like this:
ptxas /tmp/tmpxft_000011a1_00000000-5_bfs_app.compute_70.ptx, line 104919; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4

Previously this was only deprecated, but in [CUDA 10.1 (which uses PTX version 6.4) this was actually removed.](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#ptx-isa-version-6-4).

I think you all will be able to figure out the best solution for this, as I am not very well versed in gunrock yet. For now I will just downgrade to CUDA 10.0, but I thought I would post in case this went unnoticed (or if someone else runs into the same issue, to prevent them from being very confused like I was).

I do not know if this is already on the roadmap, but I looked through the upcoming 1.0 release notes and past pull requests, and they did not indicate anything related to this issue.

Thanks in advance!

**Comment by neoblizz** [comment]
The error you are seeing is due to some of the now deprecated instructions. Thank you for bringing this up, we plan to support CUDA 10.1+ with the next release (and it should trickle down to current release as well).

**Comment by neoblizz** [comment]
Fixed in (https://github.com/moderngpu/moderngpu/pull/32), I will update the gitmodules once the PR is merged in the moderngpu repo.
