### ISSUE TITLE
Should rmat generate an output file?

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#528]
Hi,
I would like to know is it possible to use `rmat` while giving an .mtx file as input? I expect to get an R-MAT graph as an output file, but nothing is generated.

So, is ` bfs rmat hollywood-2009.mtx` a correct command?
The execution time is much less than `market`. Maybe I misunderstood something.

**Comment by jowens** [comment]
You've got two choices: let Gunrock generate an rmat graph or ask Gunrock to input a specific matrix-market-format graph from a file. I don't believe there's any facility to ask Gunrock to write a generated graph to a file (there's surely plenty of rmat generators out there already).

**Comment by neoblizz** [comment]
We do have the capability to write an rgg or rmat to file, but you can't use two different types of graphs inputs `rmat` and `mtx` together. Therefore, `bfs rmat hollywood-2009.mtx` is not a valid command. It is probably running bfs on rmat instead of the `hollywood-2009.mtx` file.

**Comment by neoblizz** [comment]
Here's how to save to a file: https://github.com/gunrock/gunrock/blob/master/examples/grmat/test_grmat.cu#L47-L48

**Comment by mahmoodn** [comment]
So, the default type for available mtx formats (which we download) is `market`. Am I right?
My question is then, how can I use rmat to generate a graph? What is the raw input then? The downloaded file is mtx and you said `bfs rmat file.mtx` is not valid. Can you give an example?

**Comment by neoblizz** [comment]
@mahmoodn yes, the downloaded input format is `market`, so you will run `bfs market file.mtx` to run the market format.

If you want to output rmat, you will run the `grmat` executable after building gunrock.
