### ISSUE TITLE
Storing output stats & scripts for processing them

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#53]
How did you want to organize storing output performance data (JSON files) and the scripts that generate them? Some other repo under the gunrock org? Something within the gunrock org? Your call. I'll move stuff per your orders here.

**Comment by yzhwang** [comment]
I'd like to add a repo with the name Stats or Performance Graph Generator (feel free to try new names, I suck at giving names). You can go ahead and create the repo and then we can add stuff to it together.

**Comment by jowens** [comment]
gunrock/io
