### ISSUE TITLE
Can Gunrock SSSP support negative weights?

### ISSUE THREAD

**Issue by bookug** [gunrock/gunrock#539]
I know it is based on the paper titled "Work-Efficient Parallel GPU Methods for Single-Source Shortest Paths".
In the paper it only deals with non-negative weights, but can it support negatives?
It seems the algorithm is not totally a delta-stepping strategy, but a tradeoff between delta-stepping and bellman-ford.
So does it support negative weights as well?

**Comment by jowens** [comment]
Fairly sure the answer is going to be "no, we don't support negative weights". Any delta-stepping variation is (to my knowledge) not capable of handling negative weights, even if the number of buckets is only two. @sgpyc , thoughts?

**Comment by bookug** [comment]
But in that paper, the solution is not like a label-setting algorithm, but a label-correcting algorithm.
A vertex may be added to queue multiple times, right?
In that case it can deal with negative weights.
If a vertex can only be added to queue once, like delta-stepping, then the parallelism must be limited, because in each step only the smallest ones can be selected and extended.

**Comment by jowens** [comment]
Honestly, I don't think I'm the expert here. We have never tested it, and if you do, please report back. It's probably fair to say we did not consider whether it did or not when we wrote it.
