### ISSUE TITLE
Future of gunrock/road map

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#546]
Road map needs to be updated: https://github.com/gunrock/docs/blob/master/source/includes/road_map.md

Future of gunrock doc can help us define a road map for gunrock: https://github.com/gunrock/docs/blob/master/source/future_gunrock.html.md

Needs John's input on what the road map looks like.

**Comment by jowens** [comment]
`future_gunrock` can of course be in the repo but should not be linked directly on the web pages.

**Comment by jowens** [comment]
https://github.com/gunrock/docs/commit/0af40145341a4bff085893fffde03146d9b1386e
