### ISSUE TITLE
What are the THREE biggest takeaways from gunrock as a graph analytics library?

### ISSUE THREAD

**Issue by neoblizz** [gunrock/gunrock#547]
- Our data-centric abstraction (frontiers)
- Parallelism within operators and BSP
- Load-balancing

These are what I believe the core of gunrock, and what it has to offer. Need a sentence each and should be located in the readme as a takeaway message of what gunrock is.

Maybe another one is multi-gpu.

**Comment by jowens** [comment]
https://github.com/gunrock/docs/commit/b616b521bbd6effbf75ae010c9a011640e30a370
