### ISSUE TITLE
[branch:dev-refactor] fails to compile due to a template error

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#548]
**Summary:**
dev-refactor head returns error during make test.

**Reproducibility:**
Always

**To Reproduce:**
git clone gunrock
init and update submodule
switch to dev-refactor branch
cmake and make, make test

**Expected Behavior:**
success

**Actual Results:**
/root/dev/gunrock-dev/gunrock/graphio/graphio.cuh(410): error: class "gunrock::graph::Csr<int, int, float, 0U, 0U, false>" has no member "Sort"
          detected during:
            instantiation of "cudaError_t gunrock::graphio::LoadGraph(gunrock::util::Parameters &, GraphT &, std::string) [with GraphT=gunrock::app::TestGraph<int, int, float, 1536U, 0U>]"
/root/dev/gunrock-dev/gunrock/app/pr/pr_app.cu(356): here
            instantiation of "double pagerank(SizeT, SizeT, const SizeT *, const VertexT *, int, __nv_bool, VertexT *, VertexT **, ValueT **) [with VertexT=int, SizeT=int, ValueT=float]"
/root/dev/gunrock-dev/gunrock/app/pr/pr_app.cu(396): here
            instantiation of "double pagerank(SizeT, SizeT, const SizeT *, const VertexT *, __nv_bool, VertexT, VertexT *, ValueT *) [with VertexT=int, SizeT=int, ValueT=float]"
/root/dev/gunrock-dev/gunrock/app/pr/pr_app.cu(434): here

/root/dev/gunrock-dev/gunrock/graphio/graphio.cuh(410): error: class "gunrock::graph::Csr<int, int, float, 0U, 0U, false>" has no member "Sort"
          detected during:
            instantiation of "cudaError_t gunrock::graphio::LoadGraph(gunrock::util::Parameters &, GraphT &, std::string) [with GraphT=gunrock::app::TestGraph<int, int, float, 1536U, 0U>]"
/root/dev/gunrock-dev/gunrock/app/pr/pr_app.cu(356): here
            instantiation of "double pagerank(SizeT, SizeT, const SizeT *, const VertexT *, int, __nv_bool, VertexT *, VertexT **, ValueT **) [with VertexT=int, SizeT=int, ValueT=float]"
/root/dev/gunrock-dev/gunrock/app/pr/pr_app.cu(396): here
            instantiation of "double pagerank(SizeT, SizeT, const SizeT *, const VertexT *, __nv_bool, VertexT, VertexT *, ValueT *) [with VertexT=int, SizeT=int, ValueT=float]"
/root/dev/gunrock-dev/gunrock/app/pr/pr_app.cu(434): here

1 error detected in the compilation of "/tmp/tmpxft_0000395f_00000000-8_pr_app.compute_61.cpp1.ii".
CMake Error at gunrock_generated_pr_app.cu.o.cmake:279 (message):
  Error generating file
  /root/dev/gunrock-dev/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o

**System Configuration:**
I don't have the access of the machine (my colleague told me the problem), so can only provide as much info as possible.
GPU: P40
CPU: N/A
OS: CentOS 7

NVIDIA-SMI N/A
Driver Version: N/A
CUDA Version: 10.0/9.0
gcc: N/A

I suspect it is due to this line:
https://github.com/gunrock/gunrock/blob/dev-refactor/gunrock/app/app_base.cuh#L55
Since it seems that this value is different between the instantiated class and the called class. cudaHostRegisterDefault should be 0 but not sure where does the number 1536 come from.

Thank you!

**Comment by neoblizz** [comment]
This was fixed in pre-release, I recommend using that branch because I have a bunch of things fixed there and cleaned up: https://github.com/gunrock/gunrock/commit/9cbfbbcb154047bc6f921059a65ae07c26ebdf15#diff-e2b194bddc1f0b4a7b7173a18d398ce4

After the v1.0 release, I plan to merge pre-release to dev-refactor/dev as well, so that becomes our new dev environment.

**Comment by yzhwang** [comment]
Thanks @neoblizz !
