### ISSUE TITLE
About Gunrock kernels

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#552]
I have noticed that with one algorithm, e.g. BFS, and different inputs, the kernels executed during the run may be different. For example, a dense graph may use kernel X while a sparse graph may not use that X. Or as another example, a graph which has high number of edges on vertices may use kernel Y, while another graph with small number of edges on vertices may use kernel Z where Y and Z are dominant kernels for two inputs.

I guess that one algorithm, e.g. BFS, has different approaches and computational models with different types of graphs. Am I right? Or there is something wrong?

**Comment by jowens** [comment]
"may be different" on a Gunrock run (you've seen this?), or instead that the optimal kernel selection may differ for different data sets?

I believe the primary difference between the optimal kernel selection on Gunrock runs for different datasets would be from choosing different load-balancing strategies. The best strategy for, say, a road network would be different than the best strategy for a social network.

**Comment by mahmoodn** [comment]
I am using one GPU device. 
For example, visual profiler shows edge_map_forward::kernel is domenent in BFS on belgium_osm. However, for hollywood, it is RelaxPartitionEdges2.

I think different partitioning methods are used for different types of graphs for optimum runtime. Do you confirm that? I think you were agreed by your last sentence.

**Comment by jowens** [comment]
Gunrock's single-GPU implementation doesn't do partitioning in the way that you probably think of partitioning; this is more of a "divide up work among multiple blocks" but is not a partition in the sense of METIS. 

It is accurate that two very different graph types, run with the same load-balancing method, may spend substantially different proportions of time in different kernels.
