### ISSUE TITLE
multi-GPU random walk and louvain algorithm return segfault

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#561]
**Summary:**
running run.sh for random walk and louvain algorithm will return this:
`./run.sh: line 68:   355 Segmentation fault      ./louvain market ./soc_LiveJournal1.mtx --undirected --max-iters=2 --max-passes=3 --quick=true --device=0,1`
and
`./run.sh: line 77:   355 Segmentation fault      ./rw market ./soc_LiveJournal1.mtx --undirected --store-walks=false --device=0,1`

**Reproducibility:**
Always

**To Reproduce:**
Happens on the clean build version off the head of master.

**System Configuration:**

GPU: Tesla P40 (cc: 6.1)
CPU: N/A
OS: CentOS 6
Driver Version: 396.44
CUDA Version: 9
gcc 4.8.5

**Comment by neoblizz** [comment]
Multi-GPU implementations for `louvain` and `rw` do not exist, see the application list and multi-gpu status of each application here: https://gunrock.github.io/docs/#gunrock-39-s-application-cases

**Comment by jowens** [comment]
It'd be polite to return a proper error though instead of segfaulting.

**Comment by yzhwang** [comment]
Thanks for the reply!
@jowens I would post more info if I had them. Here the segfault is the only thing my colleague got. As Muhammad said, looks like it is due to the lack of multi-gpu version of the two algorithms. I will close the issue now. And when I get the access of the machine and their test environment, I promise I will do more inspection before posting any issue here :-)
