### ISSUE TITLE
Suggestion of the test scripts

### ISSUE THREAD

**Issue by Z-Y00** [gunrock/gunrock#564]
I suggest to remove the dataset that is only on someone's PC or rewrite the script with download links

https://github.com/gunrock/gunrock/blob/fc229b445ef67dc007791d544de8d0e03fe47d8e/examples/rw/examples.sh#L47

**Comment by Z-Y00** [comment]
btw, I do wish someone can add these dataset to gunrock/dataset

**Comment by Z-Y00** [comment]
Also, many scripts are hard coded as * _9.1_x86_64
which is harmful, for I'm getting  _9.0_x86_64
plz change these to better scripts
https://github.com/gunrock/gunrock/blob/478cc55e151aa17ede183d022042ccf6a6a94a2f/examples/proj/test.sh#L5

**Comment by Z-Y00** [comment]
You can rename test_foo_9.1_x86_64 to  test_foo_* as here.
You can just fix this with a pull request
https://github.com/gunrock/gunrock/compare/master...Z-Y00:fc5c1ac7f8ce6d19651310a167034b5d7e2eda00

**Comment by neoblizz** [comment]
Some datasets we can't publish because they were part of a DARPA project, and the scripts needed to stay online for the DARPA to try stuff out, but thank you for the PR and fixing hard-coded binary names!
