### ISSUE TITLE
JSON issues (compared to previous JSON generation)

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#577]
- [x] Traversal options should be strings, not an array of one string
- [x] Are we running `direction-optimized = false`? In some runs we appear to be.
- [x] No tags have been generated yet
- [x] `gpuinfo`, `sysinfo`, `userinfo` are missing from generated JSONs
- [x] All Boolean outputs should be of boolean type (right now we do `1/0`, `"true"/"false"`, and `true/false`; should only be `true/false`
- [x] Be consistent about field names with multiple words (`word-word`? `word_word`?) (previously we've done `word_word`)
- [x] Previously we did `mark_predecessors` but now it's `mark-pred`
- [x] Subsecond runs probably have filename collisions (probably need ms resolution on filenames)
- [x] Some runs randomly put an extra number then close-brace at the end of the JSON, making the JSON file invalid
- [x] Throw out runs that are too fast (with the idea that those runs are probably on small disconnected subgraphs)
- [x] Beyond having `min-process-time` and `max-process-time`, could we also have `min-MTEPS` and `max-MTEPS`?

**Comment by neoblizz** [comment]
> Traversal options should be strings, not an array of one string
Does this mean, instead of this:
```
 "advance-mode": [
        "LB_CULL"
    ],
```

do this:
```
 "advance-mode": "LB_CULL"
```

**Comment by neoblizz** [comment]
>  Be consistent about field names with multiple words (word-word? word_word?) (previously we've done word_word)

We are using `word-word` for every single parameter name. Have you seen `word_word` anywhere? Changing that to underscore would require me to edit every single app. As the name of the json field is extracted from the parameters.

**Comment by neoblizz** [comment]
>  Are we running direction-optimized = false? In some runs we appear to be.

Yes. I take back what I said in slack, we are actually doing `--direction-optimized=true,false`, which should generate a json for direction-optimized set to true and false.

**Comment by neoblizz** [comment]
Can we also lose the support for json_spirit_writer? Some changes that I am making would require me to add ifdefs and snippets for json_spirit_writer. We've also let go of the old way of having a giant info struct (as each apps required unique parameters, which forced us to manually manage that file).

**Comment by neoblizz** [comment]
> All Boolean outputs should be of boolean type (right now we do 1/0, "true"/"false", and true/false; should only be true/false

Do you have an example of where you saw anything but true/false?

**Comment by jowens** [comment]
- `advance_mode`: If the array is always one element long, then just the string instead of an array of strings makes more sense, thanks.
- `word_word` was the standard in previous JSONs, but I'm fine with `word-word` if you prefer that. No problem. Just be consistent.
- If rapidjson works, I don't care if json_spirit disappears.

**Comment by jowens** [comment]
Is `elapsed` the mean of `process-times`? I like there's a `min-process-time` and a `max-process-time`; I'd like to start putting error bars onto some of our plots. If that's the case, I'd also appreciate a `min-m-teps` and `max-m-teps` (although I'd probably rename these `MTEPS`).

**Comment by jowens** [comment]
Also I know there was some effort to throw out too-small results in the past. For instance, running BFS on a piece of the graph that is very small will produce anomalous results, e.g. (`BFS_arabic-2005_Wed May 22 190139 2019.json`):

```
    "process-times": [
        93.98198127746582,
        98.21605682373047,
        96.12607955932617,
        98.46210479736328,
        94.01297569274903,
        102.62417793273926,
        99.06911849975586,
        98.00195693969727,
        96.77600860595703,
        1.4178752899169922
    ],
```

where that last run is probably on some sort of tiny disconnected subgraph and properly should be thrown out. (`elapsed` is smaller as a result than any of the 9 other entries in that array.)

**Comment by neoblizz** [comment]
> Is `elapsed` the mean of `process-times`? I like there's a `min-process-time` and a `max-process-time`; I'd like to start putting error bars onto some of our plots. If that's the case, I'd also appreciate a `min-m-teps` and `max-m-teps` (although I'd probably rename these `MTEPS`).

```
    "min-process-time": 4.4269561767578129,
    "max-process-time": 5.457162857055664,
```

are also recorded. I can add min-max MTEPS.

**Comment by jowens** [comment]
If `mxx-process-time` and `elapsed` measure the same thing, they should be named the same thing. I don't care what it is. But it should be consistent.

**Comment by neoblizz** [comment]
> All Boolean outputs should be of boolean type (right now we do 1/0, "true"/"false", and true/false; should only be true/false

This one is tricky, I will address as many as I can, and when these come up again we can fix them.

> If `mxx-process-time` and `elapsed` measure the same thing, they should be named the same thing. I don't care what it is. But it should be consistent.

How about `elapsed` = `avg-process-time`?

**Comment by neoblizz** [comment]
> Is `elapsed` the mean of `process-times`? I like there's a `min-process-time` and a `max-process-time`; I'd like to start putting error bars onto some of our plots. If that's the case, I'd also appreciate a `min-m-teps` and `max-m-teps` (although I'd probably rename these `MTEPS`).

Can I name it `mteps`, since everything else is lowercase? And yes, have `mxx-mteps` along with it?

**Comment by jowens** [comment]
Bools: Please at least fix `idempotence`, `mark_predecessors`, `undirected`. But there's more:

```
    "64bit-SizeT": "0",
    "64bit-ValueT": "0",
    "64bit-VertexT": "0",
    "communicate-latency": 0,
    "expand-latency": 0,
    "fullqueue-latency": 0,  // not sure
    "makeout-latency": 0, // not sure
    "subqueue-latency": 0, // not sure
```

`avg-process-time` and `mteps` are just fine with me.

**Comment by neoblizz** [comment]
Latency numbers need to be integers, but thank you for the rest. This helps.

**Comment by neoblizz** [comment]
[BFS_delaunay_n10.txt](https://github.com/gunrock/gunrock/files/3459816/BFS_delaunay_n10.txt)

Known things:

- [ ] mxx-mteps / 1000
- [ ] 64bit... should be a bool not integer (true/false instead of 0/1)

**Comment by jowens** [comment]
There's other true/false settings to be made (idempotence, mark_predecessors, undirected) but this looks great!

**Comment by neoblizz** [comment]
>  Throw out runs that are too fast (with the idea that those runs are probably on small disconnected subgraphs)

I am not sure how I determine when to throw out.

**Comment by jowens** [comment]
Less than 10% of the average runtime?

**Comment by neoblizz** [comment]
> Less than 10% of the average runtime?

Ok, I can do this.

**Comment by jowens** [comment]
2 standard deviations away from the average would be perhaps more meaningful.

**Comment by jowens** [comment]
I'm most curious to find out where the spurious numbers at the end are coming from.

**Comment by neoblizz** [comment]
@jowens resolved?

**Comment by jowens** [comment]
If you tell me it's resolved ("spurious numbers"), it's resolved.

**Comment by neoblizz** [comment]
It is. I don't see it with the runs after I fixed things up.
