### ISSUE TITLE
Question about kernel activity

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#581]
Hi,
In my profiling analysis, I see a kernel with the following name
```
_ZN7gunrock5oprtr2LB15RelaxLightEdgesILj1ENS_5graph3CsrIjjjLj256ELj0ELb1EEEjjZNS_3app3bfs16BFSIterationLoopINS7_7EnactorINS7_7ProblemINS6_9TestGraphIjjjLj768ELj0EEEjjLj0EEELj0ELj0EEEE4CoreEiEUlRKjRjSH_SH_SH_SI_E_EEvbNT0_7VertexTESK_PKT1_NSK_5SizeTEPKSP_PT2_PNSK_6ValueTEPSP_NS_4util15CtaWorkProgressISP_EET3_
```
Using [demangler](https://demangler.com/), I get this name
```
void gunrock::oprtr::LB::RelaxLightEdges<1u, gunrock::graph::Csr<unsigned int, unsigned int, unsigned int, 256u, 0u, true>, unsigned int, unsigned int, gunrock::app::bfs::BFSIterationLoop<gunrock::app::bfs::Enactor<gunrock::app::bfs::Problem<gunrock::app::TestGraph<unsigned int, unsigned int, unsigned int, 768u, 0u>, unsigned int, unsigned int, 0u>, 0u, 0u> >::Core(int)::{lambda(unsigned int const&, unsigned int&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int&)#1}>(bool, gunrock::graph::Csr<unsigned int, unsigned int, unsigned int, 256u, 0u, true>::VertexT, gunrock::app::bfs::BFSIterationLoop<gunrock::app::bfs::Enactor<gunrock::app::bfs::Problem<gunrock::app::TestGraph<unsigned int, unsigned int, unsigned int, 768u, 0u>, unsigned int, unsigned int, 0u>, 0u, 0u> >::Core(int)::{lambda(unsigned int const&, unsigned int&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int&)#1}, unsigned int const*, gunrock::app::bfs::BFSIterationLoop<gunrock::app::bfs::Enactor<gunrock::app::bfs::Problem<gunrock::app::TestGraph<unsigned int, unsigned int, unsigned int, 768u, 0u>, unsigned int, unsigned int, 0u>, 0u, 0u> >::Core(int)::{lambda(unsigned int const&, unsigned int&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int&)#1}::SizeT, unsigned int const* const*, unsigned int*, gunrock::app::bfs::BFSIterationLoop<gunrock::app::bfs::Enactor<gunrock::app::bfs::Problem<gunrock::app::TestGraph<unsigned int, unsigned int, unsigned int, 768u, 0u>, unsigned int, unsigned int, 0u>, 0u, 0u> >::Core(int)::{lambda(unsigned int const&, unsigned int&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int&)#1}::ValueT*, unsigned int const**, gunrock::util::CtaWorkProgress<unsigned int const*>, gunrock::app::bfs::BFSIterationLoop<gunrock::app::bfs::Enactor<gunrock::app::bfs::Problem<gunrock::app::TestGraph<unsigned int, unsigned int, unsigned int, 768u, 0u>, unsigned int, unsigned int, 0u>, 0u, 0u> >::Core(int)::{lambda(unsigned int const&, unsigned int&, unsigned int const&, unsigned int const&, unsigned int const&, unsigned int&)#1})
```

As I grep `RelaxLightEdges`, I see multiple instances in 
```
./gunrock/oprtr/LB_advance/kernel.cuh
./gunrock/oprtr/advance/kernel.cuh
./gunrock/oprtr/LB_CULL_advance/kernel.cuh
./gunrock/oprtr/edge_map_partitioned_backward/kernel.cuh
```

I guess it is `LB_advance/kernel.cuh`. Am I right?
That is a rather large kernel and I see that for a graph, this kernel (if that linker name has been correctly mapped) has low multiprocessor activity (less than 40%). That means SMs mostly have idle warps. Shared memory efficiency is also low (less than 40%). Moreover, the kernel has multiple `if` statements, but the branch efficiency is high (99.8%).

According to the documentation, this kernel is used in the load balance phase. For a graph with about 2M vertices (90% of them are of degree 2^1), I expect that load balancing should be done smoothly since the graph vertices and edges are not complicated and sounds like a sparse graph. That is an intuition though. Maybe the definition of load balancing is something different than my thoughts.
 
Any comment?

**Comment by jowens** [comment]
I don't understand the `bug` label. Is there a bug?

**Comment by jowens** [comment]
`LB_advance` makes sense to me. The different locations are for different load-balance strategies. Your command line likely tells you which strategy you're using (and/or dump the JSON and that will tell you as well).

**Comment by jowens** [comment]
There's a lot of internal work to try to make branch efficiency high, both for keeping our compute resources busy and for getting better memory coalescing. In general our load-balance strategies are more oriented toward scale-free graphs than road-network-ish low-degree graphs. Because of the low number of neighbors and the relatively small frontiers in a low-degree graph, it's hard to keep the GPU busy, and that may be what you're seeing. As well, we might be fully main-memory bound. @neoblizz and @sgpyc will surely correct anything I've said above that is incorrect.

We appreciate any performance analysis you do that you'd like to share with us!

**Comment by mahmoodn** [comment]
> I don't understand the bug label. Is there a bug?

No, when I create an issue (question) there are three options:
  Bug report
  Feature request
  Report a security vulnerability

**Comment by sgpyc** [comment]
The LB load balancing has quite heavy overhead in the balancing part, it's a binary search. Most vertices having degrees of 2 can easily make the kernel spend most time in workload balancing. 

Maybe try out TWC? If the rest 10% of the vertices do not have very large neighbor lists.

By the way, how long does the kernel take? 2M vertices with only a few M edges may not be able to fully utilize the GPU

**Comment by mahmoodn** [comment]
I used `market`. To be exact, it is 1.5M vertices with 3M edges. 
The bfs execution (average elapsed) is about 304ms. The device is M2000 with 700 cuda cores and 4G of memory.

May I know more technical details of LB? 
"binary search"ing what?

**Comment by jowens** [comment]
These results might be interesting for you: https://gunrock.github.io/docs/frontier.html

What they're saying is that the input frontier needs to get up to several tens of thousands to approach the maximum throughput of the GPU. Look at, say, the upside-down green triangles (`road_usa`). They don't reach maximum throughput. The diameter of a road network is large enough, and 2M is small enough of an overall dataset, that we don't keep the whole GPU busy in traversing a graph like that.

"Load-balanced partitioning" (LB) has binary search as part of it and is described in Section 3.4 of our TOPC paper. https://escholarship.org/uc/item/6xz7z9k0

**Comment by mahmoodn** [comment]
Regarding the frontier size, where can I change the number? Is that `--queue-factor`?

**Comment by jowens** [comment]
No, we experimentally measured that (every time we ran an advance operation, we recorded the size and the runtime). You could perhaps just build your own graph that had the characteristics you wanted in terms of frontier size.

**Comment by neoblizz** [comment]
As @jowens said, the frontier automatically resizes to fit the output, but you can define your own "initial" frontier queue in the enactor file of the respective application. This is not an easy change, and it cannot be done through command line.

Also, I feel like this question is well answered, highly recommend checking out the paper for more details, closing the issue.
