### ISSUE TITLE
Building Connected Component Application generates error

### ISSUE THREAD

**Issue by akifrehman371** [gunrock/gunrock#584]
I have using the latest version of Gunrock. I am getting following error while trying to build the Connected Component Application. Rest of the application are building fine.

$ cmake .. -DGUNROCK_BUILD_SHARED_LIBS=OFF -DGUNROCK_BUILD_APPLICATIONS=OFF -DGUNROCK_APP_CC=ON
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "7.5") 
-- Boost version: 1.59.0
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   timer
--   chrono
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found OpenMP
-- Found rapidjson header files in /home/mahmad/work/gunrock/externals/rapidjson/include
-- Project Added: cc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mahmad/work/gunrock/build_1
[mahmad@onrportal build_1]$ make -j16
[  5%] [ 11%] [ 16%] [ 22%] [ 27%] [ 33%] [ 38%] [ 44%] [ 50%] [ 55%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o
[ 61%] [ 66%] Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/__/externals/moderngpu/src/./gunrock_generated_mgpucontext.cu.o
Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/./gunrock_generated_test_utils.cu.o
Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/./gunrock_generated_str_to_T.cu.o
Building NVCC (Device) object examples/cc/CMakeFiles/cc.dir/__/__/gunrock/util/./cc_generated_str_to_T.cu.o
Building NVCC (Device) object examples/cc/CMakeFiles/cc.dir//./cc_generated_test_cc.cu.o
Building NVCC (Device) object examples/cc/CMakeFiles/cc.dir/__/__/gunrock/util/./cc_generated_error_utils.cu.o
Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/./gunrock_generated_error_utils.cu.o
Building NVCC (Device) object examples/cc/CMakeFiles/cc.dir/__/__/gunrock/util/./cc_generated_test_utils.cu.o
Building NVCC (Device) object gunrock/CMakeFiles/gunrock.dir/util/./gunrock_generated_misc_utils.cu.o
Building NVCC (Device) object examples/cc/CMakeFiles/cc.dir/__/__/externals/moderngpu/src/./cc_generated_mgpucontext.cu.o
Building NVCC (Device) object examples/cc/CMakeFiles/cc.dir/__/__/gunrock/util/./cc_generated_misc_utils.cu.o
In file included from /home/mahmad/work/gunrock/gunrock/app/cc/cc_enactor.cuh:29:0,
                 from /home/mahmad/work/gunrock/examples/cc/test_cc.cu:25:
/home/mahmad/work/gunrock/gunrock/app/cc/cc_problem.cuh:18:10: fatal error: gunrock/util/memset_kernel.cuh: No such file or directory
 #include <gunrock/util/memset_kernel.cuh>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at cc_generated_test_cc.cu.o.cmake:206 (message):
  Error generating
  /home/mahmad/work/gunrock/build_1/examples/cc/CMakeFiles/cc.dir//./cc_generated_test_cc.cu.o

make[2]: *** [examples/cc/CMakeFiles/cc.dir/build.make:61: examples/cc/CMakeFiles/cc.dir/./cc_generated_test_cc.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:174: examples/cc/CMakeFiles/cc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by neoblizz** [comment]
@porumbes is currently porting this to Gunrock v1.0.0. It is currently only available in v0.5.x.

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/issues/496
