### ISSUE TITLE
bfs example compute_XX

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#586]
For `example/bfs`, the build command is
```
"/usr/local/cuda-10.1/bin/nvcc" -DGIT_SHA1="\"\"" -gencode=arch=compute_70,code=\"sm_70,compute_70\"  -o bin/test_bfs_10.1_x86_64 test_bfs.cu ../../gunrock/util/str_to_T.cu ../../gunrock/util/test_utils.cu ../../gunrock/util/error_utils.cu ../../externals/moderngpu/src/mgpucontext.cu ../../externals/moderngpu/src/mgpuutil.cpp ../../gunrock/util/gitsha1make.c -lineinfo --std=c++11 --expt-extended-lambda -rdc=true  -m64 -I"/usr/local/cuda-10.1/bin/../include"  -I"../../externals/moderngpu/include" -I"../../externals/cub" -I"../../externals/rapidjson/include" -I.. -I../..  -Xcompiler -fopenmp -Xlinker -lgomp  -Xcompiler -DGUNROCKVERSION=1.0.0 -O3
```
So, it only generates the code for CC 70. Does that mean this example is explicitly incompatible with 1080ti (CC 61)? With `run.sh`, I get

```
$ ./run.sh
./bin/test_bfs_10.1_x86_64 market ../../dataset/large/ak2010/ak2010.mtx --num-runs=10 --validation=each --device=2 --jsondir=./eval/GUNROCK_v1-0-0_TitanXp --src=random --64bit-SizeT=false,true --64bit-VertexT=false,true --idempotence=false,true --mark-pred=false,true --direction-optimized=true,false --advance-mode=LB_CULL,LB,TWC --undirected=true > ./eval/GUNROCK_v1-0-0_TitanXp/ak2010.UDIR.txt
[../../gunrock/util/test_utils.cu, 59 @ gpu 0] cudaSetDevice failed. (CUDA error 101: invalid device ordinal)
[@ gpu 0] (CUDA error 101: invalid device ordinal)
```
Can I manually change the CC version in the makefile? Or there is a logic behind that? 
```

**Comment by jowens** [comment]
If you wanted to edit the build command manually to generate 61, you can certainly do that. Much easier is to use cmake capabilities when you generate the build directory (and Makefiles):

https://gunrock.github.io/docs/#building-gunrock

specifically `GUNROCK_GENCODE_SM61`:

`cmake -DGUNROCK_GENCODE_SM61=ON`

**Comment by mahmoodn** [comment]
Yes I did that while running `mkdir build && cd build/ && cmake -DGUNROCK_GENCODE_SM61=ON ..`
However, when I go to `examples/bfs` and run `make`, I see `-gencode=arch=compute_70,code=\"sm_70,compute_70\"`

**Comment by jowens** [comment]
Oh! Well, that's a problem, then. Gotta drag @neoblizz into this one.

**Comment by neoblizz** [comment]
Individual makefiles in the examples folder are unrelated to the cmake builds. Cmake wi generate it's own makefiles. 

The individual makefiles exist for you to only build that specific application by running make in that directory. 

For cmake, what John suggested is the way to go. If it didn't work, try removing the build directory, which clears the cmake cache and doing the command again.

**Comment by neoblizz** [comment]
You can also edit this line directly in the cmake file: https://github.com/gunrock/gunrock/blob/eae431099e003e8eb5f7600bfa43514fc0ac2404/CMakeLists.txt#L263 and build again.

**Comment by neoblizz** [comment]
I am assuming this is resolved?
