### ISSUE TITLE
Replace moderngpu with CUB

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#593]
@neoblizz helpfully found all mgpu instances. CUB is likely better supported going forward.

```
./gunrock/app/enactor_types.cuh:238:  mgpu::ContextPtr context;
./gunrock/app/enactor_types.cuh:269:      context = mgpu::CreateCudaDeviceAttachStream(gpu_idx, stream);
./gunrock/oprtr/LB_CULL_advance/kernel.cuh:1096:    mgpu::SortedSearch<mgpu::MgpuBoundsLower>(
./gunrock/oprtr/advance/advance_base.cuh:181:  mgpu::Scan<mgpu::MgpuScanTypeInc>(
./gunrock/oprtr/advance/advance_base.cuh:184:      (SizeT)0, mgpu::plus<SizeT>(),
./gunrock/oprtr/advance/kernel.cuh:103:(Value)0, mgpu::plus<typename KernelPolicy::Value>(), context); break;
./gunrock/oprtr/advance/kernel.cuh:108:(Value)1, mgpu::multiplies<typename KernelPolicy::Value>(), context); break;
./gunrock/oprtr/advance/kernel.cuh:113:(Value)INT_MIN, mgpu::maximum<typename KernelPolicy::Value>(), context); break;
./gunrock/oprtr/advance/kernel.cuh:118:(Value)INT_MAX, mgpu::minimum<typename KernelPolicy::Value>(), context); break;
./gunrock/oprtr/advance/kernel.cuh:124:(Value)0, mgpu::plus<typename KernelPolicy::Value>(), context); break;
./gunrock/oprtr/advance/kernel.cuh:224: * @tparam Op Operation for gather reduce. mgpu::plus<int> by default.
./gunrock/oprtr/filter/kernel.cuh:208:    Scan<mgpu::MgpuScanTypeExc>(
./gunrock/oprtr/filter/kernel.cuh:210:        mgpu::plus<SizeT>(), (SizeT *)NULL, (SizeT *)NULL,
./gunrock/oprtr/oprtr_parameters.cuh:48:  mgpu::ContextPtr context;
./gunrock/oprtr/LB_advance/kernel.cuh:564:    mgpu::SortedSearch<mgpu::MgpuBoundsLower>(
./gunrock/oprtr/LB_advance/kernel.cuh:600:  (Value)0, mgpu::plus<typename KernelPolicy::Value>(), context); break;
./gunrock/oprtr/LB_advance/kernel.cuh:605:  (Value)1, mgpu::multiplies<typename KernelPolicy::Value>(), context); break;
./gunrock/oprtr/LB_advance/kernel.cuh:610:  (Value)INT_MIN, mgpu::maximum<typename KernelPolicy::Value>(), context);
./gunrock/oprtr/LB_advance/kernel.cuh:616:  (Value)INT_MAX, mgpu::minimum<typename KernelPolicy::Value>(), context);
./gunrock/oprtr/LB_advance/kernel.cuh:623:  (Value)0, mgpu::plus<typename KernelPolicy::Value>(), context); break;
./gunrock/util/sort_device.cuh:189:    mgpu::CudaContext &context,
./gunrock/util/sort_device.cuh:201:      mgpu::SegSortPairsFromIndices(
./gunrock/util/sort_device.cuh:211:      mgpu::SegSortKeysFromIndices(
```

**Comment by neoblizz** [comment]
Here's what needs to be replaced to CUB exactly, everything else is either replaced already or just mgpu context support.

https://github.com/gunrock/gunrock/blob/master/gunrock/oprtr/LB_advance/kernel.cuh#L564-L570

https://github.com/gunrock/gunrock/blob/master/gunrock/oprtr/advance/advance_base.cuh#L181-L188

https://github.com/gunrock/gunrock/blob/master/gunrock/oprtr/LB_CULL_advance/kernel.cuh#L1096-L1102

**Comment by yzhwang** [comment]
I see currently we use moderngpu for two primitives: SortedSearch and Scan, where Scan has its equivalent implementation in CUB, but SortedSearch does not. SortedSearch is based on merge-path, which is not implemented in CUB either. So we have two choices to fully remove the dependency of moderngpu: 1) implement a minimal version of merge-path based SortedSearch ourselves; 2) add one to CUB. Seems that 1) would be easier if we want to use SortedSearch without moderngpu at all. I'm interested and want to give it a try. Assign myself first as switching to CUB for Scan is easy. Can work on the moderngpu one next month.

**Comment by jowens** [comment]
Awesome!

We talked to the Thrust team on this (hoping they'd implement it, but no dice):

> We have no plans for this right now, but are open to pull requests for this.

**Comment by jowens** [comment]
@yzhwang Checkin' in on `SortedSearch`. 新年好!

**Comment by yzhwang** [comment]
Happy New Year John! This issue is pending now. I am doing other stuff such as learning multi-GPU Gunrock as well as adding hdfs/csv file support. (There are a couple more changes I committed internally but will submit as PR(s) once everything works fine.
I am go through a bunch of basic GPU primitive implementations and is doing benchmarks (I have some posts for the future book plan I told you before, I will send you the links in a separate email). I still think a handcrafted sorted search is the easiest way but alas, I wish I had more time. Current estimation is that I will have time to start working on this from middle to late January. I will update this thread then.

**Comment by neoblizz** [comment]
Nearly entirely removed in `gunrock/essentials`. I just use the `transform_lb` for merge-path load balancing. But this can be removed as well in near future. I am closing this issue right now as it is not as impactful for future releases.
