### ISSUE TITLE
Page Rank Nibble Implementation

### ISSUE THREAD

**Issue by ajaleel1** [gunrock/gunrock#596]
**Feature Description:**
A clear and concise description of the feature you are requesting and the problem it solves.

When I was comparing the Gunrock implemention, it looks like the algorithm implemented in Gunrock seems to differ from the version I have been working with (Figure 5 in [1]).  Below is a C++ version of the code:

[1] https://arxiv.org/pdf/1604.07515.pdf

![pr_src](https://user-images.githubusercontent.com/53351499/64725805-573ec500-d4a3-11e9-8fdc-289639cdf2e3.png)

What algorithm are you using?  Also, how difficult would it be to modify the Gunrock implementation to follow the algorithm attached?

**Describe the solution you'd like**

**Comment by ajaleel1** [comment]
Just pinging again on this.

From: Aamer Jaleel
Sent: Thursday, September 12, 2019 10:26 PM
To: gunrock/gunrock <reply@reply.github.com>; gunrock/gunrock <gunrock@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [gunrock/gunrock] Page Rank Nibble Implementation (#596)

Hi Ben,

Thank you for getting back to me.  How easy would it be to morph your PRN version to the reference I provided?

Thanks

**Comment by jowens** [comment]
@ajaleel1 Ben told you exactly where his implementation came from. We documented what we did so that others could take our implementations and change them to meet their needs. I would imagine that it's probably one of the easier Gunrock programming tasks to take an existing pr_nibble implementation and change it to a different formulation.

**Comment by ajaleel1** [comment]
That’s good to know.  I didn’t want to go down a path if there were any foreseeable issues with the algorithm that I pointed to.

Will let you know based on progress that I make on my front.

**Comment by jowens** [comment]
My quick glance at the sample code you provided makes me think there shouldn't be any significant issues. I haven't gone through the pr_nibble code, but what you want to implement ought to map to Gunrock well.

**Comment by ajaleel1** [comment]
Hi,

I’ve started the implementation and was wondering if I could pick some Gunrock developers brain on whether the approach I’m taking is the right now.

I’ve successfully integrated the C++ implementation into the Gunrock framework and have also started using the existing pr_nibble implementation framework to kickstart the implementation I’m interested in.

Looking at the C++ source below, and mapping them onto GunRock operators, here is what I’m thinking:

The first for loop is implemented using the Compute operator
The second for loop is implemented using the Advance Operator
The third for loop is using the Filter operator (to generate the new frontier).

This repeats itself until the Filter operator returns an empty frontier.

I was going to start off by writing the above, but before doing so, was wondering if the experts verify that I’m on the right track?

Thanks,
  Aamer

[cid:image003.jpg@01D5720A.E99C9450]

From: Aamer Jaleel
Sent: Wednesday, September 18, 2019 3:03 PM
To: gunrock/gunrock <reply@reply.github.com>; gunrock/gunrock <gunrock@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [gunrock/gunrock] Page Rank Nibble Implementation (#596)

That’s good to know.  I didn’t want to go down a path if there were any foreseeable issues with the algorithm that I pointed to.

Will let you know based on progress that I make on my front.

**Comment by bkj** [comment]
Yes -- I think your approach sounds correct.  Let us know if you have more questions!

**Comment by jowens** [comment]
Thank you @bkj !

**Comment by ajaleel1** [comment]
Hi John,

If possible, I’d like a short discussion with somebody on the GunRock interface side to help answer a few questions.


Who would be a good person?

Thanks
  Aamer
