### ISSUE TITLE
Memory usage for large graphs

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#601]
I would like to know more information about how gunrock uses device memory. I mean what is loaded into the memory after printing the degree histogram?

Is there any possibility to use host memory in conjunction with the device memory in order to handle large memory usage? In short, I want to know if gunrock can run a 6GB graph on a 4GB GPU device.

**Comment by jowens** [comment]
We've never tried this. I would expect it to run poorly and be completely dominated by CPU-GPU traffic as graph data, which has little locality, is paged back and forth.

**Comment by mahmoodn** [comment]
OK thanks.

**Comment by jowens** [comment]
http://netsyslab.ece.ubc.ca/wiki/index.php/Totem  <- might be interesting for you, definitely targets your use case
