### ISSUE TITLE
Add paper reference or wikipedia reference for each app in Gunrock

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#607]
**Feature Description:**
Could we add in the comment, for each app we have in Gunrock, the source of the original 
 algorithm, be it a wikipedia page, or an arxiv paper (or any link which is not behind a paywall)?

Since now we are having more and more apps, a lot of them go beyond the scope of text-style graph algorithms, which we can easily recognize without any reference. Plus, with the abbreviation as directory name, one is very difficult to tell what the algorithm is about.

**Comment by jowens** [comment]
@yzhwang I have that info for you if you want it (for the HIVE apps). Good thing to put in the docs though.

**Comment by neoblizz** [comment]
Also https://gunrock.github.io/docs/#gunrock-39-s-application-cases, we can add references to the table as well.

**Comment by yzhwang** [comment]
Thanks guys! I somehow missed that table. The info there is useful and good enough. Close the issue now.
