### ISSUE TITLE
PageRank illegal memory access when using rmat generator

### ISSUE THREAD

**Issue by porumbes** [gunrock/gunrock#615]
**Summary:**
CUDA error 77: an illegal memory access was encountered.

**Reproducibility:**
Always

**To Reproduce:**
/path/to/pr/binary rmat

or 

/path/to/pr/binary rmat --grmat true

**Expected Behavior:**
Generate pr result.

**Actual Results:**
Illegal memory access error.

**System Configuration:**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GV100        On   | 00000000:18:00.0 Off |                  Off |
| 29%   27C    P2    36W / 250W |     11MiB / 32478MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro GV100        On   | 00000000:3B:00.0 Off |                  Off |
| 29%   28C    P2    37W / 250W |     11MiB / 32478MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   25C    P0    24W / 250W |     11MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
CPU: Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz
OS: Ubuntu 18.04.1 LTS
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by porumbes** [comment]
I ran a some initial checks and there seems to be an out of bounds memory access during a foreach at gunrock/oprtr/1D_oprtr/for_each.cuh (line 104). Unfortunately, the app runs to completion with the debugger connected.

**Comment by neoblizz** [comment]
It's whatever is calling that for_each that is causing the bug. I couldn't get backtrace to tell me what it is.

**Comment by porumbes** [comment]
@neoblizz ditto, I had the same issue and couldn't actually get a backtrace. Dropping various breadcrumbs to hone in on the problem.

**Comment by porumbes** [comment]
pr is unlikely to be the cause of the problem, but here's a bit of a trace to what triggers the issue.

pr_test.cuh Compensate_ZeroDegrees, line 146 
`GUARD_CU(graph.FromCoo(new_coo, util::LOCATION_DEFAULT, 0, quiet));`

app_base.cuh line 93 
`if (!self_coo) GUARD_CU(this->CooT::FromCoo(coo, target, stream, quiet));`

**Comment by neoblizz** [comment]
@maawad mentioned an inherent problem with the generator that may be leading to this (@maawad do you have any insights on this?)

**Comment by maawad** [comment]
I didn't really look into it. I exported the rmat output and used it as an input market file, that worked for me.

**Comment by porumbes** [comment]
Just a quick note, you can workaround the problem by running with `--compensate=false`

**Comment by sgpyc** [comment]
The “Compensate_ZeroDegrees” method is not an algorithm, but more like how to deal with vanishing ranking values from the 0-out-degree vertices. Considering PR as a flow problem, the sum of all ranking values of vertices should stay the same, (in the case of normalized PR, the sum is 1). But for 0-out-degree vertices, ranking values escape. So to compensate this, one extra vertex is added to have in edges from all 0-out-degree vertices, and out edges to all vertices. The graph is modified using the coo format (it will fail if the graph is not available in coo format).
