### ISSUE TITLE
ForEach_Kernel source

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#620]
While profiling a graph, I see the following kernel
```
void gunrock::oprtr::ForEach_Kernel<gunrock::util::Array1D<unsigned int, unsigned int, 0u, 0u>, 
unsigned int, gunrock::app::bfs::Problem<gunrock::app::TestGraph<unsigned int, unsigned int, 
unsigned int, 768u, 0u>, unsigned int, unsigned int, 0u>::DataSlice::Reset(unsigned int, unsigned
 int)::{lambda(unsigned int&)#1}>(gunrock::util::Array1D<unsigned int, unsigned int, 0u, 0u>,
 gunrock::app::bfs::Problem<gunrock::app::TestGraph<unsigned int, unsigned int, unsigned int,
 768u, 0u>, unsigned int, unsigned int, 0u>::DataSlice::Reset(unsigned int, unsigned int)::
{lambda(unsigned int&)#1}, unsigned int)
```

I see more than one instance of  `ForEach_Kernel` in `gunrock/oprtr/1D_oprtr/for_each.cuh`. Some are comment though. I would like to know, which one matches that? Also, may I ask what is the main purpose of this kernel? Since it has taken most of the GPU time compared to other kernels.

**Comment by neoblizz** [comment]
Hi, this is under the BFS problem file. It is not actually timed in the computation of the algorithm. You can think of this as setting up the problem for the algorithm: https://github.com/gunrock/gunrock/blob/master/gunrock/app/bfs/bfs_problem.cuh

**Comment by mahmoodn** [comment]
Yes I used BFS binary. But it takes about half of the GPU time. I mean it affects the performance. The kernel is invoked 1 time and takes the most time compared to others.

**Comment by neoblizz** [comment]
Right. It is part of the overall load time setting things to Invalid: https://github.com/gunrock/gunrock/blob/master/gunrock/app/bfs/bfs_problem.cuh#L227-L249 You may be able to improve this by using cudamemset, but I don't think this is significant to the algorithm at all. We don't put any effort optimizing for the load-time. @jowens can comment on how performance numbers are reported for GPU algorithms.

**Comment by jowens** [comment]
We have tried to write this up here:

https://gunrock.github.io/docs/#methodology

If anything is unclear there or you want more detail/clarification, we can update.

**Comment by mahmoodn** [comment]
OK thank you.
