### ISSUE TITLE
Support `--remote` when initializing submodules

### ISSUE THREAD

**Issue by afender** [gunrock/gunrock#622]
**Problem**
Using `--remote` will result in grabbing the `master` branch of moderngpu while gunrock supports `branch_1.1`. There might be others submodules that have this issue.

Notice that RAPIDS currently uses `git submodule update --init --recursive --remote`

**Solution**
This is an easy fix. Just tell git what branch you are using for your submodules and make sure gunrock is compatible with the latest version of that branch. 
There are a couple of ways to do that: https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule

**Comment by jowens** [comment]
Can you change `.gitmodules` to point to moderngpu `branch_1.1` and tell us if that works?

**Comment by neoblizz** [comment]
Commit 5ffbae648ab8e544d3bde8ebbce2c8e1ab2d1c06 fixes this issue, you can see from the log below that correct commit is being fetched for moderngpu: `Submodule path 'externals/moderngpu': checked out '5029d38cab83492d8091cce5902c077ab3ca72a9'`


```
mosama@daisy:~/Temp/gunrock (master)$ git submodule update --init --recursive --remote
Submodule 'docs' (https://github.com/gunrock/docs.git) registered for path 'docs'
Submodule 'externals/cub' (https://github.com/NVlabs/cub.git) registered for path 'externals/cub'
Submodule 'externals/moderngpu' (https://github.com/NVlabs/moderngpu.git) registered for path 'externals/moderngpu'
Submodule 'externals/rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'externals/rapidjson'
Cloning into '/home/mosama/Temp/gunrock/docs'...
Cloning into '/home/mosama/Temp/gunrock/externals/cub'...
Cloning into '/home/mosama/Temp/gunrock/externals/moderngpu'...
Cloning into '/home/mosama/Temp/gunrock/externals/rapidjson'...
Submodule path 'docs': checked out '5c7afd2ba79a10cdfc5bb9c0ae15b8b2a4bfd660'
Submodule path 'externals/cub': checked out '135da60fefd3938144dff20e0e45d07070287a61'
Submodule path 'externals/moderngpu': checked out '5029d38cab83492d8091cce5902c077ab3ca72a9'
Submodule path 'externals/rapidjson': checked out '6a6bed2759d42891f9e29a37b21315d3192890ed'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'externals/rapidjson/thirdparty/gtest'
Cloning into '/home/mosama/Temp/gunrock/externals/rapidjson/thirdparty/gtest'...
Submodule path 'externals/rapidjson/thirdparty/gtest': checked out 'ba513d2c9525a7c986c115ed5d603f2cf17c6016'
```
