### ISSUE TITLE
Need cublas?

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#624]
Is cublas mandatory?
```
[  4%] Building NVCC intermediate link file gunrock/CMakeFiles/gunrock.dir/gunrock_intermediate_link.o
nvcc fatal   : Don't know what to do with 'CUDA_cublas_device_LIBRARY-NOTFOUND'
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/gunrock_intermediate_link.o] Error 1
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
```
cmake didn't complain about that.

**Comment by neoblizz** [comment]
No, not at all. It could be your system settings of cuda messing up there. The error is due to nvcc. Make sure you have the right version of nvcc.

**Comment by mahmoodn** [comment]
OK it seems that things are messy.
Can you please say how to give gunrock a custom gcc path and not the system installation?

**Comment by jowens** [comment]
https://gitlab.kitware.com/cmake/community/wikis/FAQ#how-do-i-use-a-different-compiler
