### ISSUE TITLE
Relax kernels for LB

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#626]
I would like to know what is the difference between `./oprtr/LB_advance/kernel.cuh:RelaxPartitionedEdges2<>` and `./oprtr/LB_CULL_advance/kernel.cuh:RelaxPartitionedEdges2<>`?
Also, may I know what the algorithm that this kernel is trying to do?

The same question is for `RelaxLightEdges` in those two paths. I know these are related to Load Balancing, but I would like to know its original description and method.

**Comment by mahmoodn** [comment]
Are these related to Section 4.4 in the [paper](https://arxiv.org/pdf/1501.05387.pdf)?

**Comment by neoblizz** [comment]
@mahmoodn yes, that section alone would answer a lot of your questions. The difference between the two kernels is that one does `advance` using the LB strategy (prefix-sum), and the other does `advance` and `filter` (CULL) in the same kernel as an optimization called kernel fusion (section 4.3 in the paper).

**Comment by sgpyc** [comment]
As @neoblizz said, the difference between LB & LB_CULL is that LB_CULL is a fused implementation of advance (LB) and filter (CULL).

The difference between the RelaxPartitionedEdges kernels and the RelaxLightEdges is that, RelaxPartitionedEdges uses a two level binary search to find perfect output balance across blocks and threads (this is for large output frontiers), and RelaxLightEdges takes in a block of fixed size input vertices for a block then balance the workload between threads (this is for small output frontiers)

**Comment by mahmoodn** [comment]
Thanks. I will provide more detail on the question soon.
