### ISSUE TITLE
PageRank problem

### ISSUE THREAD

**Issue by OsipovMax** [gunrock/gunrock#629]
**Summary:**
1. If I run a PageRank test with an RMAT graph type and also specify a graph-scale parameter value greater than 5, I get "CUDA error 77: an illegal memory access was encountered".
2. If I specify the graph-edgefactor parameter, I also get "CUDA error 77: an illegal memory access was encountered".
But if I don't specify the graph-edgefactor parameter and the graph-scale parameter value is less than 6, then everything works fine in this case.

P.S. On other tests, there is no such problem.

**Reproducibility:**
Always

**To Reproduce:**
сlone gunrock
mkdir build && cd build
cmake ..
make pr
cd bin
./pr --graph-scale 20 --graph-type rmat --graph-edgefactor 32

**Expected Behavior:**
Generate pr result.

**Actual Results:**
CUDA error 77: an illegal memory access was encountered.

**System Configuration:**
GPU: NVIDIA Tesla P100
Driver Version: 418.40.04
CUDA Version: 10.1

**Comment by neoblizz** [comment]
Related to #615
