### ISSUE TITLE
Couldn't compile with ENABLE_PERFORMANCE_PROFILING flag

### ISSUE THREAD

**Issue by YuxinxinChen** [gunrock/gunrock#630]
**Summary:**
I am trying to compile Gunrock with the ENABLE_PERFORMANCE_PROFILING flag to produce some profiling data. 

**Reproducibility:**
I am using the master branch. I start with:
``
mkdir build & cd build
cmake -DENABLE_PERFORMANCE_PROFILING=ON -DGUNROCK_BUILD_APPLICATIONS=OFF -DGUNROCK_APP_BFS=ON -DGUNROCK_APP_PR=ON ..
``

However, I got warning when I do cmake:
``
Manually-specified variables were not used by the project:
   ENABLE_PERFORMANCE_PROFILING
``
Somehow cmake is not recognizing it. 
When I compile the code with ``make ``
I got the compilation errors:
``
error: identifier "Display_Performance_Profiling" is undefined
``

**System Configuration:**
Daisy: Nvidia v100 
CUDA: V10.0.130

**Comment by yzhwang** [comment]
I don't think ENABLE_PERFORMANCE_PROFILING is a cmake defined flag (like other flags you used there). Current head seems to have defined this:
https://github.com/gunrock/gunrock/blob/master/gunrock/app/enactor_types.cuh#L31
But just disabled its actual function in the code:
https://github.com/gunrock/gunrock/blob/master/gunrock/app/bfs/bfs_app.cu#L134

Easy way to fix is to uncomment those lines between #ifdef ENABLE_PERFORMANCE_PROFILING and #endif 

Also, changed the label to fit the topic better.

**Comment by YuxinxinChen** [comment]
Tried what @yzhwang suggested:
uncomment line https://github.com/gunrock/gunrock/blob/master/gunrock/app/bfs/bfs_app.cu#L134
```
mkdir build & cd build
cmake .. 
make  
```
Got this error: 
```
error: identifier "Display_Performance_Profiling" is undefined
```
So I tried to add the header file by:
```
#include <gunrock/util/shared_utils.cuh>
```
Also changed the Display_Performance_Profiling call to 
```
Display_Performance_Profiling(&enactor);
```
Got this error:
```
error: class "gunrock::app::bfs::Enactor<gunrock::app::bfs::Problem<gunrock::app::TestGraph<uint32_t, uint32_t, uint32_t, 768U, 0U>, uint32_t, uint32_t, 0U>, 0U, 0U>" has no member "enactor_stats"
```

I guess many gunrock API has changed but display_performance_profiling hasn't been updated. 
Maybe I should @maawad , to provide above information.

**Comment by YuxinxinChen** [comment]
Finally the profiling tools seem to work on v0.5.1
Also uncomment this line: https://github.com/gunrock/gunrock/blob/v0.5.1/gunrock/app/enactor_types.cuh#L25

Now I have tried running profiling tools on hollywood_2009 dataset and got these results:
```
Performance profiling log begins
Iter	 GPU	 Item	 Per-iter readings
0	 0	 Sub queue time	 0.031948 0.007153 0.006914 0.005960 0.005960 0.007868 0.006914 0.005960 0.003815 0.005960 0.005007
0	 0	 Fu-queue nodes	 1 4 23 1249 110694 752777 194415 9482 461 19 1
0	 0	 Fu-queue edges	 4 39 2128 656914 52557063 56516753 2821596 55618 3140 50 1
0	 0	 Fu-queue time	 0.169039 0.095844 0.083923 0.179052 3.576994 4.565001 0.287056 0.101089 0.087023 0.086069 0.082970
0	 0	 Other time	 0.002861 0.002146 0.002146 0.000954 0.004053 0.001192 0.000954 0.000000 0.002146 0.000954 0.000000
0	 0	 Iteration time	 0.203848 0.105143 0.092983 0.185966 3.587008 4.574060 0.294924 0.107050 0.092983 0.092983 0.087976
0	 0	 Out length 0	 4 23 1249 110694 752777 194415 9482 461 19 1 0

Performance profiling log ended
```

Thank you very much @yzhwang  You are a lifesaver!

**Comment by yzhwang** [comment]
What is Fu-queue? (should be full-queue right?) I also noticed a couple of 'neibor' exist in the code.  @neoblizz consider doing a global code clean to get rid of these embarrassing names? I could do it but I do not know how many more of these exist. I think change like this should be in one commit.

**Comment by neoblizz** [comment]
@yzhwang Idk if I will be willing to spend time to clean-up 0.5.x API, if anything we should enable this functionality in v1.x and have proper names with it.

**Comment by yzhwang** [comment]
'neibor's are in v1.x too :-) anyway, just a suggestion. Of course do not put it high up on the to-do list.

**Comment by neoblizz** [comment]
Yeah, definitely worth doing a pass-through for v1.x! Would love it if you can spend some time on it, and whatever is left I can do a pass-through to clear others.
