### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by LuciaRan** [gunrock/gunrock#631]
### some errors occur when I tried to compile.
I follow the guide,and do like

1. git clone --recursive https://github.com/gunrock/gunrock/
2. cd gunrock
3. mkdir build && cd build
4. cmake .. 
5. make 

### environment
NVIDIA-SMI 418.87.00    
Driver Version: 418.87.00    
CUDA Version: 10.1 
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

**but some errors occur  during "make"**

/home/dbci/qsy/gunrock/gunrock/util/device_intrinsics.cuh(194): error: no instance of overloaded function "atomicMin" matches the argument list
            argument types are: (unsigned long long *, unsigned long long)

/home/dbci/qsy/gunrock/gunrock/oprtr/CULL_filter/kernel.cuh(205): error: class "gunrock::oprtr::CULL::Dispatch<1U, int, int, int, float, int, lambda [](const int &, int &, const int &, const int &, const int &, int &)->__nv_bool, false>" has no member "Kernel"
          detected during:
            instantiation of "void gunrock::oprtr::CULL::Kernel<FLAG,InKeyT,OutKeyT,SizeT,ValueT,LabelT,FilterOpT>(__nv_bool, SizeT, const InKeyT *, const ValueT *, SizeT, LabelT, LabelT *, unsigned char *, OutKeyT *, gunrock::util::CtaWorkProgress<SizeT>, FilterOpT) [with FLAG=1U, InKeyT=int, OutKeyT=int, SizeT=int, ValueT=float, LabelT=int, FilterOpT=lambda [](const int &, int &, const int &, const int &, const int &, int &)->__nv_bool]" 
(249): here

/home/dbci/qsy/gunrock/gunrock/oprtr/BP_filter/kernel.cuh(103): error: class "gunrock::oprtr::BP::Dispatch<1U, int, int, int, false>" has no member "Kernel"

/home/dbci/qsy/gunrock/gunrock/oprtr/LB_advance/kernel.cuh(442): error: class "gunrock::oprtr::LB::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, false>" has no member "RelaxLightEdges"

/home/dbci/qsy/gunrock/gunrock/oprtr/LB_CULL_advance/kernel.cuh(913): error: class "gunrock::oprtr::LB_CULL::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, float, int, false>" has no member "RelaxLightEdges"

/home/dbci/qsy/gunrock/gunrock/oprtr/LB_CULL_advance/kernel.cuh(859): error: class "gunrock::oprtr::LB_CULL::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, float, int, false>" has no member "RelaxPartitionedEdges2"

/home/dbci/qsy/gunrock/gunrock/oprtr/TWC_advance/kernel.cuh(212): error: class "gunrock::oprtr::TWC::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, false>" has no member "Kernel"

/home/dbci/qsy/gunrock/gunrock/oprtr/AE_advance/kernel.cuh(230): error: class "gunrock::oprtr::AE::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, false>" has no member "Advance_Edges"

/home/dbci/qsy/gunrock/gunrock/oprtr/LB_advance/kernel.cuh(442): error: class "gunrock::oprtr::LB::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, false>" has no member "RelaxLightEdges"

/home/dbci/qsy/gunrock/gunrock/oprtr/LB_advance/kernel.cuh(391): error: class "gunrock::oprtr::LB::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, false>" has no member "RelaxPartitionedEdges2"

/home/dbci/qsy/gunrock/gunrock/oprtr/LB_CULL_advance/kernel.cuh(913): error: class "gunrock::oprtr::LB_CULL::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, float, int, false>" has no member "RelaxLightEdges"

/home/dbci/qsy/gunrock/gunrock/oprtr/LB_CULL_advance/kernel.cuh(859): error: class "gunrock::oprtr::LB_CULL::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, float, int, false>" has no member "RelaxPartitionedEdges2"

/home/dbci/qsy/gunrock/gunrock/oprtr/AE_advance/kernel.cuh(230): error: class "gunrock::oprtr::AE::Dispatch<33554449U, gunrock::graph::Csc<int, int, float, 512U, 0U, true>, int, int, false>" has no member "Advance_Edges"

16 errors detected in the compilation of "/tmp/tmpxft_000054ca_00000000-7_pr_app.cpp1.ii".
CMake Error at gunrock_generated_pr_app.cu.o.cmake:279 (message):
  Error generating file
  /home/dbci/qsy/gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/pr/./gunrock_generated_pr_app.cu.o

make[2]: *** [gunrock/CMakeFiles/gunrock.dir/app/pr/gunrock_generated_pr_app.cu.o] Error 1
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
make: *** [all] Error 2

### and some warings 
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/dbci/qsy/gunrock/gunrock/util/device_intrinsics.cuh(105): warning: missing return statement at end of non-void function "_ballot"

/home/dbci/qsy/gunrock/gunrock/util/device_intrinsics.cuh(116): warning: missing return statement at end of non-void function "_any"

/home/dbci/qsy/gunrock/gunrock/util/device_intrinsics.cuh(127): warning: missing return statement at end of non-void function "_all"

### CMake infomation as follows
dbci@node25:~/qsy/gunrock/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "7.5") 
-- Boost version: 1.58.0
-- Boost version: 1.58.0
-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Found OpenMP
-- Found rapidjson header files in /home/dbci/qsy/gunrock/externals/rapidjson/include
-- Project Added: bc
-- Project Added: bfs
-- Project Added: color
-- Project Added: geo
-- Project Added: hits
-- Project Added: knn
-- Project Added: louvain
-- Project Added: pr
-- Project Added: pr_nibble
-- Project Added: proj
-- Project Added: rw
-- Project Added: sage
-- Project Added: sm
-- Project Added: ss
-- Project Added: sssp
-- Project Added: tc
-- Project Added: vn
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dbci/qsy/gunrock/build

**Comment by neoblizz** [comment]
What kind of GPU do you have? Seems like you are building for SM 20 and 21, which is really old:
```
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
```

**Comment by neoblizz** [comment]
Make sure in your bashrc, you export the latest CUDA path 10.1, cmake still
sees you are using CUDA 8. That may be an issue.

**Comment by LuciaRan** [comment]
I update CUDA to 10.1 and CMAKE to 3.14, and everything is ok now. Thank you very much!
