### ISSUE TITLE
Reading .edges format

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#632]
Maybe the question is not directly related to gunrock, but I would like to know if there is any way to convert `.edges` format to `.mtx`? Or gunrock is able to read edges format?
It seems that the first like of mtx which is a summary of the graph is the difference between these two formats.

**Comment by jowens** [comment]
What are you asking? I don't think we have any experience with `.edges` format at all.

**Comment by mahmoodn** [comment]
OK. I thought you have run gunrock with graphs in http://networkrepository.com
Anyway...

**Comment by jowens** [comment]
Everything we've run has been .mtx.
