### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by limin2015** [gunrock/gunrock#636]
**Summary:**

I encounter some error after "make" commond:
***/gunrock-old2/examples/bfs/test_bfs.cu:76:108: error: no matching function for call to ‘CPU_Reference(GraphT&, long unsigned int&, bool&, bool, LabelT*&, NULL, long unsigned int&)’
         float elapsed = app::bfs::CPU_Reference(graph, src, quiet, false,

**To Reproduce:**

git clone --recursive https://github.com/gunrock/gunrock;
mkdir build &&cd build;
cmake -DGUNROCK_GOOGLE_TESTS=OFF -DGUNROCK_GENCODE_SM60=ON  -DGUNROCK_MGPU_TESTS=OFF -DGUNROCK_BUILD_APPLICATIONS=OFF -DGUNROCK_APP_BFS=ON -DGUNROCK_APP_PR=ON ..;
make

**System Configuration:**

GPU: Tesla P100
CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
OS: Ubuntu 18.04.1 LTS
CUDA Version: 9.0
gcc: gcc 4.8.5

**Comment by neoblizz** [comment]
@limin2015 per CUDA's guide, Ubuntu 18.04's gcc requirement is 7.4.0, and you are using 4.8.5. https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by limin2015** [comment]
I use another system configuration with cuda 9.0, gcc 4.8.5 on Red Hat 7.3 as suggested in https://docs.nvidia.com/cuda/archive/9.0/cuda-installation-guide-linux/index.html, but the same error still occurs. Do you know why?

The New System Configuration:
GPU: Tesla P100
CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
OS: Red Hat Enterprise Linux Server" VERSION="7.3 (Maipo)"
CUDA Version: 9.0
gcc: gcc 4.8.5

**Comment by neoblizz** [comment]
Yes, it's to do with C++ pointers getting handled differently in 4.8.5 I believe. @mahmoodn was fixing these for his build: https://github.com/gunrock/gunrock/issues/633, I would love for him to do a pullrequest on this so I we can fix it.

I plan to add the right cast for all pointers in the near future as well.

**Comment by limin2015** [comment]
Thanks for your help. I have another questions,  can you help me? 

1. As shown in https://docs.nvidia.com/cuda/archive/9.0/cuda-installation-guide-linux/index.html,
for ReadHat 7.3, the Native Linux Distribution Support in CUDA 9.0 is gcc 4.8.5, can I use gcc version newer than 4.8.5? 
For example, I tried with gcc 7.2.0 and got an error like this: 
nvcc error   : 'cicc' died due to signal 7 (Bus error). 
What do you think of this problem？

2. As shown in https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html,
for cuda10.1, it only shows supports for RHEL 8.0 (gcc 8.2.1), RHEL 7.6 (gcc 4.8.5), RHEL 6.10 (gcc 4.4.7), how about my RHEL 7.3? 

Thank you a lot!

**Comment by jowens** [comment]
Our experience is "use the OSes and compilers exactly as listed in the CUDA installation guide or you're going to have a real bad time". We have found that CUDA (not just Gunrock, but all of CUDA) works only with the exact compiler versions they specify. (It takes a LOT of work for NVIDIA to get a particular compiler working with CUDA. Other compiler versions simply aren't going to work.)

**Comment by limin2015** [comment]
I got that. Thanks a lot!

**Comment by limin2015** [comment]
I have solved my build problem (cuda9.0, gcc4.8.5, RedHat 7.3) by using the method from #633 by @mahmoodn. Thanks a lot!
