### ISSUE TITLE
Generate bfs tree with parent information for every vertex rather than level array

### ISSUE THREAD

**Issue by ranjanan** [gunrock/gunrock#64]
Hello,
I was wondering how I could use gunrock to generate a bfs tree that starts from `src` (input) and gives me the parent id for every vertex, instead of the levels that the bfs() function in `libgunrock.so` returns right now. The result should be an array which, at every position, contains the id of the immediate predecessor in the bfs tree. 

Just to be clear: the `src`'s parent id is `src` itself, whereas at all its neighbour's positions, the value is `src`. Then we take the first neighbour, let's call it `a`. All `a`'s neighbours will have `a` at their positions in the parent array, and so on.

**Comment by ydwu** [comment]
There's a **MARK_PREDECESSOR** flag: `[--mark-pred] Keep both label info and predecessor info.` (But we defined `src`'s parents id is `-1`).

**Comment by yzhwang** [comment]
Thanks @ydwu ! @ranjanan Let us know if adding this flag works. Note that for nodes with multiple parents, our algorithm doesn't guarantee that it will always find the parent with the smallest node ID.

**Comment by ranjanan** [comment]
Could I just change mark_predecessors = true here:
https://github.com/gunrock/gunrock/blob/master/gunrock/app/bfs/bfs_app.cu#L511
and rebuild the .so file?

**Comment by yzhwang** [comment]
@ydwu So it seems that our bfs_app hard coded the mark predecessor and idempotent option to be both false? How should we change that? Just tell me your thought and I can fix it.
@ranjanan Yes I think your method would work (but it's not ideal since there is no way to set those two flags in command line, which is not good). We will fix this asap.

**Comment by ranjanan** [comment]
@yzhwang I tried doing that, and it didn't work for me. The function still returned the distance from `src`.

**Comment by ranjanan** [comment]
@yzhwang @ydwu Oh hey, it turns out that I need to return `grapho->node_value2` instead of `node_value1` and I get what I need. Thanks!

**Comment by ydwu** [comment]
@ranjanan Right, after enabling **mark-predecessors**, `grapho->node_value1` will still outputs label information, and `grapho->node_value2` will be predecessors. You should be able to get it by changing only the here: https://github.com/gunrock/gunrock/blob/master/shared_lib_tests/shared_lib_bfs.c#L34. Lemme know if there's any other issues.

**Comment by ydwu** [comment]
Reopen: need to fix mark-predessesor flag.

**Comment by ranjanan** [comment]
@ydwu Yes, that's exactly what I did. Thanks! Though I was wondering if you think it might be a better idea to do this without changing source code, maybe as a parameter one can pass to `bfs()` or something?

**Comment by ydwu** [comment]
@ranjanan Yes, that's why I'm reopening this issue, we'll fix this. Thank for reporting!

**Comment by neoblizz** [comment]
Done using parameters.
