### ISSUE TITLE
Generate multiple bfs trees on one single device transfer

### ISSUE THREAD

**Issue by ranjanan** [gunrock/gunrock#65]
Hi.
I was working on an implementation of the Graph500 benchmark in Julia (www.graph500.org). I was using Gunrock to generate the bfs trees. The way Julia interacts with Gunrock is through a `ccall`, which essentially calls the function `void bfs()` through `libgunrock.so` by passing the appropriate arrays, as well as `bfs_label`, and getting the tree in `bfs_label`. Everytime I make this `ccall`, there is host to device transfer as well as a device to host transfer for `bfs_label`. I want to minimize this latency. 

Is there a way for the graph to stay in device memory while I perform a bunch of bfs calls? Finally, it can return a 2D array or another appropriate data structure.

**Comment by yzhwang** [comment]
Hi @ranjanan , the bfs() call there was not initially designed for doing benchmarks, so we integrated the host<->device memcpy with the bfs running together. Let me try to make a hack version in a temporary branch so that you can do a bunch of bfs calls with the data stay in memory. Will let you know when I finish.

**Comment by ranjanan** [comment]
Thanks @yzhwang

**Comment by jowens** [comment]
We have always thought that Gunrock would be a good substrate for Graph500. We support you in your efforts here (and frankly, we probably will *actually* support you in your efforts if you need help, as we're doing here).

**Comment by ViralBShah** [comment]
Thanks @jowens This will nicely feed into our other collaboration!

**Comment by ViralBShah** [comment]
@ranjanan Could you post the link to our initial efforts of graph500? Also, I think you should be able to paste the performance chart here.

**Comment by ViralBShah** [comment]
Another comment - since bfs is the building block for many other algorithms, it is useful to have it as a kernel where the graph stays on the gpu, and one can keep running operations on it. With Julia not too far away from GPU codegen, we should be able to do more interesting things.

**Comment by jowens** [comment]
cc: @veb61 (Viral, you know we're working with Jake/Jiahao/Alan on this :) )

**Comment by ViralBShah** [comment]
Yes. :-)

**Comment by ranjanan** [comment]
Here is a link to our initial efforts of implementing Graph500 in Julia: 
https://github.com/ranjanan/MT-Workloads/tree/master/Graph500/. The folder 'gpu' contains our implementation using the Gunrock library.
 
Here are a couple of performance charts: 

![image](https://cloud.githubusercontent.com/assets/9101377/11237407/ba24ef48-8e05-11e5-8911-6e57225bcd4c.png)
Varying edgefactor with Scale = 18 (Numnodes = 2^18)

![image](https://cloud.githubusercontent.com/assets/9101377/11237440/e8ec6e0a-8e05-11e5-891e-28c0526ac402.png)
Varying Scale with edgefactor = 15

**Comment by ViralBShah** [comment]
Just bumping this one. Even if you have some branch or non-standard way to do this, we'll be happy to wrap those routines in Julia.

**Comment by yzhwang** [comment]
Sorry for the delay for handling this issue. I did some experiments separating graph load, execution, and result extraction, but for multiple primitive execution, it stalls after the first one. @sgpyc I remember we discussed this couple of weeks ago. You mentioned it is because of some thread context resetting issue? Can you elaborate more on this? Do we have any workaround?

**Comment by sgpyc** [comment]
Yes, the original cpu lock is not reusable and that stops running enact multiple times.
Since now we have c++11 now (refer to #104 ), I can try to bring the new inter CPU thread communication under mgpu-cq branch into dev branch, which allows multiple enact.

**Comment by jowens** [comment]
@sgpyc Resurrecting this issue, can you take a look in the not too distant future?

**Comment by neoblizz** [comment]
Really old issue, but worth answering.
> Is there a way for the graph to stay in device memory while I perform a bunch of bfs calls? Finally, it can return a 2D array or another appropriate data structure.

Yes, in the v1.x release, you can modify the problem to not extract and just use the Array1D pointer that is already on the GPU to keep computing BFS on it. This code will soon be merged to master, but the commit (file) is here: https://github.com/gunrock/gunrock/blob/bc577f5d41027fb29df9bd180273d0ed337ec932/gunrock/app/bfs/bfs_problem.cuh
