### ISSUE TITLE
Congratulations with PPoPP 2016

### ISSUE THREAD

**Issue by kongfujianlong** [gunrock/gunrock#66]
Just see Gunrock from the accepted paper list of PPoPP 2016 http://conf.researchr.org/info/PPoPP-2016/list-of-accepted-papers

Congratulations!

**Comment by jowens** [comment]
This is my new favorite issue. Thanks @kongfujianlong!

**Comment by yzhwang** [comment]
Thanks @kongfujianlong Let me know next time you visit bay area, we should meet up and talk about graph processing :-)
