### ISSUE TITLE
Running Louvain from Python with ctypes

### ISSUE THREAD

**Issue by ArEsKay3** [gunrock/gunrock#666]
Hi all,

I'm trying to run the Louvain community detection for a large graph.
I'm currently working in python (my graph is in networkx) so I'm trying to call using the python ctypes hooks. My code looks roughly like below. (The *2 factor is from going undirected to directed).

(I did have to add the louvain stuff to CUFILES in the CMakeLists (see diff below), so I'm aware I might be in untested territory.)

When I inspect the c_types values before the gunrock call everything looks OK, but the histogram information printed from gunrock is wrong and I get a segfault during execution. **Is there some change/update I need to the louvain app code to get louvain to work this way?** I can't really see in the code where this would go wrong and my test run of calling pagerank from the python subdirectory works fine.

Any help would be greatly appreciated!
Thanks!

```python
... Load networkx graph G ...
CSR = networkx.to_scipy_sparse_matrix(G)
from ctypes import *
num_nodes = c_int(G.number_of_nodes())
num_edges = c_int(G.number_of_edges()*2)
... At this point num_nodes=211447 and num_edges=6017920 ...
row_offsets = pointer((c_int * (num_nodes.value+1))(*list(CSR.indptr)))
col_indices = pointer((c_int * (num_edges.value))(*list(CSR.indices)))
edge_values = pointer((c_int * (num_edges.value))(*([1]*num_edges.value)))
communities = pointer((c_int * (num_nodes.value))())
gunrock = cdll.LoadLibrary('../gunrock/build/lib/libgunrock.so')
elapsed = gunrock.louvain(num_nodes, num_edges, row_offsets, col_indices, edge_values, communities)
```

The information reported from the degree histogram:

```
Degree Histogram (960666711 vertices, 21927 edges):
    Degree 0: 960455264 (99.977990 %)
    Degree 2^0: 85 (0.000009 %)
    Degree 2^1: 20077 (0.002090 %)
    Degree 2^2: 32752 (0.003409 %)
    Degree 2^3: 42019 (0.004374 %)
    Degree 2^4: 49306 (0.005132 %)
    Degree 2^5: 35801 (0.003727 %)
    Degree 2^6: 31346 (0.003263 %)
    Degree 2^7: 42 (0.000004 %)
    Degree 2^8: 17 (0.000002 %)
    Degree 2^9: 1 (0.000000 %)
    Degree 2^10: 1 (0.000000 %)
```

```--- a/gunrock/CMakeLists.txt
+++ b/gunrock/CMakeLists.txt
@@ -36,7 +36,7 @@ set(CUFILES
   app/hits/hits_app.cu
   app/sm/sm_app.cu
   #app/sssp/sssp_app.cu
-  #app/louvain/louvain_app.cu
+  app/louvain/louvain_app.cu
   #app/color/color_app.cu
   util/test_utils.cu
   util/error_utils.cu```

**Comment by ArEsKay3** [comment]
It feels like a datatype issue (since the vertice count is so high), but I'm just not familiar enough to guess where it's coming from.

**Comment by neoblizz** [comment]
Got it to work after a few changes. These are more so rushed, so I will wait to push them -- but here's the diff:

```
@@ -36,7 +36,7 @@ set(CUFILES
   app/hits/hits_app.cu
   app/sm/sm_app.cu
   #app/sssp/sssp_app.cu
-  #app/louvain/louvain_app.cu
+  app/louvain/louvain_app.cu
   #app/color/color_app.cu
   util/test_utils.cu
   util/error_utils.cu
```

Important part was enabling `FromCsr` in the `louvain_app.cu` file, and then making sure ValueT was set to F64 and not Int32. That made it so I had to change edge values to be doubles. You can get away with having them floats (so F32 not F64). And here's my sample python code:

```
### sample python interface - pagerank

from ctypes import *

### load gunrock shared library - libgunrock
gunrock = cdll.LoadLibrary('../build/lib/libgunrock.so')
### read in input CSR arrays from files
row_list = [int(x.strip()) for x in open('toy_graph/row.txt')]
col_list = [int(x.strip()) for x in open('toy_graph/col.txt')]
val_list = [int(x.strip()) for x in open('toy_graph/val.txt')]

print 'set pointers'
### convert CSR graph inputs for gunrock input
row = pointer((c_int * len(row_list))(*row_list))
col = pointer((c_int * len(col_list))(*col_list))
val = pointer((c_double * len(val_list))(*val_list))

nodes = len(row_list) - 1
edges = len(col_list)

### output array
communities = pointer((c_int * nodes)())

print 'run gunrock'
### call gunrock function on device
elapsed = gunrock.louvain(nodes, edges, row, col, val, communities)

### sample results
print 'elapsed: ' + str(elapsed)
print 'Louvain Comms::'
for idx in range(nodes):
    print communities[0][idx]
```

As you can see from gunrock.h and the python code, edge_values are now double and everything else is the same and should work after adding that FromCsr line in the app file of louvain.

**Comment by neoblizz** [comment]
On another note, we haven't spent a lot of time enabling python support for gunrock. And the c interface is an example of what could be done, but is not at all tested for all the different apps. On the other hand, our c++ interface and command line should work fine.

**Comment by ArEsKay3** [comment]
Awesome, thanks! Adding back the FromCsr was exactly what I was about to try before I quit for the night ;) .  I think with this code and the previous example I should probably be equipped enough to hack my way around prototyping some initial performance numbers for my use case. I can get my hands as dirty as I feel motivated too now. Thanks again for the quick reply!

**Comment by neoblizz** [comment]
Closing this for now, let me know if you have issues applying the patch above. :)

**Comment by ArEsKay3** [comment]
Just as an FYI, I was able to get this to run on a single V100, but the performance is nowhere near what I was expecting.

Here was the statistics of one of my smaller test graphs.
Based on results on in the Louvain paper I expected this to take at most a few seconds, but I'm still waiting after more than 10 minutes of 100% GPU-Utilization.

I'm far from an expert in this space, is this runtime something you would have expected? Do you have test graphs that run much faster (maybe my graph is in some way pathological)? Or is this not implementing the algorithm I think it is?

```
Degree Histogram (2000 vertices, 2648 edges):
    Degree 0: 816 (40.800000 %)
    Degree 2^0: 341 (17.050000 %)
    Degree 2^1: 706 (35.300000 %)
    Degree 2^2: 116 (5.800000 %)
    Degree 2^3: 19 (0.950000 %)
    Degree 2^4: 2 (0.100000 %)
```

![image](https://user-images.githubusercontent.com/6547143/70953283-90944d00-201d-11ea-8dd3-ca1f5a2d9a28.png)

**Comment by jowens** [comment]
Can you run this on plain Gunrock (not through python)? That would tell us if it's a problem with Gunrock or with the Gunrock-python interface.

**Comment by ArEsKay3** [comment]
Yep, this takes a blink if I dump to a '.txt' file and read back entirely in C++.

**Comment by jowens** [comment]
Yeahhhhhh so debugging Python performance problems is not exactly in my wheelhouse. I'm not really sure what to advise you, to be honest. I hope someone else on the project can chime in. Any performance info you can get us—e.g., https://docs.python.org/3/library/profile.html—would be really helpful. I can try to get someone external who knows about this to help us. But profiling info seems important to get started.

**Comment by ArEsKay3** [comment]
Just within C++, I hit a different error when I go to 20000 nodes, but maybe the memory footprint here is actually too big (which is a bummer because I'm on a 32GB GPU).

```Found 20000 nodes and 408564 edges
Degree Histogram (20000 vertices, 408564 edges):
    Degree 0: 726 (3.630000 %)
    Degree 2^0: 654 (3.270000 %)
    Degree 2^1: 1781 (8.905000 %)
    Degree 2^2: 2792 (13.960000 %)
    Degree 2^3: 5440 (27.200000 %)
    Degree 2^4: 3818 (19.090000 %)
    Degree 2^5: 3803 (19.015000 %)
    Degree 2^6: 986 (4.930000 %)

-1       -1      -1      scanned_edges   oversize :      0 ->    3
[gunrock/util/array_utils.cuh, 520 @ gpu 0] cub_temp_space cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[gunrock/app/louvain/louvain_enactor.cuh, 280 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[gunrock/app/enactor_base.cuh, 519 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[gunrock/app/louvain/louvain_enactor.cuh, 1044 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
Segmentation fault (core dumped)
```

**Comment by jowens** [comment]
Can you share that graph in some way with us? That's not so big I'd think we should have a problem.

**Comment by ArEsKay3** [comment]
Yeah.
[row.txt](https://github.com/gunrock/gunrock/files/3971068/row.txt)
[val.txt](https://github.com/gunrock/gunrock/files/3971069/val.txt)
[col.txt](https://github.com/gunrock/gunrock/files/3971070/col.txt)
[main.cpp.txt](https://github.com/gunrock/gunrock/files/3971072/main.cpp.txt)

**Comment by ArEsKay3** [comment]
I can take a look at the python profiling sometime this week maybe. Will have to refactor some stuff to wrap it in the profiler properly.

**Comment by jowens** [comment]
And the input format of the above files? MatrixMarket is kind of all we support (but my teammates will correct me).

**Comment by ArEsKay3** [comment]
You can see how I'm reading it and calling louvain in the main.cpp file.
There are hooks to call louvain with the CSR format in app/louvain (which is what these files are).
