### ISSUE TITLE
Finding cuda codes in binaries

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#670]
I would like to work with `cuobjdump` but I can not find the binary files containing cuda code for that. For example, `bin/bfs` doesn't contain cuda instructions. 

Is there any guide to find cude binaries/libraries?

**Comment by jowens** [comment]
I'm not sure what you're asking here. When you build Gunrock do you not end up with binaries (with CUDA code) for each individual primitive?

**Comment by mahmoodn** [comment]
Yes. I have build/bin/bfs and others. I want to extract ptx with cuobjdump.
```
$ cuobjdump -ptx bfs

Fatbin elf code:
================
arch = sm_70
code version = [1,7]
producer = <unknown>
host = linux
compile_size = 64bit
compressed
```

**Comment by jowens** [comment]
I'm not sure what you're asking. There's nothing special about a Gunrock build compared to other CUDA apps. We have no specific experience with dumping PTX from our apps or any others.

**Comment by jowens** [comment]
The PTX is perhaps in a linked library? libgunrock or the like?

**Comment by mahmoodn** [comment]
No.
```
$ cuobjdump -ptx libgunrock.so

Fatbin elf code:
================
arch = sm_70
code version = [1,7]
producer = <unknown>
host = linux
compile_size = 64bit
```

However, `cuobjdump -sass bfs` works fine. That is enough for now. Thank you.
