### ISSUE TITLE
How to set up multi GPU to run BFS？

### ISSUE THREAD

**Issue by jiangjiaqi6** [gunrock/gunrock#672]
I am a college student, I really need help. Now I have joined the teacher's laboratory. The content is about graph calculation. The teacher asked me to run through BFS with multiple GPUs. I have spent more than ten days on it, but I still haven't found a breakthrough. I don't know how to set it. I know that my main problem is that I am not clear about the overall architecture of the gunrock library, and the relationship between functions is also very chaotic. I hope someone can give me some advice, and I will be grateful.

**Comment by jowens** [comment]
Suggest you build version 0.5.1 (https://github.com/gunrock/gunrock/releases/tag/v0.5.1) and then run the command-lines you'll find in the JSONs in the following directory:

https://github.com/gunrock/io/tree/master/gunrock-output/ipdps17

which produces the results you see in our IPDPS '17 paper.

e.g., look at:

https://github.com/gunrock/io/blob/master/gunrock-output/ipdps17/eval_fig2/BFS_kron_g500-logn21_Thu%20Jan%2026%20003915%202017.json

which has a `command-line` field:

`"../../../tests/bfs/bin/test_bfs_8.0_x86_64 market ../../../dataset/large/kron_g500-logn21/kron_g500-logn21.mtx --undirected --iteration-num=16 --tag=ipdps17_fig2 --jsondir=eval_fig2 --idempotence --direction-optimized --src=largestdegree --traversal-mode=LB_CULL --queue-sizing=6.5 --in-sizing=4 --partition-method=random --device=0 --do_a=0.00001 --do_b=0.1"`

**Comment by jowens** [comment]
@neoblizz if that looks right please close this issue?

**Comment by neoblizz** [comment]
Once you have built gunrock, there should be binary files just like John pointed out above. The parameter `--device=0,1,2,3...` is where you specify the multi-GPU part of gunrock, you can use as many devices as you have available in the system by appending then in a comma list.

Also note, we accept the graphs in matrix market file format, so you need your input to be in this mtx format for it to work with the gunrock binaries.

To switch to v0.5.1 just do `git checkout tags/v0.5.1`.

**Comment by jiangjiaqi6** [comment]
Thank you for your help.
