### ISSUE TITLE
Host compilation calculates occupancy information

### ISSUE THREAD

**Issue by crozhon** [gunrock/gunrock#675]
When launching kernels for our operators, we like to use the \_\_launch_bounds\_\_ construct to give extra information to the compiler. This math is done in the kernel_policy.cuh files of each operator. When compiling, nvcc sets the \_\_CUDA_ARCH\_\_ environment variable, which we use to set GR_CUDA_ARCH:

https://github.com/gunrock/gunrock/blob/6ddbd3355b7985648596d8c611153ef03a64a5bf/gunrock/util/cuda_properties.cuh#L21-L33

which is then used in the \_\_launch_bounds\_\_ calculation for each KernelPolicy struct:

https://github.com/gunrock/gunrock/blob/6ddbd3355b7985648596d8c611153ef03a64a5bf/gunrock/oprtr/CULL_filter/kernel_policy.cuh#L130-L135

As NVCC compiles each target architecture, it changes \_\_CUDA_ARCH\_\_ accordingly and so we have valid occupancy calculations for each kernel compiled for each target device. NVCC also compiles a version for the host and does not set \_\_CUDA_ARCH\_\_ for this pass. We choose to set GR_CUDA_ARCH = 300 for this compilation, which ensures the templates in KernelPolicy structs still compile. This host-side code for the KernelPolicy struct will never be used, so this is fine. 

But it's not pretty, so let's rework these template calculations. Possible solutions include not compiling KernelPolicy during the host pass with some use of #ifdefs, or changing our occupancy calculations entirely.

**Comment by crozhon** [comment]
See https://moderngpu.github.io/performance.html subsection "LaunchBox" for an abstraction that solves a similar problem in moderngpu.

**Comment by neoblizz** [comment]
Solved in essentials; https://github.com/gunrock/essentials/blob/master/include/gunrock/cuda/launch_box.hxx
