### ISSUE TITLE
test_lib_pr and test_lib_sm unit test segmenation fault

### ISSUE THREAD

**Issue by porumbes** [gunrock/gunrock#683]
**Summary:**
Running `./bin/unittests` using only `test_lib_sm.h` results in a segmentation fault.

**Reproducibility:**
Always

**To Reproduce:**

1. Clone gunrock
2. Switch to the `dev` branch
3. Enable google tests in CMakeLists.txt
4. Comment out all includes in `test_unittests.cu` except for
```
// Tests Subgraph Matching
#include "test_lib_sm.h"
```
4a. You can leave the tests as it and still see the issue, but you can see the problem faster if you disable the other tests.
5. build and then run `./bin/unittests`

**Expected Behavior:**
Tests should complete without segmentation fault.

**Actual Results:**
Test seems to pass, but there's a segmentation fault at the end.

**System Configuration:**

GPU: Quadro GV100
CPU: Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz
OS: Ubuntu 18.04.1 LTS
NVIDIA-SMI 410.104      
Driver Version: 410.104     
CUDA Version: 10.0
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by neoblizz** [comment]
Is this related to https://github.com/gunrock/gunrock/pull/678?

**Comment by Laurawly** [comment]
@porumbes If you comment out all tests except test_lib_pr.h, the same error occurred.

**Comment by porumbes** [comment]
@Laurawly You're right. I went back to your https://github.com/gunrock/gunrock/pull/637/commits/4fe863c0e79e63df681f88666514cb4c2b08adc4 commit and pr also generates a segmenation fault. Figuring out the issue for sm will likely help us figure it out for pr : ).

**Comment by Laurawly** [comment]
@porumbes I actually followed `pr`'s method when writing `test_lib_sm.h`, currently have no clue why the seg fault happened.

**Comment by neoblizz** [comment]
Tests pass, for all PRs.
