### ISSUE TITLE
PR segmentation fault

### ISSUE THREAD

**Issue by porumbes** [gunrock/gunrock#684]
**Summary:**
PR segfaults on occasion. See [Jenkins Job TEST_PR](http://daisy.ece.ucdavis.edu:8080/job/gunrock/job/PR-682/1/display/redirect) for an example test run.

**Reproducibility:**
Sometimes

**To Reproduce:**
I think it's another issue with `compensate` (that's the only time I've managed to see the segfault).

1. build gunrock in release mode
2. run pr with something like `./bin/pr rmat --graph-scale=4 --graph-seed=5` or what is shown in the Jenkins Job above.

**Expected Behavior:**
PR should run to completion without error.

**Actual Results:**
PR will get to what follows and segfault
```
Rank Validity: PASS
Reference total rank : 0.150119
```

**System Configuration:**

GPU: Quadro GV100
CPU: Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz
OS: Ubuntu 18.04.1 LTS
NVIDIA-SMI 410.104
Driver Version: 410.104
CUDA Version: 10.0
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by neoblizz** [comment]
I saw the same thing with the last SNN commit (http://daisy.ece.ucdavis.edu:8080/blue/organizations/jenkins/gunrock/detail/PR-659/11/pipeline), notice how the test passes but the error is in displaying the output. So, I am guessing it is the JSON display.

**Comment by neoblizz** [comment]
@porumbes can you please look into this? All the active PRs are reporting false failure for the respective commits, which technically should pass.

**Comment by neoblizz** [comment]
Tests pass, for all PRs.
