### ISSUE TITLE
Refactoring Plan

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#70]
- [ ] Add kernel-level parameter struct
- [ ] Add Problem-level parameter struct
- [ ] Add Primitive Launch Plan handle like CUDPP
- [ ] Use clearer (hierarchical) parameter name for command line
- [ ] Redesign TWC and filter's framework, get rid of template meta-programming without (much) perf drop

**Comment by neoblizz** [comment]
Multiple instances of this same issue are opened, see #142. And this is currently in progress by @sgpyc. Open this if you think we really need multiple of these.
