### ISSUE TITLE
Add utility functions for csr struct

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#71]
Current issue: Current implementation of gunrock::app::Init() in enactor_base.cuh will cause overhead in graph loading phase and potential bugs when choosing to generate graph using R-Mat equation but not from file (See https://github.com/gunrock/gunrock/blob/master/gunrock/app/enactor_base.cuh#L489). The correct way to do this is for directed graph, first generates csr, then use a csr2csc function to create csc directly from csr. And for undirected graph, use a copy function to create the csc. Here are two functions to implement in order to make the change:
- [ ] A copy function for CSR struct which takes another csr reference and create a copy.
- [ ] A csr2csc function for CSR struct which convert a graph to its invert graph.

Good starter project for new students!

**Comment by shariiiyy** [comment]
A quick question! I have implemented two functions and tested my code in a separate c++ with dummy csc and car variables. How should I test it in gunlock?

**Comment by yzhwang** [comment]
Hi @shariiiyy Could you point me to your implementation of the functions? I will take a look and help you figure out a way to test them.

**Comment by shariiiyy** [comment]
Sure! I didn't push them on git yet. I will put them up this afternoon! Thanks

**Comment by sgpyc** [comment]
I think now the CSR / CSC formats are handled correctly.
https://github.com/gunrock/gunrock/blob/dev/gunrock/util/info.cuh#L557
