### ISSUE TITLE
need to enable binding for sssp in cmake

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#710]
> When I compiling my code it just tells me "undefined reference to `sssp' ", no other errors or warnings. I use the command `nvcc -std=c++11 gunrock_sssp_test.cu -o out -I/tmp/gunrock_graph_library/gunrock -L/tmp/gunrock_graph_library/gunrock/build/lib -lgunrock -lpthread` to compile the code and I include `gunrock/gunrock.h` in my .cu file. I call function sssp in my main function. Is there something wrong? I haved googled it and read somthing on gunrock github webpage but still could not solve it. I have also read some examples from `gunrock/examples/shared_libs`, but they use the gunrock the same as I do.

@neoblizz:
> I think it is because in the CMakeLists.txt for the apps, we don't have the binding for sssp enabled: https://github.com/gunrock/gunrock/blob/master/gunrock/CMakeLists.txt#L38

**Comment by crozhon** [comment]
Tested locally and committed.
