### ISSUE TITLE
Doxygen warnings on .cu and .cuh files

### ISSUE THREAD

**Issue by huanzhang12** [gunrock/gunrock#72]
In previous Doxygen generated documentation pages, .cu and .cuh files were not included. This was a mistake, and has been fixed in commit 95ed5c4.

After we included .cu and .cuh files in Doxygen file list, a lot of new warnings inside .cu and .cuh files are reported by Doxygen because some source code commenting requirements are not met and Doxygen failed to extract all necessary information. We need to fix these warnings.

Here are the files involved: 

~~~
gunrock/app/bc/bc_enactor.cuh
gunrock/app/bfs/bfs_enactor.cuh
gunrock/app/cc/cc_enactor.cuh
gunrock/app/dobfs/dobfs_enactor.cuh
gunrock/app/dobfs/dobfs_problem.cuh
gunrock/app/hits/hits_enactor.cuh
gunrock/app/mst/mst_enactor.cuh
gunrock/app/salsa/salsa_enactor.cuh
gunrock/app/sssp/sssp_enactor.cuh
gunrock/app/sssp/sssp_problem.cuh
gunrock/app/wtf/wtf_enactor.cuh
gunrock/graphio/market.cuh
gunrock/graphio/rmat.cuh
gunrock/oprtr/edge_map_backward/kernel.cuh
gunrock/oprtr/edge_map_forward/kernel.cuh
gunrock/oprtr/edge_map_partitioned_backward/kernel.cuh
gunrock/oprtr/edge_map_partitioned/kernel.cuh
gunrock/oprtr/filter/kernel.cuh
gunrock/priority_queue/kernel.cuh
gunrock/util/basic_utils.h
gunrock/util/device_intrinsics.cuh
gunrock/util/error_utils.cuh
gunrock/util/mark_segment.cuh
gunrock/util/random_bits.h
gunrock/util/test_utils.cuh
~~~

For more details about the warnings please see the Doxygen warning log below:
https://gist.github.com/huanzhang12/688ab3844116849b2058

Thanks,
Huan

**Comment by yzhwang** [comment]
Thanks @jowens !
