### ISSUE TITLE
Improving dataset download script on Mac

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#74]
https://github.com/gunrock/gunrock/blob/master/dataset/large/common.mk#L7
According to our PPoPP 2016 artifact evaluation reviewer, wget is not available directly on Mac systems. We should improve this script. For Mac system, "curl -O" is equivalent. A Mac user is desirable to perform this task.

**Comment by jowens** [comment]
I think we just suggest / provide links to use homebrew or macports, both of which are exceptionally standard package managers on Mac systems. I mean, Windows doesn't have wget built in either; you have to install it using a package manager. Linux too, right? apt-get?

**Comment by neoblizz** [comment]
wget is shipped with ubuntu, I don't think this is really a problem for mac either (or asking mac users to install wget), same case with windows, even though are support there is lacking.
