### ISSUE TITLE
Add source directory structure description in our github.io page

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#75]
Also from our PPoPP 2016 artifact evaluation reviewer: It would be better that the artifact package includes a detailed introduction of information about the source directory structure.

**Comment by neoblizz** [comment]
Almost forgot about this, should be explained before v1.0 release.

**Comment by neoblizz** [comment]
https://github.com/gunrock/docs/blob/master/source/includes/directory_structure.md
