### ISSUE TITLE
Gunrock or nvGraph

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#754]
I would like to know it one can compare the structure of Gunrock and nvGraph or not? Both implement shortest path for [example](https://docs.nvidia.com/cuda/nvgraph/index.html#nvgraph-sssp-example). Or even, comparing the performance of these two... Any comment?

**Comment by jowens** [comment]
We did _some_ comparisons here: https://escholarship.org/uc/item/9gj6r1dj  (table 16). nvGraph has pretty limited functionality (it only supports a tiny number of graph primitives) and I'm fairly sure it is not maintained currently. My understanding is that it was a GraphBLAS-like framework internally, which is different than Gunrock (but similar to GraphBLAST, https://arxiv.org/abs/1908.01407). I think in general Gunrock had superior performance to nvGraph on the primitives they shared (but again, that's a very small number of primitives).

**Comment by mahmoodn** [comment]
My analysis shows that in large graphs, the load balancing operation which tries to put threads on cores, dominates the GPU time. For example, BFS algorithm, e.g. counting and ... , are not very heavy operations. So, I was curios to see what about nvgraph...

**Comment by jowens** [comment]
We haven't done detailed performance breakdowns for nvgraph. Perhaps you might want to look at GraphBLAST as it's probably more similar to nvgraph than anything else. But in any operation with sparse matrices—including both nvgraph and GraphBLAST—load balancing will similarly play a large role just as it does for Gunrock.

**Comment by mahmoodn** [comment]
Thank you.
