### ISSUE TITLE
Graph coloring 

### ISSUE THREAD

**Issue by AbandiGa** [gunrock/gunrock#755]
Hello,

I have a question about the runtime in the graph coloring code.
when I run the code I got this

**Run 0 elapsed: 3.890991, #iterations = 31
Validating result ...
Comparison: <node idx, gunrock, cpu>
0 errors occurred.
Number of colors: 61
[color] finished.
 avg. elapsed: 3.890991 ms
 iterations: 31
 min. elapsed: 3.890991 ms
 max. elapsed: 3.890991 ms
 load time: 22.6269 ms
 preprocess time: 1835.070000 ms
 postprocess time: 0.612974 ms
 total time: 1867.646933 ms**

Which of these runtimes is used on the graph coloring paper to measure the performance?

Also, is there any good documentation of how to run the code with the different algorithms/versions provided on the paper?

Thank you

**Comment by neoblizz** [comment]
> Which of these runtimes is used on the graph coloring paper to measure the performance?

`avg. elapsed` is what is reported, which is the actual algorithm time.
 
> Also, is there any good documentation of how to run the code with the different algorithms/versions provided on the paper?

The current version of graph coloring is simplified and removes most of the parameters we had. If you'd like to try all the optimizations, you can switch to the tag v1.1 (which is the last gunrock release): https://github.com/gunrock/gunrock/tree/v1.1

We also intend to improve coloring in a future release.

**Comment by jowens** [comment]
The runtime in the paper would correspond to `avg. elapsed` (@neoblizz or @agalup will correct me if I'm wrong). "preprocessing" would be, say, loading the input file from disk, and postprocessing is probably sending the result back to the CPU. We don't count those in `avg. elapsed` and neither does anyone else.

I believe all the tests we ran for the paper are in `https://github.com/gunrock/io/tree/master/gunrock-output/color_GRAPL` and they contain command lines (again @neoblizz will correct me).

**Comment by neoblizz** [comment]
Reopen the issue if the above doesn't answer your questions.
