### ISSUE TITLE
BFS kernels

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#764]
As I profile `./bfs market file.mtx`, I don't see the kernel names written in `gunrock/app/bfs/bfs_kernel.cuh` in the output data. I mean kernels such as `Inverse_Expand` or `From_Unvisited_Queue_Local_IDEM`.
The kernels I see in the output data file are:
```

_ZN7gunrock5oprtr10For_KernelIZNS_3app3bfs16BFSIterationLoopINS3_7EnactorINS3_7ProblemINS2_9TestGraphIjjjLj768ELj0EEEjjLj0EEELj0ELj0EEEE4CoreEiEUljE_EEvmT_
--

void   mgpu::KernelScanParallel<mgpu::LaunchBoxVT<int=256, int=1, int=0,   int=256, int=1, int=0, int=256, int=1, int=0>, mgpu::MgpuScanType,   unsigned int*, unsigned int*, unsigned int, mgpu::plus<unsigned   int>>(int=0, int, int=1, int=0, int=0*, int=256)

void   mgpu::KernelReduce<mgpu::LaunchBoxVT<int=128, int=15, int=0, int=128,   int=7, int=0, int=128, int=7, int=0>, unsigned int*, unsigned int,   mgpu::plus<unsigned int>>(int=15, int, int=0, int=128, int=15*)

_ZN7gunrock5oprtr14ForEach_KernelINS_4util7Array1DIjjLj0ELj0EEEjZNS_3app3bfs7EnactorINS6_7ProblemINS5_9TestGraphIjjjLj768ELj0EEEjjLj0EEELj0ELj0EE5ResetEjjEUlRjE_EEvT_T1_T0_

_ZN7gunrock5oprtr13ForAll_KernelINS_4util7Array1DIjjLj0ELj0EEEjZNS_3app3bfs7ProblemINS5_9TestGraphIjjjLj768ELj0EEEjjLj0EE5ResetEjjEUlPjRKjE_EEvT_T1_T0_

void   gunrock::oprtr::GetEdgeCounts<gunrock::graph::Csr<unsigned int,   unsigned int, unsigned int, unsigned int=256, unsigned int=0, bool=1>,   unsigned int>(unsigned int, unsigned int const *,   gunrock::oprtr::GetEdgeCounts<gunrock::graph::Csr<unsigned int,   unsigned int, unsigned int, unsigned int=256, unsigned int=0,   bool=1>::SizeT, unsigned int>, unsigned int const **, unsigned int)

void   mgpu::KernelScanDownsweep<mgpu::LaunchBoxVT<int=128, int=15, int=0,   int=128, int=7, int=0, int=128, int=7, int=0>, mgpu::MgpuScanType,   unsigned int*, unsigned int*, unsigned int, mgpu::plus<unsigned   int>>(int=0, int, int=7 const *, int=0, int=0, int=128)

void   mgpu::KernelScanParallel<mgpu::LaunchBoxVT<int=256, int=3, int=0,   int=256, int=3, int=0, int=256, int=3, int=0>, mgpu::MgpuScanType,   unsigned int*, unsigned int*, unsigned int, mgpu::plus<unsigned   int>>(int=0, int, int=3, int=0, int=0*, int=256)

void   mgpu::KernelScanParallel<mgpu::LaunchBoxVT<int=512, int=5, int=0,   int=512, int=5, int=0, int=512, int=5, int=0>, mgpu::MgpuScanType,   unsigned int*, unsigned int*, unsigned int, mgpu::plus<unsigned   int>>(int=0, int, int=5, int=0, int=0*, int=512)

_ZN7gunrock5oprtr4CULL6KernelILj1EjjjjjZNS_3app3bfs16BFSIterationLoopINS4_7EnactorINS4_7ProblemINS3_9TestGraphIjjjLj768ELj0EEEjjLj0EEELj0ELj0EEEE4CoreEiEUlRKjRjSE_SE_SE_SF_E0_EEvbT2_PKT0_PKT3_SH_T4_PSO_PhPT1_NS_4util15CtaWorkProgressISH_EET5_

_ZN7gunrock5oprtr2LB15RelaxLightEdgesILj1ENS_5graph3CsrIjjjLj256ELj0ELb1EEEjjZNS_3app3bfs16BFSIterationLoopINS7_7EnactorINS7_7ProblemINS6_9TestGraphIjjjLj768ELj0EEEjjLj0EEELj0ELj0EEEE4CoreEiEUlRKjRjSH_SH_SH_SI_E_EEvbNT0_7VertexTESK_PKT1_NSK_5SizeTEPKSP_PT2_PNSK_6ValueTEPSP_NS_4util15CtaWorkProgressISP_EET3_

_ZN7gunrock5oprtr14ForEach_KernelINS_4util7Array1DIjjLj0ELj0EEEjZNS_3app3bfs7ProblemINS5_9TestGraphIjjjLj768ELj0EEEjjLj0EE9DataSlice5ResetEjjEUlRjE_EEvT_T1_T0_

```
So, am I looking into the wrong place? or something else?

**Comment by neoblizz** [comment]
@mahmoodn you can look at the enactor to see when they are invoked: https://github.com/gunrock/gunrock/blob/fc229b445ef67dc007791d544de8d0e03fe47d8e/gunrock/app/bfs/bfs_enactor.cuh#L395

I believe the kernels in the bfs_kernels file are only used with direction optimized bfs, which is the fastest optimized bfs we support. You can enable that using command line parameter: `direction-optimized`.

https://github.com/gunrock/gunrock/blob/fc229b445ef67dc007791d544de8d0e03fe47d8e/gunrock/app/bfs/bfs_enactor.cuh#L43-L46

**Comment by mahmoodn** [comment]
Excuse me, but I didn't understand that.
I asked, what I see as BFS kernels in the profiler seems to be different from what I see in the code. In other words, I expected to see the kernels in bfs_kernel.cuh but in really I don't see any of them.

That means for BFS there are some other kernels. Is that right? 
I guess what you said is that, when `--direction-optimized=false`, I don't see the kernels written in bfs_kernel.cuh. Right? So, where are they?

Also, you said, when `--direction-optimized=true` is used, then kernels in bfs_kernel.cuh are used. Right?

**Comment by neoblizz** [comment]
> Also, you said, when `--direction-optimized=true` is used, then kernels in bfs_kernel.cuh are used. Right?

Yes. When you use dobfs, it uses the bfs_kernels. Which are special kernels implemented to support that optimization.



> I guess what you said is that, when `--direction-optimized=false`, I don't see the kernels written in bfs_kernel.cuh. Right? So, where are they?

If you don't use dobfs, it uses the traditional gunrock operators, which are implemented using the kernels you see after you profiled it. Collection of those kernels implements operators such as advance, filter, etc.

The following, for example, are from moderngpu that implement scan and reduce:
- mgpu::KernelScanParallel
- mgpu::KernelReduce

The others are from different gunrock operators:
- gunrock::oprtr::CULL::Kernel (CULL filter)
- gunrock::oprtr::LB::RelaxLightEdges (LB advance)
- gunrock::oprtr::ForEach_Kernel and ForAll (are parallel for)

**Comment by mahmoodn** [comment]
OK. With and without that option, I see that partitioning and edge counting are still on the top. In fact, the kernels in bfs_kernel.cuh are not so important, at least for belgium_osm that I tested.
