### ISSUE TITLE
Error running dynamic_graph inside bin folder in dynamic-graph branch

### ISSUE THREAD

**Issue by GuglielmoCerri** [gunrock/gunrock#769]
**Summary:**
When I call dynamic_graph inside build/bin it returns me the following error: 

> [/home/cudatest/Desktop/Project/gunrock-dynamic-graph/gunrock/util/parameters.h, 244 @ gpu 0] Parameter load-time has not been defined (CUDA error 11: invalid argument)

**To Reproduce:**
I downloaded the branch **dynamic-graph**
I call: `./dynamic_graph market ../../dataset/large/ak2010/ak2010.mtx` inside gunrock-dynamic-graph/build/bin. I also tried with other graphs (also inside small folder) but there is always the same error.

**System Configuration:**

GPU: GeForce GTX 980 with 4043MiB
CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
NVIDIA-SMI 440.82
Driver Version: 440.82
OS: Ubuntu 1804
Cuda compilation tools, release 10.2, V10.2.89
gcc (Ubuntu 7.5.0-3ubuntu1~18.04): 7.5.0

**Comment by maawad** [comment]
Fixed in PR https://github.com/gunrock/gunrock/pull/768
