### ISSUE TITLE
SSSP pre-processing code

### ISSUE THREAD

**Issue by ArindamK92** [gunrock/gunrock#771]
I am observing that the SSSP(Single Source Shortest Path) application is omitting a large number of edges just by pre-processing by saying the duplicate edges and self-loops are removed. Can you please tell me at which part of the code this preprocessing is being done? 

I am working on some SSSP related problems and want to use or compare the preprocessing techniques.

**Comment by neoblizz** [comment]
You can turn these options off. When loading the graph from a matrix market format (or other formats), gunrock will remove self-loops or duplicate edges: https://github.com/gunrock/gunrock/blob/9c8102fa74cc473443ffff120e1c62fe7e6ac578/gunrock/graphio/market.cuh#L496-L505

It's not technically modifying the graph. Just removing duplicated work.

**Comment by ArindamK92** [comment]
Thanks for quick response
