### ISSUE TITLE
Error in fetching externals

### ISSUE THREAD

**Issue by Sinan81** [gunrock/gunrock#777]
**Summary:**
I am building Gunrock using Spack HPC package manager, which pulls in package sources files as git as follows. Until recently this was working just fine. But it seems there is an issue with an external package dependency. Wondering if you have any suggestions comments.

Spack issues the following commands to clone the git repo:
```
/usr/bin/git clone --single-branch --depth 1 https://github.com/gunrock/gunrock.git
...
/usr/bin/git pull --tags
...
/usr/bin/git checkout v1.1
...
/usr/bin/git submodule update --init --recursive
...
Submodule path 'externals/rapidjson': checked out '4b3d7c2f42142f10b888e580c515f60ca98e2ee9'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'thirdparty/gtest'
Cloning into 'thirdparty/gtest'...
remote: Enumerating objects: 20649, done.
remote: Total 20649 (delta 0), reused 0 (delta 0), pack-reused 20649
Receiving objects: 100% (20649/20649), 7.62 MiB | 4.33 MiB/s, done.
Resolving deltas: 100% (15269/15269), done.
Submodule path 'externals/rapidjson/thirdparty/gtest': checked out 'ba96d0b1161f540656efdaed035b3c062b60e006'
Unable to checkout '5be4ef286d25cb1ac548f33dc113ad93792c9adb' in submodule path 'docs'
==> [2020-07-01-20:53:04.897438, 18270] Fetching from [git] https://github.com/gunrock/gunrock.git at tag v1.1 failed.
==> [2020-07-01-20:53:04.897568, 18270] ProcessError: Command exited with status 1:
    '/usr/bin/git' 'submodule' 'update' '--init' '--recursive'
```

**Reproducibility:**
Always 

**To Reproduce:**
```
 git clone --recursive https://github.com/gunrock/gunrock/
 cd gunrock/
 git checkout v1.1 
 git submodule update --init --recursive
```

**Expected Behavior:**
Git should clone just fine

**Actual Results:**
See above

**System Configuration:**
Centos7
git version 1.8.3.1

**Comment by Sinan81** [comment]
Also created an Issue in Spack repo: https://github.com/spack/spack/issues/17342

**Comment by neoblizz** [comment]
@Sinan81 why the `--recursive` flag for the submodules? I have never personally used that because for gunrock, I just need the module and not googletests, etc. So, this is what I would do:

```
git clone https://github.com/gunrock/gunrock/
 cd gunrock/
 git checkout v1.1 
 git submodule update --init
```

**Comment by neoblizz** [comment]
Oh! Nvm, the error is `Unable to checkout '5be4ef286d25cb1ac548f33dc113ad93792c9adb' in submodule path 'docs'`, it is because we archived the docs repository. Is it possible for you to use `master` or `dev` branch instead of `v1.1` tag?

**Comment by Sinan81** [comment]
That should be do'able but it is not ideal if we can't compile precise tag versions. Would it be possible to create a simple patch file to fix so that Spack will apply the patch after cloning the source files.

Also, when I attempted to build master branch, it seems no `bin` folder is created. Is that expected for the latest version of gunrock?

**Comment by neoblizz** [comment]
That's good that you figured it out.

> Would it be possible to create a simple patch file to fix it so that Spack will apply the patch after cloning the source files.

I think the `docs` thing is still relevant, I will create a simple patch for tag `v1.1`. :)

**Comment by Sinan81** [comment]
Great. Thanks!

**Comment by Sinan81** [comment]
version 1.2 doesn't have this issue anymore. So, probably there is no need to fix it anymore. The issue can be closed.
