### ISSUE TITLE
badly formed edge error

### ISSUE THREAD

**Issue by ArindamK92** [gunrock/gunrock#784]
I am trying to run gunrock sssp on a matrix market format dataset using the command: "./bin/test_sssp_10.2_x86_64 market <dataset name>  --src=0 --device=0 --undirected=1"

I am getting the below error. Please let me know why this error is coming or if I need to use a different command to run sssp.

Loading Matrix-market coordinate-formatted graph ...
  Reading from /lustre/scratch/akkcm/soc-orkut_wp_sor_gun_5M_100:
[../../gunrock/graphio/market.cuh, 181 @ gpu 0] Error parsing MARKET graph: badly formed edge (CUDA error 999: unknown error)
[../../gunrock/graphio/market.cuh, 440 @ gpu 0] error encountered (CUDA error 999: unknown error)
[../../gunrock/graphio/market.cuh, 537 @ gpu 0] error encountered (CUDA error 999: unknown error)
[../../gunrock/graphio/graphio.cuh, 202 @ gpu 0] error encountered (CUDA error 999: unknown error)
[test_sssp.cu, 52 @ gpu 0] error encountered (CUDA error 999: unknown error)
  Parsing MARKET COO format (2997166 nodes, 111349210 directed edges)...

**Comment by jowens** [comment]
Where did this graph come from? It's entirely possible it really is a badly formed edge.

**Comment by ArindamK92** [comment]
It is a mix of soc-orkut and a synthesized graph. Can you please tell me what do you mean by badly formed edge?

**Comment by jowens** [comment]
The code is in `market.cuh` and I didn't write it but I believe what it means is that the input graph is badly formed; it's not a valid MatrixMarket graph.

**Comment by jowens** [comment]
There's two places where that error occurs, one if your MM graph has edge values and one where it does not. It looks like the same condition though.

**Comment by ArindamK92** [comment]
Thanks for your help. I will check it

**Comment by jowens** [comment]
Please let us know either way!

**Comment by ArindamK92** [comment]
My mistake. There is some blank line and I counted that as edge. Thanks for your help again

**Comment by jowens** [comment]
Gotcha. Good luck!
