### ISSUE TITLE
error: identifier "__builtin_ia32_sqrtsd_round" is undefined

### ISSUE THREAD

**Issue by OswArti** [gunrock/gunrock#787]
I got the following  error when compiling bfs example on gunrock:

oarti001@raptor:~/documents/gunrock/examples/bfs$ make
mkdir -p bin
"/usr/local/cuda-10.1/bin/nvcc" -DGIT_SHA1="\"81f58d628463561969dafe65868e72251562e806\"" -gencode=arch=compute_61,code=\"sm_61,compute_61\"  -o bin/test_bfs_10.1_x86_64 test_bfs.cu ../../gunrock/util/str_to_T.cu ../../gunrock/util/test_utils.cu ../../gunrock/util/error_utils.cu ../../gunrock/util/gitsha1make.c -lineinfo --std=c++11 -D_MWAITXINTRIN_H_INCLUDED  -D_FORCE_INLINES  -D__STRICT_ANSI__  -lstdc++  --expt-extended-lambda -rdc=true  -m64 -I"/usr/local/cuda-10.1/bin/../include"  -I"../../externals/moderngpu/src" -I"../../externals/cub" -I"../../externals/rapidjson/include" -I.. -I../..  -Xcompiler -fopenmp -Xlinker -lgomp  -Xcompiler -DGUNROCKVERSION=1.1.0 -O3
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(1740): error: identifier "__builtin_ia32_sqrtsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(1749): error: identifier "__builtin_ia32_sqrtss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(2707): error: identifier "__builtin_ia32_scalefsd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(2716): error: identifier "__builtin_ia32_scalefss_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(5677): error: argument of type "const __v8df *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(5687): error: argument of type "const __v8df *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(5696): error: argument of type "const __v8df *" is incompatible with parameter of type "const double *"
 
and more similar errors.......

73 errors detected in the compilation of "/tmp/tmpxft_00035354_00000000-20_test_bfs.cpp1.ii".
Makefile:19: recipe for target 'bin/test_bfs_10.1_x86_64' failed
make: *** [bin/test_bfs_10.1_x86_64] Error 1

I added to the BaseMakefile.mk file the following NVCC flags
NVCCFLAGS = - -D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__  -lstdc++ 
However the compilation error was not solved. 

The server GPU/CUDA/OS/gcc I am using:

Device 0: "TITAN Xp" CUDA Driver Version / Runtime Version          
10.1 / 10.1 CUDA Capability Major/Minor version number:    
6.1Ubuntu 16.04.6 LTS
gcc (Ubuntu 8.4.0-1ubuntu1~16.04.1) 8.4.0

Solution to the problem of incompatibility between CUDA 10.1 and GNU 8.4.0. 

To run different versions of gcc as default  create
a local bin directory:

# Create the directory
mkdir ~/bin-defaults

# Add it in front of  your path so it's searched first
export PATH=~/bin-defaults:$PATH

Drop in symlinks to the appropriate version:

ln -s /usr/bin/gcc-5 ~/bin-defaults/gcc
ln -s /usr/bin/g++-5 ~/bin-defaults/g++

Now since that directory is first in your path, you will  run gcc-5 by 
default, and all the various configure scripts should see it first.

**Comment by neoblizz** [comment]
> Device 0: "TITAN Xp" CUDA Driver Version / Runtime Version         
> 10.1 / 10.1 CUDA Capability Major/Minor version number:   
> 6.1Ubuntu 16.04.6 LTS
> gcc (Ubuntu 8.4.0-1ubuntu1~16.04.1) 8.4.0

https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html It looks like the recommended gcc version for Ubuntu 16.04 is 5.4.0 (for CUDA 10.1), can you try compiling with that?

**Comment by OswArti** [comment]
To compile with gcc 5 to solve the problem of incompatibility between CUDA 10.1 and GNU 8.4.0. 

To run different versions of gcc as default  create
a local bin directory:

# Create the directory
mkdir ~/bin-defaults

# Add it in front of  your path so it's searched first
export PATH=~/bin-defaults:$PATH

Drop in symlinks to the appropriate version:

ln -s /usr/bin/gcc-5 ~/bin-defaults/gcc
ln -s /usr/bin/g++-5 ~/bin-defaults/g++

Now since that directory is first in your path, you will  run gcc-5 by 
default, and all the various configure scripts should see it first.

**Comment by jowens** [comment]
Great! Does this fix your build problem?

**Comment by OswArti** [comment]
Yes. Thank you.
