### ISSUE TITLE
[Subgraph Matching]About the generating query graph node exploration sequence

### ISSUE THREAD

**Issue by curiosityyy** [gunrock/gunrock#793]
https://github.com/gunrock/gunrock/blob/06fafd77b39c0c02a7f1bf1945296c650538e1c3/gunrock/app/sm/sm_problem.cuh#L237

I don't think this opertion will add priority to its neighbors. In the for loop at line 210 in sm_problem.cuh, array ```d_m``` is only for checking whether the node is solved.

**Comment by Laurawly** [comment]
@curiosityyy No, the priority of the neighbors are defined as their degree when labels are not given. They are done in sm_enacotr.cuh. https://github.com/gunrock/gunrock/blob/06fafd77b39c0c02a7f1bf1945296c650538e1c3/gunrock/app/sm/sm_enactor.cuh#L94

**Comment by curiosityyy** [comment]
Oh, okay, I will take a look at this code, thanks.
