### ISSUE TITLE
Improving mark-pred validation code

### ISSUE THREAD

**Issue by yzhwang** [gunrock/gunrock#80]
Currently Gunrock has no validation code for mark predecessor in BFS. Actually with the help of label values, we could verify the correctness of predecessor by checking whether its label value is one less than its child. We should add this validation in our BFS/DOBFS code.

**Comment by sgpyc** [comment]
Already added pred validation for BFS, can copy it to DOBFS or simply wait for merging DOBFS into BFS

**Comment by sgpyc** [comment]
https://github.com/gunrock/gunrock/blob/master/tests/bfs/test_bfs.cu#L542
And DOBFS has been merged into BFS.
