### ISSUE TITLE
BFS (master branch) produces wrong result when using idempotence 

### ISSUE THREAD

**Issue by sgpyc** [gunrock/gunrock#81]
on the friendster-10M dataset
command line: ./bin/test_bfs_7.5_x86_64 market /data/gunrock_dataset/large/soc-friendster/soc-friendser_edges_gte_10M.mtx --src=largestdegree --queue-sizing=0 --idempotence
output:
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (2s).

Degree Histogram (124836417 vertices, 1342099766 edges):
    Degree   0: 92939499 (74.45%)
    Degree 2^0: 8626076 (6.91%)
    Degree 2^1: 5727721 (4.59%)
    Degree 2^2: 4440940 (3.56%)
    Degree 2^3: 3746118 (3.00%)
    Degree 2^4: 3136844 (2.51%)
    Degree 2^5: 2373034 (1.90%)
    Degree 2^6: 1561282 (1.25%)
    Degree 2^7: 1050394 (0.84%)
    Degree 2^8: 727210 (0.58%)
    Degree 2^9: 363095 (0.29%)
    Degree 2^10: 113313 (0.09%)
    Degree 2^11: 30885 (0.02%)
    Degree 2^12: 6 (0.00%)

Using highest degree (5214), vertex: 71768985
Source vertex: 71768985
Using 1 GPU: [ 0 ].
Computing reference value ...
CPU BFS finished in 20178.914062 msec. cpu_search_depth: 10

__________________________
[../../gunrock/app/enactor_base.cuh, 2076 @ gpu 0] cudaStreamSynchronize failed (CUDA error 77: an illegal memory access was encountered)
(CUDA error 77 @ GPU 0: an illegal memory access was encountered
(CUDA error 77 @ GPU 0: an illegal memory access was encountered
(CUDA error 77 @ GPU 0: an illegal memory access was encountered
[test_bfs.cu, 402 @ gpu 0] BFS Problem Enact Failed (CUDA error 77: an illegal memory access was encountered)
--------------------------
[../../gunrock/util/array_utils.cuh, 528 @ gpu 0] labels cudaMemcpy D2H failed (CUDA error 77: an illegal memory access was encountered)
[test_bfs.cu, 417 @ gpu 0] BFS Problem Data Extraction Failed (CUDA error 77: an illegal memory access was encountered)
Label Validity: 
INCORRECT: [0]: 0 != -1
result[...0, 0, 0, 0, 0, ...]
reference[...-1, -1, -1, -1, -1, ...]
124836417 errors occurred.

First 40 labels of the GPU result:
[0:0 1:0 2:0 3:0 4:0 5:0 6:0 7:0 8:0 9:0 10:0 11:0 12:0 13:0 14:0 15:0 16:0 17:0 18:0 19:0 20:0 21:0 22:0 23:0 24:0 25:0 26:0 27:0 28:0 29:0 30:0 31:0 32:0 33:0 34:0 35:0 36:0 37:0 38:0 39:0 ]
[../../gunrock/util/array_utils.cuh, 528 @ gpu 0] edges_queued cudaMemcpy D2H failed (CUDA error 77: an illegal memory access was encountered)
[../../gunrock/util/array_utils.cuh, 528 @ gpu 0] nodes_queued cudaMemcpy D2H failed (CUDA error 77: an illegal memory access was encountered)

 [BFS] finished.
 elapsed: 883.1599 ms
 iterations: 3
 rate: 1519.6567 MiEdges/s
 src: 71768985
 nodes_visited: 124836417
 edges_visited: 1342099766
 nodes queued: 2184440

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 11973386240	 124836419	 294165429
	 queue_sizing =	 1.000000 	 2.356407

It's fine when idempotence is not enable
./bin/test_bfs_7.5_x86_64 market /data/gunrock_dataset/large/soc-friendster/soc-friendser_edges_gte_10M.mtx --src=largestdegree --queue-sizing=0
Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays ...
Done reading (2s).

Degree Histogram (124836417 vertices, 1342099766 edges):
    Degree   0: 92939499 (74.45%)
    Degree 2^0: 8626076 (6.91%)
    Degree 2^1: 5727721 (4.59%)
    Degree 2^2: 4440940 (3.56%)
    Degree 2^3: 3746118 (3.00%)
    Degree 2^4: 3136844 (2.51%)
    Degree 2^5: 2373034 (1.90%)
    Degree 2^6: 1561282 (1.25%)
    Degree 2^7: 1050394 (0.84%)
    Degree 2^8: 727210 (0.58%)
    Degree 2^9: 363095 (0.29%)
    Degree 2^10: 113313 (0.09%)
    Degree 2^11: 30885 (0.02%)
    Degree 2^12: 6 (0.00%)

Using highest degree (5214), vertex: 71768985
Source vertex: 71768985
Using 1 GPU: [ 0 ].
Computing reference value ...
CPU BFS finished in 20633.333984 msec. cpu_search_depth: 10

__________________________
--------------------------
Label Validity: 
CORRECT
First 40 labels of the GPU result:
[0:2147483646 1:2147483646 2:2147483646 3:2147483646 4:2147483646 5:2147483646 6:2147483646 7:2147483646 8:2147483646 9:2147483646 10:2147483646 11:2147483646 12:2147483646 13:2147483646 14:2147483646 15:2147483646 16:2147483646 17:2147483646 18:2147483646 19:2147483646 20:2147483646 21:2147483646 22:2147483646 23:2147483646 24:2147483646 25:2147483646 26:2147483646 27:2147483646 28:2147483646 29:2147483646 30:2147483646 31:2147483646 32:2147483646 33:2147483646 34:2147483646 35:2147483646 36:2147483646 37:2147483646 38:2147483646 39:2147483646 ]

 [BFS] finished.
 elapsed: 4048.1558 ms
 iterations: 10
 rate: 331.5336 MiEdges/s
 src: 71768985
 nodes_visited: 124836417
 edges_visited: 1342099766
 nodes queued: 37758736
 edges queued: 1336164886

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 11822899200	 124836419	 1092954680
	 queue_sizing =	 1.000000 	 8.755095

**Comment by yzhwang** [comment]
@sgpyc I tracked the bug and it seems that the problem is triggered by this line:
https://github.com/gunrock/gunrock/blob/master/gunrock/oprtr/edge_map_partitioned/kernel.cuh#L210
my_id is bounded by max_edge, which is set to the current frontier length. I couldn't find the allocation code for scanned_edges, but I guess is that the frontier_length is too large and the preallocated scanned_edges is not large enough. Could you point me to the allocation code for scanned_edges? Is it in base_enactor.cuh?

**Comment by sgpyc** [comment]
@yzhwang the size of scanned_edges is checked here https://github.com/gunrock/gunrock/blob/dev/gunrock/app/bfs/bfs_enactor.cuh#L309 , it will be at least equal to current frontier length. You can check whether that line is called or what's the size it requested there.

**Comment by yzhwang** [comment]
@sgpyc Thanks! I think the scanned_edges is alright. From another run with --v I got the attached results. First error happened after this line:
0    2   0   stage3  1   Queue_Length = 1086842
[../../gunrock/app/enactor_base.cuh, 2076 @ gpu 0] cudaStreamSynchronize failed (CUDA error 77: an illegal memory access was encountered)
seems to be related to streams[].
[result.txt](https://github.com/gunrock/gunrock/files/75350/result.txt)

**Comment by sgpyc** [comment]
Now it has (almost) no issue after solving the traversal-mode=1 bug, works under single or multiple-GPU.
