### ISSUE TITLE
Q: Should cmake [subdirectory] be able to generate Makefile?

### ISSUE THREAD

**Issue by ctcyang** [gunrock/gunrock#82]
Currently CMake shows an error if cmake [subdirectory] is called from command-line:
CMake Error at CMakeLists.txt:15 (CUDA_ADD_EXECUTABLE):
  Unknown CMake command "CUDA_ADD_EXECUTABLE".

Even if find_package(CUDA) is added to the CMakeLists.txt in the subdirectory, another error message pops up:
  Cannot find source file:
    /home/ctcyang/gunrock_build/gunrock/tests/bfs/gunrock/util/test_utils.cu

which is due to the relative path variable ${CMAKE_SRC_PATH}. My question is whether the functionality of cmake [subdirectory] is possible to implement or even worth implementing.

**Comment by neoblizz** [comment]
This was added with 0.4 release, to compile individual primitives using CMake: http://gunrock.github.io/gunrock/doc/latest/building_gunrock.html#compilation

* **GUNROCK_BUILD_APPLICATIONS** (default: ON) - Set off to only build one of the following primitive (GUNROCK\_APP\_* must be set on to build if this option is turned off.)
  * **GUNROCK_APP_BC** (default: OFF)
  * **GUNROCK_APP_BFS** (default: OFF)
  * **GUNROCK_APP_CC** (default: OFF)
  * **GUNROCK_APP_PR** (default: OFF)
  * **GUNROCK_APP_SSSP** (default: OFF)
  * **GUNROCK_APP_DOBFS** (default: OFF)
  * **GUNROCK_APP_HITS** (default: OFF)
  * **GUNROCK_APP_SALSA** (default: OFF)
  * **GUNROCK_APP_MST** (default: OFF)
  * **GUNROCK_APP_WTF** (default: OFF)
  * **GUNROCK_APP_TOPK** (default: OFF)

Discussed @ stackoverflow: https://stackoverflow.com/q/35732776/5729690
