### ISSUE TITLE
Data race in color_enactor.cuh

### ISSUE THREAD

**Issue by AKKamath** [gunrock/gunrock#827]
**Summary:**
There seems to be a data race in color_enactor.cuh at lines 109, 110, 118 and 121.
colors[v] is being set on lines 118 and 121 while colors[u] is being read on lines 109 and 110 causing the race.

    for (SizeT e = start_edge; e < start_edge + num_neighbors; e++) {
        VertexT u = graph.CsrT::GetEdgeDest(e);
       
        if ((util::isValid(**colors[u]**)) && (**colors[u]** != color + 1) &&
                (**colors[u]** != color + 2) ||
            (v == u))
          continue;
        if (rand[v] <= rand[u]) colormax = false;
        if (rand[v] >= rand[u]) colormin = false;
      }

      if (colormax) { 
        **colors[v]** = color + 1; 
        return false; 
      } else if (colormin) { 
        **colors[v]** = color + 2; 
        return false;

**Comment by neoblizz** [comment]
In this case, it doesn't matter as we iterate till all vertices are assigned a color per JPL algorithm. Lines 109 and 110 are simply checking the neighbor's colors, and lines 118 and 121 are assigning colors to the active vertex if it is the minimum or maximum random number. If the neighbor is also an active vertex in another thread, we assume that its random number will likely not be the same as the vertex, and if it is, any "conflicts" can be fixed at the very end. Here, it doesn't matter which thread "wins", as this will be iterated on until all vertices have assigned colors, and no vertex shares the color with its neighbor.
