### ISSUE TITLE
pagerank compile errors (OS X, clang)

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#83]
Presumably related to @sgpyc's recent checkins. I'm nervous about in-progress code being checked into master. @yzhwang shouldn't that go into dev instead? 

Compile errors here: https://gist.github.com/jowens/34bab2ee0406599367bf

**Comment by yzhwang** [comment]
I agree. @sgpyc If it's possible. Could you first cherrypick or merge the pagerank checkin yesterday into dev branch then revert the master commit? (The dev branch has been merged with master last week, so if you have any other new comments, please make them into dev too)

**Comment by jowens** [comment]
Yeah, there's a lot of broken builds in master on OS X currently, not just PageRank. (MST has never worked properly on OS X.)

```
46% tests passed, 7 tests failed out of 13

Total Test time (real) =   6.79 sec

The following tests FAILED:
	  6 - TEST_DOBFS (Not Run)
	  8 - TEST_MST (Not Run)
	  9 - SHARED_LIB_TEST_BFS (Not Run)
	 10 - SHARED_LIB_TEST_BC (Not Run)
	 11 - SHARED_LIB_TEST_CC (Not Run)
	 12 - SHARED_LIB_TEST_SSSP (Not Run)
	 13 - SHARED_LIB_TEST_PAGERANK (Not Run)
```

**Comment by yzhwang** [comment]
Let me fix it. I plan to merge dev with master again (which should be easy), and then revert 5 commits from YC, then cherrypick John's latest commit back to master. Just FYI.

**Comment by jowens** [comment]
It was weird that my latest commit wasn't merged to master a week ago ... that's a fix I made in dev months ago.

**Comment by yzhwang** [comment]
That's because I was merging master back to dev to keep dev up-to-date. But if it was an old commit in dev, should have been merged into master before the v0.3 release. Carl did something to the repo last week and destroyed the master branch (brought it back to July), but later he fixed it. Might be related to that change too. For what I am sure, now (after I finish the things I said in the previous comment), master and dev should identical, except the latest 5 commits by YC. Let's have a discussion next quarter to finalize an official best practice for dev in git :-).

**Comment by jowens** [comment]
@ctcyang! Destroyer of branches!

**Comment by jowens** [comment]
My impression on our best-practice was:
- Master should correspond to actual releases, i.e., what's checked into master should have a version x.y.z. It should of course be stable and pass ctest. It should give us stable but good performance.
- Dev should also be stable and pass ctest. 
- If you're making changes that will break something, then make your own branch, work in it until it passes ctest, then merge it into dev.

**Comment by yzhwang** [comment]
I've finished the process. @sgpyc If you have uncommited change in your current master local repo, please "git stash" then "git stash branch dev" to move them to dev. Other than that, everything should be back to normal in master. @jowens Does master's MST never work on OS X? If so please open another issue.

**Comment by jowens** [comment]
Best practice issue filed as https://github.com/gunrock/gunrock/issues/85

**Comment by sgpyc** [comment]
Sorry for messing with the master vs. dev thing. Working on dev now.
@jowens Do you have the actual error message from the compilation? I got something saying pthread_barrier not supported in the x86_64 architecture (or similar) on latest OS X with clang and cuda 7.5 (when compiling from gunrock/tests/bfs and redirecting the boost and openmp include / lib paths to the correct place). Both dev and master break (using the default cmake and make method) on my mac, saying string.h not found (-stdlib=libc++ may correct this). I think clang changes a bit in OS X 10.11, will figure out how to change accordingly.

**Comment by sgpyc** [comment]
@yzhwang thanks a lot for the reverting / merging.

**Comment by jowens** [comment]
@sgpyc [errors.txt](https://github.com/gunrock/gunrock/files/75230/errors.txt)

**Comment by sgpyc** [comment]
@jowens Oh, I haven't changed the pr_app.cu file yet. Will do that after the normalized pr is tested (GPU version coded, working on CPU version for result comparison).

**Comment by jowens** [comment]
@sgpyc gunrock/util/misc_utils has pthread calls that are specific to Apple (I added 'em last summer camp when I was making it work on Mac). See if those calls are getting compiled in for you? I don't actually see any calls called `pthread_barrier` though, instead they're all `pthread_barrier_X`.

**Comment by jowens** [comment]
@sgpyc Sure, no problem on pr_app, but if you're going to make changes that break the dev build, make your own branch and develop there and merge them back in when the build works again.

**Comment by jowens** [comment]
Current status on ctest on dev branch/OS X (just FYI):

```
mission-burrito 9392$ ctest
Test project /Users/jowens/Documents/working/gunrock-build
      Start  1: TEST_BFS
 1/13 Test  #1: TEST_BFS .........................   Passed    0.87 sec
      Start  2: TEST_BC
 2/13 Test  #2: TEST_BC ..........................   Passed    0.70 sec
      Start  3: TEST_CC
 3/13 Test  #3: TEST_CC ..........................   Passed    0.69 sec
      Start  4: TEST_SSSP
 4/13 Test  #4: TEST_SSSP ........................   Passed    0.61 sec
      Start  5: TEST_PAGERANK
 5/13 Test  #5: TEST_PAGERANK ....................   Passed    1.04 sec
      Start  6: TEST_DOBFS
 6/13 Test  #6: TEST_DOBFS .......................   Passed    0.69 sec
      Start  7: TEST_TOPK
 7/13 Test  #7: TEST_TOPK ........................   Passed    0.56 sec
      Start  8: TEST_MST
Could not find executable /Users/jowens/Documents/working/gunrock-build/bin/minimum_spanning_tree
 8/13 Test  #8: TEST_MST .........................***Not Run   0.00 sec
      Start  9: SHARED_LIB_TEST_BFS
```
(hangs on test 9 forever)

**Comment by jowens** [comment]
@yzhwang @sgpyc It appears to me that test 9 also hangs on mario for the dev branch.

**Comment by yzhwang** [comment]
Yep. That started to happen after I separate BFS's data load, run, and extraction process. I'm still trying to figure out the problem. I should change the test to prevent this.

**Comment by jowens** [comment]
@neoblizz is this in the dev build (if I build the dev build, it'll run MST)?

**Comment by neoblizz** [comment]
Yes, this is the dev build. https://github.com/gunrock/gunrock/blob/dev/CMakeLists.txt#L280

**Comment by jowens** [comment]
MST passes on dev on OS X.
