### ISSUE TITLE
Codify best practices wrt git and branches for Gunrock development

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#85]
My impression on our best-practice was:
- We are trying to follow this: http://nvie.com/posts/a-successful-git-branching-model/
- Master should correspond to actual releases, i.e., what's checked into master should have a version x.y.z. It should of course be stable and pass ctest. It should give us stable but good performance.
- Dev should also be stable and pass ctest. But it might have features in it that haven't been integrated into master yet. Generally we work within dev.
- If you're making changes that will break something, then make your own branch, work in it until it passes ctest, then merge it into dev.
- We use semantic versioning. http://semver.org/

**Comment by neoblizz** [comment]
We need to documents this and some other things for gunrock developers.

**Comment by neoblizz** [comment]
New method suggested, let's move the discussion there: https://github.com/gunrock/gunrock/pull/267
