### ISSUE TITLE
Overhead of CTA launches

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#854]
Hi,
As I profile a BFS for road_usa on 3080, I see that 
```
mgpu::launch_box_cta_k<mgpu::launch_params_t<512, 3, 3, 0>, mgpu::scan_event<(mgpu::scan_type_… 
```
takes a lot of GPU time. When I check the source code [here](https://github.com/moderngpu/moderngpu/blob/master/src/moderngpu/launch_params.hxx#L76), I see that this kernel itself doesn't do any thing, but a call to `restrict_forward`. So, I wonder why it is listed in the profiler's output. Any idea about that?

**Comment by neoblizz** [comment]
@mahmoodn what's the full signature, I believe that is actually pointing to the `scan` kernel and the `launch_box` is just the parameter type passed in. And `scan` can be a costly kernel. :)

**Comment by mahmoodn** [comment]
This is the name
```
void mgpu::launch_box_cta_k<mgpu::launch_params_t<512, 3, 3, 0>, mgpu::scan_event<(mgpu::scan_type_t)1, 
mgpu::launch_box_t<mgpu::arch_30<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, 
mgpu::arch_35<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_50<mgpu::launch_cta_t<256, 7, 7, 0>, 
mgpu::empty_t>, mgpu::arch_60<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_70<mgpu::launch_cta_t<256, 7, 
7, 0>, mgpu::empty_t>, mgpu::arch_75<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t> >, unsigned int*, unsigned int*, 
mgpu::plus_t<unsigned int>, unsigned int*>(unsigned int*, int, unsigned int*, mgpu::plus_t<unsigned int>, unsigned int*, 
mgpu::context_t&, CUevent_st*)::{lambda(int, int)#3}>(mgpu::scan_event<(mgpu::scan_type_t)1, 
mgpu::launch_box_t<mgpu::arch_30<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, 
mgpu::arch_35<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_50<mgpu::launch_cta_t<256, 7, 7, 0>, 
mgpu::empty_t>, mgpu::arch_60<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_70<mgpu::launch_cta_t<256, 7,
 7, 0>, mgpu::empty_t>, mgpu::arch_75<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t> >, unsigned int*, unsigned int*, 
mgpu::plus_t<unsigned int>, unsigned int*>(unsigned int*, int, unsigned int*, mgpu::plus_t<unsigned int>, unsigned int*, 
mgpu::context_t&, CUevent_st*)::{lambda(int, int)#3}, int), Block Size 512, Grid Size 1, Device 0, 12524 invocations
```
If you say that it is pointing to a `scan`, then why scan kernel is not mentioned?

**Comment by mahmoodn** [comment]
BTW, I run the latest version on RTX 3080 (sm_86). I wasn't able to specify GUNROCK_GENCODE_SM86=ON and it seems that it ses `arch_70` as can be seen in the previous post. Does that matter?

And one more question. With the long name in the kernel, where can I find the main kernel that this `launch_box_cta_k` has called?

**Comment by neoblizz** [comment]
> This is the name
> 
> ```
> void mgpu::launch_box_cta_k<mgpu::launch_params_t<512, 3, 3, 0>, mgpu::scan_event<(mgpu::scan_type_t)1, 
> mgpu::launch_box_t<mgpu::arch_30<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, 
> mgpu::arch_35<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_50<mgpu::launch_cta_t<256, 7, 7, 0>, 
> mgpu::empty_t>, mgpu::arch_60<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_70<mgpu::launch_cta_t<256, 7, 
> 7, 0>, mgpu::empty_t>, mgpu::arch_75<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t> >, unsigned int*, unsigned int*, 
> mgpu::plus_t<unsigned int>, unsigned int*>(unsigned int*, int, unsigned int*, mgpu::plus_t<unsigned int>, unsigned int*, 
> mgpu::context_t&, CUevent_st*)::{lambda(int, int)#3}>(mgpu::scan_event<(mgpu::scan_type_t)1, 
> mgpu::launch_box_t<mgpu::arch_30<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, 
> mgpu::arch_35<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_50<mgpu::launch_cta_t<256, 7, 7, 0>, 
> mgpu::empty_t>, mgpu::arch_60<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t>, mgpu::arch_70<mgpu::launch_cta_t<256, 7,
>  7, 0>, mgpu::empty_t>, mgpu::arch_75<mgpu::launch_cta_t<256, 7, 7, 0>, mgpu::empty_t> >, unsigned int*, unsigned int*, 
> mgpu::plus_t<unsigned int>, unsigned int*>(unsigned int*, int, unsigned int*, mgpu::plus_t<unsigned int>, unsigned int*, 
> mgpu::context_t&, CUevent_st*)::{lambda(int, int)#3}, int), Block Size 512, Grid Size 1, Device 0, 12524 invocations
> ```
> 
> If you say that it is pointing to a `scan`, then why scan kernel is not mentioned?

It is mentioned, it is called `scan_event`, see below;
https://github.com/moderngpu/moderngpu/blob/master/src/moderngpu/kernel_scan.hxx#L11-L15
```cpp
template<scan_type_t scan_type = scan_type_exc, 
  typename launch_arg_t = empty_t, typename input_it, 
  typename output_it, typename op_t, typename reduction_it>
void scan_event(input_it input, int count, output_it output, op_t op, 
  reduction_it reduction, context_t& context, cudaEvent_t event) {
```
You can compare the parameters with the ones from the signature you gave me;
```cpp
(unsigned int*, int, unsigned int*, mgpu::plus_t<unsigned int>, unsigned int*, 
mgpu::context_t&, CUevent_st*)::{lambda(int, int)#3}, int)
```

I believe this is how it matches;
```
unsigned int* = input_it input
int = int count
unsigned int* = output_it output
lambda = op_t op
mgpu::context_t = context_t& context
int = cudaEvent_t event
```

It also tells you the scan type its using is `1`, with a `plus_t` reduction operator. 
`launch_box_cta_k` is pretty much just the template parameter being passed in, which are the settings to launch the kernel, like grid/block size, etc.

**Comment by neoblizz** [comment]
> BTW, I run the latest version on RTX 3080 (sm_86). I wasn't able to specify GUNROCK_GENCODE_SM86=ON and it seems that it ses `arch_70` as can be seen in the previous post. Does that matter?
> 
> And one more question. With the long name in the kernel, where can I find the main kernel that this `launch_box_cta_k` has called?



> BTW, I run the latest version on RTX 3080 (sm_86). I wasn't able to specify GUNROCK_GENCODE_SM86=ON and it seems that it ses `arch_70` as can be seen in the previous post. Does that matter?

We have to add support for SM architecture `86`; https://github.com/gunrock/gunrock/blob/master/CMakeLists.txt#L160-L161 Maybe @crozhon can help you with that. Although it should be simple to modify the CMakeLists.txt file to add `86` just like `80`.

**Comment by crozhon** [comment]
Like @neoblizz says the kernel is `scan_event`. The `launch_box` just holds things like granularity of thread and how many threads you launch.

If you want to specify GENCODE_SM86, you'll need to set it up in CMake yourself. 

Specify the compiler option
```
set(GENCODE_SM86
  -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_86,code=compute_86)
 ```
 
Add a CMake option to flip the switch:
```
option(GUNROCK_GENCODE_SM86
  "ON to generate code for Compute Capability 8.6 devices"
  OFF)
  ```

And add the logic so if the option is set, the `GENCODE` is set properly
```
if (GUNROCK_GENCODE_SM80)
  set(GENCODE ${GENCODE} ${GENCODE_SM80})
endif(GUNROCK_GENCODE_SM80)
```

You'll have some effect on performance. It depends on a lot. You can use `cuobjdump` to get an idea of what is in your final binary.

**Comment by mahmoodn** [comment]
Thanks for the responses. If I understand correctly, the scan_event is not heavy but the kernel that launches CTAs for that is actually heavy. Otherwise, I expect to see scan_event, itself, in the sorted GPU time list. Is that correct?

**Comment by crozhon** [comment]
> Thanks for the responses. If I understand correctly, the scan_event is not heavy but the kernel that launches CTAs for that is actually heavy. Otherwise, I expect to see scan_event, itself, in the sorted GPU time list. Is that correct?

No worries. It's just hard to describe. 

The kernels are templated based upon the 'launch' struct you pass in. Suppose I have a few different variants of 'launch' with a different thread granularity in each. 

Code for a new function is generated (through a template parameter) for each 'launch'. 

So it is the scan_event that is taking a long time, but it's _this version_ of scan event, generated to use this number of threads via this 'launch_box'.  On its own, the code for 'scan_event' is not complete code - it includes a template parameter that has to be placed inside the generated code first.

**Comment by mahmoodn** [comment]
Thanks for that. I understand it.
