### ISSUE TITLE
Running KNN over a large dataset

### ISSUE THREAD

**Issue by nayakajay** [gunrock/gunrock#855]
There appears to be a "nearest-neighbour" folder in dataset, with a generator.cpp file. I wanted to know how to use it to create a set that takes a long time to run on GPU (atleast 1s). 

I compiled it using c++, and to the scanf gave 100,100,100 as inputs and store it in custom-pts.

Then to the knn binary, I run with the following executable
```
$> ./a.out > custom-pts
$> bin/knn market --labels-file /custom-pts
```

I get the following output
```
Points File Input: gunrock/dataset/nearest_neighbors/custom-pts
Loading Labels into an array ...
Reading from gunrock/dataset/nearest_neighbors/custom-pts:
table is not tranposed
Number of labels 482, dimension 2
Done parsing (0 s).
number of points 482, k 10
__________________________
______ CPU Reference _____
Host Allocation done.
KNNs Allocation done.
Distance/Keys and Device management done.
Main algroithm loop done.
Synchronized all GPUs.
Moved KNNs from DEVICE to HOST.
Copy KNNs device result to output KNNs array.
Clean-up GPU Arrays:: keys, distance done.
Clean-up CPU Arrays:: keys, distance done.
Clean-up CPU Arrays:: knns_d[*] done.
Clean-up done.
--------------------------
 Elapsed: 179.210907
__________________________
==============================================
64bit-VertexT=false 64bit-SizeT=false 64bit-ValueT=false undirected=false advance-mode=LB
data_size = 4
Using advance mode LB
Using filter mode CULL
__________________________
[gunrock/gunrock/app/enactor_loop.cuh, 646 @ gpu 0] FullQueue_Core failed. (CUDA error 700: an illegal memory access was encountered)
[gunrock/gunrock/app/enactor_base.cuh, 519 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[gunrock/gunrock/app/knn/knn_enactor.cuh, 773 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[gunrock/gunrock/app/knn/knn_app.cu, 165 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[gunrock/gunrock/util/array_utils.cuh, 546 @ gpu 0] knns cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[gunrock/gunrock/app/knn/knn_problem.cuh, 106 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[gunrock/gunrock/util/array_utils.cuh, 546 @ gpu 0] data_slices[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[gunrock/gunrock/app/knn/knn_problem.cuh, 231 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[gunrock/examples/knn/test_knn.cu, 147 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
```

Am I doing something wrong?

**Comment by nayakajay** [comment]
I am not sure if the issue label is correct; type "question." Should I edit and add a different label?

**Comment by agalup** [comment]
Hi @nayakajay, thank you for posting the issue. I believe, problem is fixed now. 

To run the code longer, please generate bigger test, for example use generator.cpp with input "1000 1000 1000" and increase parameter "k" (the number of the nearest neighbors). Default is k = 10. For giving example you could run: 

bin/knn market --labels-file /custom-pts --k=4979

**Comment by neoblizz** [comment]
The patch is in `dev` branch btw.

**Comment by nayakajay** [comment]
I checked out the ```dev``` branch and ran the code as mentioned. There are no errors (thanks!), but the kernel is taking very long to finish/terminate. The example @agalup mentions did not terminate even after a day.
I tried applying just the patch from [pull-request 872](https://github.com/gunrock/gunrock/pull/872/files) after checking out the ```master``` branch; it still takes long time to run. Even when I give the argument as ```k=300``` for the file generated using "1000 1000 1000", the kernel seems to not terminate. I am under the impression that it should not run for this long.
For ```k=200```, the kernel terminates though.

**Comment by nayakajay** [comment]
@neoblizz should I be opening this as another issue? If possible, I just need an estimate of how long the below kernel will run for. Running for long hours and not terminating is my concern.
Yes, it definitely depends on the GPU, I have access to a RTX Titan 24GB, 72 SM GPU. 
Driver version: 450.51, Runtime: 11.0

```
g++ generator.cpp -o a.out
/* Giving 1000 1000 1000 as inputs*/
./a.out > custom-pts 
bin/knn market --labels-file /custom-pts --k=4979
```

**Comment by agalup** [comment]
@nayakajay I am sorry for late answer.

**Comment by jowens** [comment]
For the record, what does `--quick` do?

**Comment by agalup** [comment]
'--quick' option turns the validation of a GPU result off, is used in testing. Without `--quick`, the application computes two results: one on the CPU with the use of a single thread (slow) and the another one on the GPU. Then compares the results.

**Comment by nayakajay** [comment]
Thanks @agalup, as you mentioned on skipping the CPU check, it terminates in ~32s.
