### ISSUE TITLE
set --device=0,1,2,3 will Segmentation fault

### ISSUE THREAD

**Issue by jiangxiaobin96** [gunrock/gunrock#878]
Only can set --device=0. if set --device=0,1,2,3 or more, the program will print segmentation fault.

**Comment by jowens** [comment]
What is the Gunrock version, what CUDA version, what GPU, and especially, what command line?

**Comment by crozhon** [comment]
@jiangxiaobin96 Which branch were you encountering this on? I remember fixing a bug like this a decent while ago.

**Comment by jiangxiaobin96** [comment]
The master.
CUDA version : 10.2
GPU : NVIDIA V100
command line : ./sssp market {filedir}.mtx --src=0 --undirected --iteration-num=10 --device=0,1,2,3 ...

**Comment by crozhon** [comment]
Could you try dev branch instead? Your issue may already be fixed.

**Comment by crozhon** [comment]
Are you still having issues? Happy to take a closer look if you're still hitting that seg. fault.
