### ISSUE TITLE
Graph features

### ISSUE THREAD

**Issue by mahmoodn** [gunrock/gunrock#883]
Hi
In the paper, I see some information about road_usa, e.g. large diameter and small node degree. However, I don't see such information about soc-twitter-2010. I searched the web for that but didn't find it. In the output of Gunrock I see that the vertex degree distribution is less than road-usa. How to extract this information?

**Comment by jowens** [comment]
I think it's this one:

http://networkrepository.com/soc-twitter-2010.php

What are you specifically wanting to know here?

**Comment by mahmoodn** [comment]
Yes I have seen that page. Don't know why but the network data preview is always "loading data", so I don't know if that section answers my question. 
I am looking for similar metrics like road_usa. Considering about 28M vertices and 260M edges, is the graph diameter large or small?

**Comment by jowens** [comment]
Because it's a social network, it's almost certainly scale-free and has a relatively small diameter. You could probably figure this out yourself if you wanted to run a few hundred BFSes from random nodes and just extract the largest depth you see?

**Comment by mahmoodn** [comment]
OK I got it. Thanks.
