### ISSUE TITLE
docs need to say how we're calculating MTEPS

### ISSUE THREAD

**Issue by jowens** [gunrock/gunrock#90]
We need to be precise about this. We want to make sure that if anyone else is using our MTEPS numbers, they calculate their MTEPS in the same way that we do. Good new-student project.

**Comment by neoblizz** [comment]
Discussed in issues: #226 (public) and https://github.com/owensgroup/gunrock-TOPC-paper/issues/19 (private). Mentioned in TOPC paper available @ https://arxiv.org/abs/1701.01170. 

**Final documentation available at:** http://gunrock.github.io/gunrock/doc/latest/md_methodology.html
