### ISSUE TITLE
Gunrock build error

### ISSUE THREAD

**Issue by ishitachaturvedi** [gunrock/gunrock#905]
**Summary:**
On running make on gunrock the following error is seen-
/gunrock/gunrock/util/reduce_device.cuh(86): error: too few arguments for class template "cub::DispatchSegmentedReduce"

/gunrock/gunrock/util/reduce_device.cuh(100): error: too few arguments for class template "cub::DispatchSegmentedReduce"

2 errors detected in the compilation of "/gunrock/gunrock/app/hits/hits_app.cu".
CMake Error at gunrock_generated_hits_app.cu.o.RelWithDebInfo.cmake:280 (message):
  Error generating file
 /gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o
**Reproducibility:**
Always

**To Reproduce:**
git clone --recursive https://github.com/gunrock/gunrock
cd gunrock
mkdir build && cd build
cmake ..
make

**Expected Behavior:**
Gunrock should have built.

**Actual Results:**
Gunrock does not build.

**System Configuration:**

GPU: TITANV
CPU: Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
OS: Ubuntu 18.04.1 LTS
Cuda compilation tools, release 11.6, V11.6.55
NVIDIA-SMI 415.13
Driver Version: 415.13
CUDA Version: 11.6
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by crozhon** [comment]
See https://github.com/gunrock/gunrock/issues/892#issuecomment-940222665 maybe? 

I think your GCC version is insufficient, so you're getting template errors. Try GCC-9.

**Comment by ishitachaturvedi** [comment]
Changed to - gcc (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
Error -
2 errors detected in the compilation of "gunrock/gunrock/app/hits/hits_app.cu".
CMake Error at gunrock_generated_hits_app.cu.o.RelWithDebInfo.cmake:280 (message):
  Error generating file
  gunrock/build/gunrock/CMakeFiles/gunrock.dir/app/hits/./gunrock_generated_hits_app.cu.o


gunrock/CMakeFiles/gunrock.dir/build.make:2389: recipe for target 'gunrock/CMakeFiles/gunrock.dir/app/hits/gunrock_generated_hits_app.cu.o' failed
make[2]: *** [gunrock/CMakeFiles/gunrock.dir/app/hits/gunrock_generated_hits_app.cu.o] Error 1
CMakeFiles/Makefile2:2178: recipe for target 'gunrock/CMakeFiles/gunrock.dir/all' failed
make[1]: *** [gunrock/CMakeFiles/gunrock.dir/all] Error 2
Makefile:145: recipe for target 'all'
 failed
make: *** [all] Error 2

**Comment by crozhon** [comment]
Did you create a fresh build directory after setting CC and CXX? 

I just cloned fresh and compiled with GCC-9, and I didn't have any issues.

**Comment by ishitachaturvedi** [comment]
I did. Somehow the issue still persists for me.

**Comment by crozhon** [comment]
Can you provide the output from CMake? Should look like:
```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-9 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-9 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "11.5", minimum required is "9.0") 
-- Boost version: 1.78.0
-- Found Boost: /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.58")  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenMP
-- Downloading CPM.cmake to /home/charlie/src/gunrock/build/cmake/CPM_0.27.5.cmake
-- CPM: adding package RapidJSON@1.1.0 (v1.1.0-489-g4b3d7c2f)
CMake Deprecation Warning at externals/rapidjson/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found Doxygen: /usr/bin/doxygen (found version "1.9.3") found components: doxygen dot 
CMake Deprecation Warning at externals/rapidjson/example/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found GTestSrc: /home/charlie/src/gunrock/externals/rapidjson/thirdparty/gtest/googletest  
CMake Deprecation Warning at externals/rapidjson/thirdparty/gtest/googletest/CMakeLists.txt:53 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found PythonInterp: /usr/bin/python (found version "3.10.1") 
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- CPM: adding package ModernGPU@2.12 (v2.12_june_8_2016-16-g2b39855)
-- CPM: adding package CUB@1.8.0 (1.8.0)
-- Found rapidjson header files in /usr/include
-- Listing chosen GENCODE commands
-- -gencode=arch=compute_70,code=sm_70
-- -gencode=arch=compute_70,code=compute_70
-- Project Added: bc
-- Project Added: bfs
-- Project Added: color
-- Project Added: geo
-- Project Added: hits
-- Project Added: knn
-- Project Added: louvain
-- Project Added: pr
-- Project Added: pr_nibble
-- Project Added: proj
-- Project Added: rw
-- Project Added: sage
-- Project Added: sm
-- Project Added: snn
-- Project Added: ss
-- Project Added: sssp
-- Project Added: tc
-- Project Added: vn
-- Project Added: lp
-- Configuring done
-- Generating done
-- Build files have been written to: src/gunrock/build
```

**Comment by ishitachaturvedi** [comment]
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-9 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-9 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "11.6", minimum required is "9.0") 
-- Could NOT find Boost
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least version "1.58")
CMake Warning at cmake/FindBoost.cmake:11 (MESSAGE):
  Boost was requested but support was not found, run

    `sudo apt-get install libboost1.58-all-dev` `/dep/install_boost.sh` for installation.
Call Stack (most recent call first):
  CMakeLists.txt:53 (include)


-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenMP
-- Downloading CPM.cmake to /scratch/ishitac/gpu_benchmarks/gunrock/build/cmake/CPM_0.27.5.cmake
-- CPM: adding package RapidJSON@1.1.0 (v1.1.0-489-g4b3d7c2f)
CMake Deprecation Warning at externals/rapidjson/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- No Doxygen found. Documentation won't be built
CMake Deprecation Warning at externals/rapidjson/example/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found GTestSrc: /scratch/ishitac/gpu_benchmarks/gunrock/externals/rapidjson/thirdparty/gtest/googletest  
CMake Deprecation Warning at externals/rapidjson/thirdparty/gtest/googletest/CMakeLists.txt:53 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- CPM: adding package ModernGPU@2.12 (v2.12_june_8_2016-16-g2b39855)
-- CPM: adding package CUB@1.8.0 (1.8.0)
-- Found rapidjson header files in /scratch/ishitac/gpu_benchmarks/gunrock/externals/rapidjson/include
-- Listing chosen GENCODE commands
-- -gencode=arch=compute_70,code=sm_70
-- -gencode=arch=compute_70,code=compute_70
-- Project Added: bc
-- Project Added: bfs
-- Project Added: color
-- Project Added: geo
-- Project Added: hits
-- Project Added: knn
-- Project Added: louvain
-- Project Added: pr
-- Project Added: pr_nibble
-- Project Added: proj
-- Project Added: rw
-- Project Added: sage
-- Project Added: sm
-- Project Added: snn
-- Project Added: ss
-- Project Added: sssp
-- Project Added: tc
-- Project Added: vn
-- Project Added: lp
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/ishitac/gpu_benchmarks/gunrock/build

**Comment by crozhon** [comment]
It's the missing Boost. Just uninstalled the package to confirm. I get your same error about "too few arguments for a class template." So installing libboost-dev via the package manager should solve your problem.

It used to be optional, but I think we're building things slightly differently. Let me know if that fixes it, and thanks for finding.

**Comment by ishitachaturvedi** [comment]
I installed Boost. cmake .. comand gives-
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-9 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-9 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "11.6", minimum required is "9.0") 
-- Boost version: 1.65.1
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.58")  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenMP
-- Downloading CPM.cmake to /scratch/ishitac/gpu_benchmarks/gunrock/build/cmake/CPM_0.27.5.cmake
-- CPM: adding package RapidJSON@1.1.0 (v1.1.0-489-g4b3d7c2f)
CMake Deprecation Warning at externals/rapidjson/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- No Doxygen found. Documentation won't be built
CMake Deprecation Warning at externals/rapidjson/example/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found GTestSrc: /scratch/ishitac/gpu_benchmarks/gunrock/externals/rapidjson/thirdparty/gtest/googletest  
CMake Deprecation Warning at externals/rapidjson/thirdparty/gtest/googletest/CMakeLists.txt:53 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- CPM: adding package ModernGPU@2.12 (v2.12_june_8_2016-16-g2b39855)
-- CPM: adding package CUB@1.8.0 (1.8.0)
-- Found rapidjson header files in /scratch/ishitac/gpu_benchmarks/gunrock/externals/rapidjson/include
-- Listing chosen GENCODE commands
-- -gencode=arch=compute_70,code=sm_70
-- -gencode=arch=compute_70,code=compute_70
-- Project Added: bc
-- Project Added: bfs
-- Project Added: color
-- Project Added: geo
-- Project Added: hits
-- Project Added: knn
-- Project Added: louvain
-- Project Added: pr
-- Project Added: pr_nibble
-- Project Added: proj
-- Project Added: rw
-- Project Added: sage
-- Project Added: sm
-- Project Added: snn
-- Project Added: ss
-- Project Added: sssp
-- Project Added: tc
-- Project Added: vn
-- Project Added: lp
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/ishitac/gpu_benchmarks/gunrock/build


However the error still persists->
/scratch/ishitac/gpu_benchmarks/gunrock/gunrock/util/reduce_device.cuh(86): error: too few arguments for class template "cub::DispatchSegmentedReduce"

/scratch/ishitac/gpu_benchmarks/gunrock/gunrock/util/reduce_device.cuh(100): error: too few arguments for class template "cub::DispatchSegmentedReduce"

2 errors detected in the compilation of "/scratch/ishitac/gpu_benchmarks/gunrock/examples/sage/test_sage.cu".
CMake Error at sage_generated_test_sage.cu.o.RelWithDebInfo.cmake:280 (message):
  Error generating file
  /scratch/ishitac/gpu_benchmarks/gunrock/build/examples/sage/CMakeFiles/sage.dir//./sage_generated_test_sage.cu.o

**Comment by jowens** [comment]
Thank you @crozhon !

**Comment by jowens** [comment]
This actually sounds like the wrong version of CUB.

**Comment by ishitachaturvedi** [comment]
@jowens how do I correct it?

**Comment by crozhon** [comment]
Agreed on CUB. 

Can you re-clone the repository without "--recursive"? That shouldn't be needed anymore.

**Comment by ishitachaturvedi** [comment]
Running cmake on the dev branch gives->
CMake Error at CMakeLists.txt:231:
  Parse error.  Function missing ending ")".  End of file reached.

**Comment by ishitachaturvedi** [comment]
Line 232 should have a OFF) in CMakeLists.txt which was missing in the dev branch. 
After correcting the error gunrock built!

Thank you so much for helping me out :)

**Comment by crozhon** [comment]
Great glad you got it working!
