### ISSUE TITLE
Gunrock run.sh bug

### ISSUE THREAD

**Issue by ishitachaturvedi** [gunrock/gunrock#906]
**Summary:**
running make on benchmarks in example directory and then running run.sh tries to run files not in bin directory

**Reproducibility:**
Always

**To Reproduce:**
Switch to dev branch
Build gunrock
cd gunrock/examples/bf
make
./run.sh

**Expected Behavior:**
should run BFS benchmark 

**Actual Results:**
Tries to run -> 
./bin/test_bfs_10.0_x86_64 market /data/gunrock_dataset/large/coPapersCiteseer/coPapersCiteseer.mtx --src=random --num-runs=10 --direction-optimized=true --advance-mode=TWC,LB,LB_CULL --do-b=0.000001,0.000002,0.000005,0.00001,0.00002,0.00005,0.0001,0.0002,0.0005,0.001,0.002,0.005,0.01,0.02,0.05,0.1,0.2,0.5,1,2,5,10,20,50,100,200,500,1000,2000,5000,10000,20000 --do-a=0.2,0.5,0.05 --device=0 --jsondir=./eval/GUNROCK_v1-0-0_TitanVx1 > ./eval/GUNROCK_v1-0-0_TitanVx1/coPapersCiteseer.do2.txt

Has error ->
./bin/test_bfs_10.0_x86_64: No such file or directory

File in bin directory->
test_bfs_11.6_x86_64

**System Configuration:**

GPU: TITANV
CPU: Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
OS: Ubuntu 18.04.1 LTS
Cuda compilation tools, release 11.6, V11.6.55
NVIDIA-SMI 415.13
Driver Version: 415.13
CUDA Version: 11.6
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by crozhon** [comment]
Thanks for pointing out! Looks like the bit that iterates over ./bin isn't working. Some of the run scripts might require you to update them. In this case just set $EXECUTION to what you expect.
