### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by agalup** [gunrock/gunrock#910]
**Summary:**

Dev branch, [CMakeLists.txt](https://github.com/gunrock/gunrock/blob/9aad94e8d9992a083e939c198337d084322226f3/CMakeLists.txt#L233)

`CMake Error at CMakeLists.txt:231:
  Parse error.  Function missing ending ")".  End of file reached.
`

**Reproducibility:**
Always

**To Reproduce:**
Please add: `OFF)` to  [CMakeLists.txt](https://github.com/gunrock/gunrock/blob/9aad94e8d9992a083e939c198337d084322226f3/CMakeLists.txt#L233)

1. Clone gunrock
2. Switch to the dev branch
3. cd gunrock
4. mkdir build && cd build && cmake ..

**Comment by crozhon** [comment]
Thanks for reporting - should be easy enough to fix.

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/commit/56c2e2b3524bed9d14422d81640d00624b615bae
