### ISSUE TITLE
Number of edges mismatch in the dynamic graph example

### ISSUE THREAD

**Issue by nicklin96** [gunrock/gunrock#911]
I am currently trying to run the codes under ./examples/dynamic_graph , using one of the dataset in the project, DBLP, but it outputs the following log:

> Loading Matrix-market coordinate-formatted graph ...
  Reading from ../../dataset/test//coAuthorsDBLP/coAuthorsDBLP.mtx:
  Parsing MARKET COO format (299067 nodes, 977676 directed edges)...   Done (0 s).
  Writing meta data into ../../dataset/test//coAuthorsDBLP/coAuthorsDBLP.mtx.meta
  Writting edge pairs in binary into ../../dataset/test//coAuthorsDBLP/coAuthorsDBLP.mtx.coo_edge_pairs
  Assigning 1 to all 977676 edges
  Substracting 1 from node Ids...
  Edge doubleing: 977676 -> 1955352 edges
  graph loaded as COO in 0.374235s.
  Converting 299067 vertices, 1955352 directed edges ( ordered tuples) to CSR format...Done (0s).
  Degree Histogram (299067 vertices, 1955352 edges):
    Degree 0: 0 (0.000000 %)
    Degree 2^0: 41376 (13.835027 %)
    Degree 2^1: 102633 (34.317728 %)
    Degree 2^2: 87368 (29.213521 %)
    Degree 2^3: 42746 (14.293118 %)
    Degree 2^4: 17441 (5.831804 %)
    Degree 2^5: 6019 (2.012592 %)
    Degree 2^6: 1324 (0.442710 %)
    Degree 2^7: 156 (0.052162 %)
    Degree 2^8: 4 (0.001337 %)
    __________________________
    --------------------------
    Run 0 elapsed: 0.001536 ms.
    Number of edges mismatch.
    FAILED!

The construction seems OK and make test was passed.
I am using CentOS 7.4 and CUDA 11. My GPU is Titan xp.
Any ideas on where should I have a check?

**Comment by maawad** [comment]
Hi @nicklin96, 

This error message is at the [beginning of validation](https://github.com/gunrock/gunrock/blob/dynamic-graph/examples/dynamic_graph/validation.cuh#L39), so a first check would be to print the number of edges and see how big the difference is. 
> The construction seems OK and make test was passed.

Do you mean that the unit tests passed? The log showing the degree distribution is printed after the graph is loaded from the disk, so I'm not sure if the construction succeeded or not. 


I'll try to reproduce the bug later this week.

**Comment by maawad** [comment]
The dynamic graph unit tests are using google tests. Try this command:
``` bash
gunrock/build$ ./bin/unittests --gtest_filter=dynamicGraph*
```
Correct output looks like this:
```bash
./bin/unittests: unrecognized option '--gtest_filter=dynamicGraph*'
Note: Google Test filter = dynamicGraph*
[==========] Running 9 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 6 tests from dynamicGraph
[ RUN      ] dynamicGraph.buildDirectedWeighted
[       OK ] dynamicGraph.buildDirectedWeighted (351 ms)
[ RUN      ] dynamicGraph.buildUndirectedWeighted
[       OK ] dynamicGraph.buildUndirectedWeighted (64 ms)
[ RUN      ] dynamicGraph.insertUndirectedWeighted
[       OK ] dynamicGraph.insertUndirectedWeighted (71 ms)
[ RUN      ] dynamicGraph.insertDirectedWeighted
[       OK ] dynamicGraph.insertDirectedWeighted (84 ms)
[ RUN      ] dynamicGraph.deleteUndirectedWeighted
[       OK ] dynamicGraph.deleteUndirectedWeighted (88 ms)
[ RUN      ] dynamicGraph.deleteDirectedWeighted
[       OK ] dynamicGraph.deleteDirectedWeighted (73 ms)
[----------] 6 tests from dynamicGraph (731 ms total)

[----------] 3 tests from dynamicGraphIterator
[ RUN      ] dynamicGraphIterator.MultipleBuckets
[       OK ] dynamicGraphIterator.MultipleBuckets (133 ms)
[ RUN      ] dynamicGraphIterator.SingleBucketMultipleChains
[       OK ] dynamicGraphIterator.SingleBucketMultipleChains (99 ms)
[ RUN      ] dynamicGraphIterator.MultipleBucketMultipleChains
[       OK ] dynamicGraphIterator.MultipleBucketMultipleChains (764 ms)
[----------] 3 tests from dynamicGraphIterator (996 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 2 test suites ran. (1727 ms total)
[  PASSED  ] 9 tests.
```


I tested the graph you mentioned and here is my output:
```bash
gunrock/build$ ./bin/dynamic_graph market coAuthorsDBLP.mtx
Loading Matrix-market coordinate-formatted graph ...
  Reading from coAuthorsDBLP.mtx:
  Parsing MARKET COO format (299067 nodes, 977676 directed edges)...   Done (1 s).
  Writing meta data into coAuthorsDBLP.mtx.meta
  Writting edge pairs in binary into coAuthorsDBLP.mtx.coo_edge_pairs
  Assigning 1 to all 977676 edges
  Substracting 1 from node Ids...
  Edge doubleing: 977676 -> 1955352 edges
  graph loaded as COO in 0.890304s.
Converting 299067 vertices, 1955352 directed edges ( ordered tuples) to CSR format...Done (0s).
Degree Histogram (299067 vertices, 1955352 edges):
    Degree 0: 0 (0.000000 %)
    Degree 2^0: 41376 (13.835027 %)
    Degree 2^1: 102633 (34.317728 %)
    Degree 2^2: 87368 (29.213521 %)
    Degree 2^3: 42746 (14.293118 %)
    Degree 2^4: 17441 (5.831804 %)
    Degree 2^5: 6019 (2.012592 %)
    Degree 2^6: 1324 (0.442710 %)
    Degree 2^7: 156 (0.052162 %)
    Degree 2^8: 4 (0.001337 %)

__________________________
--------------------------
Run 0 elapsed: 2.000256 ms.
PASSED
[dynamicgraphbuilding] finished.
 avg. elapsed: 2.000256 ms
 iterations: 0
 min. elapsed: 0.000000 ms
 max. elapsed: 0.000000 ms
 src: 0
 nodes_visited: 140564349519024
 edges_visited: 6
 load time: 965.431 ms
 preprocess time: 0.000000 ms
 postprocess time: 1.641035 ms
 total time: 1297.403097 ms
```


> BTW, I am building gunrock under the branch named dynamic_graph instead of master. May it be the problem?

You are on the right branch. The dynamic graph implementation is only available under the dynamic graph branch.

**Comment by nicklin96** [comment]
I don't have unittests under gunrock/build/bin. Maybe I missed something during building gunrock?
However, I can get the seemingly correct results by running "./bin/dynamic_graph market ../dataset/large/coAuthorsDBLP/coAuthorsDBLP.mtx"

```
Loading Matrix-market coordinate-formatted graph ...
  Reading meta data from ../dataset/large/coAuthorsDBLP/coAuthorsDBLP.mtx.meta
  Reading edge lists from ../dataset/large/coAuthorsDBLP/coAuthorsDBLP.mtx.coo_edge_pairs
Reading from ../dataset/large/coAuthorsDBLP/coAuthorsDBLP.mtx.coo_edge_pairs, typeId = 262, targetId = 262, length = 977676
  Assigning 1 to all 977676 edges
  Substracting 1 from node Ids...
  Edge doubleing: 977676 -> 1955352 edges
  graph loaded as COO in 0.148153s.
Converting 299067 vertices, 1955352 directed edges ( ordered tuples) to CSR format...Done (0s).
Degree Histogram (299067 vertices, 1955352 edges):
    Degree 0: 0 (0.000000 %)
    Degree 2^0: 41376 (13.835027 %)
    Degree 2^1: 102633 (34.317728 %)
    Degree 2^2: 87368 (29.213521 %)
    Degree 2^3: 42746 (14.293118 %)
    Degree 2^4: 17441 (5.831804 %)
    Degree 2^5: 6019 (2.012592 %)
    Degree 2^6: 1324 (0.442710 %)
    Degree 2^7: 156 (0.052162 %)
    Degree 2^8: 4 (0.001337 %)

__________________________
--------------------------
Run 0 elapsed: 2.066752 ms.
PASSED
[dynamicgraphbuilding] finished.
 avg. elapsed: 2.066752 ms
 iterations: 24053513
 min. elapsed: 0.000000 ms
 max. elapsed: 0.000000 ms
 src: 0
 nodes_visited: 11225856
 edges_visited: 5303700
 edges queued: 11225856
 load time: 204.816 ms
 preprocess time: 0.000000 ms
 postprocess time: 16.813993 ms
 total time: 2254.977942 ms
```
Actually my first task is to evaluate the performance of dynamic graph on gunrock so your comments is of great help! Thanks!

BTW, can I take the function arguments used [here](https://github.com/gunrock/gunrock/blob/280fd77105f3b6884eb42d148780983dd0de458b/examples/dynamic_graph/bulk_build.sh#L61) as a reference when I am using gunrock/build/bin/dynamic_graph ?
