### ISSUE TITLE
What does total time indicate?

### ISSUE THREAD

**Issue by the-humble-programmer** [gunrock/gunrock#913]
I ran Gunrock's Connected Components implementation, and I'm trying to make sense of the times reported here. This is the output I obtained:

```

Loading Matrix-market coordinate-formatted graph ...
  Reading directly from stored binary CSR arrays from ../inputs/gemsec-FB/.artist_edges.mtx.ud.0.bin ...
Done reading (0s).

Degree Histogram (50515 vertices, 1638180 edges):
    Degree   0: 0 (0.00%)
    Degree 2^0: 3124 (6.18%)
    Degree 2^1: 5919 (11.72%)
    Degree 2^2: 8312 (16.45%)
    Degree 2^3: 9938 (19.67%)
    Degree 2^4: 9500 (18.81%)
    Degree 2^5: 7242 (14.34%)
    Degree 2^6: 4206 (8.33%)
    Degree 2^7: 1649 (3.26%)
    Degree 2^8: 478 (0.95%)
    Degree 2^9: 126 (0.25%)
    Degree 2^10: 21 (0.04%)

Using 1 GPU: [ 0 ].
graph #nodes : 50515 -> 50515 
Computing reference value ...
CPU CC finished in 1286.802979 msec.

Using traversal mode LB
_________________________
-------------------------
iteration 0 elapsed: 61.277866 ms
CORRECT. Component Count: 1
Label Validity: 
CORRECT
Top 1 largest components:
CC ID: 0, CC Root: 0, CC Size: 50515

	Memory Usage(B)	 #keys0,0	 #keys0,1
GPU_0	 20971520	 0	 0
	 queue_sizing =	 0.000000 	 0.000000

 [CC] finished.
 avg. elapsed: 61.2779 ms
 iterations: 2
 min. elapsed: 61.2779 ms
 max. elapsed: 61.2779 ms
 rate: 26.7336 MiEdges/s
 src: 0
 nodes_visited: 50515
 edges_visited: 1638180
 nodes queued: 808240
 edges queued: 6552720
 nodes redundance: 1500.00%
 edges redundance: 300.00%
 load time: 1660.9428 ms
 preprocess time: 38.6770 ms
 postprocess time: 117.1720 ms
 total time: 5446.7261 ms
```

Specifically, I need to understand what each of the times mentioned indicate (such as total time, preprocess time, postprocess time), and whether these times are that on the CPU or the the GPU or both. Also, if you observe, in the beginning, it computes the CC on the CPU so as to get reference values for comparing GPU's output. It shows that CPU CC finished in 1286 ms. Does this time also include the loading time/preprocess time as well? So, at the bottom, when it shows total time, is this the total time it has taken to run both on CPU as well as on the GPU? If not, will it suffice to subtract the total time mentioned there from 1286 to get total time on GPU, or is there something else to be handled as well (such as subtracting load time, preprocess time, etc)? I would like to know how much time it has taken on the GPU (barring the time taken to load the graph).

**Comment by the-humble-programmer** [comment]
Thank you so much for the clarification. It does answer my questions! :)

But, somehow, something feels strange. 
(a) If we do total time - load time - preprocess time - CPU CC time, we should get the time it takes to run just the GPU CC (along with postprocessing). For the above input, this comes to roughly 2460 ms (5446.7261 - 1660.9428 - 38.677 - 1286.802979). Which seems to be quite a lot of time! I implemented a basic Push-based CC, and for the same input above, it takes a total time of 76 ms. This in general seems to be the case for any input graph, where a vanilla Push-based CC algorithm seems to take much less time than that calculated here for Gunrock. Not sure what I'm doing wrong here.
(b) I also don't understand the iterations count here. It's always showing 2, for any graph. Once again, I am comparing against a basic Push-based CC, and the number of iterations for the same graph is 9 there. I don't understand the discrepancy (since I can't see how convergence can happen within 2 iterations for this graph).

**Comment by neoblizz** [comment]
> Which seems to be quite a lot of time! I implemented a basic Push-based CC, and for the same input above, it takes a total time (excluding load time) of 76 ms. This in general seems to be the case for any input graph, where a vanilla Push-based CC algorithm seems to take much less time than that calculated here for Gunrock. Not sure what I'm doing wrong here.

The total time GPC CC time is given by `avg. elapsed: 61.2779 ms`, which is what you would compare to 76 ms (the only time here that really matters). You don't need to calculate it from the various timers since we have spent zero engineering time on optimizing anything other than the algorithm.

Is there a particular time you're interested in besides "how long did CC algorithm take?" (which again is the elapsed time).

**Comment by neoblizz** [comment]
> (b) I also don't understand the iterations count here. It's always showing 2, for any graph. Once again, I am comparing against a basic Push-based CC, and the number of iterations for the same graph is 9 there. I don't understand the discrepancy (since I can't see how convergence can happen within 2 iterations for this graph).

I am not super familiar with our `0.5` version of CC code, which is the only working version we have as it wasn't ported to `1.0` release. But it seems like the `iterations` is not being reported correctly, and the variable itself is being used as part of the implementation in several places along with another counter `turn`. So, it may just be reporting that incorrectly and may do more than 2 iterations in reality. https://github.com/gunrock/gunrock/blob/v0.5/gunrock/app/cc/cc_enactor.cuh#L666

**Comment by the-humble-programmer** [comment]
> > Which seems to be quite a lot of time! I implemented a basic Push-based CC, and for the same input above, it takes a total time (excluding load time) of 76 ms. This in general seems to be the case for any input graph, where a vanilla Push-based CC algorithm seems to take much less time than that calculated here for Gunrock. Not sure what I'm doing wrong here.
> 
> The total time GPC CC time is given by `avg. elapsed: 61.2779 ms`, which is what you would compare against your `76 ms` (the only time here that really matters). You don't need to calculate it from the various timers since we have spent zero engineering time on optimizing anything other than the algorithm.
> 
> Is there a particular time you're interested in besides "how long did CC algorithm take?" (which again is the elapsed time).

Ok. I am guessing that there is some amount of "miscellaneous" stuff happening (such as setting up the required Data Structures, allocating memory, cleaning up, Memory Transfer operations, etc.), so I have partitioned the times into "CC-Time", which is the time taken by the kernel to actually do CC, and the rest. When I said 76 ms, I meant that the overall time (which is the CC-Time+Miscellaneous-Time) came to be 76. I'm wondering if comparing this against avg. elapsed time of 61 ms would be an apples-to-apples comparison, since that 61 ms excludes the Miscellaneous stuff, whereas the 76 ms does. So if I were to do an apples-to-apples comparison, I should be comparing the 76 ms to whatever is the equivalent time here, so I wondered what to compare it with.



> > (b) I also don't understand the iterations count here. It's always showing 2, for any graph. Once again, I am comparing against a basic Push-based CC, and the number of iterations for the same graph is 9 there. I don't understand the discrepancy (since I can't see how convergence can happen within 2 iterations for this graph).
> 
> I am not super familiar with our `0.5` version of CC code, which is the only working version we have as it wasn't ported to `1.0` release. But it seems like the `iterations` is not being reported correctly, and the variable itself is being used as part of the implementation in several places along with another counter `turn`. So, it may just be reporting that incorrectly and may do more than 2 iterations in reality. https://github.com/gunrock/gunrock/blob/v0.5/gunrock/app/cc/cc_enactor.cuh#L666

Ok thank you! This makes sense :)

**Comment by neoblizz** [comment]
> Ok. I am guessing that there is some amount of "miscellaneous" stuff happening (such as setting up the required Data Structures, allocating memory, cleaning up, Memory Transfer operations, etc.), so I have partitioned the times into "CC-Time", which is the time taken by the kernel to actually do CC, and the rest. When I said 76 ms, I meant that the overall time (which is the CC-Time+Miscellaneous-Time) came to be 76. I'm wondering if comparing this against avg. elapsed time of 61 ms would be an apples-to-apples comparison, since that 61 ms excludes the Miscellaneous stuff, whereas the 76 ms includes it. So if I were to do an apples-to-apples comparison, I should be comparing the 76 ms to whatever is the equivalent time here, so I wondered what to compare it with.

Ah! I understand now. But I think the code that you're working with is too old for me to comment on. The total time in gunrock was often large (at least in 0.5v and below), and very little engineering went into making sure that was done as fast as possible. I don't think if you truly account for the clean-up and whatnot it will be much over 61 ms. The total time might be accounting also for json information setup, any printfs, etc. which might not be captured in `load-time` or `pre/post-processing`. So, simply subtracting those times from total time might still result in an apples-to-oranges comparison.

You could potentially change the code by moving the cpu_timer around the whole application to time data movement and setup as well, but that is not what literature usually reports for "algorithm time." The change you're looking to make is very minor (see: https://github.com/gunrock/gunrock/blob/v0.5/gunrock/app/cc/cc_app.cu#L115-L129), just moving the timer over the whole `gunrock_cc` or `dispatch_cc`.

If you're interested, I'll also point you to https://github.com/gunrock/essentials, which is our work-in-progress next version of gunrock. Making any modifications there is much simpler (and also writing algorithms is simpler as well). But there's no CC implementation, yet.

**Comment by the-humble-programmer** [comment]
> You could potentially change the code by moving the cpu_timer around the whole application to time data movement and setup as well, but that is not what literature usually reports for "algorithm time." The change you're looking to make is very minor (see: https://github.com/gunrock/gunrock/blob/v0.5/gunrock/app/cc/cc_app.cu#L115-L129), just moving the timer over the whole gunrock_cc or dispatch_cc.

Thank you for this. This was useful!

> If you're interested, I'll also point you to https://github.com/gunrock/essentials, which is our work-in-progress next version of gunrock. Making any modifications there is much simpler (and also writing algorithms is simpler as well). But there's no CC implementation, yet.

Looks interesting. I do hope that CC implementation would also be there in the next version. Thanks for all the help
