### ISSUE TITLE
CPM related build issue

### ISSUE THREAD

**Issue by sg0** [gunrock/gunrock#914]
**Summary:**
CMAKE build issue with CPM.

**Reproducibility:**
Always

**To Reproduce:**
Clone gunrock (dev/master), and then build:
`
cmake -DBOOST_ROOT=/share/apps/boost/1.58/no_mpi ..
`

**Expected Behavior:**
Build success.

**Actual Results:**
`
CMake Error at CMakeLists.txt:76 (CPMAddPackage):
  Unknown CMake command "CPMAddPackage".
`

**System Configuration:**
`
Currently Loaded Modulefiles:1) boost/1.58     2) cuda/11.1      3) cmake/3.21.4   4) gcc/9.1.0
`

**Comment by sg0** [comment]
Assuming you know this already: copy-pasting CPM.cmake (from GH) into `/your/path/builds/cmake/CPM_0.27.5.cmake` fixes the issue.

**Comment by crozhon** [comment]
Thanks for letting us know.
