### ISSUE TITLE
Gunrock/SM : Cuda out of memory / Read Access Violation

### ISSUE THREAD

**Issue by sam0oneau** [gunrock/gunrock#919]
Currently, when I run GSM (Gunrock/SM), I get either a read access violation or a cuda out of memory violation mattering on what I set the memory limit to (Including leaving memory limit as what is defined in gunrock/dev repo). This occurs both on an Ampere Device (RTX 3060ti) and on a Turing Device (RTX 8000). An of example of this occurs for the following GSM arguments:

> ./build/bin/sm market dataset/large/roadNet-CA/roadNet-CA.mtx --pattern-graph-type=market --pattern-graph-file=dataset/small/tri_sm.mtx --undirected=1 --pattern-undirected=1 --num-runs=1 --quiet=False

I haven't tested GSM on all the available datasets, so the problems could be endemic with the datasets I've tested. A big query I wonder is what does mem_limit actually mean? Is it max global usage of vram for intermediate results, in bytes, or is it something more nuanced, possibly max elements in various intermediate buffers? I have tried to run this on mem_limits ranging between 500,000 - 50,000,000,000, with no success.

I see another user has had a very similar or identical issue to me, but I couldn't find any fix in the responses.
https://github.com/gunrock/gunrock/issues/833

I am currently writing a paper where we wish to include the benchmarks of GSM for comparison. Although, due to the aforementioned reasons, I am still unable to get any. I understand that the lead author for GSM has finished their studies, so is no longer available to help, so I could understand if this is a problem that is unable to be solved in the short-term. If there is any available help, it would be very much appreciated, although, I expect its possible there is no solution.

**Example of errors:**
**Cuda out of memory:** (Mem_limit = 1,000,000 - 30,000,000,000)
> [.../gunrock/gunrock/util/select_device.cuh, 65 @ gpu 0] CUBSelect malloc d_temp_storage failed (CUDA error 2: out of memory)
> [.../gunrock/gunrock/app/sm/sm_enactor.cuh, 274 @ gpu 0] error encountered (CUDA error 2: out of memory)
> [.../gunrock/gunrock/app/enactor_base.cuh, 519 @ gpu 0] error encountered (CUDA error 2: out of memory)
> [.../gunrock/gunrock/app/sm/sm_enactor.cuh, 492 @ gpu 0] error encountered (CUDA error 2: out of memory)
> [.../gunrock/gunrock/app/sm/sm_app.cuh, 81 @ gpu 0] error encountered (CUDA error 2: out of memory)
> [.../gunrock/examples/sm/test_sm.cu, 97 @ gpu 0] error encountered (CUDA error 2: out of memory)

**Cuda Read Access Violation** (Mem_limit = 500,000)
> [.../gunrock/gunrock/util/array_utils.cuh, 843 @ gpu 0] row_offsets cudaMemcpy H2D failed (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/graph/csr.cuh, 142 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/app/sm/sm_problem.cuh, 336 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/app/sm/sm_problem.cuh, 500 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/app/sm/sm_app.cuh, 68 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/util/array_utils.cuh, 546 @ gpu 0] subgraphs cudaFree failed (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/app/sm/sm_problem.cuh, 141 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/util/array_utils.cuh, 546 @ gpu 0] data_slices[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/gunrock/app/sm/sm_problem.cuh, 391 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
> [.../gunrock/examples/sm/test_sm.cu, 97 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)

System:
Cuda/11.1
Cmake/3.22.0
Gnumake/4.2
Gcc/8.5.0
Nvidia RTX 8000 48GB

**Comment by crozhon** [comment]
We'll take a look at this.

**Comment by crozhon** [comment]
Took a look - `mem_limit` is the size of the allocated arrays on the GPU. (i.e. hipMalloc(mem_limit) for each array) By default, mem_limit == V**2. We shouldn't have done that. So there are two cases:

* We over-allocated memory and there exists some number N < `mem_limit` such that the program won't run out of memory, but it will still execute properly. It looks like you tried this already, and I did too - couldn't find a number that worked. You have to work around things like CUB needing to allocate memory too.
* We need V**2 allocated for some reason and use it for indexing. Based on those illegal memory access errors, this is what I think is going on. So it expects a size that large. Sorry if this is the case, it's just the app falling short.

IMO, you'll need to fix the app to get it working on larger datasets. As written, it doesn't work with any graphs where |V| > ~100000 (100000bytes * 100000bytes =~ 10GB).

**Comment by sam0oneau** [comment]
I see, I very much appreciate the work you and your colleagues have to done to help in working with GSM. That is a real shame, as it gives us less experimental data about other GPU approaches.

Thank you for the help. The communication has been top notch.

**Comment by crozhon** [comment]
@sam0oneau Tried out a few more things and ended up fixing it - I think. It works on roadNetCA at least:
```
carozhon@wario:~/wario/gunrock$ ./build/bin/sm market /data/gunrock/roadNet-CA/roadNet-CA.mtx --pattern-graph-type=market --pattern-graph-file=dataset/small/tri_sm.mtx --undirected=1 --pattern-undirected=1 --num-runs=1 --quiet=False

...
__________________________
--------------------------
Run 0 elapsed: 55889.872789 ms, #iterations = 1
Subgraph Matching Validity: PASS
PASS
[sm] finished.
 avg. elapsed: 55889.872789 ms
 iterations: 1
 min. elapsed: 55889.872789 ms
 max. elapsed: 55889.872789 ms
 load time: 262.527 ms
 preprocess time: 10624.800000 ms
 postprocess time: 3.840923 ms
 total time: 66527.858019 ms

```

New commit is on dev branch - `git fetch && git checkout dev` Let us know if it does the trick for you.

**Comment by jowens** [comment]
holy cow @crozhon that's amazing

**Comment by sam0oneau** [comment]
> @sam0oneau Tried out a few more things and ended up fixing it - I think. It works on roadNetCA at least:
> 
> ```
> carozhon@wario:~/wario/gunrock$ ./build/bin/sm market /data/gunrock/roadNet-CA/roadNet-CA.mtx --pattern-graph-type=market --pattern-graph-file=dataset/small/tri_sm.mtx --undirected=1 --pattern-undirected=1 --num-runs=1 --quiet=False
> 
> ...
> __________________________
> --------------------------
> Run 0 elapsed: 55889.872789 ms, #iterations = 1
> Subgraph Matching Validity: PASS
> PASS
> [sm] finished.
>  avg. elapsed: 55889.872789 ms
>  iterations: 1
>  min. elapsed: 55889.872789 ms
>  max. elapsed: 55889.872789 ms
>  load time: 262.527 ms
>  preprocess time: 10624.800000 ms
>  postprocess time: 3.840923 ms
>  total time: 66527.858019 ms
> ```
> 
> New commit is on dev branch - `git fetch && git checkout dev` Let us know if it does the trick for you on your other datasets too.

I appreciate all the work you've done, this is very impressive. I've ratified that is does indeed run on my end. This is great to see. I will mark this issue as closed.

I do have a question. I was wondering how to compute labelled subgraph matches on GSM and whether GSM even supports this? I presume this is a simple task, although, I couldn't find reference on how to do this? https://github.com/gunrock/gunrock/issues/834 seems to indicate that GSM doesn't support this, although, if my memory serves me well, I believe GSI did experiments against GSM using labelled graphs?

**Comment by crozhon** [comment]
Glad we could help!

> I do have a question. I was wondering how to compute subgraph matches on GSM for edge labelled graphs and whether GSM even supports this (i.e. edge preservation of labelled edges)? I presume this is a simple task, although, I couldn't find reference on how to do this? https://github.com/gunrock/gunrock/issues/834 seems to indicate that GSM doesn't support this, although, if my memory serves me well, I believe GSI did experiments against GSM using labelled graphs, so I was wondering if you knew how they achieved it?

Do you know anything about this @neoblizz?

**Comment by neoblizz** [comment]
@sam0oneau I presume you mean subgraph matching on a label edges, where labels are more than just the edge ids? That will require significant changes to the subgraph matching C++ lambda expression to get it working with gunrock.

We are also moving onto a new API accessible under `main` and `develop` branch, subgraph matching currently needs to be ported over to the new version and could theoretically support this much easily than the older API. If you're interested in porting, let me know and I will send you the pointers for it.

**Comment by sam0oneau** [comment]
> @sam0oneau I presume you mean subgraph matching on a label edges, where labels are more than just the edge ids? That will require significant changes to the subgraph matching C++ lambda expression to get it working with gunrock.
> 
> We are also moving onto a new API accessible under `main` and `develop` branch, subgraph matching currently needs to be ported over to the new version and could theoretically support this much easily than the older API. If you're interested in porting, let me know and I will send you the pointers for it.

Hmm I see. If I'm understanding you correctly, by edge id, you mean each edge has a distinct edge id? Or is an edge id just a label?

So in SM problems you have unlabelled graph matching and labelled graph matching. How did Leyuan Wang achieve their labelled graph matching experiments in their paper on this (Fig 3, [1])? Both GSM and GSI reference doing labelled experiments with GSM, so I presume it is possible, although, I presume I've either missed something in the dataset section or I've misunderstood your response

[1] - https://arxiv.org/pdf/2003.01527.pdf

**Comment by neoblizz** [comment]
> Hmm I see. If I'm understanding you correctly, by edge id, you mean each edge has a distinct edge id? Or is an edge id just a label?

I believe the edge ids are treated as the label. @Laurawly can answer this better though. The change I was referring to was using the edge id to index into a separate data structure for matching.
