### ISSUE TITLE
Function calls inside `assert`

### ISSUE THREAD

**Issue by maawad** [gunrock/gunrock#927]
**Describe the bug**
Function calls inside `assert` are optimized away when `NDEBUG` is defined.

**To Reproduce**
Define `NDEBUG`

**Environment (please complete the following information):**
Any

**Additional context**
See these lines in [`read_binary`](https://github.com/gunrock/essentials/blob/0cf0913d7b53515a207f97737ef1e2771e5ee533/include/gunrock/formats/csr.hxx#L155-L195).

**Comment by neoblizz** [comment]
> See these lines in [`read_binary`](https://github.com/gunrock/essentials/blob/0cf0913d7b53515a207f97737ef1e2771e5ee533/include/gunrock/formats/csr.hxx#L155-L195).

https://github.com/gunrock/gunrock/commit/2c395341e8f825928cf496d80914549ec3d700ad
