### ISSUE TITLE
Input a list of graphs

### ISSUE THREAD

**Issue by Laurawly** [gunrock/gunrock#93]
Currently, Gunrock supports taking in only one input graph file at runtime. For future applications (e.g. subgraph matching), we probably want to pass a list of input graphs. Since subgraph matching needs two input graph (query graph and data graph) as well as their corresponding labels in .label files, temporarily, I redefined LoadGraph and Init functions specially for SM in enactor_base.cuh file. In the future, we can modify these two functions for all applications to take any number of input graphs based on the graph_args (number of input graphs) variable and make some changes to the GetCmdLineArgvDataDataset() function in test_utils.h file correspondingly.

**Comment by neoblizz** [comment]
Noting that  this is now easier to do in dev-refactor using `parameters` and `LoadGraph`, also there are multiple ways to read in labels, one of them is within Array utilities called `Read` and another I wrote for Geolocation called `Labels`, we can refine these later or add one for SM.
